### ISSUE TITLE
search workspace for project by ID

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1000]
This crops up regularly and we already have searching by project ID via management so perhaps an easy addition to the standard workspace.

**Comment by torinfo** [comment]
@ronm123 It uses the search plugin functionality of the javascript tree that we use. Fortunately, the latest version adds the ability to change the search, to search on more items than only visible text of the node.

I updated the jstree.js component (used in workspace and editor) and added the capability to search for IDs. Please let me know what you think.
