### ISSUE TITLE
Hide property groups when all children are removed as conditional parameters

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1010]
I want to have a group of properties in a page which are conditional on another property's value. The individual form fields are hidden correctly but it leaves behind an empty group box:

![conditional](https://user-images.githubusercontent.com/8926470/116687577-52e35a80-a9ad-11eb-9e31-a0e5e654fbc2.PNG)

I've tried also adding the condition to the group in the xwd but this doesn't work:
`<notesGroup type="group" label="Notes" condition="mode=='Notes'">
    <notesPos label="Position" type="combobox" options="Panel 1,Panel 2" data="panelA,panelB" condition="mode=='Notes'"/>
    <notesTitle label="Title" type="TextInput" wysiwyg="true" condition="mode=='Notes'"/>
</notesGroup>`

I think that this just doesn't work rather than me doing something wrong in the way I'm setting it up.

**Comment by torinfo** [comment]
@FayCross I agree that this would be a good feature and the easiest would be to allow the condition on the group as well. I'll implament that.
