### ISSUE TITLE
Bootstrap adding a text block after a XOT, the XOT does not work anymore

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#1019]
Hi,

When you add a XOT page to a bootstrap project (in this case Button sequence) and in the same section you add a text block after the XOT, the button sequens does not work anymore.
![image](https://user-images.githubusercontent.com/5703781/118288877-14818b80-b4d5-11eb-81bb-bd26b650839e.png)

**Comment by FayCross** [comment]
@ingedonke have you got a link to an example of this? I can't recreate it. Thanks

**Comment by ingedonke** [comment]
I tried this in the xot310beta installation but it seems to work ok there and also in our 3.9 installation. So I close this issue. It had something to do with their installation I think.
