### ISSUE TITLE
Bugs with gap fill answers on results page

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1022]
When in drag drop mode the answers you submit aren't always shown correctly on the results page:
- [x] If the answer given is a distractor then it doesn't show on results page & it looks like gap wasn't filled
- [x] If all answers are incorrect then the answers shown on results page don't represent what you actually did. e.g. they might be in the wrong order (so look like you put a word in gap 1 rather than 2) or if distractors are used they may show that you answered with a label that you didn't use at all

The data submitted by the gap fill page seems correct but I think it's misinterpreted by the results page.

Also, the format of the results when in drag drop mode is odd. Both your answer and correct answer are shown as 'correctAnswer --> yourAnswer' rather than just having a single bit of info like you do in the two other gap fill modes

**Comment by torinfo** [comment]
I'll have a look
