### ISSUE TITLE
menu connector not showing ticks where buttons are generated via the first page to last page options.

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1023]
Hi all
I just committed an optional property to allow the menu connector to span multiple columns. https://github.com/thexerteproject/xerteonlinetoolkits/commit/92e82d98a75c97a24dea92a6df03c958732fed94
That all works fine except in testing I noticed a bug and can't work out what's causing that bug. As far as I can see it's not my commit that has caused this because I checked on a separate copy of develop that doesn't have my changes. I also tested on a 3.9-13 install and it works fine on that too.

To replicate:
Create a new project and add a menu connector page or add a menu connector page to an existing project.
Set the optional property to Tick When Viewed.
Use the First Entry and Last Entry optional properties to link to a set of pages rather than adding manual links to specific pages.
Use the menu or navigate to the linked pages then back to the menu. No ticks are shown?

Duplicate that menu connector and remove the First Entry and Last Entry options and add some manual links to pages.
Use the menu or navigate to the linked pages then back to the menu. Ticks are now shown?

@torinfo @FayCross Can you replicate this? Any idea of the cause/solution?

**Comment by FayCross** [comment]
I made some changes to this page a couple of weeks ago so I might have caused this. I’ll look when I’m back in.

**Comment by torinfo** [comment]
I made some changes too, so I will check as well.
