### ISSUE TITLE
IE11 incompatibility with Bootstrap

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1029]
Hi all
I had it reported to me that students were saying that the Xerte bootstrap resources they were pointed to do not work in IE 11. I don't have a link to the exact example(s) but I did some testing and first I tested with our Bootstrap demonstrator https://xot.xerte.org.uk/play.php?template_id=137#page1 which works fine so I figured perhaps it was something to do with what had been added to their resources and perhaps something embedded.

However I did some further testing and there does seem to be an incompatibility but not sure why it doesn't show up with the demonstrator. If you try to view our release notes in IE 11 https://xot.xerte.org.uk/play.php?template_id=81 you'll see the error which is as follows:

Object doesn't support property or method 'isInteger'

`if (Number.isInteger(pageID)) {
// pageID refers to actual page num of valid pages - need to convert to index of all pages
if (pageRefType == 'start' || pageRefType == 'check') {
pageID = validPages[pageID];
}`

is there an alternative to using isInteger that does work with IE?

**Comment by ronm123** [comment]
Sorry if you received this via email already I had to edit because it was meant to say there **does** seem to be an incompatibility but the initial post said doesn't.

**Comment by torinfo** [comment]
We would have to use a polyfill

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

**Comment by ronm123** [comment]
@torinfo @FayCross So I tested this by changing the code to the following and it seems to resolve the IE 11 issue. Or at least now the test projects I'm using loads and allows navigation. But is this correct or is there somewhere else this is all used that needs testing? If ok shall I commit?
`// check if it's a valid page index
	if (pageRefType != 'id') {
		pageID = $.isNumeric(pageID) ? Number(pageID) : pageID;

		if (Number.isInteger = Number.isInteger || function(pageID) {
			return typeof pageID === 'number' &&
				isFinite(pageID) &&
				Math.floor(pageID) === pageID;
		})
		{
			// pageID refers to actual page num of valid pages - need to convert to index of all pages
			if (pageRefType == 'start' || pageRefType == 'check') {
				pageID = validPages[pageID];
			}`

**Comment by torinfo** [comment]
@ronm123 No, I don't think that's correct, but I have not been able to verify this yet. Will do so a.s.a.p.  I want to be able to include this in the release.... :-)

**Comment by ronm123** [comment]
@torinfo @FayCross thanks for your responses here and by email.
Obviously what I pasted above didn't all go into the code display so it starts at the // and when I tested certainly worked for me. But as Fay has said it really needs testing against some examples and with reference to why it was done that way in the first place. I was surprised that it hasn't been reported before but I guess IE11 is used less now than it was but not in the health sector which is where I received the report from.

**Comment by FayCross** [comment]
Could you try this @ronm123 I couldn't recreate the bug in my IE11 but this removes isInteger and still works with my test projects

**Comment by ronm123** [comment]
@FayCross could you reproduce it with the release notes? https://xot.xerte.org.uk/play.php?template_id=81 
I've tested locally with a copy of that when checking the issue and now with your fix in place it works fine.

**Comment by FayCross** [comment]
@ronm123 Yes I could, but not with my local tests - even though the isInteger line was definitely being reached (not missed because of an if statement or anything like that).
