### ISSUE TITLE
Importing pages that include images in folders bug

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1033]
If an image (or other file) is in a folder within the media folder, the image is not included in the import when a page is imported into another project. The file path in the editor field is correct but the folder & file isn't copied over into the media folder.

**Comment by FayCross** [comment]
This is now working - fixed as part of v3.11?

**Comment by torinfo** [comment]
@FayCross Yes, fixed as part of v3.11
