### ISSUE TITLE
Cannot create a new folder in Workspace

### ISSUE THREAD

**Issue by obgeneralao** [thexerteproject/xerteonlinetoolkits#1034]
Hi,
I am having an issue where I cannot create a folder in the Workspace in the develop branch. It has been a while that I was able to create a folder. Interestingly, I can still create a subfolder under an already existing folder.
In the meantime, my workaround is, I created a folder inside an already existing folder then drag it to the Workspace. Now I have a new folder on the Workspace.

Thanks

**Comment by torinfo** [comment]
@obgeneralao Which version of Xerte Toolkits are you using? Any error messages in the php log on or in the browser's console?

**Comment by obgeneralao** [comment]
Hi
I am on **develop** branch.
Attached is the debug file when I created a new folder.
[debug.log](https://github.com/thexerteproject/xerteonlinetoolkits/files/6706806/debug.log)

**Comment by torinfo** [comment]
I cannot reproduce on my install of develop.

It would be good to see the php error log, which you can normally find in the apache2 error log.

**Comment by obgeneralao** [comment]
This what I got in apache2/logs/error_log. The timestamp is consistent with the debug.log file.

_[Thu Jun 24 06:21:38.700329 2021] [mpm_prefork:notice] [pid 1643] AH00169: caught SIGTERM, shutting down
[Thu Jun 24 06:21:52.743577 2021] [ssl:warn] [pid 19867] AH01882: Init: this version of mod_ssl was compiled against a newer library (OpenSSL 1.1.1j  16 Feb 2021, version currently loaded is OpenSSL 1.1.1i  8 Dec 2020) - may result in undefined or erroneous behavior
[Thu Jun 24 06:21:52.770590 2021] [ssl:warn] [pid 19868] AH01882: Init: this version of mod_ssl was compiled against a newer library (OpenSSL 1.1.1j  16 Feb 2021, version currently loaded is OpenSSL 1.1.1i  8 Dec 2020) - may result in undefined or erroneous behavior
[Thu Jun 24 06:21:52.802623 2021] [mpm_prefork:notice] [pid 19868] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1i PHP/7.3.27 configured -- resuming normal operations
[Thu Jun 24 06:21:52.802655 2021] [core:notice] [pid 19868] AH00094: Command line: '/opt/lampstack-7.3.27-2/apache2/bin/httpd.bin -f /opt/lampstack-7.3.27-2/apache2/conf/httpd.conf'
[Thu Jun 24 06:21:54.055867 2021] [php7:warn] [pid 19877] [client 152.32.99.56:31966] PHP Warning:  Invalid argument supplied for foreach() in /opt/lampstack-7.3.27-2/apps/xerte/htdocs/xerteonlinetoolkits/website_code/php/display_library.php on line 728, referer: https://my.olibgen.com/xerte/
[Thu Jun 24 06:21:56.144133 2021] [php7:warn] [pid 19877] [client 152.32.99.56:31966] PHP Warning:  Invalid argument supplied for foreach() in /opt/lampstack-7.3.27-2/apps/xerte/htdocs/xerteonlinetoolkits/website_code/php/display_library.php on line 728, referer: https://my.olibgen.com/xerte/
[Thu Jun 24 06:24:18.235082 2021] [mpm_prefork:notice] [pid 19868] AH00169: caught SIGTERM, shutting down_

**Comment by torinfo** [comment]
Ok. So that does not explain anything. Are you using the latest develop? I still cannot reproduce.

**Comment by torinfo** [comment]
Ok, I probably fixed this in d5b2b0046a10d4b5c79e7e733afcbeb1bfc9885c. Could you please verify?

**Comment by torinfo** [comment]
Still do not understand why I could not reproduce, but it was definitely a bug.

**Comment by obgeneralao** [comment]
Hi,
This is very interesting. I still could not create new folders in Workspace using Google Chrome and Edge even updating the develop branch. However, I successfully created the folder in Workspace with IE 11.

**Comment by torinfo** [comment]
Caching?

**Comment by obgeneralao** [comment]
There. It is working now in all 3 browsers. Thank you very much.
