### ISSUE TITLE
Group sharing tab in project properties

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1036]
The group sharing tab still shows in project properties when there are no groups available to share with. Could this be hidden unless there are groups available? This is assuming that the groups have to be set up in the management pages - or am I missing something and users can set up their own groups?

**Comment by torinfo** [comment]
@FayCross Fixed this, will commit later and cherry-pick to 3.10

**Comment by torinfo** [comment]
Fixed in fc3f136178b6fe0bf5510ae360fdab1cc3a53934
