### ISSUE TITLE
Hotspot Question bugs

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1037]
- [x] There needs to be a way of viewing what the correct answers were if you didn't get them all right
- [x] If you complete activity the page is locked to new selections but if you then resize the page you can start clicking hotspots again
- [x] Ideally the string 'You have x answer(s) right and y wrong' would change if all are correct to something like 'You have selected all correct answers' and if all are wrong to 'You have not selected any of the correct answers'. At the moment the text doesn't give you an indication of whether there were more correct answers that you didn't select.
- [x] You can tab to hotspots and click space to select but there's no focus highlight so you can't see which hotspot you are focused on
- [x] When show hotspot is on, there's no difference in appearance between hotspots you have selected and those you haven't
- [x] Not much space for feedback text so if it's several lines long the page layout goes odd once it's been added to the page
- [x] If you make selections and then page size changes it looks like they have been removed. If you then click check it's clear that they are still selected (as they are marked as if selected) but the highlight has gone

**Comment by torinfo** [comment]
@FayCross Will have a look
