### ISSUE TITLE
Bootstrap preview %TRACKING_SUPPORT%

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1039]
When creating a new Bootstrap project in v3.10 '%TRACKING_SUPPORT%' can be seen at the top of the project on preview.

Although this doesn't stay on screen in this way when previewing existing Bootstrap projects (made before upgrading to 3.10) it can be seen briefly flashing on screen and then disappearing when the project has loaded.

![newBS](https://user-images.githubusercontent.com/8926470/124269435-c97a1100-db32-11eb-953a-85a71c5998e7.PNG)

**Comment by ronm123** [comment]
This appears to be because site preview.php doesn't contain `$page_content = str_replace("%TRACKING_SUPPORT%", $tracking, $page_content);` whereas site play.php does. I just added that line to preview.php and it seems to resolve the issue. Shall I commit that?

**Comment by FayCross** [comment]
@ronm123 sounds like that will do it. I thought it wasn't showing when previewing older projects but it seems like it's there but the pages are slightly scrolled down (so it's off the top of the screen). Thanks

**Comment by ronm123** [comment]
@FayCross have committed so will close the issue. I'm sure @torinfo will advise if it isn't as simple as that! ;-)

**Comment by torinfo** [comment]
Thanks @ronm123 and @FayCross Yes, that should do it. I'll cherry-pick later to 3.10
