### ISSUE TITLE
Enable resuming does not work on some page types where # is amended in URL

### ISSUE THREAD

**Issue by obgeneralao** [thexerteproject/xerteonlinetoolkits#1046]
Hi,

I am in develop branch. I have a few of  **Tabbed Navigator +** contents and whenever I refresh my preview (F5), it brings me back to the very first page, not to the (updated/refreshed) current page.

**Comment by torinfo** [comment]
@obgeneralao @FayCross Indeed. It's caused by the fact that somehow if you select a tab, the #page anchor is removed from the URL!

**Comment by FayCross** [comment]
Looking into this now. This is also a problem on the following pages:

- [ ] Multiple perspectives
- [ ] Tabbed navigator +
- [ ] Thumbnail viewer
- [ ] Interactive text
- [ ] Annotated diagram
- [ ] Interactive list

**Comment by obgeneralao** [comment]
Is it possible that the nested pages(of those main pages listed above including Multi-Navigator) will have page anchors as well?

**Comment by obgeneralao** [comment]
This issue reoccurs in the **master** branch.

**Comment by torinfo** [comment]
@obgeneralao Master is the current release. The last release was on June 30, 2021. So this fix is not in master yet. This will happen on the next release.

**Comment by obgeneralao** [comment]
Hi,
This issue is happening in [v3.10.5](https://github.com/thexerteproject/xerteonlinetoolkits/releases/tag/v3.10.5).
Once topic  in `xerteonlinetoolkits/preview.php?template_id=172#page2` is clicked, I was expecting a behavior something like `xerteonlinetoolkits/preview.php?template_id=172#page2#topic0` but the address bar changed to `xerteonlinetoolkits/preview.php?template_id=172#topic0` and refreshing the page reverts to `xerteonlinetoolkits/preview.php?template_id=172#page1`.
