### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'user'@'host' (using password: YES)

### ISSUE THREAD

**Issue by GaneshKandu** [thexerteproject/xerteonlinetoolkits#1048]
Hi,

I am getting this issue while install of 3.10 (git v3.10.4-3-g176ec48) ( Downloaded from [https://xerte.org.uk/index.php/en/downloads-1/category/3-xerte-online-toolkits](https://xerte.org.uk/index.php/en/downloads-1/category/3-xerte-online-toolkits) )

```SQLSTATE[HY000] [1045] Access denied for user 'user'@'host' (using password: YES)```

MySQL 5.5.62
OS Centos 6
Browser FireFox 91.0b6
PHP 5.3

**Comment by torinfo** [comment]
@GaneshKandu I downloaded the same zip file and installed it on xampp. That works fine.

So, in principle, it works. There are 3 locations where you need to supply a username and password. Two of those are related to MySQL, one is not.

The first username/password needs to be a mysql user that is allowed to create a database. It is on the age where you specify the mysql server (localhost y default) and the name of the database.

Then, tyou get a page where you can supply a (potentially) different mysql user that will be used when running the software. This mysql user does not need to have the permissions to create a database but needs to have the rights to create/alter table (to be able to install upgrades) and write to the database.

The last username/password is for Xerte's management.php page. So, one of the first two combinations is wrong. You can check the second in database.php. Those users already need to exist.

**Comment by GaneshKandu** [comment]
Thanks !
