### ISSUE TITLE
Accessibility issue with drag and drop labelling

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1063]
A question on the forums https://www.xerte.org.uk/index.php/en/forum/accessibility/2683-keyboard-users-how-to-access-descriptive-text-on-drag-and-drop-page-using-keys#7680 has highlighted an issue with the drag and drop labelling page when used by keyboard only users. e.g. if the text attached to each hotspot contains links those links can't be reached by a keyboard only user because tabbing away from the hotspots or draggable items hides the text. You can get to the text and links via mouse but not via keyboard only.

**Comment by stutteringp0et** [comment]
How long has the website been down?
