### ISSUE TITLE
Support/documentation/example site offline

### ISSUE THREAD

**Issue by stutteringp0et** [thexerteproject/xerteonlinetoolkits#1064]
The website used for all documentation, is offline

https://xot.xerte.org.uk/

I'm loving the software, but having access to these documents would be massively helpful.  Without them, I'm feeling my way through the system - and it isn't very efficient.

**Comment by torinfo** [comment]
Apologies, the website has been down since last Friday due to a configuration error during maintenance.

The website is online now. Again apologies for the inconvenience.
