### ISSUE TITLE
page links to panes in multi-nav not working

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1069]
not sure if this is already a know issue but we've noticed it on a future teacher resource and I've now tested in 3.10 and develop and it does seem this has stopped working.

e.g. multi-nav set to tabs with 3 panes tab 1, tab 2, tab 3
page links in the page text to each of the tabs which show in the page links menu as -tab 1, -tab 2, -tab 3
I think this did work but now doesn't?

**Comment by FayCross** [comment]
@ronm123 It's taken me ages to recreate this as it only seems to be when the tabs are named numerically. See this example: [Link example](https://xot310beta.dlearning.nl/play.php?template_id=59) where the links to tabs A,B,C work but the links to tabs 1,2,3 aren't right.

Does this fit with your examples where you've seen the links not working correctly?

**Comment by FayCross** [comment]
There are two bugs with links to tabs:

- [ ] Links to tabs with numeric names don't work (see link above)
- [ ] Links to tabs **on the same page** don't work

**Comment by FayCross** [comment]
@ronm123 could you see if this fixes it for you? I haven't looked at the additional bug I found yet, so make sure your tabs don't just have a number as their name when testing. Thanks

**Comment by ronm123** [comment]
Thanks for checking this @FayCross and sorry it took you ages to find the issue with numeric names. That wasn't the issue I noticed even though I referred to creating tab1 tab2 etc to test because the FT resource where I first noticed this didn't have numeric names. However it was the issue with the links being on the same page rather than a previous or later page and those links on previous or later pages do work. I'll pull down your partial fix but as we discussed I can't help thinking this did work and is a result of a change and I'm pretty sure that once I tested links on the same page previously I used it in other places too. Trouble is I'm not sure I still have any older installs to verify that.

**Comment by FayCross** [comment]
@ronm123 no problem. If it did work previously then it's probably the work I did sometime ago to get the url to reflect page changes that broke it as that rewrote a lot of the linking code. I think I have a fix for the other bug too so will commit shortly after testing

**Comment by ronm123** [comment]
@FayCross just tested and yes thanks that fixes the same page issue which is great. I'll update xenith in the FT install where I noticed this and add the links back in. Actually I might wait until you've checked and committed the numeric name fix too.

**Comment by FayCross** [comment]
@ronm123 second issue should also now be fixed
