### ISSUE TITLE
Lack of consistency in what can be used as video source in the various video pages

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1074]
From forum: https://xerte.org.uk/index.php/en/forum/general-chat/2806-interactive-video-can-i-use-a-url#7924

There's no consistency in what can be used as the source for videos when using a video on YouTube. For example, the video page will accept https://www.youtube.com/watch?v=msTEuI0eLZA (URL from browser address bar), https://youtu.be/msTEuI0eLZA (URL shown when you click share button) and embed code. Media Lesson & Interactive Video pages will only work with the first of these. If it's not possible for them to use all of these then we should put guidance in editor.

**Comment by JohnSmith-LT** [comment]
Hi @FayCross and @ronm123 this commit possibly has the chance to break the most LOs so probably needs testing with a lot of LOs that contain videos, across all the pages that can have video added.

I've basically intercepted all the video URLs and if any match a current YouTube or Vimeo format then the URL will be changed into the most basic of each URL. Currently i've tested with the 43x different Youtube formats below and the 9x Vimeo ones and in my basic testing they all seem to work now across all video pages (I haven't done the Youtube page model yet but is there any reason not to??)

Anyway, if it doesn't match either then it should fail gracefully and just pass whatever URL has been entered so uploaded video still appears to work fine.

Here are some examples of the URLs that it will match and work with:

https://www.youtube.com/watch?v=DFYRQ_zQ-gk&feature=featured
https://www.youtube.com/watch?v=DFYRQ_zQ-gk
http://www.youtube.com/watch?v=DFYRQ_zQ-gk
//www.youtube.com/watch?v=DFYRQ_zQ-gk
www.youtube.com/watch?v=DFYRQ_zQ-gk
https://youtube.com/watch?v=DFYRQ_zQ-gk
http://youtube.com/watch?v=DFYRQ_zQ-gk
//youtube.com/watch?v=DFYRQ_zQ-gk
youtube.com/watch?v=DFYRQ_zQ-gk

https://m.youtube.com/watch?v=DFYRQ_zQ-gk
http://m.youtube.com/watch?v=DFYRQ_zQ-gk
//m.youtube.com/watch?v=DFYRQ_zQ-gk
m.youtube.com/watch?v=DFYRQ_zQ-gk

https://www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
http://www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
//www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US

https://www.youtube.com/embed/DFYRQ_zQ-gk?autoplay=1
https://www.youtube.com/embed/DFYRQ_zQ-gk
http://www.youtube.com/embed/DFYRQ_zQ-gk
//www.youtube.com/embed/DFYRQ_zQ-gk
www.youtube.com/embed/DFYRQ_zQ-gk
https://youtube.com/embed/DFYRQ_zQ-gk
http://youtube.com/embed/DFYRQ_zQ-gk
//youtube.com/embed/DFYRQ_zQ-gk
youtube.com/embed/DFYRQ_zQ-gk

https://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk?autoplay=1
https://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk
http://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk
//www.youtube-nocookie.com/embed/DFYRQ_zQ-gk
www.youtube-nocookie.com/embed/DFYRQ_zQ-gk
https://youtube-nocookie.com/embed/DFYRQ_zQ-gk
http://youtube-nocookie.com/embed/DFYRQ_zQ-gk
//youtube-nocookie.com/embed/DFYRQ_zQ-gk
youtube-nocookie.com/embed/DFYRQ_zQ-gk

https://youtu.be/DFYRQ_zQ-gk?t=120
https://youtu.be/DFYRQ_zQ-gk
http://youtu.be/DFYRQ_zQ-gk
//youtu.be/DFYRQ_zQ-gk
youtu.be/DFYRQ_zQ-gk

https://www.youtube.com/HamdiKickProduction?v=DFYRQ_zQ-gk

vimeo.com/123456789
vimeo.com/channels/mychannel/123456789
vimeo.com/groups/shortfilms/videos/123456789
player.vimeo.com/video/123456789
http://vimeo.com/123456789
https://vimeo.com/channels/mychannel/123456789
https://vimeo.com/groups/shortfilms/videos/123456789
https://www.player.vimeo.com/video/123456789

It should also handle the Youtube and Vimeo <iframe> embed codes in any of the video URL boxes now too:

<iframe width="560" height="315" src="https://www.youtube.com/embed/0DBmHb8O4c8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe src="https://player.vimeo.com/video/704734657?h=37bd069b2b" width="640" height="268" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
<p><a href="https://vimeo.com/704734657">PUNCH-DRUNK</a> from <a href="https://vimeo.com/falsetoothfilms">Falsetooth Films</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

The only Vimeo link it doesn't work with is the aliased links:

https://vimeo.com/falsetoothfilms/punch-drunk

Please test!!

**Comment by FayCross** [comment]
@JohnSmith-LT I haven't tested this yet but it's worth tagging @torinfo in this too. In last dev meeting he was talking about moving all pages that use mediaelement for video to use popcorn instead. Not sure if that will affect any of this.

**Comment by JohnSmith-LT** [comment]
Thanks @FayCross, Yeah I wondered whether I should have tagged @torinfo in this too...

Some of the pages already use PopCorn obviously and a few of those urls above didn't work on those pages but because the function is basically just translating to a known good url then it can probably just be incorporated into that check. It shouldn't cause any issue I don't think, I think it's more important that it doesn't mistakenly match and rewrite an uploaded video for example that has been named vimeo.com.mp4 or something bizarre like that...

Will wait for @torinfo to come back with any suggestions about this or if I can assist with the migration to Popcorn but I was thinking that should we perhaps be doing similar for audio such as SoundCloud etc which Popcorn appears to support with a plugin?

**Comment by torinfo** [comment]
@JohnSmith-LT @FayCross We did migrate a lot of the pages to popcorn (as I have implemented xAPI tracking in popcorn). Also, because of the plugin setup of popcorn it's easier to add services like vimeo and youtube. We've added peertube. 

I'll look into the code and see where we can put them in popcorn.

The code is in the torinf fork of xertetoolkits (torinfo/xerteonlintetookits) and I need to create pull requests for a number of work we did. At the moment we're testing.

**Comment by JohnSmith-LT** [comment]
I need to also do some work in the editor since the Preview button for most of these URLs now doesn't work even though they play fine in the LO. Does your work @torinfo include using Popcorn for video display in the editor because it seems that the functionality you are using for xAPI tracking may also be capable of being used to finally add the sync point functionality that is missing since the flash editor

https://github.com/thexerteproject/xerteonlinetoolkits/issues/439

**Comment by FayCross** [comment]
Not sure if this is related to the work to move to using popcorn but some videos in video page which were responsive in v3.10 are now fixed size in develop. For example, [3.10](https://xot.xerte.org.uk/play_326#page1) where using YouTube embed code, it is made responsive but [develop](https://xot310beta.dlearning.nl/play.php?template_id=68) same YouTube embed code on same page is showing as fixed size. Page 2 on both these projects show if you use YouTube URL instead then it's not responsive either but I'm not sure it ever has been.

**Comment by torinfo** [comment]
I'll try to push the popcorn cahnges to develop a.s.a.p.

I'll let yoiu know when done.

**Comment by FayCross** [comment]
@torinfo @JohnSmith-LT Is the video page now supposed to be using popcorn? I've just set up some test projects so I can test if different source formats still work but it seems to still be using mediaelement:

[v3.10 test project](https://xerte.nottingham.ac.uk/play_41125)

[develop test project (created on https://xot310beta.dlearning.nl/)](https://xot310beta.dlearning.nl/play.php?template_id=74)

You can see there are various problems with sizing of videos too in develop

**Comment by FayCross** [comment]
Actually, I'm confused. The first page with the MP4 is loading all the mediaelement stuff as well as popcorn - is that right? I thought popcorn was going to replace the use of mediaelement.js but maybe not?

Anyway, you can see from comparing the two projects above that there are issues with what used to work and what now works, as well as issues with sizing (and resizing) videos in develop.

**Comment by torinfo** [comment]
Thank you for this project. It will help me fix issues.

Popcorn itself uses mediaelemsnts if the video is an mp4. It will use the youtube and vimeo players when the video is youtube or vimeo.

The video page itself will NOT use popcorn for iFrames, but just embed the video. In that case NO tracking will take place.

**Comment by FayCross** [comment]
@torinfo only tested Video page but initial thoughts are it's much better in lots of ways. Bugs/comments below:

- [ ] MP4 file. On first load of page it often appears like this:

![video1](https://user-images.githubusercontent.com/8926470/176681179-19c5f6ef-2bb4-4a2b-8e40-128e2536da60.PNG)
The video player then loads correctly when the browser is resized (albeit at the wrong size)

- [ ] When YouTube & Vimeo are used you initially see the thumbnail image for a second but then it changes so the video is paused on the 1st frame. You can see this here: https://xot310beta.dlearning.nl/play.php?template_id=74#page5 it pauses on white screen. It should show the Xerte logo frame instead until it's played: https://xerte.nottingham.ac.uk/play_41125#page5

- [ ] When YouTube is used you don't see the play button in the centre of the video. Even when hovering over the video player, no controls become visible. You can click to play/pause but can't skip forwards etc.
