### ISSUE TITLE
Twittercard bug in SCORM exports

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1076]
The %TWITTERCARD% text can be seen at the top of SCORM exports:
![scormTwitter](https://user-images.githubusercontent.com/8926470/152364458-2423ac89-76df-4d5d-b714-ff75b6eeeab0.PNG)

**Comment by JohnSmith-LT** [comment]
Hi @FayCross does this fix it for you?

**Comment by FayCross** [comment]
@JohnSmith-LT yes, that's fine now. Thanks
