### ISSUE TITLE
3D image page 

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#1094]
I got this request. "We now have the 360° image. But we would also love to have a page for 3D images. So you can walk around a 3D figure and see it from all sides can view. And then on with options for adding hotspots, audio, interactions (go to page)."
Is this something we can do?

**Comment by FayCross** [comment]
[Online 3D Viewer](https://github.com/kovacsv/Online3DViewer) allows you to embed 3D models ([e.g. embed in Xerte page](https://xerte.nottingham.ac.uk/play_40066)). It's open source so might be possible to properly integrate into a new Xerte page with hotspots etc.

**Comment by mehmetakin1996** [comment]
Can I create a free account?
