### ISSUE TITLE
Drag & drop labelling bug

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1097]
Labels placed on drag & drop label page don't adjust to be in the correct position if page changes size:

![dragdrop](https://user-images.githubusercontent.com/8926470/167860197-a75be597-b2a2-4936-b9be-48c729e07d6f.PNG)

**Comment by JohnSmith-LT** [comment]
This is very similar to the bug that kept giving back in 2020 #980
We thought it was fixed but maybe there were other things that didn't get tested correctly.

**Comment by FayCross** [comment]
Yes, I thought this was an old problem that had been fixed too. The page model hasn't been changed for a couple of years though so I don't think it's a new change that's reintroduced it.

**Comment by JohnSmith-LT** [comment]
Could try rolling back to before those fixes and see if it worked then and whether the fixes for the returning to the page introduced the resize issue or whether it existed prior to this bug also...
