### ISSUE TITLE
controlling what happens after clicking download on the results page

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1098]
Issue reported on the forums https://xerte.org.uk/index.php/en/forum/bugs-and-issues/2862-pdf-document-downloaded-from-results-page-does-not-display-all-text-cuts-off#8093 this was a report of two separate issues:

#1 truncated text in the pdf 
Tom had already fixed this and is in 3.10.5

#2 Different browsers behaving differently after clicking the download button
The report was that the LO closes or minimises but in my testing (and I think Tom's testing) each browser can be different e.g.
when clicking the download button on the results page:
Chrome – prompts to download the pdf and the LO remains open in the background.
Edge – same as Chrome.
Firefox – opens the pdf in the tab occupied by the LO so replacing the LO. I can chose the download button top right and then use the Firefox back button to return to the LO.
I suspect there are browser preferences and/or programme defaults at play here that determine how each browser responds when launching the pdf. I’m not sure it’s anything that we can control with Xerte code but worth looking into. e.g. from memory is there something that controls whether something is seen as an attachment for download rather than opening in the browser? Or can we somehow force a new window so that the LO remains open?

**Comment by JohnSmith-LT** [comment]
Hi @torinfo @ronm123 @FayCross

I've changed the code for this slightly (using the FileSaver library) as suggested by the thread at the link above and modified it for Firefox 98+ detection only.

It seems to work the same as the window.open but perhaps gives us more opportunity for changing the blob in future to make it possible to get back to similar functionality for Firefox 98+. Might also let us do some other things with the blob that jsPDF cannot, in the future.

When you get time can you check that this hasn't broken anything that you already have working.

**Comment by JohnSmith-LT** [comment]
This appears to have been fixed in FF 101 which is in beta just now...

https://bugzilla.mozilla.org/show_bug.cgi?id=1756980

**Comment by ronm123** [comment]
@JohnSmith-LT just tested your commit for this and yes now in FF it opens in a new tab and automatically downloads. I guess even if it's fixed in FF 101 we should keep the new tab for now because it will take a while before people have upgraded?

**Comment by JohnSmith-LT** [comment]
Yeah @ronm123 I think this is the best that we are going to get for these FF  versions. If it is fixed in FF101 then we have the option of only using the new method only for FF98/99/100 and then reverting to the old method or alternatively we could just make the new code that i've added the default way because it appears to work the same as before in Chrome and Edge by bringing up the Save As dialog - not sure about Safari though. What do you thing @torinfo ?

I'll leave it open to see if @FayCross wants to test.

**Comment by JohnSmith-LT** [comment]
Don't worry about it @FayCross, i've just been working through some of the issues - they'll get closed when they get closed! :-D
