### ISSUE TITLE
Default values for text in xwds

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1111]
Should we start to move away from the way we use the default text in fields within the editor? At the moment, you have to override strings like 'Enter Page Title here' with the text you want to use instead. Would it be better to have these fields empty by default instead? 

As long as the fields are labelled sensibly and have a tooltip hint with extra info if needed they don't need the default text. I see so many projects that give feedback 'Enter feedback here' or image alt text as 'Enter description for accessibility'. We could add placeholder text in the fields that automatically disappears when you start to type if needed.

**Comment by torinfo** [comment]
@FayCross I'll check, but an added attribute is automatically translatbale. I need to do something to prevent tarsnlation (for example  for 'file' attribute of scenePos and position nodes of media360?
