### ISSUE TITLE
Change format of glossary

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1115]
Glossary button opens a table containing glossary terms and their descriptions. This might be better done using a description list: https://www.w3.org/WAI/WCAG21/Techniques/html/H40

**Comment by JohnSmith-LT** [comment]
Hi @FayCross not sure if you've seen this article which suggests that VoiceOver and NVDA both don't do well with definition lists and that their findings suggest that a table or unordered list is still the best, with use of scopes and roles...

https://snook.ca/archives/html_and_css/definition-lists-v-tables

It was written 10 years ago so not sure if it still hold up but probably worth looking into before we spend a lot of time reworking this.

**Comment by FayCross** [comment]
@JohnSmith-LT interesting - I will have to do some testing. We could just leave it as a table - perhaps with a header row with 'term' & 'definition'

**Comment by JohnSmith-LT** [comment]
Maybe try finding some more recent guidance on this. Personally I don't think there's anything wrong with using a table like this but perhaps the markup could be improved upon to make it more accessible...

I will have a hunt when I get time and post anything here that I find that is more recent... Perhaps NVDA, VoiceOver and other screen readers are better at dealing with the mentioned issues than they were 10 years ago...

**Comment by FayCross** [comment]
@JohnSmith-LT I tried it with NVDA yesterday a definition list of two terms and definitions was announced as 'list containing four items' and didn't make it clear that the term and definition were related in any way. I will close
