### ISSUE TITLE
New back to top button optional properties - issue and questions?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1118]
Have just committed back to top button optional properties for the Bootstrap template https://github.com/thexerteproject/xerteonlinetoolkits/commit/24c4b33aa32388920351c2c330764ad5fd85bb17 but there's an issue that I can't spot why and also some questions:

1. Option to hide the back to top button - works fine. Keeping this at LO level for all pages for now.

2. Option to change to a circle with an up arrow rather than the word Top - works fine. Have kept this quite small so it's unobtrusive - do you think the size is ok? 
Do you think the default styling is ok?
Once the issue is resolved (see below) will had some tweaking to some of the themes e.g. the Dark: Black & Grey theme at least.

3. Have styled the circle by adding a new .top-round class so as not to impact existing projects that have custom styled btn-mini. Can't see any reason this would be a problem and seems better to do it this way. Any reason not to do it this way?

4. Issue: Have added this in application.js where the default back to top button got added but when the optional property group is added and change to a circle selected and then custom colours chosen for some reason this changes all the buttons except the last one and I can see why. Can anyone spot why and resolve this? @JohnSmith-LT @torinfo @FayCross any ideas?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 does that fix it for you?

That section runs every time a section is added so your code was running 15 times in my test (15 sections). That's fine but your selector $(".top-round") was equally running for that section and every one that went before so it was changing 1, then 2, then 3, all the way to end... still not sure why that was an issue though.

I've rewritten to create the button, apply your code only to that one button, then add the button. Not the ideal way to do it - ideally we'd just attach the handlers once, using $(".top-round") after the loop is exited but I can't see the best place to do this off the top of my head. I think that file could do with a bit of restructuring but maybe now isn't the best time too start that...

**Comment by JohnSmith-LT** [comment]
You could also create two new css rules for the optional colours and then just add or remove the two css classes to show the two states.

**Comment by ronm123** [comment]
@JohnSmith-LT thanks John I can see that at least changes all the buttons now and so works but yes I wasn't sure where to put this and it would probably be better to split it up so that the check whether to hide the button and so not add it, use the default button or change to a circle is where it is now but the style of the circle is moved elsewhere. I just couldn't work out the best place.

**Comment by JohnSmith-LT** [comment]
Yeah, I had a quick look @ronm123 and couldn't see straight away off the top of my head where best to put it. I'll take another look later if you want and relocate it.

**Comment by ronm123** [comment]
@JohnSmith-LT if any of it needs changing feel free. It obviously needs to run on page load and page change and initially tried where I thought that should be but then it wasn’t picking up the optional properties and probably something I was doing wrong. Also I did think about adding additional classes for the hover colours etc but looked at how we were already dealing with optional hover colour on the nav bar and so followed the same method with jquery .hover etc.

**Comment by ronm123** [comment]
@JohnSmith-LT thanks for your help with this. I've just committed a change https://github.com/thexerteproject/xerteonlinetoolkits/commit/04ef266e999ece8dbfb94cb1d97a9e8c0bcae24f with the description:
improve the efficiency of the optional back to top button code e.g. only check if the button is hidden or set to round in the loadSection function, then apply the additional optional styling at the end of the loadPage function, so after all the sections have been created.
That seems like it's likely to be more efficient to me because the extra styling is then only happening  on page load or on page change but I may be mistaken?

**Comment by FayCross** [comment]
@ronm123 a minor thing but should there be some extra space beneath each section when the back to top button is hidden? The titles end up being closer to the section text above than the section text it's the title for

**Comment by ronm123** [comment]
@FayCross I'm sure both those things can be resolved. Let's discuss at 4pm.
Re the extra space needed if the button is hidden. I didn't actually add anything to hide the button it's just that we wrapped what was already there in a condition that checked for not being hidden and in the original button code there is a <P> around the button that now doesn't exist if the condition isn't met. Will probably have to look at adding that <p> back in if the button is hidden.
I wonder about whether the text is needed for screen reader users and in fact the link should be hidden for screen reader users?

**Comment by FayCross** [comment]
@ronm123 I'm closing this as I can't see any outstanding issues in comments above. Please reopen if there's still some outstanding work to do
