### ISSUE TITLE
auto columns option for plain text page (and other pages?)

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1123]
@JohnSmith-LT @FayCross @torinfo 
I've committed the new auto columns optional properties for the plain text page https://github.com/thexerteproject/xerteonlinetoolkits/commit/07271b543aff9565b0b51f5c6f8843add59cfe04
I think even if we don't add this anywhere else, it's useful for the plain text page. The options include how many columns, gap/gutter size and ruler style, width and colour. e.g.
![image](https://user-images.githubusercontent.com/5167146/174796870-528259ca-7de3-4eef-9268-3746c4fb2ccd.png)
Please try it out and let me know if there are any issues or changes needed?
I'd like to add similar functionality to the multi-navigator (obviously not the columns option on that page) but might depend on when we think we are ready to release. There are some other pages that it would be useful for too but less important I think.

**Comment by FayCross** [comment]
@ronm123 works well!

**Comment by ronm123** [comment]
Thanks for testing @FayCross @JohnSmith-LT I'll close this now. Would like to add similar functionality to the multi-navigator but that's slightly more complicated because it would need to be per navigator pane so might have to wait until a later release.
