### ISSUE TITLE
Import pages into an empty project bug

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1131]
The editor breaks if you attempt to import pages from another project into a project containing no pages. The page tree on left goes blank and you have to refresh the editor to get it working again. After refresh you can see that the pages were imported successfully. Importing pages into a project that is not empty works fine

**Comment by ronm123** [comment]
@FayCross I think I found this previously but can't remember if I added it as an issue or just discussed via email or verbally but it's been there a while I think.

**Comment by FayCross** [comment]
This is fixed in 3.12
