### ISSUE TITLE
Sortable Grid issue

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#1132]
If two draggables have the same answer then shouldn't they preferably be interchangable?

![image](https://user-images.githubusercontent.com/3907362/176781633-ef74f6b4-9855-456b-acb7-56ffc667e4de.png)

**Comment by torinfo** [comment]
Don't even start that... :-)

**Comment by JohnSmith-LT** [comment]
I knew you were having issues with this page @torinfo so that was a little bit tongue-in-cheek but I do think it's a valid point although maybe not for today to fix ;-) - if you want (after this release is over) to open an issue and list some of the things that are still outstanding with this page then I will take a look at it and see if a fresh pair of eyes could help - a link to any examples you have would be helpful also to give me a reference...

I know what you mean @FayCross but on the other hand I think this could be a really useful page and I have a couple of things that it could be used for that would be hard to do otherwise - perhaps it just needs refactored a little and then it will become clearer where the issues are - there are a few pages like that that I think could be really great pages but get let down by the few annoying bugs - gap fill and drag-drop style pages have had more issues through the years than they have had features which may also be putting people off using them which is a shame because they are some of the best pages we have with the most potential...

**Comment by ronm123** [comment]
Hi all
I had it reported that the the small, medium, large settings do not appear to change the size of the grid. Actually on my tests the options do make a change but not consistent with what you might expect e.g. see attached:
![image](https://user-images.githubusercontent.com/5167146/178312688-a8a5ecb9-f2df-42af-b410-af2e3f4e50d2.png)

**Comment by torinfo** [comment]
@ronm123 @FayCross The actual grid will never be larger than needed. This might result in what you see above. However if you make tthe window narrower you see the difference again. So the grid in image 3 has all the space it needs, without wrapping the contents in a cell. Than making it larger (as in 4) does not change the appearance of the grid.

In this case it would have been cleaner to set the width of the text in stead of the size of the grid. Because that does change. Don't know if we can still change that....

**Comment by ronm123** [comment]
@torinfo @FayCross a few comments...

I think one of the problems is how similar options work on other pages (mostly with images) so I think there's probably an expectation that the options here work the same.
1. Grid size = small doesn't seem right
4. Grid size = full  hides the page text (like full options on other pages) but I suspect users will expect that to fill the window.

I'm sure Fay will have further thoughts on this but one possibility is to just remove some of those size options to make it simpler or to add some further clarification in the tooltips.

**Comment by FayCross** [comment]
Closing as first issue is fixed. Size issues are discussed in this other bug: https://github.com/thexerteproject/xerteonlinetoolkits/issues/544
