### ISSUE TITLE
test and document what can and can't be used in page ID names

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1135]
Just adding this as an issue after we troubleshooted the clash between page ID names in Bootstrap and the scroll highlighting.

@JohnSmith-LT added a fix for when periods have been used in pageID names. Using periods didn't impact linking to those pages but did clash with the scroll highlighting of the section menu.

It seems brackets in page ID names cause that issue too but underscores are fine.

So it seems there is a difference between what works for linking purpose in Bootstrap and XOT vs what works for scroll highlighting in Bootstrap.

John suggested we should update the tooltip info in both wizards but we probably need to verify what is and isn't ok before we do so.

**Comment by FayCross** [comment]
I've done some testing in Bootstrap and pretty much all symbols in pageIDs stop either the correct page being selected, or stop the section menu from highlighting correctly. The only symbols that you can use are - and _
