### ISSUE TITLE
some issues with image sequence page

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1136]
@FayCross @torinfo just adding some notes about this while fresh in my mind...

1. As discussed via email - would be good if the speed option could be used to slow down the speed of image change even when there are just a relatively small number of images.
2. I noticed a bug or two when importing an image sequence page from one LO to another. This might not be specific to the image sequence page and could be an issue with import pages when sub folders and/or a number of images are included.
Steps to reproduce: Create a new project and add a title page to avoid the known bug with import pages into an empty project.
Select import pages and browse to the xot page types demo and select the image sequence page.
The import will appear to work and the image sequence page will contain the correct structure but the sub folders with images only contain the first and last images not all 40 or more images e.g. series1 should contain 1-41 but only contains 1 & 41:
![image](https://user-images.githubusercontent.com/5167146/178307021-5a974190-447c-4df4-ac6c-a4a36dbfce7d.png)
I wondered if this might be because those images contain a comma in the filename but I did a test with the commas removed and got the same issue.
3. The other thing I noticed while testing this which may just be a limitation of the media browser/upload rather than a bug as such - when manually creating an image sequence page and creating a folder to contain the images and then browsing to upload a set of 41 images by selecting all - it only seems to upload 20 at a time which is easily missed. I then had to select images 21-40 and so on to upload the complete set. If this is a limitation of this method of uploading we should document it somewhere and perhaps in the guidance in the image sequence wizard.

**Comment by torinfo** [comment]
Regarding 3. Could this be a php setting: max_file_uploads?

**Comment by torinfo** [comment]
Regarding 2. Bleeh. That is no fun at all.... Only the first and the last filename are set in the xml. The intermediate files are not. So... according to the code, those files are not used, and so, they are not copied.

The same happens in the media and quota pannel. All the files except the first and last are marked as not used...

Not sure yet how to best fix this.

**Comment by ronm123** [comment]
@torinfo re 3 sorry I didn't even think about that but yes you're right max_file_uploads is the restriction.
I guess that rarely crops up as an issue but in my xampp and I guess also on xot.xerte.org.uk the default values of 20 is set. I changed that in xampp to 60 and could then upload the set of 41 images in one go. I'll add a note about that in the section about this page in the release notes but should we also add something about this in the wizard? e.g. Note: due to default server settings you may only be able to upload 20 images at a time. Simply repeat the upload step until all of your images are uploaded.

Re 2 would an option be to automatically include the 'in-between' images in the xml (without having to select them all) even though they aren't needed for the page to work?

**Comment by torinfo** [comment]
Issue 2 is fixed by commit 24ee9e49e269988f50d929d067931f0e4d78af06

**Comment by FayCross** [comment]
@torinfo - thanks for looking at issue 2. Specifying the first and last images was the only easy way I could see of creating this page. Much too time consuming to select every image individually in the editor!

@ronm123 - I'll have a look into issue 1 (play speed) tomorrow

**Comment by ronm123** [comment]
@FayCross while you're doing that was it also meant to be limited to 0 to 1? Might be worth changing what is displayed even if the values used are 0.1 0.2 etc or perhaps just adding a tooltip.
