### ISSUE TITLE
New feature - project introduction optional property

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1140]
Add new optional property group to project level that allows you to add instructions / introduction for the whole project. This would add a new button to footer bar and info would open in a light box when button is clicked. The optional property group should allow you to edit:

- Project intro text
- Whether the intro lightbox is opened automatically when project 1st opens
- Whether to include a 'start' button in the lightbox which closes the lightbox (probably only useful if the lightbox is set to auto-open on project load)
- If set to auto-open on project load, should this happen if project is not loaded on first page?
- Include project title in lightbox?
- Icon & label used on button

**Comment by FayCross** [comment]
This is almost complete - I've committed the code for this to work but the following themes that use images for buttons need an info image creating for the footer button:

- [ ] Xerte Online Toolkits
- [ ]  Dark: Grey
- [ ]  Flat: Blue
- [ ]  Flat: Orange & Purple
- [ ]  Flat: Red
- [ ]  Flat: White
- [ ]  Informal: Sketch
- [ ]  Modern: Django
- [ ]  Simple: Black & White

**Comment by ronm123** [comment]
@FayCross I can probably help with those buttons - will have a look next week.

**Comment by ronm123** [comment]
@FayCross I've created and committed all the project_intro buttons for these themes but there are some remaining issues and things to discuss during our meeting on Wednesday. 

One of the issues is an alignment or width setting that I can't work out. This happens on all the FA icon themes but lets use the Dark: blue grey as a reference. Add a project intro and without ticking the box to customise the icon view the project - all is fine with the alignment and spacing of the button comparable to the others.
Now tick the box to customise the button icon and without changing the default icon view the project - typically the i is a bit too large and positioned to the left with extra space on the right before the next button in my case the glossary button.
Now change that icon to info-circle instead - the alignment, spacing and size is comparable to the others again.
I can't work out why this is the case or what to add to fix it and ideally without having to change every FA theme. Perhaps just changing the default to info-circle instead? Bit then what if a user changes it to info?
Hope this makes sense and I can demo during the meeting.

Examples:
Without custom icon selected:
![image](https://user-images.githubusercontent.com/5167146/180986750-780a148d-1155-46ba-95af-691decddd28b.png)

With custom selected and current default icon:
![image](https://user-images.githubusercontent.com/5167146/180986871-bc6510c6-fc36-42d3-b791-deb83b769987.png)

With custom selected and changes to info circle:
![image](https://user-images.githubusercontent.com/5167146/180986973-bfa19d24-1487-4b36-b1b2-e660303bfeae.png)
