### ISSUE TITLE
Answer X of Y page not marking correctly

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1148]
This page no longer works https://xot.xerte.org.uk/play_116#answerxofy 
All answers are marked as incorrect

**Comment by FayCross** [comment]
@torinfo the fix for this bug needs to go to master as the Answer X of Y page no longer worked, unless the delimiter optional property wasn't added

**Comment by torinfo** [comment]
@FayCross Thanks for the fix. pushed to master.
