### ISSUE TITLE
narrow display of transcript on media > video page

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1152]
Adding this after having it reported and will check the model file after posting. It seems the display of the optional transcript in 3.11 (and possibly earlier) has become an issue in two ways:
1. it displays as a narrow column rather than filling the width of the video
2. it displays over the top of the panel rather than expanding the height of the panel

Both of these issue can be seen in the screenshot below and via the test I created at https://xotbeta.dlearning.nl/play.php?template_id=112#page1 

![image](https://user-images.githubusercontent.com/5167146/183685498-4825d32f-d5f1-4ee9-b080-07005baccf0f.png)

**Comment by ronm123** [comment]
@JohnSmith-LT @torinfo @FayCross sorry I'm not sure who last worked on this page but I know there's potentially some overlap with the popcorn developments. Anyway I might be wrong but as far as I can see there are two places in the textVideo model where the width of the transcript divs are meant to be controlled e.g.
120
if ($("#transcriptHolder").length > 0) {
$("#transcript").width($pageVideo.width());
}			
185
if ($("#transcriptHolder").length > 0) {
$("#transcript").width(videoDimensions[0]);
}
and I think the first issue is they are referencing ID's but should be classes instead e.g. the conditions don't seem to be triggered because of this?

I checked the similar code in the textGraphics model and in there they are IDs rather than classes and work fine.

So I tried changing the conditions in the textVideo model to use classes instead and that worked to a certain extent in that the width of the transcript became closer to what it should be but the layout still wasn't correct and in any case the panel should also fit the video and expand accordingly when the transcript button is clicked and that isn't happening either. So I've removed my test changes and will leave this to whoever is most familiar with this model and related code.

**Comment by JohnSmith-LT** [comment]
This has been stopped with https://github.com/thexerteproject/xerteonlinetoolkits/commit/f5c8770ffe62f46c494948995ee5869d6935ed09 but I feel that these pages still need some work - the transcript makes the video really small which makes it hard to watch without going full screen...

**Comment by ronm123** [comment]
@JohnSmith-LT I've imported my local test project into xotbeta and shared co-author access with your account but also made that public so you cab view via https://xotbeta.dlearning.nl/play.php?template_id=115#page1 
The test contains a graphic and sound page with transcript added and then 3 video pages all with transcript added 1st with local video, second with YouTube and 3rd with Panopto embed code. Not sure what you mean about the video going really small but as you'll see in this test project the size of each video and the size of the panel and how the transcript displays when opened varies with each. In fact not sure why but the transcript button and transcript doesn't even show in the Panopto example.

**Comment by JohnSmith-LT** [comment]
Go to page 3 @ronm123 and open the transcript. Then resize a little and you get this:

![image](https://user-images.githubusercontent.com/3907362/189146865-dee88403-0218-4dbe-bc67-5c6306efe832.png)

**Comment by ronm123** [comment]
@JohnSmith-LT just noticed that if you do that resizing when on page 3 and then navigate to page 2 then the size of the local video and everything else on that page is screwed up too:
![image](https://user-images.githubusercontent.com/5167146/189155189-a66ca921-b2ef-4149-8ddb-4dd235ec8bf1.png)

**Comment by FayCross** [comment]
@ronm123 @JohnSmith-LT closing this as I've committed fix to panel resize bug wheb transcript opened. I can no longer recreate the bug John found with small video after resize - it's possible Tom's recent video sizing commit has fixed this - reopen if you can still see this bug
