### ISSUE TITLE
publish from workspace button results in session expired error

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1156]
Reported via forums https://www.xerte.org.uk/index.php/en/forum/installation/2944-click-publish-button-get-session-is-invalid-or-expired#8320

Not sure when this bug crept in but can replicate in 3.11x and develop.

**Comment by torinfo** [comment]
Fixed by 7fe333ace7fec878fdd57ecd43f88d761a63e3a6
