### ISSUE TITLE
Using variables in answers of a question does not work as expected if Glossary is enabled

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#1161]
See https://xotbeta.dlearning.nl/play.php?template_id=114#page3 (which is working) and https://xotbeta.dlearning.nl/play.php?template_id=114#page4 (which is a copy).

On page3 Glossary is disabled, on Page 4 is enabled.

What is used is something like thsi:
[BWM1A] %

or

€ [BWM1A]

If Glossary is enabled, the % disaapears or the number dissapears (only € is left)

**Comment by JohnSmith-LT** [comment]
Think that is it fixed @torinfo, you can now even add glossary terms into the questions and they appear to work correctly.

![image](https://user-images.githubusercontent.com/3907362/189198082-f88f0ae8-3fe0-48d9-adae-304606019810.png)
