### ISSUE TITLE
Some files are not recognised as being in use

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#1162]
When a filename contains certain characaters (such as &) they are not always recognised as being in use in Media and Quota panel

This has to do with encoding (In the XML file, the & is encoded as & amp;
Smae problem can occur with & nbsp;

**Comment by FayCross** [comment]
@torinfo is this one fixed? If not, should we hold off including the bulk delete of unused media in the next release? We could easily have people deleting lots of files that are in use if it's not detecting correctly

**Comment by torinfo** [comment]
I am not sure, I'll check. I'll fix it before the release (it has to do with the encoding of special characters in the file name like ë and é
