### ISSUE TITLE
Gap fill drag drop marking incorrect on results page

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1175]
There's a bug in gap fill page which means it's no longer marked correctly when viewing results page.
Old working version:
![gapfill1](https://user-images.githubusercontent.com/8926470/202733571-edc3c0da-563a-43d7-99db-311d4701cdd7.PNG)

Bug version:
![gapfill2](https://user-images.githubusercontent.com/8926470/202733598-20ab6344-9a9d-476a-bce3-81151c8a77de.PNG)

Looks like it was introduced with this commit: https://github.com/thexerteproject/xerteonlinetoolkits/commit/e88e50a7f9c6ea7e15eda1390e9675a547f37810 @torinfo

**Comment by torinfo** [comment]
The commit you mentioned was just one part of the changes. The biggest change I think is the change from a fill-in to a match interaction, because really drage and drop is a match exercise.

Obviously the tracking is incorrect as it is now.
