### ISSUE TITLE
Standalone page (in lightbox) not being tracked

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#1179]
Standalone pages are not tracked and/or shown in the results page

This is caused by the fact that they are generally started as a new session in a lightbox and there is (at the moment) no relation with the page where we started from.

**Comment by torinfo** [comment]
I fixed this for a standalone page from the same LO that is shown in a lightbox.

It required some extra code to detect this sitaution, and than piggy back on the tracking state of the parent object.

**Comment by FayCross** [comment]
@torinfo is this in master? Might be worth adding to release notes

**Comment by torinfo** [comment]
Fixed in bb2a214171b3beec25be4ee9f664b8c1635ccb62

**Comment by torinfo** [comment]
@FayCross No, this is only in 3.12, and yes good idea to add to release notes. This also effected the results page in non-tracking situations

**Comment by FayCross** [comment]
I've added this to English release notes (@ingedonke - you might want to copy this to Dutch release notes)

**Comment by ingedonke** [comment]
Hi Fay,

I tried to add it but John was editting the release notes. So I send him a question to close it. I asume it's closed now?

I'll take a look :)

Bye, Inge

FayCross ***@***.***> schreef op 17 februari 2023 11:53:53 CET:
