### ISSUE TITLE
Flexible gap fill spaces

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1184]
This was requested via the forum but is a good idea: 
_In a drag-and-drop gap fill, all the gaps are as wide as the widest content. This can lead to over-wide gaps. Would it be possible to have narrower gaps initially, which then expand to fit the text that is dragged into them?_

[Forum post](https://www.xerte.org.uk/index.php/en/forum/wish-list/2978-flexible-gap-fills#8427)

**Comment by JMarco27** [comment]
I'd support this request.  There isn't a page type which requires learners to put elements of a sentence in the correct order, so that it looks like a sentence when completed, and this type of gap fill would meet that need. Very useful in language learning.
