### ISSUE TITLE
Link to wiki pages from editor

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1185]
Link to new wiki pages for each page type from editor

**Comment by FayCross** [comment]
@ronm123 @torinfo I've just added a link to wiki pages from editor. Have a look and let me know what you think - do you think the link icon needs to be different to the icon used for property tooltips? I have put the links in the xwd files as I think this is probably a better way of linking to wiki pages in different languages than auto-generating a link based on the page's name (we'd also need to change the wiki URLs to so it this way).

**Comment by ronm123** [comment]
@FayCross @torinfo works well! How about using fa-list-alt as the icon? I think it would be better to use a different icon than the one used for tooltips and after a quick search fa-list-alt seemed to me to mimic the toc style of the wiki. But there may be a better FA icon that I didn't spot?

**Comment by torinfo** [comment]
@FayCross @ronm123 This is great, and yes, I think a different icon would be best.

**Comment by FayCross** [comment]
@ronm123 @torinfo I knew you'd both say that but I was being lazy ;) I'll have a look to see what's best and change it
