### ISSUE TITLE
Section title not showing correctly when clicking on a menu item

### ISSUE THREAD

**Issue by Albertovh** [thexerteproject/xerteonlinetoolkits#1190]
Section title not showing correctly when clicking on a menu item

![image](https://user-images.githubusercontent.com/47412828/215101727-8fbad6a3-bcb2-43a5-a939-e034a18c6762.png)

**Comment by FayCross** [comment]
@Albertovh I'm afraid this is another I can't recreate. Can you share a link to the project you are having problems with?
