### ISSUE TITLE
Correction to text for Hints on Gap Fill page

### ISSUE THREAD

**Issue by JMarco27** [thexerteproject/xerteonlinetoolkits#1199]
Can we correct the text for this?
![image](https://user-images.githubusercontent.com/106071385/223378141-ef96164c-3922-422e-b6ae-ea652d52e954.png)

There is no Hint/Correct Answers **Button**, so it potentially confuses.  Can we replace the text with "Show Hints" or "Hide/Unhide Hints"?

**Comment by AdachiTK** [comment]
This setting has a double purpose - it will 'Show Hint' in the default gap fill conditions, but also there is a button that appears when 'Mark at End' OP is enabled, after the Check button has been pressed the specified number of times.  However this is labelled "Show Answers", not "Correct Answers", so agree that correcting the text to reflect this would be good.

**Comment by FayCross** [comment]
@JMarco27 @AdachiTK I've made the following changes:
- Label is now 'Show Hint/Correct Answers' to cover both uses of this check box
- Tooltip added to hints optional property group: 'Show a hint tooltip (fill in blank) or show answers button (drag drop/drop down menu) if answered incorrectly'
- The hints optional property group will not be shown when the interactivity type is drag drop and it is not set to mark at end as no hint/show answers button can be shown in these circumstances
- The mark at end optional property group will not be shown if interactivity type is drop down menu as it will always mark via a button click and not immediately
- Tooltip added to mark at end optional property: 'Allow incorrect answers to be entered or dragged before marking when the check button is clicked'

I can change any of these if you would like different wording
