### ISSUE TITLE
Themes with image buttons - in sidebar only a small part of the button is shown

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#1218]
@FayCross 
We've got loads of custom thmes and we're working through the changes. However, we still have an issue with thems using images. The Home button shows only a part of the image when the sidebar is enabled.

The same issue exists in flat blue. Do you have a solution for flat blue?

![image](https://github.com/thexerteproject/xerteonlinetoolkits/assets/5166596/652ead73-f21f-4aed-9c47-a54dc87bbaef)

**Comment by FayCross** [comment]
@torinfo let me know if this fixes it. Thanks
