### ISSUE TITLE
When Responsive Text is enabled, the Default Text Size should be ignored

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#1222]
When Responsive Text is enabled, the Default Text Size is not ignored. If the Default Text Size is set to a l;arger value than default (12) the navigation buttons are cut off if the buttons are font-awesome buttons. See also #1223

![image](https://github.com/thexerteproject/xerteonlinetoolkits/assets/5166596/9cc97121-68a7-4ca2-a4e8-2b8760ade08a)

**Comment by ronm123** [comment]
@torinfo I've lost track of this but I just tested on a 3.10x install and checked existing projects as well as creating a new project...

The same issue existed in 3.10 so isn't to do with hiding the text size option.
More importantly the default Text size in 3.10 was 12 not 14 and is 12 in develop too. Although at the moment I'm only looking at the editor option numbers not the CSS. Where did you get a default of 14 from?

**Comment by torinfo** [comment]
@ronm123 You are right default is 12.

I agree that it has nothing to do with hiding the default text size value. But hiding the Text size value suggests that the Default Text Size doesn't do anything when Responsive Text is enabled. And that is not the case.

I also agree with you that we should change it so that the default text size will not impact the footer buttons at all. I created #1223 for that.

**Comment by torinfo** [comment]
See #1223 for the remaining issues
