### ISSUE TITLE
Workspace does not show newly created projects

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#1232]
When creating a new project, the workspace is not updated. It requires a refresh to see it.

**Comment by ronm123** [comment]
@torinfo I think you fixed this and committed it to both develop and to the latest download. However I've just been alerted to a slightly different issue with 3.12.16 which may or may not be related...
e.g. create a new project (either XOT or Bootstrap) and yes the tree in the left pane shows the new project but the right pane where you named the new project isn't refreshed so the text box and the name you typed remains visible.
I tested the same thing on a 3.11 install and with 3.11 (and presumably earlier versions too) the right pane is cleared and the form field and title removed.

**Comment by torinfo** [comment]
@ronm123 I'll have a look.

**Comment by torinfo** [comment]
The project not showing up in the tree was indeed fixed (17a96f9bc4ee78b27286aa56891b43f392b0cabf)
