### ISSUE TITLE
Should connector pages still have navigation buttons turned off by default?

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1246]
I've wondered this for a while and now someone at UoN has also commented on this. All connector pages have navigation buttons optional property added by default with the buttons turned off. What do you think about removing this so it has to be added via optional properties if needed instead? @torinfo @ronm123 

There are lots of examples where disabling the buttons is not appropriate - particularly with hotspot image connector where it is now often used as a click explore activity rather than click to navigate. I find that more often than not, when I am telling someone how to use the pages, I tell them to remove the navigation buttons optional property straight away anyway. Thoughts?

**Comment by ronm123** [comment]
@FayCross I guess changing it to an optional property would make it consistent with other page types although presumably would not impact existing projects/pages where the nav buttons options were added by default.
I guess one question would be whether it then becomes the same as the option for other/all pages or remains different for the connectors e.g. when you add to other pages all the button options are checked by default but with the connectors only the save session button is checked by default. I think it would be best to keep it that way for the connectors but just change to an optional property. I guess @torinfo will have thoughts about this given the heavy use of hotspot connector by Deltion etc?

**Comment by FayCross** [comment]
It would be removed from newly added pages - so no, it wouldn't affect any existing pages. We'd need to change some editor code if we wanted it to have boxes unchecked initially when the optional property is first added as I don't think there's a way at the moment for general optional properties to have different default values depending on the page they are added to.

**Comment by ronm123** [comment]
@FayCross as there are only 3 connector pages I was thinking we should just keep it as it is but just change to optional rather than  change it to the navigation buttons general property and so that way could have different checks to the general property?

**Comment by ingedonke** [comment]
Good idea to make this an optional property just like the other pages and that for new pages the default stat is the same as for the other pages :)
