### ISSUE TITLE
Colour contrast accessibility in Bootstrap Blue & Grey theme

### ISSUE THREAD

**Issue by takadachi** [thexerteproject/xerteonlinetoolkits#1256]
The $brightcolor value #0098C3 is flagged up by accessibility checker (e.g. WAVE) as not having enough contrast with white.  Suggested value is #007395.

**Comment by FayCross** [comment]
@takadachi It looks like this was fixed sometime ago (https://github.com/thexerteproject/xerteonlinetoolkits/commit/d51fb0d15d2fed831448f9f778e4b322339ec0c4 3.12?)
