### ISSUE TITLE
confirmation pop-ups in Firefox?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1257]
Hi all
I was testing sharing functionality via management and noticed an issue with confirmation boxes but it turns out to be nothing to do with management and only seems to be an issue with Firefox too. But do you get the same issue or is it just my Firefox? To replicate...

Add a shared user to a project as editor or co-author etc and then click to remove them. In Firefox the confirmation dialogue looks like this:
![image](https://github.com/thexerteproject/xerteonlinetoolkits/assets/5167146/8cde0a26-7d55-4922-8bff-8cfe03cf308a)
e.g. no labels/text and also the grey cancel button doesn't work so have to use the Escape key.
The same thing happens in the media & quota tab when trying to delete an item of unused media e.g.
![image](https://github.com/thexerteproject/xerteonlinetoolkits/assets/5167146/a1b2860d-abcd-4eef-a9b0-a15c6ace51f4)
and again clicking the grey button doesn't work.
This probably applies wherever there is a similar confirmation dialogue with Firefox but doesn't happen with Chrome, Edge or Opera.
So do you also get this with Firefox or is it just an issue with my Firefox?
I've cleared offline files so it doesn't seem to be that and I've done a quick search around but couldn't find anything relevant.

**Comment by FayCross** [comment]
@ronm123 I've just tried this and these dialog buttons are showing as normal in my Firefox

**Comment by ronm123** [comment]
@FayCross thanks for checking and confirming. I've done some further testing with my Firefox including clearing offline files again, removing extensions, changing the Firefox theme, private tab etc etc and all still result in the same pop-up issue e.g. no button label and cancel button doesn't work. However then I tested a non-xerte example and it's the same thing! Don't know why it would just be my Firefox but I'll close the issue as it's clearly not a Xerte specific issue. e.g.
https://www.w3schools.com/js/tryit.asp?filename=tryjs_confirm
results in:
![image](https://github.com/thexerteproject/xerteonlinetoolkits/assets/5167146/85854b23-8acb-492e-925a-1f317e07b1e0)

**Comment by torinfo** [comment]
@ronm123 This works fine for me too (Firefox 117.0 and 118.0.2 (64-bits))
