### ISSUE TITLE
Add the pwplay option to the access tab

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1283]
Make the password protected project option (with password set by author) more visible. At the moment you have to turn on peer review, set password there and then edit the peer review URL to change 'peer' to 'pwplay'. This should really be an option in the access tab with password to be able to be set there and then correct URL shown in project details.

**Comment by torinfo** [comment]
@FayCross It is almost ready for the next release.

**Comment by FayCross** [comment]
This is now working in 3.13
