### ISSUE TITLE
current develop 2nd August 2024 can't create new projects and also get session issues

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1298]
I pulled down the latest develop yesterday and now this morning when I try to create any new projects the workspace flashes but no project is created and it doesn't matter what project template I choose. The error is:
![image](https://github.com/user-attachments/assets/7ca6d57e-3a6f-4f0c-a758-ef526e5c8f05)

1326 template_management.js
var options = "height=" + data[2].trim() + ", width=" + data[1].trim();

Also if I try to edit an existing project and then publish or play I get a session error:
![image](https://github.com/user-attachments/assets/7d88e2d5-6516-482b-a06c-644903760af1)

**Comment by torinfo** [comment]
Sorry Ron that I only see this now, but I fixed this later on Friday. It had to do with the check on path_traversal (one of the security fixes of the next release). It took some attempts to get it working properly on both XAMPP and Linux. apologies for any inconvenience

**Comment by ronm123** [comment]
Hi Tom no problem but glad you resolved it. I’ll test tomorrow and close the issue after testing.
You’ve said security fixes for the next release so I’ll assume it’s not likely to happen with 3.12.13 but let me know if that’s not the case.
Cheers
Ron

**Comment by torinfo** [comment]
No, it's only in develop.

On Tuesday, I'll send out the message to known admins about the issues Utrecht found. Using your text.

Cheers,

Tom

Ron Mitchell ***@***.***> schreef op 4 augustus 2024 22:48:02 CEST:
>Hi Tom no problem but glad you resolved it. I’ll test tomorrow and close the issue after testing.
>You’ve said security fixes for the next release so I’ll assume it’s not likely to happen with 3.12.13 but let me know if that’s not the case.
>Cheers
>Ron
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/thexerteproject/xerteonlinetoolkits/issues/1298#issuecomment-2267663932
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Tom Reijnders
DLearning B.V.

Utopialaan 49
Gebouw A
5232 CD 's-Hertogenbosch
Verstuurd vanaf mijn Android-apparaat met K-9 Mail.

**Comment by ronm123** [comment]
@torinfo I pulled down the updated develop (seems like there were a lot of changed files!) and when I visited my usual install I got a blank window.
I set development to true and got Parse error: syntax error, unexpected '?' in H:\xampp\htdocs\develop\functions.php on line 374 and that line is:
$mesg = $message ?? "Path traversal detected!";
I'm guessing that is perhaps php compatibility? As you know I've kept my local xampp install to php 5.6 for testing that backwards compatibility but perhaps that not viable any more?
Anyway I changed it to php 7.2, again for testing backwards compatibility but for now I think we need to maintain this, and now I get an empty workspace, (and management too) and undefined index: toManagement in index.php on line 53.

**Comment by torinfo** [comment]
I'll have a look at that later this afternoon. I am traveling to Barcelona now for a day trip.

Yes, lot's of changes because of potential security fixes identified by Snyk and Qodana.

Cheers,

Tom

Ron Mitchell ***@***.***> schreef op 5 augustus 2024 10:23:20 CEST:
>@torinfo I pulled down the updated develop (seems like there were a lot of changed files!) and when I visited my usual install I got a blank window.
>I set development to true and got Parse error: syntax error, unexpected '?' in H:\xampp\htdocs\develop\functions.php on line 374 and that line is:
>$mesg = $message ?? "Path traversal detected!";
>I'm guessing that is perhaps php compatibility? As you know I've kept my local xampp install to php 5.6 for testing that backwards compatibility but perhaps that not viable any more?
>Anyway I changed it to php 7.2, again for testing backwards compatibility but for now I think we need to maintain this, and now I get an empty workspace, (and management too) and undefined index: toManagement in index.php on line 53.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/thexerteproject/xerteonlinetoolkits/issues/1298#issuecomment-2268465049
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Tom Reijnders
DLearning B.V.

Utopialaan 49
Gebouw A
5232 CD 's-Hertogenbosch
Verstuurd vanaf mijn Android-apparaat met K-9 Mail.

**Comment by torinfo** [comment]
Hi Ron,

Does it work now?

Cheers,

Tom

Ron Mitchell ***@***.***> schreef op 5 augustus 2024 10:23:20 CEST:
>@torinfo I pulled down the updated develop (seems like there were a lot of changed files!) and when I visited my usual install I got a blank window.
>I set development to true and got Parse error: syntax error, unexpected '?' in H:\xampp\htdocs\develop\functions.php on line 374 and that line is:
>$mesg = $message ?? "Path traversal detected!";
>I'm guessing that is perhaps php compatibility? As you know I've kept my local xampp install to php 5.6 for testing that backwards compatibility but perhaps that not viable any more?
>Anyway I changed it to php 7.2, again for testing backwards compatibility but for now I think we need to maintain this, and now I get an empty workspace, (and management too) and undefined index: toManagement in index.php on line 53.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/thexerteproject/xerteonlinetoolkits/issues/1298#issuecomment-2268465049
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Tom Reijnders
DLearning B.V.

Utopialaan 49
Gebouw A
5232 CD 's-Hertogenbosch
Verstuurd vanaf mijn Android-apparaat met K-9 Mail.

**Comment by ronm123** [comment]
@torinfo well first it seems like there's a typo?
e.g. Parse error: syntax error, unexpected ';' in H:\xampp\htdocs\develop\functions.php on line 374
$mesg = ($message != null ? $message ;: "Path traversal detected!");
I removed that ; after message and then that error goes away and I committed that change.
This is with PHP 7.2 and I still got an empty workspace. :-( However then I remembered we've previously had an issue when development is set to true so I set that to false and all seems fine - at least in terms of these initial issues! Management also loads now too but I haven't tested anything else yet,

Wasn't there a fix for allowing development to be set to true when using xampp?
Also with development set to true I do also get some errors flash up then disappear about smtp e.g.
Warning: mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set() in website_code\php\error_library.php on line 213
But maybe that's because development is set to true and/or the change to php 7.2?

**Comment by FayCross** [comment]
@torinfo @ronm123 fixed in 3.13? Can we close?

**Comment by torinfo** [comment]
@FayCross Main issue is resolved (I plan to check $development = true before 21st)

**Comment by torinfo** [comment]
Close for now
