### ISSUE TITLE
Recent changes to mainStyle.css are forcing scroll bars on many themes

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1321]
@torinfo - the change in CSS to the x_pageDiv element in this commit https://github.com/thexerteproject/xerteonlinetoolkits/commit/8875bc70969f084e2afb8279902019cd60d4160a is ok in default theme but causing problems in some other themes (e.g. UoN custom theme now always has scroll bars) as it assumes that the padding on the element is always 10px (e.g. padding in UoN theme is 3vmin). Is it needed (if so we need to check all themes and put a note in release notes that people need to check custom themes) or is there another way of achieving this?

**Comment by ronm123** [comment]
@FayCross @torinfo there surely must be a way to isolate this so that it only impacts the access code/vault and doesn't impact the x_pageDiv anywhere else at all?

**Comment by torinfo** [comment]
@FayCross @ronm123 Yes, I will tweak it.

**Comment by FayCross** [comment]
The way this has been done has been changed by Tom. All ok now
