### ISSUE TITLE
Editor window - show toolbar  

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#134]
Show toolbar is available even when there is no text field on the screen (would rpefer to just leave this to the up / down arrow on the form)
By Julian

**Comment by FayCross** [comment]
I like the show toolbar checkbox as it means you don't have to constantly click the arrows on individual fields. Maybe it could disappear when there aren't any text fields on the wizard though (like the language one only appears when there are lang properties)
