### ISSUE TITLE
Bootstrap - cannot add javascript libraries

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#135]
Cannot add new javascript libraries to the control for bootstrap projects: cannot save the URL
By Julian

**Comment by torinfo** [comment]
I can add a script page, but don't know whther that was the original issue.
I don't understand the words 'libraries' and 'the control' in this context;

**Comment by JohnSmith-LT** [comment]
I suspect your interpretation is right and its been fixed with editor changes and other bootstrap fixes otherwise it would have shown up by now...

**Comment by JohnSmith-LT** [comment]
Fixed with #261 we think...
