### ISSUE TITLE
install of 3.13 failing at page 2

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1361]
Just testing install of 3.13 on local xampp and it seems to be failing at page 2.
Steps to replicate:
complete page 1 changes db name to something relevant e.g. xerte313
enter correct credentials and click next
results in error: **SQLSTATE[HY000] [1049] Unknown database 'xerte313'**
Tried with root credentials and with and without creating the database first and each ends with this error.
Tested the same with 3.12 and works fine.

@FayCross @torinfo do I remember you both having a discussion about this recently?

**Comment by FayCross** [comment]
Tom had a look at this issue a couple of weeks ago: https://github.com/thexerteproject/xerteonlinetoolkits/issues/1358

**Comment by ronm123** [comment]
@FayCross thanks Fay I thought I remembered seeing something. However I just tested that fix and still get the same error. I'll close this issue and reopen https://github.com/thexerteproject/xerteonlinetoolkits/issues/1358
