### ISSUE TITLE
Optional properties - tooltip?

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#139]
Should we have a tooltip for the optional properties buttons so you have some idea what they do?
By Julian

**Comment by torinfo** [comment]
This is implemented in the code already but needs work on the xwd's.

Add `tooltip="Explnation"` to the optional property

**Comment by JohnSmith-LT** [comment]
Confirm that this works as expected

![image](https://cloud.githubusercontent.com/assets/3907362/7811673/1d982c9e-03a4-11e5-957b-6df009082bf2.png)

Going to close and move to a new issue.

**Comment by FayCross** [comment]
Ooo, I didn't know about this. I've added it to the documentation!

**Comment by JohnSmith-LT** [comment]
Great Fay. I've also opened another issue to actually get all the optional properties given a tooltip in the xwd files but it's marked as an enhancement so not really high priority...
