### ISSUE TITLE
Editor window - misc menu doens't work

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#156]
Have tested this with two different installations and using 2 different browsers. Selecting any of the insert menus seem to work fine apart from the Misc menu. If I select the Misc menu the top 3 items are not showing and will not scroll up using the mouse scroll wheel. I can use the keyboard up arrow to select the page types at the top of the list but this is guesswork because you can't see what is selected. It looks like it's Flickr, Delicious and QR Code which don't show - see screenshot below:
![image](https://cloud.githubusercontent.com/assets/5703781/5563836/b4309a76-8e95-11e4-8131-8ac2ca1e2ae1.png)
By Ron

**Comment by FayCross** [comment]
Fixed with new insert page menu
