### ISSUE TITLE
Drag and drop labels - images not always displayed

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#161]
The images are not always displayed. The upload is done properly in the mediafolder. I send 2 screenshots in Annex
By Katrien

**Comment by JohnSmith-LT** [comment]
Do we have the screenshots for this somewhere?

**Comment by ronm123** [comment]
Hi John
I think Inge collated issues reported on the community site forums and the screenshots are there. Not sure if this link will work http://xerte.org.uk/index.php?option=com_kunena&view=topic&catid=18&id=745&Itemid=530&lang=nl#2422

**Comment by ronm123** [comment]
In case the forum link doesn't work images attached here. I suspect this dates back to earlier issues with the editor and url conversion etc but can't be sure.
![2014-11-12_2101](https://cloud.githubusercontent.com/assets/5167146/7820812/8605b16e-03e2-11e5-8c12-2ce4e5e06553.png)
![student](https://cloud.githubusercontent.com/assets/5167146/7820814/8a185400-03e2-11e5-89c9-cd9bf2f225b6.jpg)

**Comment by JohnSmith-LT** [comment]
Ah great, Inge says in her last forum post that this is resolved in the new editor so I'm just going to close it.
