### ISSUE TITLE
inserting new page, can't get all the items on the submenu

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#162]
When I try to insert a new page (as in this short video) techdis-ac.mangoapps.com/sf/MzEyNjJfMTAxNjU0Mw . I can't get to all the items on the submenu. I tested this with both mouse and keyboard shortcuts and had the same problem. * Tested on Google Chrome v 38 * Also tried to test on FireFox 27.0.1 but couldn't log on to server, even after disabling adblockers, popup blockers etc..* I tried to test on IE 9 but couldn't log in to the Beta site - see techdis-ac.mangoapps.com/sf/MzEyNjZfMTAxNjU3Mg
By Alistair

**Comment by FayCross** [comment]
Fixed with new insert page menu
