### ISSUE TITLE
Editor - optional parameters

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#182]
Page wizard: Optional parameters added to a page should appear below the required ones so everything doesn’t jump when they’re added/removed.
By Fay

**Comment by torinfo** [comment]
I can do that, but now they appear exacly ath same location as in the old editor.

Any votes?

**Comment by FayCross** [comment]
It always annoyed me in the old editor too!

**Comment by JohnSmith-LT** [comment]
Hmm if its easy to do then perhaps we should just do this, what do you think? Probably makes sense...

**Comment by ronm123** [comment]
yeah agree but not a biggie

**Comment by torinfo** [comment]
It's easy, It's just swapping two loops. I'll implement it
