### ISSUE TITLE
Design - table editing

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#189]
Page wizard: Not keen on the table editing bit (e.g. for glossary or on the table page type). I’d prefer to be able to type in the bit you see in the editor rather than it open a dialog every time I want to edit. Particularly on the table page where it might not be logical to enter info for a row without easily seeing which column each bit of info will be in.
By Fay

**Comment by JohnSmith-LT** [comment]
Should be possible as shown in this demo http://www.trirand.com/blog/jqgrid/jqgrid.html

Select "Row Editing (new)" - "Inline Navigator (new)"

**Comment by torinfo** [comment]
Yes, but, I couldn't get it to work properly with local storage.

But we could have a look later.

**Comment by JohnSmith-LT** [comment]
Yeah, thought as much. just leaving notes and links for future ref.

**Comment by JohnSmith-LT** [comment]
This probably isn't useful now for glossary or table page since we have wysiwyg editor but perhaps for the variables table. This example seems to work:

http://jsfiddle.net/aditib/CzVVK/
