### ISSUE TITLE
Editor - table page edit

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#191]
Page wizard: Table page: after deleting and adding some rows and columns I can no longer edit some of the cells of the table and the table in preview doesn’t show the same as in the editor (missing rows etc.)
By Fay

**Comment by FayCross** [comment]
This is still an issue. You can add new rows but not edit existing ones. The charts page is unusable because of this (you need to edit the 1st line to begin).

It looks like you have edited it but your changes aren't saved.

**Comment by FayCross** [comment]
Oops, didn't mean to close this...
