### ISSUE TITLE
Editor - page title bold

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#193]
Page wizard: Page Title: Bold won’t do anything as it’s bold by default.
By Fay

**Comment by JohnSmith-LT** [comment]
Isn't that only due to the theme though @FayCross? Now that we have different themes we could in theory bold a page title on a single page?

**Comment by FayCross** [comment]
Yes, it's because of the css. I think this is from my initial comments so I wasn't saying it was a bug, just that we need to change it so that either the css allows it to be changed from the editor or we take the text appearance options off that field in the wizard.

**Comment by JohnSmith-LT** [comment]
I say we leave this as is... if we take the (B) button away and someone changes the theme then they may want to make it bold on a single page... what do you think @torinfo  @ronm123 ?

**Comment by ronm123** [comment]
Yeah with the default interface and default size and weight it probably ought to remain bold by default to maintain good contrast. 

With the source button option on the title field window it's possible to un-bolden anyway e.g. <p><span style="font-size: 26px; font-weight: normal;">page title test</span></p>

Just a thought out loud - is it easy and a possibility to add an N for normal button to the left of the B for bold which then adds font-weight: normal; to the span?

**Comment by torinfo** [comment]
I am ok with leaving this as is. 

It can be done, but it's not easy, it would need to be a custom button

**Comment by JohnSmith-LT** [comment]
I'm just going to make an executive decision and close this... there are other css things that can't be overridden by the editor. If it's raised by the community then we can revisit
