### ISSUE TITLE
Editor - single line text input

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#194]
Page wizard: On other single line text input boxes the text/background colour buttons are very temperamental. They seem to work once but then if you do something like move the page position, they stop working and now don’t work on any pages (no colour picker appears).
By Fay

**Comment by JohnSmith-LT** [comment]
I can't reproduce this but might not be doing it properly @FayCross 

Do you still get this?

**Comment by FayCross** [comment]
This was from the 1st testing months ago. I haven't noticed this problem for ages.
