### ISSUE TITLE
Editor - spell check

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#197]
Page wizard: Spell check is nice feature but do we want it if it has banner ads?
By Fay

**Comment by JohnSmith-LT** [comment]
Hmmm, perhaps not... but it seems to always just be advertising their service so maybe ok?? Whether this changes ever though is then outwith our control...

![image](https://cloud.githubusercontent.com/assets/3907362/7725298/3724c972-fef1-11e4-96ab-1cf781c356ff.png)

**Comment by JohnSmith-LT** [comment]
I'm gonna close this, I think its a useful feature, even with the ads...
