### ISSUE TITLE
pictures instead of words

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#203]
Is it possible to use pictures instead of words in the pagetypes categories and timeline? We are currently creating learning objects for illiterate people which means that we have to work visually.
By Katrien

**Comment by FayCross** [comment]
You can do this now by dragging & dropping images into the label fields in the editor.

**Comment by ronm123** [comment]
@FayCross @torinfo can this be made to work with .svg files too? Have tested with .png and .jpg and .gif and all work but .svg doesn't.
