### ISSUE TITLE
Connectorpages - 

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#205]
I have a complex learning object imported with HTML code and connectorpages. The layout is not good in the backend (see attachment 1). The layout for the student is fine. Unfortunately, the connection page no longer works. The problem is the html codes in the destination page (see attachment 2 box). Tom, you can find the learningobject under my account with the name "Natalie".
![image](https://cloud.githubusercontent.com/assets/5703781/5578994/0f5b1af4-9033-11e4-81d9-d6585851e8aa.png)
![image](https://cloud.githubusercontent.com/assets/5703781/5578995/19f756a8-9033-11e4-8201-0935627ea8ee.png)

By Katrien

**Comment by JohnSmith-LT** [comment]
Do you know @torinfo if this is still valid? Interface looks sufficiently old that it may now be resolved?

**Comment by torinfo** [comment]
No, I was trying to verify this. This should have been fixed last week... :-)

**Comment by torinfo** [comment]
Checked, and this is indeed fixed.
