### ISSUE TITLE
Multiple perspective - video tekst in beeld

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#207]
Als ik een Meerdere perspectieven pagina en dan Video toevoeg krijg ik in het toon-scherm een tekst in het beeld.
![image](https://cloud.githubusercontent.com/assets/5703781/5579001/51c016a6-9033-11e4-8cc5-551427631e7e.png)

By Rene Exterkate

**Comment by JohnSmith-LT** [comment]
Anyone know what browser this happens in or if it is still happening? @ronm123  @torinfo

**Comment by torinfo** [comment]
Cannot reproduce this, so I am closing this one.

**Comment by ronm123** [comment]
Can't reproduce this either.
