### ISSUE TITLE
Bullets - foutmelding toevoegen

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#208]
3 keer geprobeerd om (in Mozilla Firefox) via Voeg toe / Tekst > bullets - Voeg toe aan einde, toe te voegen, maar niet gelukt (6 november, 12.20 uur). Duurt heel lang en Mozilla Firefox geeft foutmelding en ik sluit dan maar af.
By Rene Exterkate

**Comment by torinfo** [comment]
Cannot reproduce. Closed
