### ISSUE TITLE
Editor - copy/cut/paste text

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#209]
In the text areas of the editor you can select text and then right click to get the options to copy/cut/paste text. If I select one of these then it comes up with a dialog box (screen shot attached) because my browser security settings won’t allow access to the clipboard. It’s the default setting to not allow access I think so I doubt these options will work for most people. I thought if it generally won’t work then probably best not to have the option there.
![image](https://cloud.githubusercontent.com/assets/5703781/5579007/8464f27a-9033-11e4-863b-b74dac2b109c.png)

By Fay

**Comment by JohnSmith-LT** [comment]
Is this now being handled correctly @torinfo that we can close?

![image](https://cloud.githubusercontent.com/assets/3907362/7725185/18116bd6-fef0-11e4-8008-25e757d06fda.png)

**Comment by torinfo** [comment]
Yes, this is fine.
