### ISSUE TITLE
Bullets

### ISSUE THREAD

**Issue by sarahberthelemy** [thexerteproject/xerteonlinetoolkits#211]
Hi, 
Something peculiar is happening with the bullets page.
I want a piece of non-bulletted text followed by two pieces of text with bullets to be revealed one-by-one. 

In the Xerte editor I've got something like:

---
This is a paragraph of text which I want to appear without a bullet

<li>This is a bulletted line</li>

<li>Another bulletted line (with the bullets added using Right-Click > Bullet)</li>

--- End of example
Instead, I get all the text appearing at the same time, with extra line spaces added in a moment later.

I'm using Chrome on a Chromebook.

**Comment by FayCross** [comment]
The bullets page automatically converts the text to a bulleted list so it doesn't really work if you add bullets in the editor too. It also doesn't support some text being unbulleted and other text having bullets - it either all does or all doesn't.

The best way of this page working in the new editor might be for it to be a more generic timed text page where text is only bulleted if you add bullets in the editor? This would be for a future release though.
