### ISSUE TITLE
Editor - Order of new nodes is reversed

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#215]
When there is more than 1 type of nested page / node you can add to a page, the order in which they show in the editor is reversed compared to the Flash editor. Generally the least important ones are now at the bottom

e.g. see media lesson page where you can add multiple types of content to a panel.

**Comment by torinfo** [comment]
Interesting. I hadn't noticed this before. The order in the Flash editor is reversed. I just take the order in which the newnodes appear. Weird.

For now I'll changed the HTML editor to reverse the order as well, to be consistent with the Flash editor.
