### ISSUE TITLE
Editor - nested nodes don't initially appear when the xwd says they should

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#216]
For example, see the Tabbed Navigator + page where in the Flash editor when you add a new topic it appears already containing a tab and a nested page. In the new editor, any newly added topics are empty. See Media Lesson page for another example of this.

**Comment by torinfo** [comment]
New editor is only adding 1 level of subnodes. 
I'll fix that.

**Comment by torinfo** [comment]
Can you check if mediaLesson behaves like it should now? If not Fay, could you re-open this issue?
