### ISSUE TITLE
Missing icon for IndexChanger

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#217]
Hi @FayCross 

There's a missing icIndexChanger icon for the index changer page you added a few days ago. Just logging it so we keep track of it.

**Comment by FayCross** [comment]
I'm not sure it was me, I don't recognise the name of the page and can't see it being added in any of my recent changes. It's since been removed from the xwd anyway so I'll close this now.

**Comment by JohnSmith-LT** [comment]
Hmm, sorry about that. I was sure I looked and saw that you committed the indexChanger file but now I don't see that either?
