### ISSUE TITLE
The feature of being able to add URLs between quotes not working in new editor

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#219]

**Comment by torinfo** [comment]
- media with an url enclosed in '' work again
- you don't have to quote the url anymore, you can paste the url directly

**Comment by ronm123** [comment]
Thanks Tom I left my test file complete with an example of each link and can confirm all 3 work now e.g. stylesheet link, help file link and image link. Great stuff!
