### ISSUE TITLE
Labels don't stick on the image in hot spot 

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#220]
Hi,

In this learning object on page 3 (http://xot.pedit.no/play.php?template_id=149) there is a hot spot interactivity. When you place the labels on the hot spot and then schrink the page a bit (FF) the label don't stick. If you do the same when the default window size is used that it sticks on the hotspot. 
Here a short screenvideo to explain what I mean. 
http://screencast.com/t/jZgk77BQK
Can anyone solve this?

Bye,
Inge

**Comment by ronm123** [comment]
Haven't noticed that before - I guess because most of the time once starting an interaction you wouldn't typically resize. But it does seem like a bit of a bug or at least undesirable.

**Comment by JohnSmith-LT** [comment]
This is fixed in the latest templates...
