### ISSUE TITLE
shared editing

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#221]
I can't remember if this has always worked like this or not but testing with both 2.1 and latest develop it seems like we need to improve the way this works. I had occasion to demonstrate and discuss the shared editing option earlier this week and tried to demonstrate that a teacher could share editing access with a student and then change that sharing to read only so that the student could then no longer make changes but still see the LO in their workspace. This does sort of work but there's a definite problem that I can't remember if it's always been the case or not in that the student can still appear to edit and add pages but those changes are not saved. For instance even after logging off and then back in again the student can edit, add a graphics and sound page and upload an image all appearing to work except clearly the changes aren't saved when playing or publishing. However the image is uploaded to the media folder and could therefore replace an existing image of the same name. Perhaps it shouldn't be possible to open the editor if the access is read only?

**Comment by thexerteproject** [comment]
You might want to share an example to show how somerthing has been done, but not allow the user to mess up your project

**Comment by ronm123** [comment]
wouldn't giving a copy achieve that?
The problem here is that a shared editor could spend quite a bit of time trying to edit or add a page without realising that although it seems to work actually it won't save. Also if they upload media and docs via media and quota they do upload and potentially replace files with the same name. I suspect this has always been the case but never noticed before :-(

**Comment by thexerteproject** [comment]
A copy would acheive that. I've never noticed it or heard of it before - it could well be a longer term issue?

**Comment by ronm123** [comment]
With one of the projects I'm supporting this has become quite a contentious issue because they are working with students creating LO's as indeed may organisations are these days. Scenario is that a teacher shares editing access with students then when ready to assess teacher changes the student access to read only rather than editor. They can just about live with the fact that the student can seemingly still edit the LO but changes are not saved but it clearly shouldn't be possible for the student to replace media if they only have view access but they can. Not sure if this has always been the case but it does seem to devalue the difference between shared editor and read only.

**Comment by torinfo** [comment]
I'll have a look, it should be possible to deny editing, but I don't think it is checked properly at the moment,
