### ISSUE TITLE
Insert Menu

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#224]
Can we make the three buttons a bit more graceful please? I think they should be on the same line, even better would be a button group, or one of those drop down buttons which defaults to 'at end', but allows you to select from the other options.

**Comment by ronm123** [comment]
![3buttons](https://cloud.githubusercontent.com/assets/5167146/7349449/05ead372-ecf1-11e4-9f78-3999309f12b5.png)
What do you see? Buttons seem fine to me?

**Comment by torinfo** [comment]
Can we please not assign the tasks, and let the owners pick it up themselves? Fay created the Insert Menu.

**Comment by thexerteproject** [comment]
Sorry, I see this:

![buttons](https://cloud.githubusercontent.com/assets/5164845/7409203/3d8394e0-ef1c-11e4-84f7-50e1ef790e0e.png)

**Comment by FayCross** [comment]
I'm looking at this at the moment. Will change it to a drop down button thing.

**Comment by thexerteproject** [comment]
Can you think of better text for the labels? Should we have options for first and last as well as before and after?

**Comment by ronm123** [comment]
Is that screenshot from Firefox? What do you see in Chrome or IE? Wondering if it's zoom or font size etc and on my machine Firefox always seems to display much larger text and images even when definitely set to 100%.
I think the current labels are fine. At end is the same as last I think so if anything At beginning would be the correct match but I suppose First and Last would be shorter labels.
