### ISSUE TITLE
Editor - Buttons for New Children

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#227]
Can we go back to having links for the New Question items at the bottom of the form for adding children? The buttons look nasty.

**Comment by torinfo** [comment]
As far as I am concerned I would wait for the redesign, and I think Links that behave as buttons are ugly.... (But that;s my personal taste).

Of course this can be changed if you want.

**Comment by FayCross** [comment]
Julian said he was happy with the look of these now the new design is finished
