### ISSUE TITLE
Workspace Project Titles

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#228]
Underscores are shown on the tree: projects with a title like 'test piece' show as 'test_piece'. we shouldn't see the underscore there.

**Comment by JohnSmith-LT** [comment]
I don't get this one? We now allow _ and I only see the _ in the tree when it is in the title?? Has this been fixed @torinfo @thexerteproject ?

**Comment by torinfo** [comment]
I didn't change anything yet. I'll check again.

**Comment by JohnSmith-LT** [comment]
Do we need to? I dont see what the issue is... if you add underscores to the name then they show as they should... Is that not what we want? People have asked for non alphabetic chars there in the past.

**Comment by FayCross** [comment]
The problem is that _ is replacing spaces in project names. It's fine for the underscore to be in there when it's supposed to be but not when it's meant to be a space.

**Comment by JohnSmith-LT** [comment]
Hmm, thats strange. I played around with this for a while yesterday and couldn't reproduce this behaviour but I was perhaps looking in the wrong place.

Just to get this straight, we are talking about the new workspace and changing the project name via the properties? Or does it only happen if you include spaces in the name when you create the project?

**Comment by FayCross** [comment]
When creating a new project. I'm not sure what happens when you change it, I don't know if I've tried that

**Comment by JohnSmith-LT** [comment]
Ok, I'll take a look at this today too. I'm not 100% sure I created a new one with spaces becausevi got into the habit of not doing it... should be an easy win since it looks like everything still works if you change it afterwards...

**Comment by ronm123** [comment]
Hi John I just pulled the latest code and tested this. Did you only test with two word titles by any chance? What seems to be happening now is a space is retained and not replaced by underscore between the first two words but not subsequent words. e.g. "my test" works but "my test project" becomes "my test_project" This happens when cerating a new project or when renaming an existing project.

**Comment by JohnSmith-LT** [comment]
Thanks Ron, yes looking back I only have test LOs with two words and forgot that javascript replace(for the tree) works differently from php replace (for the properties panel)... 

Should be ok now...
