### ISSUE TITLE
Fade when minimising new project pane in workspace

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#230]
I don't like the fade when minimising this pane. I'm not even sure users should be able to minimise it. The fade tranition is ugly though, and doesn't run smoothly.

**Comment by ronm123** [comment]
I don't think the fade does any harm and certainly wouldn't describe it as ugly!
Similar to #231 I think the ability to minimise is definitely useful for those using lower res devices.

**Comment by FayCross** [comment]
This has been removed in new design
