### ISSUE TITLE
Editor - Content not saved when changing between pages

### ISSUE THREAD

**Issue by usernamenumber** [thexerteproject/xerteonlinetoolkits#234]
I am seeing the following behavior:

1. Insert a new content object (Page, etc)
1. Enter content
1. Move to another page
1. Return to the new page

Result: changes have *NOT* been saved!

I dug into this a bit, and it looks like [the "blur" event on editor element is bound to `inputChanged()` in `toolbox.js`](https://github.com/thexerteproject/xerteonlinetoolkits/blob/develop/editor/js/toolbox.js#L775), which eventually calls [`setAtrributeValue()`](https://github.com/thexerteproject/xerteonlinetoolkits/blob/develop/editor/js/toolbox.js#L1190) to save content. 

Unfortunately, at least for me (Chrome v42 in OSX Yosemite), while the blur event fires as expected if you change windows, or click between e.g. the title and main content sections of the page, it does ***not*** appear to fire when you switch between pages.

This is a big deal, and it’s already caused me to lose data. I don’t see how this can be just me, but I also haven't seen others talking about it. Can others reproduce?

Assuming it's not just me, some thoughts on solutions:

1. At least for now, bring back the save button (it's not just missing for me, right?).
1. Make the editor save upon destruction/unloading. I've gone through some of the ckeditor docs, but can't find a way to just make it do this, though. 
1. Bind `inputChanged()` to the click event for menu items, though this may be nontrivial, since the editor is in a different iframe and `inputChanged()` requires values (e.g. `key`) that are passed to ckeditor when it's created, but that I can't figure out how to get back so I can call `inputChanged()` again.

**Comment by torinfo** [comment]
It definitely works for me on Windows 7 pro and Chrome 42.
I'll try to get access to an OSX machine to replicate. (I tries latest develop from Github)

**Comment by usernamenumber** [comment]
Yup, working now. Great work, @torinfo!
