### ISSUE TITLE
Editor locks up in IE10

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#235]
An issue that I've noticed for a while when using IE10 (but not other browsers) is that after a few edits (not a consistant number) clicking in a text field no longer works and I have to close the editor window and the re-open to make further changes. As I toggle between text fields the IE console shows setting sub attribute and no errors yet the text isn't editable until closing and re-opening the editor. I haven't had this happen in other browsers and will do some testing to check if it's limited to just IE10 or perhaps just my Win 7 laptop and IE10.

**Comment by ronm123** [comment]
Can't make this happen now after the latest changes so looks like it's fixed and closing the issue

**Comment by ronm123** [comment]
I was at a college on Wednesday and had helped them upgrade their install to xerte 3 on the previous Friday. All using IE and mostly IE 9 I think and seemed like a lot of them where having this problem where clicking in the text field to edit or select the text stops working. In the title field clicking the source button then closing restores the ability to edit again and someone said using the tab key does too. Closing and re-opening the editor restores the ability to edit again too. But something not right and someone on their own won't know these cheats so re-opening and marking as needing to be fixed for version 3 release.

**Comment by torinfo** [comment]
I really need more than this. I cannot reproduce this behaviour.

**Comment by ronm123** [comment]
Hi Tom - I can reproduce it regularly with my IE 10 so I'll record a screencast at some point today...

**Comment by torinfo** [comment]
Thank you!

**Comment by ronm123** [comment]
Hi Tom sorry about the hum on audio, mains hum not me, here's a quick demo https://drive.google.com/file/d/0B4t6SSPcAW7MaUw5cTRLZ1VMMnM/view?usp=sharing

**Comment by torinfo** [comment]
I still cannot reproduce. I can reproduce a diffrent problem though:
Clicking in the text doesn't show the cursor, clicking outside the text does.

**Comment by ronm123** [comment]
This is still an issue so just adding a version 3 fix label. Clicking tab does restore the ability to edit but we should really try to fix this if we can.
I can replicate reliably with my IE10 on Windows 7. Will test again on IE11 but don't have regular access to IE9 to test that properly.
