### ISSUE TITLE
js failure checking undefined `xot_offline` in mediaLesson.html

### ISSUE THREAD

**Issue by usernamenumber** [thexerteproject/xerteonlinetoolkits#237]
There is an if statement that does a naive true/false test on the variable `xot_offline`, which causes the page to fail to load if it is undefined (which is the case, as the only other reference to it that I've found anywhere else in the codebase is in `export.php`).

PR with fix forthcoming.

**Comment by JohnSmith-LT** [comment]
Fixed in #238
