### ISSUE TITLE
Intermittent error editing bullets page

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#241]
Intermittent error when trying to edit non-text fields in Bullets Page (e.g. numeric stepper & drop down options).

I get ‘Error: Permission denied to access property "nodeType"’ (ckeditor.js line 51). Sometimes when this happens the field is completely unresponsive but at other times it seems to changes ok.

I’ve only noticed this on bullets page but I wouldn’t have thought it’s unique to that page. I'm using Firefox

**Comment by JohnSmith-LT** [comment]
Hi @FayCross 

Again, I can't seem to reproduce this using the latest codebase on Firefox but Mac version. Can anyone else reproduce this or is there potentially a link between this and other issues on Fay's machine?

**Comment by FayCross** [comment]
I've played around with this today and I still get the error in firebug every time I use a numeric stepper field (in bullets page and elsewhere). It doesn't seem to be making the field unresponsive anymore though and it's saving the changes I make to the XML. I don't get the error message from other fields until after I've changed something with the numeric stepper, at which point I then get the same message if I change combo boxes too. The error is as in the 1st message but as it doesn't seem to be affecting the functionality it's not a priority.

**Comment by JohnSmith-LT** [comment]
Hmm, might be possible to do something differently in Firefox for windows (i don't see anything in  Mac version). Can you paste a screenshot of the Firebug error here for the record and then I will try to look  at it at some point in future?

**Comment by ronm123** [comment]
I've just tested and don't get any errors in Firefox or Chrome when using the stepper. In IE 10 the stepper doesn't appear at all just a text entry although again that works without error and changes the value correctly when re-opened in FF or Chrome.

**Comment by FayCross** [comment]
![image](https://cloud.githubusercontent.com/assets/8926470/7771851/26ace28a-0092-11e5-8d6d-8ff986ed5176.png)

**Comment by FayCross** [comment]
I still get the error but I'll close it as it doesn't freeze things now and doesn't seem to cause any problems (& because no one else can reproduce it!)
