### ISSUE TITLE
Upload video problems

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#244]
Try to upload mp4 and I get 'Invalid backend response. Data is not JSON'

Images & mp3s upload ok. I think this was looked at a while ago but I can't find an outstanding issue for it. I'm using a fresh XAMPP install

**Comment by JohnSmith-LT** [comment]
Hi @FayCross 

Just tried and this worked fine for me... I know this was reported and fixed recently with a change to the way login cookies are handled. With latest codebase can you still reproduce? Is the mp4 bigger than your upload settings or anything like that? Could be something odd like that that is still not being captured.

**Comment by FayCross** [comment]
I think you I think you might be right. I get a 'File exceeds maximum allowed size' message above 2Mb but I start getting the 'Invalid backend response' message for anything over around 7Mb. Not sure why the message changes but it's definitely to do with that. Thanks
