### ISSUE TITLE
Editor inserts extra '<br>' tags between paras if a heading is present?

### ISSUE THREAD

**Issue by usernamenumber** [thexerteproject/xerteonlinetoolkits#246]
If I create a text page with following HTML source:

```
<p>Para 1
</p>
<p>Para 2
</p>
```

When I click Play it looks as I would expect it to, and if I look at the source of the page I see basically that markup inside the `pageContents` div.

However, if I add a heading like so:

```
<h2>Heading
</h2>
<p>Para 1
</p>
<p>Para 2
</p>
```

What actually gets rendered now is:

```
<h2>Heading</h2>
<br>
<br>
<p>Para 1</p>
<br>
<br>
<p>Para 2</p>
<br>
```

The result... doesn’t look very good. 

I haven’t gotten to dig into this much, but I can’t imagine what would do a thing like this, let alone why. Does anyone know?

**Comment by torinfo** [comment]
I already created an issue based on your email, and it's also already fixed...
See #240
