### ISSUE TITLE
Editor - script field height

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#247]
The height attribute in XWD doesn't work to set the height of a script field in the editor like it does for text area fields. The script fields are always a set height

**Comment by JohnSmith-LT** [comment]
Hi @FayCross 

Was having a look at this and it seems to be working fine now... I tried 3 pages and each seems to be getting the right size (Distractors on Gapfill = 50px, Embed on Embed Content gets 300px and Words on Hangman gets 100px). Are there any that you have that are not being handled?

**Comment by FayCross** [comment]
No it looks ok now. It was the gapfill distractors one that I noticed it on but it's fine now. Thanks
