### ISSUE TITLE
New "import Media" button looks like download or export to me...

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#249]
![image](https://cloud.githubusercontent.com/assets/3907362/7702328/50480e66-fe27-11e4-9f11-b69d44b9fc6d.png)

Shouldn't we use an up arrow for upload? Can I flip it around or is there an alternative in the bitmap?

**Comment by ronm123** [comment]
I thought/wondered the same thing. The fa icon currently used is the download version and there is of course an upload alternative http://fortawesome.github.io/Font-Awesome/icon/upload/
Looks like we just need to change fa-download to fa-upload in toolbox.js but perhaps there was a reason the download version was used instead - Tom?
