### ISSUE TITLE
Only 1 template can be published at any time

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#253]
Select a project in the workspace and click publish
An alert appears saying Only 1 template can be published at any time.
Publishing the same project with the editor window open works fine.

**Comment by ronm123** [comment]
Have been testing further to check if this is IE10 specific or happens in other versions of IE. This particular issue happens on my IE11 Win 8.1 laptop too.

**Comment by ronm123** [comment]
This happens on FF too and both Win 7 and Win 8.1

**Comment by torinfo** [comment]
I'll have a look. It seems to be a issue with 'counting' the number of selected items....
