### ISSUE TITLE
site.rlt): failed to open stream

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#254]
Select a project and select edit displays a warning that /modules/site/parent_templates/site/site.rlt): failed to open stream: No such files or directory in \website_code\php\screen_size_library.php on line 37

**Comment by JohnSmith-LT** [comment]
I don't see this anywhere and i've been working with it all afternoon... can you clear your temp internet files Ron and get the latest code and try again? And include a screenshot of the error if you still get it?

**Comment by ronm123** [comment]
Hi John
good point I deleted temp internet files and now don't see the error so will close the issue.
