### ISSUE TITLE
preview button alongside browse button?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#255]
In 2.1 we had a preview button alongside the browse for media button to quickly preview the currently selected media. I know that's not needed inside the wysiwyg editor itself but can/should we still have this alongside the browse for media button e.g. the graphics and sound page etc?

**Comment by torinfo** [comment]
Well yes, it would be good to have that. It's also a pre-requisite to be able to implement the 'synching'feature, wich would be most welcom to the mediaLesson.

I simply don't have the time to implement it now.
