### ISSUE TITLE
Hotspot image issue with ie10

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#256]
Seems fine in Chrome and not sure about other versions of IE? but in my IE10 on Win 7 add a hotspot image page then add and edit a hotspot and the image display in the edit window resizes incorrectly. Here's a link to a quick screencast 
https://drive.google.com/drive/folders/0B4t6SSPcAW7MeTFaRHRNZ19ibWM 

Does anyone else get this in IE10 or other IE?

**Comment by ronm123** [comment]
Looks like this happens on other pages too e.g. annotated diagram and regardless of the image used

**Comment by ronm123** [comment]
Have been testing further to check if this is IE10 specific or happens in other versions of IE. This particular issue doesn't happen on my IE11 Win 8.1 laptop so may be IE10 specific.

**Comment by torinfo** [comment]
I'll send you a file that uses the latest JQuery. Can you check for all the IE issues? I don't have access to IE10.

**Comment by ronm123** [comment]
Hi Tom with the latest code in place and then adding the edithtml.php you sent when I click edit I get a blank editor window. Remove this new version and editing is fine but still the same issue with the image.

**Comment by torinfo** [comment]
Any errors in the web server log?

**Comment by ronm123** [comment]
Hi Tom just checked again... 
access log shows /xerteonlinetoolkits/edithtml.php?template_id=10 HTTP/1.1" 200 2 "-" "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)"
But nothing at the same time in the error log

**Comment by torinfo** [comment]
Ah. you replaced the wrong edithtml.ph (there are 4 of them). this one belongs in modules/xerte

**Comment by ronm123** [comment]
My bad! ;-)
With the new file in place it fixes the insert menu issue but when closing the editor gives an invalid state error:

SCRIPT5022: InvalidStateError 
template_management.js, line 376 character 17

xmlHttp.open("post",url,true);

**Comment by torinfo** [comment]
I'll have a look at that. What about this particular issue.

**Comment by ronm123** [comment]
No sorry should have said - the new edithtml.php fixes the insert menu issue but not this hotspot image issue

**Comment by ronm123** [comment]
Have tested this again today with latest code and remains an issue on my Win 7 laptop with IE 10. But works fine on Win 8.1 IE 11. Can anyone else replicate on IE 10 or other IE versions?

**Comment by ronm123** [comment]
Have added a "Browser or Platform specific label" perhaps we'll get a change during the conference and workshops to test these more variable issues on more platforms and devices.

**Comment by JohnSmith-LT** [comment]
Does that fix it for you Ron?
