### ISSUE TITLE
Another IE10 issue with the do you wish to publish prompt

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#257]
Not sure if anyone else is testing with IE10? So not sure if these IE10 issues are just my setup? or common? or happen in other versions of IE too?

This doesn't happen in Chrome but in IE10 if I select a project, click edit and then attempt to close the editor I get do you wish to publish and then do you wish to leave this webpage. See screencast:
https://drive.google.com/file/d/0B4t6SSPcAW7MS1F6cmJ2UDVnNzA/view?usp=sharing 

If I make a change and click publish in the editor I no longer get do you wish to publish but I do get do you wish to leave this webpage.

**Comment by ronm123** [comment]
Have been testing further to check if this is IE10 specific or happens in other versions of IE. This particular issue happens on my IE11 Win 8.1 laptop too.

**Comment by ronm123** [comment]
In FF and Chrome the do you wish to publish prompt correctly only happens if a change has been made and previewed without clicking publish in the editor. But in IE the do you wish to publish prompt happens whether a change has been made or not if closing the editor without clicking publish.
In IE when clicking publish in the editor, or after the subsequent prompt, the do you wish to leave this webpage appears but this only seems to happen in IE not Chrome or FF.

**Comment by torinfo** [comment]
This is a pain. The way onbeforeunload is handled across browsers is a nightmare. If we do not use it, the LO preview is not saved when closing the editor.

**Comment by JohnSmith-LT** [comment]
This https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload even says that many mobile browsers ignore it... not good for supporting mobile editing...
