### ISSUE TITLE
Editor: Table page - can't edit existing rows

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#261]
Not sure where the data goes...

**Comment by FayCross** [comment]
This is for all pages with a table editor in wizard (chart & table pages) & also a problem for glossary too. Charts page doesn't work at all because of this bug as you need to be able to edit 1st row

**Comment by JohnSmith-LT** [comment]
Thanks Fay, I'm going to look at the table editing code this afternoon as i've found at least 6 different issues that we should be able to fix quickly which will hopefully help with the other pages also.

Sorry for keeping tagging you but I thought given the impending release I needed to get on with some of the issues. It would be really helpful to me if you had the time Fay if you were able to review and close some of the ones from initial testing that Inge has opened if you know for definite that you haven't seen the issue during recent testing...

I know you are busy with your own stuff though so no worries if you cannot...

**Comment by FayCross** [comment]
no problem. I'll have a look - probably not until later today / tomorrow though. I think quite a lot of issues were about   things that the new design will have sorted.

**Comment by JohnSmith-LT** [comment]
Brilliant. Hopefully by same period I will have fixed the majority of the table/chart/glossary problems...

**Comment by FayCross** [comment]
Great, I've just quickly closed a lot - will have a more thorough look later though.

**Comment by JohnSmith-LT** [comment]
Hi @torinfo 

I've been looking at this and I seem to have found the problem but I don't really know how to fix it and more importantly I don't want to break anything in the process!!... It seems that the post data that comes back to the function "onclickJqGridSubmitLocal" should have the row id in it so it knows what row has been edited... problem is that the id that is passed is the data contained in the first cell of the row... so in this screenshot where the row is data/data this is what is passed which is why it is not updating the row

![image](https://cloud.githubusercontent.com/assets/3907362/7728361/bcace7d6-ff06-11e4-97f3-1bccdf6d44e6.png)

I've traced this back and it is coming from the onclickSubmit button of the form so is jsGrid passing the wrong data?? Or do we need a "column 0" that has ids in it and then somehow we don't show it??

![image](https://cloud.githubusercontent.com/assets/3907362/7728419/0456f4f0-ff07-11e4-96e3-3d9a4df228f7.png)

Is there any chance you could take a look at this as it is affecting glossary, tables and charts and would be a good win if we were to get it fixed!!

John

**Comment by JohnSmith-LT** [comment]
Linked to #191

**Comment by torinfo** [comment]
Pffff..., that's a while ago. From the code I understand that there used to be a hidden numerical id, but I cannot figure out quickly why there isn't a numerical row id anymore. I am absolutely positive this used to work previously.

I need som time to backtrack this.

**Comment by JohnSmith-LT** [comment]
I'm i a meeting until 4ish. i'll update this with findings afterwards. i've had a good look at this today so think i know why it doesn't work, i just don't know how to fix it...

**Comment by JohnSmith-LT** [comment]
My findings so far... The ids for the rows seem to be causing this... When the data goes in the table the first cell contents becomes the id, so for example I have this table

![image](https://cloud.githubusercontent.com/assets/3907362/7751485/2e15eda2-ffd2-11e4-92b4-386b41fa0209.png)

and I get this code produced

![image](https://cloud.githubusercontent.com/assets/3907362/7751478/27c0bb12-ffd2-11e4-905d-e59e64b7a013.png)

Now see that the<tr id= part is the same as the first cell contents. Clicking on 3rd row in the table has a console.log statement which shows

![image](https://cloud.githubusercontent.com/assets/3907362/7751830/d9c9df2c-ffd3-11e4-9ea9-288082256d55.png)

This from the code should be showing the row and column index (or id)

onCellSelect: function(iRow, iCol, content, event) {
                    console.log("Select cell: " + iRow + ", " + iCol); // iRow is strangely always the data in cell 1??

Not sure why this is happening...

**Comment by JohnSmith-LT** [comment]
Oddly, i've tried it with the demo data contained here http://www.ok-soft-gmbh.com/jqGrid/LocalReader.htm

            var myData = [
                    { id: "1",  cell: ["test",   "2007-10-01", "200.00", "10.00", "210.00", "true",  "TN", "note"] },
                    { id: "2",  cell: ["test2",  "2007-10-02", "300.00", "20.00", "320.00", "false", "FE", "note2"] },
                    { id: "3",  cell: ["test3",  "2007-09-01", "400.00", "30.00", "430.00", "false", "FE", "note3"] },
                    { id: "4",  cell: ["test4",  "2007-10-04", "200.00", "10.00", "210.00", "true",  "TN", "note4"] },
                    { id: "5",  cell: ["test5",  "2007-10-31", "300.00", "20.00", "320.00", "false", "FE", "note5"] },
                    { id: "6",  cell: ["test6",  "2007-09-06", "400.00", "30.00", "430.00", "false", "FE", "note6"] },
                    { id: "7",  cell: ["test7",  "2007-10-04", "200.00", "10.00", "210.00", "true",  "TN", "note7"] },
                    { id: "8",  cell: ["test8",  "2007-10-03", "300.00", "20.00", "320.00", "false", "FE", "note8"] },
                    { id: "9",  cell: ["test9",  "2007-09-01", "400.00", "30.00", "430.00", "false", "TN", "note9"] },
                    { id: "10", cell: ["test10", "2007-09-08", "500.00", "30.00", "530.00", "true",  "TN", "note10"] },
                    { id: "11", cell: ["test11", "2007-09-08", "500.00", "30.00", "530.00", "false", "FE", "note11"] },
                    { id: "12", cell: ["test12", "2007-09-10", "500.00", "30.00", "530.00", "false", "FE", "note12"] }
                ],

Where you can see that the IDs are assigned in the local data but still, in the above example, the ids become test1, test2, test 3 etc and so does the contents of cell 1...

very frustrating...

**Comment by torinfo** [comment]
John,

I really have no idea how this could ever have worked properly. Anyhow, I changed the column model so we now have a hidden column with the idea of the row, so col_0 contains 1,2,3 etc.

I'll send it to you by email, Can you please verify that it works for you? This is really some hairy code...
