### ISSUE TITLE
On QRcode page short url doesn't show when viewing an exported LO locally

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#267]
This is linked to #233 but opening new issue since rss_proxy errors now fixed...

**Comment by JohnSmith-LT** [comment]
I contacted support at is.gd and it seems that localhost access has not been enabled due to the potential for abuse and because they would be unable to block on an individual basis.

This looks promising though http://gistflow.com/posts/986-jquery-ajax-goo-gl-shortner-request

Would you have any reservations about switching to goo.gl if it works @ronm123 ?

**Comment by ronm123** [comment]
@JohnSmith-LT if it works sounds fine. Not so worried about local host but exported projects should certainly work and it would be good if localhost did too. 
For the qr code part we use a service run by university of Southampton but that still works so no need to change that?

**Comment by JohnSmith-LT** [comment]
Ok, I'll look into it. Yes the qr image still works so I'll not touch that part.

**Comment by JohnSmith-LT** [comment]
Have looked at the google example and almost all on this page http://mashable.com/2008/01/08/url-shortening-services/ and only is.gd provide that free access service which unfortunately doesn't work cross domain when exported. I think i'll just close this @ronm123 since the qrcode works and the shortened url works via rss_proxy when on the server...

**Comment by ronm123** [comment]
@JohnSmith-LT thanks for looking at alternatives.One possibility is that we simply document/advise that for projects intended for offline/localhost access authors preview the page, copy the short url and then add that to the text panel or title of the page manually.

**Comment by JohnSmith-LT** [comment]
Yes, that would probably be enough. We could always add a field for a url and if present it adds it there where the short url is placed and if it's not there then it fetches it...
