### ISSUE TITLE
Problem with insert menu in IE

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#271]
Confession: Have noticed this for a while but thought it might just be my setup as not mentioned by anyone else but have just re-tested with latest code and Win 7 IE10 and Win 8.1 IE 11 and same thing on both...

Try inserting a new page to an LO and the 3rd menu panel with buttons and thumbnail either closes or seems to display transparent and moving mouse almost seems to redraw the buttons. I know that sounds like a display issue but two separate machines and OS/IE versions and only seems to happen in IE? Easier explained via a screencast:
https://drive.google.com/file/d/0B4t6SSPcAW7MY3o0QkkxSHdGT2s/view?usp=sharing

**Comment by torinfo** [comment]
This seems to be 'kind-of'fixed when using the latest jquery, but I am not thrilled by that....

I'll check the other IE issues first.

**Comment by JohnSmith-LT** [comment]
@ronm123 if you inspect the element in the debugger and watch the live html as you hover over the menu item do you see any of the css classes appear and disappear in apparent time to the flickering? It looks very much like a css issue to me but might indeed be causes by jquery doing stuff wrongly in ie

**Comment by ronm123** [comment]
Hi John I'm probably doing it wrong - not sure how to watch the live html?

**Comment by JohnSmith-LT** [comment]
Yeah, I'm not sure if you can or not in IE, I never use it because I have a mac...

On Chrome though if you open the menu and right click on something and select inspect element then the inpector shows the html of the element. With that in view if you hover back over the webpage view thennyou can often see that the html is having css classes etc switched in and out of the code as you hover over things. I just wondered whether any odd css classes were being switched in, out when it fades away...

Sometimes though you just need to add a tag specifically for ie10 to override one of the other css commands... any screenshots though may be helpful in debugging...

Sorry I can't be more help. If its still there on Tuesday then I'll try to get hold of a windows machine and try ie.

**Comment by torinfo** [comment]
This seems to be fixed by using latest jquery and jquery ui, but not sure we blindly should upgrade to latest jquery

**Comment by JohnSmith-LT** [comment]
I agree... How many major versions are we moving? They often deprecare stuff in one version then remove in the next... when Dave Goodwin did this last year it broke a number of things that we didnt notice for a while...

That said, this is a major release and if we get to the latest version if jQuery it buys us a lot of time... my only worry would be what else should we/will we need to update on the back of this...

We really need IE working though so it may be only way!!!

**Comment by torinfo** [comment]
From 1.9.1 -> 1.11.3 for jQuery itself, 
From 1.10.4 -> 1.11.4 for jQuery UI

Although I must admit, that I didn't try updating jQuery UI only. Will try that first.

**Comment by torinfo** [comment]
That seems to work fine as well, and that's a lot safer....

**Comment by JohnSmith-LT** [comment]
Sounds good. Once we create 3.0 release we can upgrade everything to latest and then work through issues in dev branch.

**Comment by ronm123** [comment]
Thanks @torinfo I can confirm this fixes the issue on my Win7 IE10.

**Comment by ronm123** [comment]
@torinfo not sure this is directly related or whether to open as a separate issue but have just tested latest code on iPad too and although the issue with display of panels and projects on iPad seems resolved now it seems the insert menu doesn't work on iPad now :-(
Can select insert and choose the page required but the third menu with the buttons and thumbnails etc doesn't open so can't add pages.
Tested on a different iPad too so it's not a caching issue.
