### ISSUE TITLE
Should we rip out old commented code

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#272]
Before we release should we get rid of allbthe commented our blocks that have been redeveloped? There is a lot of code bloat because of this in new editor...

**Comment by torinfo** [comment]
Yes, No problem, also remove (or at least comment out) console.log messages and also perhaps minify.

**Comment by JohnSmith-LT** [comment]
Remove _ignore folder from editor that has early prototype code

**Comment by palepurple** [comment]
Surely minification would be a bad idea - unless it's code that's been sourced from elsewhere....
