### ISSUE TITLE
YouTube feed page no longer working - showing single device support info

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#276]
Have updated to latest to revision but this may have stopped working before today. For me this now only shows a single video about YouTube device support regardless of the device I'm using. e.g. happens on my Win7 laptop and my iPad.
Is this the same for everyone? Is it due to yet another change at YouTube end?
The single clip that now shows links to https://support.google.com/youtube/answer/6098135?p=yt_devicesupport&hl=en&rd=1

**Comment by JohnSmith-LT** [comment]
Same for me. Upon investigation it seems that they have changed their API and now place a restriction on the number of unauthorised accesses anyone can make - I did about 5 before receiving this message

![image](https://cloud.githubusercontent.com/assets/3907362/7811061/3cac5844-039f-11e5-9d00-587c52505494.png)

We might not be able to get around this...

**Comment by ronm123** [comment]
Although not our fault this is a biggie in terms of breaking existing projects. e.g. I'm certain that Alistair will now have plenty of LO's with this page type added and now broken.

Is there a solution where whoever is responsible for an installation registers for the api to work?

**Comment by JohnSmith-LT** [comment]
The problem is that the api key would be exposed in the javascript so anyone could use it. The only way would be to have a youtube_proxy.php file on the server and use that as a go between... we would however have the same problem for exported standalone LOs; they would always be tethered to the server..

**Comment by thexerteproject** [comment]
I suspect we use the key I set up, and everyone is using that. Institutions ought to really set up their own, same goes for flickr.

**Comment by JohnSmith-LT** [comment]
We dont use a key, v2 of the youtube feed gave us the required feed without authentication... Google have now moved on to v3 since March and require auth using a key. with an api key though we could solve this and the qrcode short url issue...

**Comment by thexerteproject** [comment]
So the answer is to provide space in management.php for the various keys?

**Comment by thexerteproject** [comment]
I've got a basic search working and will finish this off next week. At the very least we can leave a placeholder INSERT YOUR KEY HERE, but so much the better if management.php can hold a slot for it, and we can get it from there (and error if it isn't present)

**Comment by thexerteproject** [comment]
All done. api_key_dist.php is the placeholder, code checks for existence of api_keys.php and then includes it if it exists.
