### ISSUE TITLE
Should we prevent users deleting the last row of the glossary?

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#282]
![image](https://cloud.githubusercontent.com/assets/3907362/7812643/1d220552-03ac-11e5-9ec1-978f3ec0d2b7.png)

**Comment by FayCross** [comment]
The LO won't show the glossary button if there's no data in the glossary so I don't think it's problem to leave this as it is.

**Comment by JohnSmith-LT** [comment]
Ok. I couldn't figure out how to easily do it anyway...
