### ISSUE TITLE
Glossary updates not always saved

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#283]
Try adding a few rows or deleting a few rows in the glossary
Then click on another page
Then click back on the Learning Object node

The changes you made before have reverted... anyone else seeing this?

**Comment by FayCross** [comment]
Yes, to an extent. New rows I add seem to be saved OK but deleted rows return when I go back to LO node

**Comment by FayCross** [comment]
Closing this as it affects all instances of DataGrid in the wizard & there's another issue open for it #344
