### ISSUE TITLE
pdf page no longer working properly on ipad

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#284]
this has changed recently as it was working on iPad as well as desktop but not sure what revision has caused it not to work.
An existing XOT template project which was working fine now only shows the first page of the pdf without the ability to scroll to lower pages.

Here's a test project: http://training.mitchellmedia.co.uk/xot/play.php?template_id=74 works on desktop but not on iPad.

**Comment by ronm123** [comment]
Just tested the pdf option in the bootstrap template and that's stopped working properly on iPad too e.g. same issue can't now scroll beyond first page.
http://training.mitchellmedia.co.uk/xot/play.php?template_id=75

**Comment by JohnSmith-LT** [comment]
Hi Ron,

When you say "an existing project template" are you able to test this on any setup of xot v2.0 or v1.9? Do these still work or is it the ipad that has caused this? Is it Safari only or any other browsers?

**Comment by ronm123** [comment]
Hi John I don't think the pdf page type ever existed in 2.1 or earlier, I think Julian added that relatively recently. I can't be 100% sure the XOT template version worked on iPad but I think it did and I'm pretty sure the Bootstrap version did but now doesn't. I can't be certain about or evidence that because the two online installations I've been using with develop code are installations I've been keeping up-to-date after numerous commits so both now have the same problem with the pdf not showing more than the first page. I might have a local xampp install that is an earlier revision so I'll see if I can change that to access via IP and test on my ipad. I'll respond once I've tested that.

**Comment by JohnSmith-LT** [comment]
Ok, I'll have a play around with it tomorrow. Haven't used it so wasnt aware that it was a recently added page.

**Comment by ronm123** [comment]
Hi John
looks like I might have been wrong about this being a change since earlier revisions and that this relatively new page type in the xot template and media type in the bootstrap template may never have worked fully on iPad. The reason I was fairly confident it had was because I knew I'd tested bootstrap projects with pdf's embedded recently and with recent develop code but I can only think those projects were using the iframe method of adding pdf's rather than the dedicated options added by Julian.
Regardless of this though obviously ideally we need to get it working on iPad as it should. If that's not possible then possibly just automatically adding a link below the embedded pdf to open in a new window might suffice.

**Comment by JohnSmith-LT** [comment]
It seems that this is normal on an ipad... apparently it can be done using a library such as pdf.js (demo - http://mozilla.github.io/pdf.js/web/viewer.html) though and I tested their demo and it worked on our ipads...

So we could detect ipads (http://stackoverflow.com/questions/4617638/detect-ipad-users-using-jquery/12999154#12999154) and shoehorn in a library and some different code if this is acceptable to people?

**Comment by FayCross** [comment]
xenith.js already does a check for iOS (x_browserInfo.iOS) you can use (or amend if you need to)

**Comment by ingedonke** [comment]
Tested this and it seems that when you push up the pdf with two fingers next to each other you can scroll up the page.

**Comment by ronm123** [comment]
@ingedonke does that work for you with this example: http://training.mitchellmedia.co.uk/xot/play.php?template_id=74 I can't get the pdf to scroll on ipad whatever I try :-(
I wonder if there's a way to force scrollbars?

**Comment by ingedonke** [comment]
Hi Ron,

Yes it works fine. Don't know if you can force scrollbars....

Bye,
Inge

12Changebv

Chopinlaan 27
5242 HM Rosmalen
T 073-5226195
M 06-50267104
F 073-5226196
E i.donkervoort@12change.eu <mailto:i.donkervoort@12change.eu>
I www.12change.eu <http://www.12change.eu>

T twitter <http://twitter.com/12ChangeLearn>
L linkedIn <http://nl.linkedin.com/pub/inge-donkervoort/7/4b/18a>
Ron Mitchell schreef op 12-7-2015 22:13:

**Comment by ronm123** [comment]
Just a point of clarification...
I can get the pdf to scroll using two fingers on my iPad but only via browsers other than Safari. e.g. Chrome, Mercury/FF, Atomic web all work but with Safari I can't make it scroll with any combination of fingers! Have tried this with Safari on two different iPads and same result. @ingedonke can you confirm again that scrolling works for you on your iPad via Safari? Using my test as an example:  http://training.mitchellmedia.co.uk/xot/play.php?template_id=74 
Anyone else?
The problem is that two finger soltion isn't really FWS.
I don't think this should delay official release of v3 but as John has suggested can we plan to use pdf.js instead? That seems to work with single finger scrolling - at least in their demo.
So perhaps we should change the status of this issue to feature request and remove the v3 Release tag?

**Comment by FayCross** [comment]
I can't get it to scroll either in Safari on iPad with any type of swipe

I was wondering about forcing a scroll bar to be visible in iOS so you'd have to move that rather than swipe on pdf. I've got this half working but for some reason it's working in the opposite way to how it should work - the scroll bar is there but dragging the handle down doesn't do anything, you have to swipe up on the scroll bar to get the handle to move down and the page to scroll. I'll see if I can get this working properly but I think you're right that it shouldn't be a blocker to the release.

**Comment by ingedonke** [comment]
Hi all,

Here my fingers and my iPad.... it works ...
http://xot.12change.eu/play.php?template_id=748
Maybe it's magic :)

Bye,
Inge

12Changebv

Chopinlaan 27
5242 HM Rosmalen
T 073-5226195
M 06-50267104
F 073-5226196
E i.donkervoort@12change.eu <mailto:i.donkervoort@12change.eu>
I www.12change.eu <http://www.12change.eu>

T twitter <http://twitter.com/12ChangeLearn>
L linkedIn <http://nl.linkedin.com/pub/inge-donkervoort/7/4b/18a>
FayCross schreef op 15-7-2015 12:33:

**Comment by ronm123** [comment]
Hi Inge
What iPad version and what iOS version?
On the two iPads I've tested on with Safari the PDF fills the Xerte page content area and doesn't look the same as yours. Whereas Chrome and Mercury and Atomic work the same as yours.

**Comment by FayCross** [comment]
Fixed this (sort of anyway). The first page of pdf will show & scroll and there's a link below it to open the whole PDF in a new tab.

**Comment by FayCross** [comment]
This is still an issue in the Bootstrap template (see http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1014&Itemid=207&lang=en)
