### ISSUE TITLE
Error on management.php when using the wrong details to log in

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#285]
![image](https://cloud.githubusercontent.com/assets/3907362/7832766/727ec82a-0459-11e5-9b46-0eda1b44b3e5.png)

Warning: file_get_contents(website_code/admin_headers): failed to open stream: No such file or directory in /home/smitcher/xerte-dev.smitcher.com/management.php on line 272

Fatal error: Call to undefined function admin_page_format_top() in /home/smitcher/xerte-dev.smitcher.com/management.php on line 286

**Comment by torinfo** [comment]
Hmm, the background should have been white!

**Comment by ronm123** [comment]
I can't reproduce that. No errors or messages just doesn't login with the wrong credentials.

BTW Tom I tested the registration via management yesterday so presumably that shows up at the other end?

**Comment by JohnSmith-LT** [comment]
Thanks Ron. Not sure why but I have checked out github directly into xampp folder as I normally do, set it up and doing updates directly there, sending fixes back to github and mirroring the files to a server...

Strangely, in xampp locally I get a similar error (although different line numbers) but as Tom says, the background is actually while on localhost...

![image](https://cloud.githubusercontent.com/assets/3907362/7833826/9ec7b646-0461-11e5-9e7d-b03e4da70393.png)

**Comment by JohnSmith-LT** [comment]
Ok, if your not seeing this Ron then i'm just going to close! Perhaps some of my files have become outdated on the server, not sure why it would be giving the error on xampp though as github is saying these are all up to date...
