### ISSUE TITLE
Feeds in management page should have a "No feeds" message

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#288]
If you have no feeds added then it just shows a white screen with no text... looks like the page hasn't loaded.. 

It should really show something when there are no feeds...

**Comment by ronm123** [comment]
agree but not really a biggie.
Also I'd say the message should be something like. No projects have been added to the feeds yet.
e.g. the feeds exist and should work but nothing added yet.
