### ISSUE TITLE
Font Awesome for Boostrap/Site projects

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#292]
Now that we have the FA insert icon in the editor this shows when creating/editing Site projects too but although the icon shows in the editor doesn't show on the published page. Suspect the new version isn't currently included in the site code as well as the old version like it is in the main xot project?

**Comment by JohnSmith-LT** [comment]
Both are there in bootstrap so it must be something else... https://github.com/thexerteproject/xerteonlinetoolkits/blob/71c738df72fedf1931f3f5d9939ffcf2b794e839/modules/site/edithtml.php#L142

**Comment by ronm123** [comment]
Hi John
that's obviously the editor code so it shows in the editor but not via preview or play because the site common folder and the site rloObject.htm doesn't include 4.3.0.
To reproduce: Site text field, Click the FA icon, search for download and click to insert the icon
The icon shows in the editor and via code view is: span class="fa fa-download"></span so all is correct for 4.3.0 but doesn't show via play or preview because that version is currently only included in the Nottingham player and folder not the site player and folder.
I could try adding what's required but I'm not sure about the implications on export code?

**Comment by JohnSmith-LT** [comment]
Haha... too much time looking at code today!! If Tom doesnt get it tonight then I'll do it tomorrow...

**Comment by JohnSmith-LT** [comment]
Tom's fix looks to have worked...

![image](https://cloud.githubusercontent.com/assets/3907362/7912374/b998ad1c-085e-11e5-8b07-7eb53d3d9070.png)

![image](https://cloud.githubusercontent.com/assets/3907362/7912383/d058f070-085e-11e5-868f-5e0216fabb43.png)
