### ISSUE TITLE
Media Interactions or the Multiple Perspectives break Workspace

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#294]
If you go into management.php and enable the Media Interactions or the Multiple Perspectives templates then they appear in the Workspace as they should...

If however you try to add one of them then you get this error

![image](https://cloud.githubusercontent.com/assets/3907362/7858337/709c8836-052f-11e5-94e8-06e52ae4ef0b.png)

And it breaks the Workspace if you refresh it

![image](https://cloud.githubusercontent.com/assets/3907362/7858475/429cec9a-0530-11e5-8852-206a8b382996.png)

**Comment by torinfo** [comment]
I was afraid of that. Similar issues as with rss.

I'll have a look.

**Comment by JohnSmith-LT** [comment]
Things are better in that the Workspace doesn't crash and the editor opens but the Workspace has a missing icon

![image](https://cloud.githubusercontent.com/assets/3907362/7912696/b8fb7ff8-0861-11e5-8955-78c5fef8c6c6.png)

/website_code/images/Icon_Page_multipersp.gif 404 (Not Found)

and the editor doesn't load with an invalid XML error

![image](https://cloud.githubusercontent.com/assets/3907362/7912686/ae0619aa-0861-11e5-899b-a17933b39ac2.png)

**Comment by torinfo** [comment]
I fixed the XML.

I would suggest the yellow triangle 'depracated' icon, for those two templates, as we really do not want to support those any more.
