### ISSUE TITLE
Editor - Long breadcrumbs push Play/Publish out of site

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#297]
![image](https://cloud.githubusercontent.com/assets/3907362/7913985/c1fbf204-086b-11e5-878c-a5538a95873e.png)

![image](https://cloud.githubusercontent.com/assets/3907362/7914004/e07a4fdc-086b-11e5-8415-92ea2bdb89ea.png)

**Comment by torinfo** [comment]
Any suggestions on how to fix this?
Using ellipses? Using a fixed size div? Smaller font?

**Comment by JohnSmith-LT** [comment]
Yeah I'd probably a fixed div, potentially that also scrolls if too big... probably least work...
