### ISSUE TITLE
The Page List type dropdown doesn't retain selected value

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#298]
Currently witnessed in the Scenario page but may be present in others

Select a page from the dropdown

![image](https://cloud.githubusercontent.com/assets/3907362/7914177/44977688-086d-11e5-8221-47b7001a2cee.png)

Navigate (or click publish and navigate) to another node and then return to the previous node and previous selection didn't populate

![image](https://cloud.githubusercontent.com/assets/3907362/7914207/7f48e1f4-086d-11e5-9a05-e3014df17844.png)

**Comment by JohnSmith-LT** [comment]
Confirmed that they don't work on the Hotspot Connector page either

![image](https://cloud.githubusercontent.com/assets/3907362/7914354/5c364944-086e-11e5-8f06-dba5e7f9c622.png)

Same process as above

![image](https://cloud.githubusercontent.com/assets/3907362/7914370/6a92a852-086e-11e5-95a9-98992b18c1f8.png)

**Comment by torinfo** [comment]
I cannot reproduce this on Windows 7, Chrome.

Do you get messages in console when you set the page
![1-6-2015 16-52-27](https://cloud.githubusercontent.com/assets/5166596/7915688/7e71d530-087f-11e5-876a-b4ad4a5138b3.png)

**Comment by JohnSmith-LT** [comment]
I get this

![image](https://cloud.githubusercontent.com/assets/3907362/7916761/cefccbe2-087d-11e5-8cbe-f951ba6d6f1b.png)

But I get it in the console when I click on the select BEFORE I even select the page... so I click the select, the console message is displayed at the same time as the dropdown shows Page1, Page 2, Page 3 etc...

**Comment by torinfo** [comment]
Weird that it sometimes worked at all!

**Comment by JohnSmith-LT** [comment]
Yeah, I was noticing at this end that it was actually storing something but it would always be what you HAD selected before clicking rather than what you selected AFTER you clicked...
