### ISSUE TITLE
IE10/11 errors - anyone else getting them?

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#301]
I'm trying to reproduce and fix @ronm123 's IE10 hotspot error but using BrowserStack since I have a mac. I'm getting some strange behaviour - IE won't load the default xml when you create a new template

![image](https://cloud.githubusercontent.com/assets/3907362/7959034/3fa74640-09ed-11e5-87e2-a333a8a8170b.png)

Can anyone reproduce this error on an actual Windows 7/IE10 setup? It seems that $.parseXML is returning an object with no children which is failing at this line 1043

![image](https://cloud.githubusercontent.com/assets/3907362/7959080/bc00fd12-09ed-11e5-8378-ceeffb7e9b1c.png)

Steps:

Latest beta3.0 branch code
Create a new xerte template
Editor opens and has this error

**Comment by torinfo** [comment]
Yes I could in IE9. I fixed it.

**Comment by JohnSmith-LT** [comment]
Ah, so .children works in every browser apart from IE? Pffft...
