### ISSUE TITLE
Chrome/Mac doesn't render CSS as it should in Workspace

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#306]
Bold doesn't seem to work on Open Sans...

![image](https://cloud.githubusercontent.com/assets/3907362/7960961/4d4d8458-09fc-11e5-9a0b-57fe21b49dd0.png)

vs this in Firefox

![image](https://cloud.githubusercontent.com/assets/3907362/7960968/59668afa-09fc-11e5-8687-09030d565a61.png)

**Comment by JohnSmith-LT** [comment]
Anyone else see this in Chrome? Or is it Mac specific?

**Comment by torinfo** [comment]
I don't see this in Chrome on Windows.

**Comment by JohnSmith-LT** [comment]
It may just be a Mac thing, different fonts etc... I'll look into it a bit more

**Comment by JohnSmith-LT** [comment]
Does removing this line make any difference on any of your machines @ronm123, @torinfo or @FayCross ? It fixes it on Mac Chrome and looks to still work on Mac Safari and Firefox also so i've committed it... still don't know why that line changes the appearance so much...

**Comment by FayCross** [comment]
OK for me

**Comment by ronm123** [comment]
Ok for me too e.g. having that line commented out bold still works

**Comment by JohnSmith-LT** [comment]
Great, i've been testing in several browsers on different platforms and all seem to work with that line removed.
