### ISSUE TITLE
Media Lesson: Multiple Choice Question with no correct answers

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#309]
If you add a multiple choice and don't indicate a correct answer then you get no feedback and if controls are disabled then they never come back.

![image](https://cloud.githubusercontent.com/assets/3907362/7961952/80aad692-0a02-11e5-8861-79c90f48550f.png)

**Comment by FayCross** [comment]
I haven't changed the feedback side of this (not sure what we would want it to say if no feedback was added by author) but the controls will now be enabled if there's no answer that can be given that would enable them automatically.

**Comment by JohnSmith-LT** [comment]
That should be fine Fay... People should test their own LOs before deployment anyway but we have had an issue here with students sitting online tests that haven't even been tested by academics and that can't actually be completed... d'oh
