### ISSUE TITLE
Improve runtime error reporting

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#31]
When someone made a mistake in the wizard (for example supplies a Term but no Definition in the glossary, or does not supply a video on a textVideo page, the LO doesn't play, but there is no way for the user to figure out what went wrong.

In these two case, you get javascript errors on split and replcae, and there is no error checking at the moment.

**Comment by JohnSmith-LT** [comment]
Moving this to #274
