### ISSUE TITLE
Quiz model

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#317]
If you add a question but don't add any answer options then you cannot move past but you still get a selectable radio button... not sure what should be the default behaviour for a question with no answer but it seems to have made this user (http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=829&Itemid=759&lang=en#2735) think that they had an issue, although I cannot replicate the issue of audio appearing on other questions...

![image](https://cloud.githubusercontent.com/assets/3907362/8008632/4f4235ec-0b9b-11e5-815f-f56732b06a8c.png)

**Comment by FayCross** [comment]
The problem with the audio was fixed a while ago (someone at UoN reported it too)
