### ISSUE TITLE
Workspace - not working in most Android browsers - Galaxy Note 10.1

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#324]
Editor and LO both work adequately in all browsers below but Workspace doesnt load which is a deal breaker since you can't then get to the editor easily.

Chrome - All works fine

Firefox
![screenshot_2015-06-08-08-05-07](https://cloud.githubusercontent.com/assets/3907362/8029432/f757b034-0db4-11e5-965c-5a58fd4d3851.png)

Dolphin
![screenshot_2015-06-07-22-47-30](https://cloud.githubusercontent.com/assets/3907362/8029442/158ddb6e-0db5-11e5-8cee-c35110fd2a7e.png)

Android/Samsung default browser
![screenshot_2015-06-08-08-13-39](https://cloud.githubusercontent.com/assets/3907362/8029525/3d375fc2-0db6-11e5-8d5f-3d9920279ab2.png)

Opera - seems to work fine
![screenshot_2015-06-08-08-16-46](https://cloud.githubusercontent.com/assets/3907362/8029596/de246bbe-0db6-11e5-9fa6-6ee46e8179dd.png)

Opera Mini
![screenshot_2015-06-08-08-18-26](https://cloud.githubusercontent.com/assets/3907362/8029601/ed378514-0db6-11e5-8253-446a0e3c11a2.png)

**Comment by FayCross** [comment]
This is also a problem in Safari on my iPad 3. I think Ron was having the same problems too although I think it was possibly working on newer iPads (it was discussed on Trello). Editor & LO work fine but you have to manually enter the URL to them as Workspace project list is blank.

Does the create button work for you in these browsers @JohnSmith-LT ? It doesn't do anything on my iPad.

**Comment by FayCross** [comment]
Ignore my comment... just seen you've also opened an issue about the iPad stuff

**Comment by JohnSmith-LT** [comment]
These also seem to now be resolved for me... Do you still have a problem on your iPad @FayCross ?

**Comment by FayCross** [comment]
It still doesn't work on my iPad.

**Comment by ingedonke** [comment]
I tested it on my android phone and the iPad. 
On my android phone the only browser that didn't work was Opera mini (of John's list). The others work well. 
On the iPad it works on Safari, Puffin, Chrome, Dolphin, Opera mini

**Comment by ronm123** [comment]
Is this still an issue and even if it is perhaps it's not an issue that should delay version 3 release?

**Comment by thexerteproject** [comment]
No, this should not delay the release: Ron and Inge have both reported that it works mostly fine.

**Comment by JohnSmith-LT** [comment]
This is resolved for me now in all but one of those browsers (can't remember which). AKAIK the only browser still having a problem is Safari or iPad3, iPad 2 and 4 work fine. I don't have an iPad3 to test on but I think Fay has opened another issue for this so i'm just gonna close this...
