### ISSUE TITLE
Editor - Theme not changing until second click

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#325]
Create an LO
Change the theme
Click Play
Theme is default xerte
Change theme again
Click Play
Theme is what it should have been after first change...

Somehow it's not being updated until after next click...

**Comment by ronm123** [comment]
@JohnSmith-LT not seeing that John. If I create a new LO, add a title page, change theme, press play, I see the theme I selected.

**Comment by JohnSmith-LT** [comment]
Thanks for confirming that Ron. Well that is quite strange. It's similar to a thing we had last week with PageLink where the first click wasn't being stored but then we fixed that... 

I'll look into it, it could I suppose be another browser specific one again...

**Comment by ronm123** [comment]
Hi John I've just re-tested on xampp and an online install with both Chrome and IE10 and latest 3.0-beta code - all work fine without this issue e.g. changing theme and pressing play shows the changed theme immediately.

**Comment by torinfo** [comment]
John, it's the same issue as last time. Callback is on 'click' in stead of 'change' (line 1758 of toolbox.js). Shall I change it, or can you do that (you can test it better)

**Comment by JohnSmith-LT** [comment]
I've just this minute found it. Yes i'll change it now. I was looking at the combobox bit of code which is already .change...

Not sure though why this works on so many machines when it shouldn't?!?

**Comment by JohnSmith-LT** [comment]
I've gone through and changed the other related .clicks() to .change() so we don't see this again... hopefully...
