### ISSUE TITLE
No error message when image is missing

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#326]
When I add a page type with an image in it and I forget to add an image then the page is white. For example the Image, sound and text page. No text appears and no message that I forget the image. Is it possible to add an error message so the user knows what he did wrong? In the Xerte playground I see a lot of these LO's with withe pages....

**Comment by JohnSmith-LT** [comment]
Hi Inge,

We've been trying to fix a lot of these in recent weeks so many of them may be fixed. Are you using The latest v3 code from Tom's site or some other server? 

If you can attach any links to LOs that show this behaviour or and page types that you have found that show this behaviour then i'll certainly take a look...

**Comment by ingedonke** [comment]
Hi John,
Yes tested this in the latest version.
Here is a link to an lo with one page (graphic and sound page). It's a LO with two pages, a title page and a graphic and sounds page.
https://server.tor.nl/~tom/xotdev/play.php?template_id=82

Bye,
Inge

**Comment by FayCross** [comment]
Closing as related to #274
