### ISSUE TITLE
Workspace - not working in Safari on iPad ?

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#328]
Hi @ronm123 Have you managed to get the Workspace working on iPad at all?

I've just tested on iPad 2 and iPad Mini and neither work for me so wondering what iPads/browsers others have and whether the Workspace works for them. As with the Android issues, the editor works fine (if you can get to it by typing in the url directly)

iPad Mini / Safari
![ipad mini](https://cloud.githubusercontent.com/assets/3907362/8034829/6be998e4-0de3-11e5-8324-b7f78d688b28.jpg)

iPad2 iOS 8.3 / Safari
![ipad 2](https://cloud.githubusercontent.com/assets/3907362/8034831/76b9daf4-0de3-11e5-947c-0ceb7adf4ece.jpg)

This is a bit of a deal breaker if we are trying to promote mobile authoring...

**Comment by ronm123** [comment]
Hi John
my iPad 4 + Safari works fine apart from the play button not doing anything which I think I added as a separate issue. Did you clear the safari cache? Does using the sort your files option have any impact?
I have an old iPad 1 that I can also test with and a Samsung 8" tablet so I'll test with them shortly and report back...

**Comment by ronm123** [comment]
Hi John
I can't test on my iPad 1 yet (completely flat) but have tested on an 8" Samsung Android and an 8" Windows 8.1 tablet and both display the workspace and editor fine. Curiously the Android tablet has the same issue as my iPad with the play button not doing anything but the Windows tablet gave a pop-up blocker message and when allowed the play button from the editor does work.

**Comment by ingedonke** [comment]
IHi John and Ron,
I use an iPad 3th generation and that looks ok.
![foto](https://cloud.githubusercontent.com/assets/5703781/8037065/00486c8c-0dfc-11e5-81b5-d32ec5ee2d9d.PNG)

**Comment by ronm123** [comment]
Hi Inge
out of curiousity does the play button in the editor work for you on your iPad?
For me on iPad and Android preview works and edit works but not play from the editor.
Ron

**Comment by torinfo** [comment]
Which issue is about the play button? I had the same issue on an Android. Had to allow for popups. NOTE, that you do NOT get a warning about the popups. Android justs supresses them.

**Comment by torinfo** [comment]
No. Play inside editor is not working by default on iPad (answering for Inge)

**Comment by JohnSmith-LT** [comment]
Hi Ron, hmm, I hadn't tried using the Sort button but yes when I do press that the workspace tree loads...

I've traced the problem and there seems to be a javascript error with the layout which is causing this. Hopefully fixing that will fix the issues on some Android browsers also...

Don't really know where to start with this one though...
![image](https://cloud.githubusercontent.com/assets/3907362/8037360/38762d12-0df5-11e5-9ebf-01dd893ab51c.png)

**Comment by torinfo** [comment]
If you allow popups in safari on the iPad, Play from the editor works.(only if you disable auto blocking of popups, will you be asked the question)

**Comment by torinfo** [comment]
John,

What happens if you use my installation? I'll send you a login shortly.

**Comment by JohnSmith-LT** [comment]
Yes, I can confirm what Tom says. Play wasn't working and was doing nothing. Turned off popup blocking and when I clicked Play I got a message about site opening a popup. Clicked Allow and LO opens...

**Comment by ronm123** [comment]
Doh! Never actually considered pop-up blocking being the cause of play not working given that edit, preview, properties all open. But yes turning Safari pop-up blocking off gives the prompt and then play works. Great!

**Comment by ronm123** [comment]
Just to add - turning off 'Block pop-ups' on my Samsung 8" Android tablet via the default browser advanced settings also then prompts when play is clicked and if allowed play works. Also using Chrome on the same tablet prompts even with block pop-ups turned on and adds the allowed site to the exceptions list.

**Comment by FayCross** [comment]
<b>Safari - iPad 3 - popups allowed - cache cleared</b>
I get a mixture of results depending on what installation I try.

On Tom's privatebeta site the Workspace list loads fine and I can select projects and preview them from Workspace. If I try to edit them though it opens the editor url but gets stuck on the loading spinner. I also can't create a new project properly - I can enter a project name and click create but no window opens. It has created the project though as if I refresh you can see it in the project list. This all works ok on my PC.

Accessing my local XAMPP installation (up to date), the Workspace list doesn't load but if I enter the url directly the editor loads OK. I can't create a project at all - clicking create doesn't do anything so I can't get to the box to enter the project name. I've tried the orientation changes and sorting projects that Ron mentioned on Trello but nothing makes the project list appear. All OK on my PC.

**Comment by JohnSmith-LT** [comment]
It's quite a strange issue really and part of me thinks it is my issue and part of me thinks it's somehow the code...  To document here what i've found..

I had 2x subdomains, setup roughly 1-2 years apart, on same domain (but not necessarily same server as they are managed) and same php version.

1 domain xerte.xxxx was set up first, running v2.1 the other, xerte-dev.xxx was setup recently. It was a direct copy of the checked out github repository and fully up to date... this is the one that didn't work on iPad. Suspecting a corrupt file, I deleted everything except config(s), database and USER-FILES and reinstalled from zip from xerte.org.uk. It still didn't work...

After testing Ron's and Tom's install, both worked flawlessly. I then decided it must be the server so I upgraded the v2.1 using the zip, ran upgrade.php and tested on the ipad and it works?!?

So the only difference i have is that they are on different subdomains on shared hosting which could possibly be different servers although supposedly configured the same or xerte-dev has a hyphen in the name whereas Tom's and Ron's don't and that is somehow the issue...

I debugged Safari on the iPad and the only console errors I got are above but not sure what is causing them. Can you debug iPad3 @FayCross ? Do you see these console errors?

**Comment by JohnSmith-LT** [comment]
Like Fay above, before doing each of these tests i've made sure popups are allowed and cleared cache.

**Comment by FayCross** [comment]
I used to be able to access the developer console for errors on the iPad but Apple have helpfully taken that feature out. I think I need to connect to a Mac to do this now - I'll borrow one to try and let you know

**Comment by JohnSmith-LT** [comment]
I'm now getting iPad2 Safari to work fine on a new install on a new subdomain so I don't really know why the previous install didn't work.... so like @FayCross i'm seeing really different results across installs and haven't found any common cause yet...

**Comment by ronm123** [comment]
@JohnSmith-LT is the install that isn't working available externally John? If it is I'm happy to test on the iPads I have if you want to share details offlist. Likewise @FayCross if the install that you have that isn't working is externally available let me know.

**Comment by JohnSmith-LT** [comment]
This seems to have resolved itself on my install anyway so i'm none the wiser but at least it's working now...
