### ISSUE TITLE
Accordeon navigator: optional property video (w,h)

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#334]
Hi,
In the optional properties of for example the nested pages of the Accordeon navigator (but also the other nested pages) I can add the optional property video (w,h). But I can't add a video with an optional property. Is this supose to be this way? 

Bye,
Inge

**Comment by FayCross** [comment]
Hmm, it looks like you can upload the video you want to use to the Image optional property. Except it's only working for swfs not mp4s. I'll have a look into getting it working for all videos and adding an extra optional property so it's more obvious.
