### ISSUE TITLE
Properties Panel: Import warning

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#337]
Get this error importing the page types zip

![image](https://cloud.githubusercontent.com/assets/3907362/8133053/ab3fc026-111d-11e5-8c5d-818b3b119364.png)

But it still gets imported...

**Comment by torinfo** [comment]
Hmm, it's easy to fix with a file_exists first. Do you want me to do that?

**Comment by JohnSmith-LT** [comment]
Sure, if you have time... out of office today but trying to setup an 'all pages' demo for an event on Tuesday... 

I can get it on Monday though...

**Comment by torinfo** [comment]
Does this fix it for you (couldn't reproduce the first error).
