### ISSUE TITLE
Nottingam.ac.uk 'all page' example no longer giving any media

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#338]
Not sure what has gone wrong @FayCross @juliantenney @thexerteproject but it looks to me like the /media folder has maybe been removed?

http://www.nottingham.ac.uk/toolkits/play_8203

**Comment by JohnSmith-LT** [comment]
560 demo is exactly the same... 404s on all the media...

**Comment by juliantenney** [comment]
my fault, was housekeeping...
________________________________________

**Comment by JohnSmith-LT** [comment]
Cool, though it was me...
