### ISSUE TITLE
New navigator page

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#340]
A new navigator page where you can change easily between accordion, tabs, button & slideshow.

Should be easy to do as they all use the same nestedPage nodes.

Possibly incorporate tabbed navigator + too.

**Comment by FayCross** [comment]
This new page is almost finished (just need to fix a few video sizing issues). It combines the accordion, slideshow, button, tabbed & column navigators so you can just change the type by selecting from a drop down menu.

What's the best thing to do with the original versions of these pages? Normally I'd just deprecate them but I'm a bit worried about the flags in the page tree worrying people when they edit existing projects as I don't think we've ever deprecated pages that will have been as widely used before.

![capture](https://user-images.githubusercontent.com/8926470/33490451-206ca31a-d6af-11e7-9e3e-e9a91d9bf2e2.JPG)

**Comment by ronm123** [comment]
@FayCross sounds good.
My suggestion would be that we don't deprecate the other navigators for the first time this is added e.g. the next release. Just call it something like 'Multi-Navigator' and in the thumbnail description something like: This new navigator combines the formats of all the separate navigators and slows quick switching from one to the other. Longer term the separate navigators will be deprecated.

Then perhaps for the release after that the separate navigators are deprecated.
