### ISSUE TITLE
Duplicate doesn't work 

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#341]
Duplication of an LO doesn't always work

- If an LO wasn't touched by the new editor, dupliace would still work
- As soon as the new editor was used to upload media, duplicatin wouldn't work anymore.

The directory structure is changed, it is deeper because of stored thumbnails etc. The code cannot handle that.

**Comment by FayCross** [comment]
Closing as Tom has fixed this

**Comment by FayCross** [comment]
Reopening this as we are having some problems with duplicating some projects. I think Julian thought it was to do with the .quarantine & .tmb folders (some projects don't duplicate until these folders have been deleted) but I've just seen an example where everything in the media folder (including both of those folders) has duplicated ok but there are no preview.xml or data.xml files in the new project.

**Comment by FayCross** [comment]
I've just noticed that all the projects that I'm having to delete the .quarantine and .tmb folders from because they won't duplicate are Bootstrap projects. I don't know where the duplicate code is but if it's in each module was this fix just done for the xerte module @torinfo ?

**Comment by FayCross** [comment]
Fixed by copying duplicate_template.php from xerte module to decision & site modules
