### ISSUE TITLE
Editor - Show Advanced Options breaks when navigating tree

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#342]
If Advanced Options is ticked then it will show the extra options for that page correctly. When you navigate elsewhere on the tree it will not show advanced options even if they exist. if you return to page where you were when you checked Show Advanced Options they are also no longer visible despite the box being checked throughout.

(can see this in Bootstrap projects where there are advanced options to add new script/canvas/HTML code to a section)

**Comment by ronm123** [comment]
Comparing this with the Nottingham template which has a show language options toggle - in that template the show/hide toggle seems to work ok. e.g. add graphics and sound pages and Flickr slideshow pages and toggle show language options on for one of the pages and the option show for each of the pages until toggled off and then likewise off for all pages. Just wondering if the solution for the site template can be borrowed from the Nottingham template?

**Comment by torinfo** [comment]
I'll fix it. the problem is really in the editor.
