### ISSUE TITLE
When sharing/giving search on username as well as name or at least display username

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#346]
I'm about to have a look at this but adding it here too as it's not the first time this has cropped up as a question or wish list item...

Sometimes there is more than one account with the same name in an installation e.g. we had this on the sandpit where Alistair, myself and others had multiple accounts. This all works because the usernames/logins are obviously different but when sharing or giving projects the only way to tell apart is the (xx) number which isn't user friendly. In a scenario where there are lot's of students and their logins are commonly known by the student ID number etc it would be useful to be able to search by ID or at least display the ID alongside the name. For the project I'm supporting this is essential because of the large number of students involved with lots of potential for duplicate names.

**Comment by ronm123** [comment]
Ok I have this working in the way that is needed for the project I'm supporting e.g.
1. Search by username e.g. 12345 as well as first name last name
2. Results shown include username in brackets before userid in brackets
3. Shared with details also show username in brackets before userid in brackets

![image](https://cloud.githubusercontent.com/assets/5167146/8499800/28d6b6a4-218e-11e5-9e16-629f725964b6.png)

Any reason not to commit this so it works for everyone in this way?
e.g. is there a concern about showing usernames?

**Comment by torinfo** [comment]
Do you really need the user id as well? That's the only thing I don't like, because it's not obvious what it means (at least to me). And in the workspace, we should change the shared settings as well.

![3-7-2015 15-24-30](https://cloud.githubusercontent.com/assets/5166596/8499929/dda63542-2197-11e5-930d-6425f0408c36.png)

**Comment by ronm123** [comment]
@torinfo I only left the userid in because it was already there but agree I'm not sure that really provides any useful purpose.
Good point about including in the workspace.
Shall I remove userid from all 3 places and add username to all three then commit?
Anyone else got any reason to leave userid in or not show username?

**Comment by ronm123** [comment]
Hi Tom
I can find where the workspace text is displayed e.g. properties_library.php but I'm struggling to find exactly where the query is defined to add username to the sql? If I add 
$info .=  "<li><span>" . $row['firstname'] . " " . $row['surname'] ." (" .$row['username'] . ")  -  (";
to properties_library.php it breaks the display. I'm guessing because username isn't part of the sql.
What am I missing?

**Comment by ronm123** [comment]
scrub that found it...

**Comment by torinfo** [comment]
Ok  :)

**Comment by ronm123** [comment]
@thexerteproject Julian - what do you think about this?
Shall I remove userid from all 3 places and add username to all three then commit?
At the moment I have this working but have left userid in but can easily remove?
Anyone else got any reason to leave userid in or not show username?

**Comment by ronm123** [comment]
have committed these changes and will close issue. Please re-open if any issues or disagree with the changes.
