### ISSUE TITLE
Testing import/export

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#347]
I've had a few occasions where import hasn't worked so trying to test/replicate.
Created new Nottingham and Site projects and exported both as deployment.
Import of both worked but error message displayed each time: 
Notice: Undefined index: folder in H:\xampp\htdocs\xerte3\website_code\php\import\import.php on line 632
That line is:
if($_POST['folder']!=""){
                $folder_id = $_POST['folder'];
            }
Is that meant to enable import into an existing workspace folder?

Also do I remember incorrectly that there was already offline export for site projects? Is that part of the plan for this release?

**Comment by torinfo** [comment]
I'll have a look at the error, and I don't know by heart what the pupose of the $folder variable is.

There is no offline export f site (yet) and given the other v3 Release items, I will probably not have time to this before my hollidays, but I will have a look.
