### ISSUE TITLE
Media Lesson Page - YouTube not working

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#348]
This used to work but a YouTube change means popcorn.js stopped working with YouTube.

**Comment by FayCross** [comment]
Does anyone know anything about minifying files?
popcorn.js have fixed the bug (https://github.com/mozilla/popcorn-js/pull/441) but their website doesn't have an up to date minified version on it (http://popcornjs.org/download)
I don't really want to replace the min version with loads of files instead.

**Comment by torinfo** [comment]
I use https://developers.google.com/closure/compiler/ in a different project. It works quite well.

**Comment by thexerteproject** [comment]
Did they make a minified version themselves yet?
