### ISSUE TITLE
Renaming projects in properties panel

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#350]
If I rename a project, the properties panel tells me the name has changed, but I don't see it reflected in the tree. If I click the rename button again, the properties panels disappears and is replaced with 'undefined'.

**Comment by thexerteproject** [comment]
The notes tab does the same thing. The rest of the proeprties panel looks OK on localhost, but worth checking on a full install.

**Comment by torinfo** [comment]
This was really not implemented correctly. Has nothing to do with local versus full install.
