### ISSUE TITLE
upgrade.php we should probably change the code so it doesn't set engine=flash

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#351]
I ran upgrade.php on one of the installs I was using for testing and it changed all the engine= values and therefore all LO's to Flash.
Do we change that bit of upgrade.php for xerte 3 so that it now changes all to HTML instead? 
Or does it need to be cleverer than that and only change the value based on some criteria? E.g just thinking where a long time user like Nottingham upgrade they probably don't want all existing/older Lo's switched to HTML and may want some left as Flash? At the same time for more recent users/installations e.g. Post xenith we definitely don't want to change all Lo's to Flash.
It probably makes sense for version 3 upgrade and is the easiest option to just change the bit in upgrade.php to change all LO's to html but as I say does it need to be cleverer than that and perhaps only change to HTML if date_created or date_modified is later than some specified date we decide is appropriate?

**Comment by thexerteproject** [comment]
We should definitely change that!

**Comment by thexerteproject** [comment]
I think we should leave existing flash LOs as Flash, and signpost somewhere that we are going to do that next time.

**Comment by ronm123** [comment]
@torinfo what if someone hasn't ever run upgrade.php? e.g. upgrading from 1.9 or 2.0 to 3.0. Are you suggesting we just take that code out of upgrade.php?

**Comment by ronm123** [comment]
Have changed the code so that it only changes value of extra_flags for projects where that value is empty. So it doesn't change where engine is already set to flash or javascript and only changes to javascript where value is currently empty. As this is now xerte 3 I think setting the empty values to javascript should be ok but we can change the value and set to Flash if we think that should be the case? The main point is that running upgrade.php doesn't now change all projects to flash which it did previously.

**Comment by torinfo** [comment]
Hmmm, I tried to commit a fix 10 minutes after you.

The point is, as soon as the field extra_flags exist, it should NOT touch the database at all anymore.
