### ISSUE TITLE
XAMPP easy setup fails with Fatal error:

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#353]
Setting up xampp the easy way leads to this error:
Fatal error: Cannot redeclare _debug() (previously declared in C:\xampp\htdocs\xertetoolkits\setup\xampp.php:41) in C:\xampp\htdocs\xertetoolkits\functions.php on line 57

Can I simply delete the function definition from the C:\xampp\htdocs\xertetoolkits\setup\xampp.php file?

**Comment by thexerteproject** [comment]
I commented out the function in setup/xampp.php. Now when I load the workspace I get error messages: 

Error Adding Button
Invalid  selector: body > .ui-layout-east .pin-button

click OK, and 

Error Adding Button
Invalid  selector: #east-closer

I then get a functioning workspae but the layout is badly broken
![ws](https://cloud.githubusercontent.com/assets/5164845/8722685/0a05face-2bbf-11e5-9c47-790331761771.png)

**Comment by thexerteproject** [comment]
Forget that stuff about layout, cleared my cahce and it's working now.

**Comment by torinfo** [comment]
Commenting out or deleting the function definition of _debug fixed this issue.
