### ISSUE TITLE
quick xampp install option doesn't insert same pod info and overwrites toolkits_data database

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#356]
ideally we should ensure that the quick xampp install option does the following:

1. inserts the same pod info as the full install option. I'm not sure how to change that because the xampp.txt file has the pod info hashed.

2. Ideally it shouldn't replace an existing database of the same name e.g. toolkits_data and perhaps should create a different db name each time the full xampp install is run from a new folder e.g. just like the admin password does.

**Comment by thexerteproject** [comment]
No longer relevant
