### ISSUE TITLE
logo images from branding folder on login page before login

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#357]
Picking up on this post from the community site forums...
"Using 3.0 we configured our site logo (image) for use with Xerte. The logo didn't appear on the login page, but did appear once logged in. The image was put into the 'branding' directory as 'logo_right.png'. The browser console showed the problem to be an incorrect URL. In our case:
http://.../var/www/html/xerte/branding/logo_right.png [HTTP/1.1 404 Not Found 1ms]
Looking at the file 'website_code/php/login_library.php' shows that both the left and right logos are checked for existence, and then tried to be loaded with the full disk pathname. This obviously fails."

The patch mentioned didn't reach the forum and looking at the code in login_library.php I can't quite work out why the logo_right.php does work but logo_left.png doesn't. Both work once logged in but only the right logo works on the login page.

Changing the code in the condition to just src="branding/logo_left.png" e.g. leaving out the echo $xerte_toolkits_site->root_file_path . seems to fix the issue but I'm not sure if that's a reliable fix?

**Comment by thexerteproject** [comment]
A patch was submitted on the forum, I've asked if Tom would kindly take a look at it.

**Comment by ronm123** [comment]
It didn't look like the patch got through but perhaps it did to Tom. 
Changing to just src="branding/logo_left.png" does seem to fix the issue but will leave Tom to comment.
I just committed a couple of small css tweaks for the login page to allow 3 lines of welcome text to fit properly.

**Comment by ronm123** [comment]
fixed - removed root_file_path
