### ISSUE TITLE
embed code in project details pane not selectable in IE10 or IE11

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#362]
just been testing this but only have access to IE10 and IE11 so not sure if applies to other versions too. Seems fine in Chrome and Firefox. It's fine in the properties panel in both versions of IE but not in the project details pane.

**Comment by JohnSmith-LT** [comment]
I'm getting confused by the jargon Ron, can you post a screenshot showing where it isn't selectable? Also, what do you mean by selectable? It has code that should select it all when it gets focus - this doesn't work in either places on Mac/Chrome though... Can you not select/highlight it manually?

**Comment by ronm123** [comment]
Hi John in IE10 and 11 the embed code box in the project details pane doesn't allow selection either by single click or by click and drag or by right click select all. So the embed code can't be selected from that panel at the moment. 
In Chrome I can click and drag to select the embed code and then copy it so that works but right click select all doesn't.
In Firefox, initial single click, drag to select all and right click select all - all these methods work.
![image](https://cloud.githubusercontent.com/assets/5167146/8928238/e23c204a-3514-11e5-8c5b-f08945e5c52a.png)

**Comment by JohnSmith-LT** [comment]
Are you able to take out that onfocus='this.select()' ? It doesn't appear to me to be doing anything useful and may be interfering with the browsers own functionality...

It's here

https://github.com/thexerteproject/xerteonlinetoolkits/blob/dc0a62fdf0ffc8edfc7b08c5b1cb78a2f2c10865/website_code/php/properties/properties_library.php#L553

Sorry, don't have access to IE at all or I would test...

**Comment by ronm123** [comment]
Hi John
have taken that out and refreshed but it's not making any difference. :-(

**Comment by ronm123** [comment]
Hi John/all
this appears to be caused by <body onselectstart="return false;"> in index.php
Does that server a useful/important purpose? Is there a way to reverse that just for the embed code textarea or iframe?

**Comment by torinfo** [comment]
The only reason I can think of is Drag and Drop support of the LO tree. If you take it out, does drag and drop still works in the LO tree? Also on touch devices? If so, I am sure you can leave it out.

**Comment by ronm123** [comment]
Hi Tom with that line remove drag and drop certainly still works on my laptop but that's a good point I'll test via my ipad too. So far I can't find anything it stops working on my laptop.

**Comment by JohnSmith-LT** [comment]
I think that is legacy from @pgogy Pat's drag and drop system... i'm sure the tree uses jQuery which will bind to the events in an OO approach so, as Tom says, if drag and drop on the tree still works then whip it out...

**Comment by ronm123** [comment]
Removing this doesn't prevent the project tree drag and drop from working on computers so have committed the change. Having said that drag and drop in the project tree doesn't work on iPad with or without this line so that's an issue to fix in future if we can.

**Comment by ronm123** [comment]
oh! I just tried putting the onselectstart="return false;" back in because what seems very odd but without it creating a new decision template stops working. This means the selection of embed code in the project details pane is still a problem.

**Comment by pgogy** [comment]
there is a selection block code in the main html, suspect it hangs around
if the JS Include has been copied over

**Comment by ronm123** [comment]
I think this is fixed without the removal of onselectstart="return false;" causing any problems so closing the issue. <famouslastwords! />
