### ISSUE TITLE
Error on setup

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#368]
I get this error every time I do a full setup on xampp. Anyone else or know what it is?

This is xampp on a Mac

![image](https://cloud.githubusercontent.com/assets/3907362/9069392/e778300e-3ae0-11e5-8f92-8ad80e9ab880.png)

If I do a quick xampp setup though it goes through fine so it's not the database...

**Comment by ronm123** [comment]
Hi John I don't get that on Windows so it sounds like a difference between xampp on Mac and xampp on Windows. I know that's not much help and I'll test on my mac at some point because it would be good to iron out. (BTW see my email about the speed issue)

**Comment by torinfo** [comment]
The error indicates that php doesn't like the hostname you provided.

**Comment by ronm123** [comment]
Hi both I just installed xampp 5.6.11 on my Macbook (10.10.4) and ran the xerte 3 full install option without any problems at all. I did use localhost/xerte3 rather than a user specifc url but no errors at ll.

**Comment by JohnSmith-LT** [comment]
Thanks Ron, must be something wrong with my setup. I'll close and do some further testing.
