### ISSUE TITLE
export and import of site/bootstrap projects 

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#369]
This is something I'd noticed previously but just tested thoroughly. 
Firstly: Creating a new site project in version 3 export and then re-import works fine.
However an existing bootstrap project created in 2.1 or an earlier revision of v3 exports ok but doesn't re-import because it's missing targetFolder="site" in template.xml. Actaully it imports but treats the imported project as a Nottingham project rather than a site project so doesn't work.
Adding targetFolder="site" manually to the template.xml and then re-zipping and re-importing works and I guess is a workaround for some but ideally we need to check for and add targetFolder="site"  when editing or during export.
Wondering if some of the code John has used to add editor version could be re-used for this?

**Comment by ronm123** [comment]
BTW export and import of decision templates seems to work fine

**Comment by daustin100** [comment]
sorry for the dual post as i am a newbie to this forum
attempted to export from bootstrap on v3.0 and it says it works with VLE but i want just the offline version like one can do in XOT so i can put on a website i am building with laravel

what do u suggest?

**Comment by ronm123** [comment]
Hi this isn't really a discussion forum for this kind of question. Discussions about how to use Xerte etc are better posted on the forums on http://xerte.org.uk or via one of our mailing lists https://www.nottingham.ac.uk/xerte/contactus.aspx However to answer your question - exporting a version 3 bootstrap project and uploading to a web server rather than a vle should work fine. You don't need the offline export for the main xot project either if your requirement is to upload to a webserver just use the deployment export. The offline export you mention is more for extracting and viewing offline via a HDD or USB etc and isn't currently available for the bootstrap template. However even with the current export option you should still be able to view offline via Firefox or via IE after a security prompt.
HTH
Ron

**Comment by ronm123** [comment]
I don't have any older installs or exports to test this with a genuine older project but I tested by removing targetFolder='site' from an export and it still imported ok so looks like this was probably directly or indirectly fixed.
