### ISSUE TITLE
Editor - Media browser window scroll bars not always showing when needed

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#376]
We have had a problem where a user can't see all of their files when they open the window to browse a project's media.

![image](https://cloud.githubusercontent.com/assets/8926470/9354924/595fb6e2-466c-11e5-9ef8-a10654292003.png)

This seems to be because the scroll bars aren't appearing (there are 30+ files in the project).
This is an intermittent problem - I managed to recreate this once but now the scroll bars always seem to appear for me.

**Comment by FayCross** [comment]
It's not browser dependent as they had issues in Safari (screenshot above) and I saw it in FF too

**Comment by thexerteproject** [comment]
Cannot replicate
