### ISSUE TITLE
Gap Fill Exercise international characters and separator issue

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#377]
I am looking into fill the gaps, because it doesn't handle international characters properly (like ç and Ø)
The fix is easy enough. You need to htmldecode the answers.

When I was doing that I saw that Fay added functionality to allow for more then 1 correct answer, by separating the correct answers with a /.

There are two reasons why I think we should change the way that is implemented a.s.a.p.

1. It is incompatible with the way distractors are added, Distractors are separated with a space.
2. It is incompatible with dialog, where correct answers are separated with a ',' by default. There is an optional parameter to change the separator.

I would suggest we opt for method 2, with a default ' ' (as otherwise old LO's with distractors will not work anymore)

We need to change this a.s.a.p. before there are LO's that make use of this.

**Comment by FayCross** [comment]
I don't mind the separator changing but aren't sure about using spaces instead. I'd worry that there's likely to be some projects out there that already have spaces inside a label because they want the label to have 2 or more words on it. This could of course be the case with / too but it seems less likely.

You're right that it's inconsistent but I'm not sure what's the best solution is. We already have projects with / in them, although it's probably just the one person who requested this to be added so wouldn't be a big problem to change the separator to something else.

**Comment by torinfo** [comment]
You cannot use a label with a space in there at the moment. It doesn't work. You have to use &nbsp; to have a space in a correct answer.

**Comment by FayCross** [comment]
It works for me. Not in distractors but in the correct answers you can

http://www.nottingham.ac.uk/toolkits/play_13034

**Comment by torinfo** [comment]
Hmmm... the challenge is to make things consistent, without breaking old LO's. if we use a comma (like in dialog) as the default, how will we handle existing LO's with disctrators.

We should start thinking about adding version numbers to the data.xml file....

**Comment by FayCross** [comment]
I could change it so that correct answers are separated by , rather than / so at least there's a bit of consistency across pages.

The distractors could just stay as they are until there's a better solution - the default text when you add the optional property tells you what to separate them by

**Comment by torinfo** [comment]
Lets do that for now....

**Comment by torinfo** [comment]
Will you, or shall I?

**Comment by FayCross** [comment]
I'll do it by the end of the day

**Comment by FayCross** [comment]
@torinfo - Just thought I've done the changing separator but haven't looked at the international characters bit of this

**Comment by torinfo** [comment]
No, that's fine, I know what to do. I'll fix that over the weekend.
