### ISSUE TITLE
Project properties - last modified date is wrong

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#378]
The last modified date for all of my projects always just shows the same as the created date.

This is a problem in the project property window & the project details section of the workspace.

**Comment by torinfo** [comment]
Yes, There is even a push requiest to fix this I beleive.

**Comment by ronm123** [comment]
I was just having a look at this but can't find the fix on the forums?
As far as I can tell we have some confusion about what fields should represent what and therefore what fields are set or updated during different actions. e.g.

files that insert or change date_modified:
import.php 
gift_this_template.php
duplicate_template.php
new_template.php

files that change or insert date_accessed
edit.php
edithtml.php
gift_this_template.php

So I could be wrong but editing a project only changes date_accessed not date_modified. I'm not sure what date_accessed is meant to represent so if we changed the two edit files to change date_modified instead or as well as date_accessed the displayed date_modified would be correct?

**Comment by FayCross** [comment]
I think this has been fixed https://github.com/thexerteproject/xerteonlinetoolkits/commit/3881c37174b69c553cba27c7badbf9b7863f101f
