### ISSUE TITLE
play_html5.php and site_html5.php not working with .htaccess in place

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#383]
Hi all
I know this dates back to a short period of time (between late version 2 and early version 2.1 I think) where we originally had play_html5.php and site_html5.php so isn't a widespread issue but I had a report that existing links accessed from a vle or blog etc were no longer working after an upgrade to version 3 and it turns out the links were quite old and all play_html5.php?template_id= etc.

I've been investigating and testing with one of my own installations and it seems that although we have a header redirect in play_html5.php which deals with this normally and redirects to play.php it doesn't work with Apache set to true and .htaccess in place to shorten the URL's. It looks like the existing .htaccess rules do try to work when following a link to play_html5.php?template_id= etc but the url in the address bar doesn't actually change and gives and error like:
Warning: file_get_contents(website_code/error_top): failed to open stream: No such file or directory in /var/www/xerte/play.php on line 144 Sorry this resource does not exist

Does this need a change to the .htaccess or is there another solution?

Ron

**Comment by thexerteproject** [comment]
How widespread a problem is it do you think? Does it need fixing, or is it sufficiently low volume to patch the installs exhibiting the problem?

**Comment by ronm123** [comment]
It's likely to be low volume but one of those where it might not crop up at the same time for everyone depending on use of _html5 links embedded in vle's etc.I couldn't work out what and how to fix it but it does seem like it ought to work with the right rules in .htaccess. e.g. the problem at the moment is that it works ok (redirects) without apache set to true but doesn't with apache set to true and an .htaccess in place.

**Comment by thexerteproject** [comment]
no longer used
