### ISSUE TITLE
Media and Quota

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#384]
Resources with spaces in the filename show as 'Not in use' on the media and quota tab, when they are in fact being used. The XML contains a %20 for the spaces, which is causing the problem I think.

**Comment by thexerteproject** [comment]
The function that does the checking takes a param filename, and then does a string replace on it to swith out & for &amp. It then checks for filename and filename2. Would the issue be fixed if filename2 also swithed out spaces for %20?

'''
function in_use($file_name){

    global $xmlpath, $previewpath;
	$file_name2 = str_replace("&", "&amp;", $file_name);
    if(!strpos(file_get_contents($xmlpath),$file_name)&&!strpos(file_get_contents($previewpath),$file_name)&&!strpos(file_get_contents($xmlpath),$file_name2)&&!strpos(file_get_contents($previewpath),$file_name2)){
        return false;
    }else{
        return true;
    }
'''
}

**Comment by FayCross** [comment]
Yes I think so, I added the bit that gets files with & in to work a few months a go and that was the same kind of problem. I can look at it later this afternoon if you want.

**Comment by thexerteproject** [comment]
I added to the install and tested it and it seems to work so I've commited it.
