### ISSUE TITLE
Site template navigators accordian and carousel don't display pdf

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#385]
In the site template if a navigator is added, dfollowed by a pane to which a pdf option is then added this works with the navigator set to tabs or pills but doesn't display the pdf if set to accordian or carousel. Not sure if this has always been the case or is a new bug but obviously it ought to work.

Also looking at how a pdf is displayed normally and inside a navigator tab or pill should we increase the height of the frame or make this a contollable property when authoring?
e.g. I tested changing lines 304 and 448 of /modules/site/parent_templates/site/common/js/application.js and changed pdfDoc height to 600 which seems to be a better default height given that most pdf's are A4 portrait etc.

**Comment by thexerteproject** [comment]
I've fixed both of those, thanks.
