### ISSUE TITLE
Does the synced video page work on your smartphone?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#386]
Hi all
does this page type work for you on a smaller device rather than tablet or desktop? For me it works fine via desktop and tablet etc but doesn't work on my iPhone. The page itself displays on the iPhone but no text or video player is shown. Is this the same on your iPhone or other smart phone?

**Comment by ronm123** [comment]
Also Interactive List page?
I'm not sure if it's a separate or related issue but the interactive list page doesn't display any content on my iPhone either whereas it works fine on iPad and desktop etc.

**Comment by FayCross** [comment]
iPhone:
Synched video page - appears to be a blank page but if you swipe to see off the right of the screen it is actually there, just offset for some reason. Although when I play the video it doesn't really show the page well as the video opens full screen so you miss the content being synched

**Comment by FayCross** [comment]
Interactive list page is blank for me on iPhone too. Not the same problem as above though, it looks more like a proper bug as the page number doesn't move on when you go onto the page which normally means it's something in the code.

**Comment by ronm123** [comment]
Thanks Fay - hadn't swiped right on the synched video page :-( but obviously it shouldn't be like that as and you say the video just opens full screen so not as intended anyway. Is there a way to prevent that full screen view? It works on iPad fine.

Interactive list is a strange one - especially as again it works on iPad fine.

**Comment by FayCross** [comment]
I only noticed it off screen by accident. I'll have a look at why it's appearing like that and see if there's a way of stopping it going full screen.

I think I've found the problem with interactive list - I'll fix it in a minute.

**Comment by FayCross** [comment]
Hmm - interactive list still not 100% after that fix. it doesn't show images. I'll have to look again at this later this afternoon

**Comment by ronm123** [comment]
Could that image issue be the jquery upgrade issue that Tom identified and fixed for the tabnav etc Fay?
