### ISSUE TITLE
XWD "mandatory" property

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#391]
basic.xwd includes this line:

\<theme type="ThemeList" label="Theme" mandatory="true" defaultValue="default" /\>

What does mandatory="true" do? Is it just a typo and it's meant to be the "required" property that Tom mentioned last week or does it do something else?

**Comment by FayCross** [comment]
Ignore this issue!

**Comment by torinfo** [comment]
Hmmm... It was not named 'required' apparently, but 'mandatory'. Aplogies.

**Comment by FayCross** [comment]
That's fine, I realised as soon as I posted that it was doing that. I was sure when I tried it a few minutes before that it didn't seem to be doing that but it must have been my mistake. Thanks
