### ISSUE TITLE
Editor - can't include a textarea on a page

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#394]
Niko (@nmiran) has been trying to create some pages that include \<textarea\> tags. Although they preview initially ok they don't display correctly in the editor. Anything after the closing textarea tag is lost.

This must be because the editor itself uses a textarea tag and therefore doesn't want another textarea nested inside it. He's been using the embed content page to type his HTML into (although every page has this same issue)

For the moment I've given him a work around of writing the HTML in a separate file and showing it in an iframe but I wasn't sure if there was a way of getting this to work directly. I'm not sure there will be to be honest but thought I'd ask!

**Comment by thexerteproject** [comment]
My own solution was to create the textarea at runtime using jquery. I think we are all noticing people doing more and more advanced stuff with html / css / js and running into a few issues. I'm wondering how we can make this more robust, though escaping code to store as xml params is tricky.

**Comment by FayCross** [comment]
That's a much better work around - thanks
