### ISSUE TITLE
Can't edit or preview projects that use the now deprecated 'Media Interactions' template

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#398]
You can no longer edit or preview old media interactions projects.

It gives an error of 'node.editor_size is null' or 'node.preview_size is null' from template_management.js. Where should template_management.js be getting this from?

It doesn't seem to be a problem with all deprecated project types, just media interactions ones.

**Comment by torinfo** [comment]
I believe this information comes from the info file.

**Comment by thexerteproject** [comment]
You can work around this by opening the edit url directly in another browser window whilst you have the workspace open. I'm going to close this as it doesn't appear to be an issue with users out there.
