### ISSUE TITLE
MANAGEMENT_TUTORIAL_TEXT undefined

### ISSUE THREAD

**Issue by radixmo** [thexerteproject/xerteonlinetoolkits#402]
MANAGEMENT_TUTORIAL_TEXT constant (line 69 website_code/php/management/site.php) is not defined.

This constant should probably be defined in:
languages/en-GB/website_code/php/management/site.inc e.g

define("MANAGEMENT_TUTORIAL_TEXT","The tutorial text is (Add information and links to tutorials here.)");

**Comment by thexerteproject** [comment]
Fixed
