### ISSUE TITLE
Editor - Allow images to be uploaded to table fields

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#403]
It would be great if you could easily upload images to cells in the editor's table fields. You can currently type the img html into a cell when you edit a table but it would be better if there was an automated way to do this.

It would be a nice enhancement for pages like Sortable Grid

**Comment by torinfo** [comment]
What about creating a richgrid, where the edit dialog would have a wysiwig editor for each cell (like the description column for the glossary)

**Comment by FayCross** [comment]
That would work well - I hadn't noticed we had something like that in the glossary
