### ISSUE TITLE
Quiz Submit Button

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#406]
Might need to look at this issue with the submit button: http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1020&Itemid=207&lang=en#3401

Always prefer to disable - rather than hide - any inactive elements though. It's better for the user to see that some functionality is currently disabled, but there, rather than hidden.

**Comment by FayCross** [comment]
Fixed with this commit - https://github.com/thexerteproject/xerteonlinetoolkits/commit/9a3685a1185a76dea126484d68b39b18de0f1a84
