### ISSUE TITLE
LO Title (and other single line text fields in the editor?)

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#412]
You can press return in the single line text field in the editor for LO Title, consequently the editor goes all screwy showing multiple lines.

Can we prevent this? And is it relevant to all text fields (rather than text areas where multiple lines are expected?)

**Comment by FayCross** [comment]
Yes, this happens in all single line fields in the editor. It's been reported a couple of times previously on the forum and there's already an issue raised for it here: #349 

![lines](https://cloud.githubusercontent.com/assets/8926470/12610862/db24f324-c4e1-11e5-8336-f977a5af310d.png)

I'll close this as a duplicate
