### ISSUE TITLE
Glossary doesn't work for words with foreign characters like the Norwegian characters  æ,ø, å 

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#416]
This is because the text is html encoed, so need to decode text first in x_insertText

**Comment by ronm123** [comment]
Not quite Tom :-( I'm now getting lots of other code displayed in the LO e.g. on the following LO the title page has some css which is now working ok again but on the second page note all the code displayed http://accessiblepractice.org/v/xerte/play_992#resume=2

**Comment by ronm123** [comment]
Note: I've put an older xenith.js in place again now so the previous link will no longer show these particular problems but the issue isn't fixed.

**Comment by torinfo** [comment]
You have to help me out here Ron, can you send the LO, or at least something that I can play with.

**Comment by ronm123** [comment]
Hi Tom
I've created a cut down copy of the LO I linked above and will send to you by direct email. It's a useful one to test with because it has examples of css, html, iframes, links, font awesome etc etc
HTH
Ron

**Comment by torinfo** [comment]
Thank you! Did you already send it? I have not received it yet.
