### ISSUE TITLE
Tooltips shown on drop area's of the category interactivity

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#418]
@FayCross 
I assume this as for accessibillity, but shouldn't this have been an alt attribute?

**Comment by FayCross** [comment]
Yes it's an accessibility thing - it's the way that worked best when I first did screen reader testing years ago. When I did some more testing a few weeks ago it wasn't working particularly well though (not always reading the text out) so I'm looking into the best way of doing this again now anyway. The screen readers don't read it out at all when it's in an alt attribute (I think this only works reliably for images)

**Comment by torinfo** [comment]
The problem with title though, is that I have some users that inserted an image into the drop area instead of a name, and than the popup relly looks weird (it's the full HTML code for the image)

One way of solving this is having an optional property for the image, and than use the alt-tag with the name in there.

You could probably even solve it like that. Make the background an image and use the alt-tag.

**Comment by FayCross** [comment]
Ok, I'll look into it when I get to this page (reviewing all pages for accessibility stuff at the moment)

**Comment by ingedonke** [comment]
This came up again with a user (see attachment). Did you find anything?
[Doc1-1.docx](https://github.com/thexerteproject/xerteonlinetoolkits/files/308494/Doc1-1.docx)

**Comment by FayCross** [comment]
Haven't got around to it yet - I'm not sure when I'll get back to finishing the accessibility review on the interactivity pages. We could probably remove the title here for now if it's causing problems.

**Comment by JohnSmith-LT** [comment]
Could we just check for and remove the HTML from this attribute, keeping the text and possibly also inserting something like " and an image with the alt text ..... and strip out the alt text for any images if they are there?

**Comment by JohnSmith-LT** [comment]
Do you know if this is still an issue @FayCross after doing all the accessibility stuff a while back or might this have been resolved now by that work?

**Comment by FayCross** [comment]
Looks like it's been fixed. Only plain text appears in title attribute now
