### ISSUE TITLE
Dialogue page doesn't allow apostrophes etc

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#424]
Hi all
I received the following report and have replicated this too. Is there a solution?

Have discovered an error in Xerte when using interactivity – dialog. There is a problem using apostrophes! Please see screen shot:

![image001](https://cloud.githubusercontent.com/assets/5167146/13775436/64973060-ea9c-11e5-8c0b-49f47454cd88.jpg)

The system correct answer appears to have some sort of code but marks we’re as incorrect. Not helpful in a grammar game! Any ideas or solutions?

**Comment by FayCross** [comment]
I think this has already been fixed by Tom in the develop code (https://github.com/thexerteproject/xerteonlinetoolkits/commit/23e27a58b849cadbed96bda46ea3f53a60751f60). It works fine for me using the develop code anyway. I'll close this for now but reopen if this doesn't fix it for you

**Comment by ronm123** [comment]
Thanks Fay. I've tested and verified that this is fixed in develop but not currently in either of the 3.1 downloads on the community site.
