### ISSUE TITLE
Errors in CSS code of themes

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#425]
All the responsivetext.css files seem to have errors:

On lines 20

**panelPage** h3 {
     font-size: 3.0vmin;
}
**mainTxt** h3 {
     font-size: 3.0vmin;
}

and on line 73

**mainPanel**.panel {
    font-size: 3.0vmin;
}

I assume there should have been a **#** - mark before the bold identifiers.

@FayCross and @ronm123 I don't know how best to fix this, as I don't know the concequences of just adding the #

**Comment by ronm123** [comment]
I'll have a look at this as soon as I can.

**Comment by ronm123** [comment]
I made the corrections to .panelPage h3, #mainTxt h3 and #mainPanel
I tested and found where the first two are used but not sure about #mainPanel .panel but at least it shouldn't show as an error now.
