### ISSUE TITLE
recent change to xenith.js causing problems with <style></style> etc

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#429]
Hi all
I've only just discovered this with an installation I've moved and then upgraded to the latest develop code. The installation has lots of LO's where styles like 
` <style>.splitScreen {
    padding: 0 0 0 20%;
    margin-right: 5px;  }
.splitScreen .left {
    width: 20%; }
  </style>`
has been added via code view and has worked fine previously but is now being display as text on the pages even though the code is all still intact. Just to check I replaced with an earlier xenith.js and all was fine again but not sure yet exactly what change has caused this? I'll try to find it but perhaps this rings bells for someone?

**Comment by torinfo** [comment]
How far did you go back?  There were like 4 changes in March, 2 in February and 4 in January, all by me or Fay.

**Comment by ronm123** [comment]
I've just been checking that. I replaced the xenith.js (from latest develop) with one from a 3.1 zip download from the community site and it seems I extracted that zip locally on 16th March. However the xenith file in that download is dated 2nd March. So it's obviously one of the March changes that has resulted in this problem.

**Comment by torinfo** [comment]
No, not necessarilly. Because the 3.1 zip is from a different branch.

**Comment by FayCross** [comment]
Is it from one of the changes that makes special characters display
properly (portugese was it?) that means text's dealt with differently?

**Comment by torinfo** [comment]
I sent Ron a xentih.js from just after that specific commit.

**Comment by torinfo** [comment]
That one still doesn't work, so, yes, likely a unintentional side effect of that change. Will have a look.

**Comment by ronm123** [comment]
Yes the file Tom sent me results in the code being displayed in the page whereas an earlier version doesn't. 

BTW I also noticed some line break issues again which might be related but can't say for sure until I've tested further.

**Comment by torinfo** [comment]
Fixed (again). See #416
