### ISSUE TITLE
SCORM completition status problem.

### ISSUE THREAD

**Issue by LeoRodz** [thexerteproject/xerteonlinetoolkits#431]
There is a problem reporting the completition status when SCORM Tracking Mode is "tracking of first pass".
I'm going to describe 2 cases to illustrate the problem.
For simplicity, let's suppose a course of only 3 pages, without score.

**Case 1: working fine.**
1) Enter course (page 1).
2) Go to page 2.
3) Go to page 3.
4) Close the course.
The status is correctly reported  as "completed".

**Case 2: wrong status**
1) Enter course (page 1).
2) Go to page 2.
3) Back to page 1.
4) Close the course.
The status is incorrectly reported  as "completed".

There is a Pull Request #428  that try to fix this issue.
Thanks.

**Comment by torinfo** [comment]
Fix merged
