### ISSUE TITLE
SCORM 1.2 status change to failed when moving fast between pages.

### ISSUE THREAD

**Issue by LeoRodz** [thexerteproject/xerteonlinetoolkits#432]
Let's suppouse a course with a simple MultipleChoice question.
Follow this steps:
1) Enter course.
2) Go forward to the page with the Multiple Choice.
3) Answer the question correctly.
4) Go forward to the last page.
5) The status is set to "passed".
6) Go back to any page.
7) Click twice and fast (less than 1 second) any arrow (back or forward).
8) The status is changed to "failed".

The Pull Request #428 was updated to fix this problem too.

**Comment by torinfo** [comment]
Fix merged
