### ISSUE TITLE
Improve responsiveness - Images

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#444]
From Xerte Conference Developers Day

Allow image sizes to be set in %
For images uploaded in WYSIWYG & in upload editor fields

**Comment by torinfo** [comment]
Partly done in commit 703f7c1ddd310291031c61faf60d331ac17cc282 (in WYSIWYG editor)

**Comment by FayCross** [comment]
These pages could do with being looked at as images responsiveness could be improved.

When page 1st loads the image is sized appropriately but stays that size if browser size changes:
- [ ] Tabbed navigator +
- [ ] Hangman

- [ ] Memory game: cards are always a fixed size and images on them stretch to fit the space
