### ISSUE TITLE
New Page Type: Wordsearch

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#456]
From Xerte Conference Developers Day

**Comment by JohnSmith-LT** [comment]
Works to a fashion, probably needs tweaking and tested for accessibility...

**Comment by FayCross** [comment]
I've committed some changes and I think it's ok for release now. Export seems fine too

**Comment by JohnSmith-LT** [comment]
Brilliant, thanks Fay!

**Comment by FayCross** [comment]
Haven't tested for accessibility to be honest - I assume it won't work but I can look at it when I get around to finishing the half done accessibility review
