### ISSUE TITLE
New Page Type: Flash Cards

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#458]
From Xerte Conference Developers Day

**Comment by JohnSmith-LT** [comment]
How would these work? What would they do?

**Comment by FayCross** [comment]
Not a very complicated page - they used to be in the now deprecated Media Interactions template.

You would add cards to a page and each card would have different info on each side. e.g. a picture on one side and the word on the other. Or the same word in two languages on different sides.

The page would show 1 card at a time (order randomised?) and you could flip the card over to see the other side.

**Comment by FayCross** [comment]
There are a few things I would like to add to this new page at some point... 

- option to randomise cards
- choices of how the other side of the card shows - e.g. so that instead of the card flipping, the 2nd side is revealed next to the 1st side - so you see both at once after the reveal
