### ISSUE TITLE
New role for sharing projects with same rights as creator

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#463]
From Xerte Conference Developers Day

Currently only the creator can do certain things with a project (export, share with others etc.)
Create a new role so that projects can be fully shared

Possibly also allow users to transfer ownership to someone else

**Comment by FayCross** [comment]
Related request from forum - allow editors to duplicate projects and allow the permissions for different roles to be changed via the management login.
http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=10&id=1201&Itemid=759&lang=en#4142

**Comment by FayCross** [comment]
@torinfo am I right in thinking there's a new co-author role that you added with the merge pages stuff? Does this role have the same permissions as creator? If not, what's different? Thanks (I can't test this on xampp)

**Comment by torinfo** [comment]
@FayCross That role is not there yet. And yes it will basically give the co-author the same rights as the creator.

**Comment by FayCross** [comment]
Ok, thanks

**Comment by FayCross** [comment]
Closing as Tom's made a new co-creator role

**Comment by ronm123** [comment]
Just checked this new role and can see that the co-creator can import pages from other projects they own which is great however should the co-creator be able to duplicate the project that they are co-creator of? I tried this and the duplicate appears in the workspace but the project folder is empty so when trying to edit the copy just an empty tree appears.

**Comment by FayCross** [comment]
Yes, I'd like it to work so that they had exactly the same roles as the creator (except probably delete project)

**Comment by torinfo** [comment]
Will have a look at that.
