### ISSUE TITLE
SCORM score and status problem.

### ISSUE THREAD

**Issue by LeoRodz** [thexerteproject/xerteonlinetoolkits#488]
Let's suppouse a 3 pages course. The second page is a Multiple Choice Question.
The Tracking Mode is "tracking of first pass".
1) Enter the course and go to the second page.
2) Answer the question correctly.
3) Go to the last page.
If we close now the couse, the status is set to passed and the score is 100.
4) Without closing the course, go back to the second page.
5) Go back to the first page.
6) Close the course.
7) The status is set to failed and the score is 0.

This issue is related to #434.
This can be fixed with PR #435.

**Comment by torinfo** [comment]
The reason that I did not merged this yet, has to do with the suspend data.
The suspend data is intentionally not sent when the LO is completed. You don't need it anymore.

Would like to add the other fixes though. And because it doesn't hurt to det the suspend_data on completed, I will merge this requiest in.

**Comment by LeoRodz** [comment]
Thank you for taking my PR into consideration. I saw you have already commited it.
Sorry for having joined two issues in one PR:

Let me try to explain better the suspend data issue.
When all pages of a course are visited and the course get status completed it is necessary to save the suspend data one more time, the last one, because otherwise the JSON data **pages_visited** is not updated to it's last value.
For example, in a 3 pages course with status completed, the suspend data **nrpages ** is 3 but **pages_visited** is 2.
This was causing the issue #489, if we enter again to the course and then close it, the status is changed to incomplete in function **finishTracking** because **getSuccessStatus()** returns incomplete (nrpages > pages_visited). This is wrong when tracking mode is "first pass".
Saving suspend_data with updated data when the course become "completed" fixes the problem.
Thanks !
