### ISSUE TITLE
Style & stylesheet

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#493]
When setting a font in style or a stylesheet on the frontage of the learning object, the learning object title and page title doesn't change.

**Comment by FayCross** [comment]
It works ok for me. What css are you using?

This affects the title & header texts as well as normal page text...
`body {
  font: italic bold 30px serif;
}`

But if you're trying to change the text colour you'll need to be more specific with the selectors...
`body, h1, h2 {
  color: red;
}`

**Comment by ingedonke** [comment]
Hi Fay,

Thanks, I'll look into this.

For the Apereo Conference we can use the Xerte installation that we have 
installed for us (Xerte Team). Tom will update is with the latest 
changes so we have the most actual version.
I'll create the LO we use in our session there. Try to do that this week 
(today//I hope).
I also create 20 demo accounts we can use in the workshops.

Bye,
Inge/

/
12Changebv

Chopinlaan 27
5242 HM Rosmalen
T 073-5226195
M 06-50267104
F 073-5226196
E i.donkervoort@12change.eu <mailto:i.donkervoort@12change.eu>
I www.12change.eu <http://www.12change.eu>

T twitter <http://twitter.com/12ChangeLearn>
L linkedIn <http://nl.linkedin.com/pub/inge-donkervoort/7/4b/18a>
FayCross schreef op 11-5-2016 10:54:

**Comment by ronm123** [comment]
If you just want to change LO title and page title I would use something like the following:
`#x_headerBlock h1 {
    font-size: 1em;
    color: red;
	font-family: cursive;
}

#x_headerBlock h2 {
    font-size: 1.2em;
    color: yellow;
	font-family: cursive;
}`

**Comment by ronm123** [comment]
Just realised I should clarify that's just for example. I would use responsive font size wrapped in media queries or not change the font siz and just change the colour/font and leave the existing responsive css to take care of the size.

**Comment by FayCross** [comment]
Yes, Ron's css is better

(...but you should avoid using h1 or h2 in main text for page anyway as it's not great accessibility - headers used there should really start from h3)

**Comment by ingedonke** [comment]
Hi,

Can't reproduce this either anymore.
It works for me also now. Maybe a caching problem....

Bye,
Inge

12Changebv

Chopinlaan 27
5242 HM Rosmalen
T 073-5226195
M 06-50267104
F 073-5226196
E i.donkervoort@12change.eu <mailto:i.donkervoort@12change.eu>
I www.12change.eu <http://www.12change.eu>

T twitter <http://twitter.com/12ChangeLearn>
L linkedIn <http://nl.linkedin.com/pub/inge-donkervoort/7/4b/18a>
FayCross schreef op 11-5-2016 10:54:
> |body {
> font: italic bold 30px serif;
> }|
