### ISSUE TITLE
MathJax not displaying in Decision Tree

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#495]
Hi @FayCross,

This was raised on the forum http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1101&Itemid=759&lang=en#3696 and i've fixed it (I think) in this commit (https://github.com/thexerteproject/xerteonlinetoolkits/commit/c709a670c57ac81b1bdd24b355749152c9150157) but just flagging it here as a fixed issue and tagging you in case it was left out by design or in case it caused some other unforeseen issue.

If it is fixed though them it might be worthwhile @torinfo  and @ronm123 pushing it into a 3.2 hotfix? Could you do that Tom if so as I can't remember how to :-(

**Comment by FayCross** [comment]
Thanks - no it wasn't left out on purpose. I wouldn't have thought it would cause any issues to have it in there
