### ISSUE TITLE
Very small margin when bullets are to the right of a left alligned image

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#499]
When you add a left alligned image with the editor, then use a bullet list to the right of the image, there is a very small margin (see attachments). The bullets are directly next to the image.
![bullet-1](https://cloud.githubusercontent.com/assets/5703781/15291560/d9205de0-1b7e-11e6-9d3f-35592663df22.png)
![bullet-2](https://cloud.githubusercontent.com/assets/5703781/15291561/d921c89c-1b7e-11e6-88e8-18d775902ec5.png)

**Comment by JohnSmith-LT** [comment]
Hi @ingedonke can you check whether this fix (to the mainStyles.css file) has made any difference without screwing up other stuff?

**Comment by FayCross** [comment]
Closing as this seems ok now
