### ISSUE TITLE
Problem with using h2 and h3 tags in Matching Text

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#500]
Matching tekst uses h2 and h3 tags and that shouldn’t, because it make custom css unworkable. Can someone take a look?

**Comment by torinfo** [comment]
Pfeew 

A lot of models depend on h3 in a way I think they should not. It should have been handeled.

- accNav.html
- annotatedDiagram.html
- audioSlideshow.html
- buttonNav.html
- captivate.html
- categories.html
- chart.html
- cMcq.html
- colourChanger.html
- columnPage.html
- customHotspots.html
- decision.html
- delicious.html
- dictation.html
- dragDropLabel.html
- flashPaper.html
- hotspotImage.html
- interactiveText.html
- inventory.html
- iSpring.html
- jing.html
- links.html
- list.html
- mcq.html
- mediaLesson.html
- modelAnswer.html
- orient.html
- perspectives.html
- quiz.html
- raptivity.html
- rss.html
- slideshow.html
- summary.html
- tabNav.html
- tabNavExtra.html
- textMatch.html
- textSWF.html
- timeline.html
- wiki.html
- youtuberss.html

**Comment by FayCross** [comment]
I'm not sure I get this.

H1 is only used for LO title on header bar
H2 is only used for page title on header bar
... if either of these are used in any page models then yes that's wrong (I don't think they are though but am happy to make changes if they are used where they shouldn't be)

H3 is often used in page models but in the vast majority of the pages above isn't that the correct use of it? For example on all the navigators the H3 is used for the text on tabs / accordion bar etc. They are sub headings so should be marked up as such.

I agree that on a handful of the page types the use of it is a bit tenuous and could be looked at (matching text being one of them) but I'd be very reluctant to remove H3 from most of the examples listed. I just don't know why we would want to do this.

**Comment by FayCross** [comment]
Could we take heading 1 & heading 2 out of the paragraph format drop down in the wysiwyg editor? We don't really want people using those in their page content.

**Comment by torinfo** [comment]
The list was just composed using grep, so it might include pages where h3 is used in a proper way. I noticed that in some of the pages there was code to serach for and replace the contents of h3 tags. I am not sure that's a good way of doing things (but I might be worng)

**Comment by FayCross** [comment]
Oh ok, yeah, not ideal if the contents of the h3 tag changes. I'll look into it

**Comment by JohnSmith-LT** [comment]
Only 6 files specifically use find("h3")

![image](https://cloud.githubusercontent.com/assets/3907362/15578721/845e7354-2359-11e6-899d-f4e4975f168a.png)

Mostly the rest use H3 in a way that could be considered ok but that is all dependant on what the end user wants to do. Since H3 is a common tag and next in line (after we've removed H1 and H2) then perhaps over time we should migrate away from using them in favour of using a class reference that's unlikely to be also used by the end user?

I couldn't find H2 in the textMatch model so I think the only issue we have is with H3
