### ISSUE TITLE
Glossary on/off

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#503]
Is it possible to disable the glossay on all the page types? Now it's only possible in the quiz.

**Comment by JohnSmith-LT** [comment]
Hi Inge,

I've now enabled this in develop branch but it's going to need someone to do testing to make sure that I haven't broken anything or changed the original functionality in Quiz as I don't have access to a fully developed Quiz page to test with. It was added to quiz by @FayCross in Jan2015

**Comment by JohnSmith-LT** [comment]
Hi Inge,

I've now enabled this in develop branch but it's going to need someone to do testing to make sure that I haven't broken anything or changed the original functionality in Quiz as I don't have access to a fully developed Quiz page to test with. It was added to quiz by @FayCross in Jan2015

**Comment by torinfo** [comment]
John,

I don't think this is what was meant. People want to be able to switch of the glossary on select pages, irrespective of the kind of page.

**Comment by JohnSmith-LT** [comment]
Tom, I don't get what you mean? I've added an optional property to every page instead of just Quiz so now you can turn off glossary on any page you wish. Is this not what was meant?

**Comment by torinfo** [comment]
Sorry John, Didn't look close enough, you're absolutely right. Thank you.

**Comment by FayCross** [comment]
I'll check this doesn't mess up quiz page and close if it's ok. Makes sense to be on all pages now it's easy to add it to all

**Comment by JohnSmith-LT** [comment]
Cool Tom and Thanks Fay. Can you also just double check that I haven't screwed the xwd files also as I just did a search and replace to create them rather than the normal build route as I wasn't quite sure of the rebuild procedure.

**Comment by torinfo** [comment]
For the future: just run one of the rebuild scripts in the build folder. The .sh one should work on an Apple (if you have php installed).

**Comment by JohnSmith-LT** [comment]
How do I run it Tom? I think this is where I got stuck before... I tried the below and looked at Fay's instructions which seem to suggest the same and still get the same error

bash-3.2$
bash-3.2$
bash-3.2$ ls
php                     rebuildNottingham.sh    rebuildsite.sh
rebuildNottingham.bat   rebuildsite.bat

bash-3.2$ rebuildNottingham.sh
bash: rebuildNottingham.sh: command not found

bash-3.2$ sudo rebuildNottingham.sh
Password:
sudo: rebuildNottingham.sh: command not found

bash-3.2$ sudo .\rebuildNottingham.sh
sudo: .rebuildNottingham.sh: command not found

bash-3.2$ sudo ./rebuildNottingham.sh
sudo: ./rebuildNottingham.sh: command not found

bash-3.2$ php -info
phpinfo()
PHP Version => 5.5.31

System => Darwin MacC02Q70JKFVH7 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
Build Date => Jan 11 2016 23:23:21


PHP devinitely installed as shown and in correct folder so i'm at a loss ?!?

John

________________________________________

**Comment by torinfo** [comment]
Two options:
1. 
Make rebuildNottingham.sh executable 
`chmod 755 rebuildNottingham.sh`

And then call

` ./rebuildNottingham.sh`

or 2:

`sh rebuildNottingham.sh`

**Comment by JohnSmith-LT** [comment]
Cheers Tom, using sh prefix got it to work but now i have another issue... it's not including the wordsearch.xwd file into data.xwd and for some reason it is removing the Disable Glossary option from data.xwd

I've double checked and I have this line

<disableGlossary label="Disable Glossary" defaultValue="false" type="CheckBox" optional="true"/>

in the basicPages.xwd file yet it's not being taken into the data.xwd 

What am I doing wrong? Any ideas?

**Comment by torinfo** [comment]
The disableGlossary works for me here (on Linux) 
Obviously not wordsearch (because I don't have that)

Make sure you have the latest update (Fay introduced this on April 22)

Make sure you copy the correct data.xwd? make sure you have write permission so the script can overwrite? I don't have any other tips....

**Comment by ingedonke** [comment]
When turning off the glossary with the optional property it's only off on the first page of pages with subpages or nested pages. For example the quiz. On the description the glossary is off but on the questions it isn't. That's also with the other pagetypes with subpages.
