### ISSUE TITLE
This project does not contain any pages error

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#510]
Just pulled down the latest develop and created a new project with xot template to test something but getting a "This project does not contain any pages" error.
The project folder and xml files are created and I'm not seeing an error in the browser console (or nothing new anyway). Existing projects play ok but it seems editing doesn't work either - e.g. changes not saved.

Anyone else getting this with latest develop?

**Comment by torinfo** [comment]
I installed the latest develop (from the unstable zip) on xot.xerte.org.uk, and that is working for me.

**Comment by ronm123** [comment]
Hi Tom
yeah but clearly that isn't how you work locally and develop? I have a local xampp install of develop and pull updates into that and it usually always works fine but something recent has caused this problem. I don't have time to investigate or test further until Wednesday now but will have a look again then. However would be useful to know if you or others can replicate?

I actually updated an online install from the same develop code and found it had the same problem so replaced that with the 3.2 download from the community site and that doesn't have the same problem.

**Comment by FayCross** [comment]
Umm, is this the same thing I emailed you a minute ago about Tom. xot.xerte.org.uk isn't working for me anymore. Can open editor but not play / publish

**Comment by torinfo** [comment]
It was a problem in editor/upload.php

Fixed
