### ISSUE TITLE
Media Lesson page panel titles aren't responsive

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#512]
Need adding to responsivetext.css files in all themes

**Comment by ronm123** [comment]
Hi Fay
Happy to have a look at this but delivering training all day tomorrow so will be Wednesday at the earliest.

**Comment by FayCross** [comment]
Don't worry Ron, I was going to look at it later but put it here as a reminder really

**Comment by FayCross** [comment]
Can't see a fix that's been committed for this but it seems ok now
