### ISSUE TITLE
Bootstrap headerColour and headerTextColour

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#516]
Hi all
I'm sure this worked at some point previously but doesn't currently and I wonder if it's since the editor change. If in a Bootstrap project you add the optional properties for header Colour and/or Header Text Colour the chosen colours get saved in the xml as headerColour and headerTextColour but they get saved as for instance `headerColour="0x3636FF" headerTextColour="0xFF2137"`
In \modules\site\parent_templates\site\common\js\application.js the chosen colours are picked up including whether two values have been added for a gradient but the colours are only displayed if the value is for instance #3636FF rather than 0x3636FF

I'm not sure how to change the values saved by the editor and colour picker to # or perhaps the best option is to replace the 0x in application.js?

**Comment by JohnSmith-LT** [comment]
Does that fix it for you Ron?

**Comment by JohnSmith-LT** [comment]
Sorry put up wrong file last night.

**Comment by ronm123** [comment]
Hi John that does fix it but sorry now that it's working I've realised another slight problem :-(

I tested what the solution might be before your fix by changing the values in the xml files including two values for the header colour to create a gradient. That all worked and works now except the colour picker in the editor doesn't allow adding a second colour, not even manually. Thinking about it this is probably when it stopped working when the property was changed at some point from a text entry field to a colour picker.
I guess we need a second header colour option and second colour picker? Or perhaps header colour is a single colour as it is now but then we add a headerGradient option that is just text entry or perhaps a gradient selector exists?

**Comment by ronm123** [comment]
Just a quick further note (going offline shortly) it is actually possible to add a gradient using the current picker but it's a bit odd and a bit of a hack...

1. select a colour with the picker and copy the value to the clipboard
2. select another colour with the picker then add a comma, followed by 0x and paste the copied value making it for instance 0x005226
3. That comma and second value disappears but is saved in the xml

![image](https://cloud.githubusercontent.com/assets/5167146/15626342/a31ded76-24ba-11e6-8fbe-a87f37e972fe.png)

**Comment by JohnSmith-LT** [comment]
Yeah after we were discussing the navigate on timer thing the other day i was thinking that we need some way of easily creating custom editor fields, even composite ones from the ones we currently have, so for example you could have 2 colour pickers for a gradient or you could have a timer navigate field with both a numeric stepper and a checkbox. That way both elements are added at same time and we dont need to have 2 or 3 optional elements where you need to add them all.

It should be relatively easy to do in a similar way to the way we are thinking of going with page models where we create a black box with inputs and outputs and each are self contained.
