### ISSUE TITLE
When copying a title the properties don't copy

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#524]
When you copy a title from one page title to another page title the properties are gone. You have to select the new copied title en add properties again and then it is allright. 
Is this something that can be fixed?

**Comment by JohnSmith-LT** [comment]
Hi Inge,

What do you mean by properties? I thought you meant the formatting (like bold, underline, colour, font size etc) but that appears to work between the page title boxes.

**Comment by ingedonke** [comment]
I'll ask for an example, that's easier to explain. I'll get back on this.

**Comment by FayCross** [comment]
#453 asks for formatting to be removed when copying titles - I think this would be my preference to be honest as it's easier to add styles than remove them

**Comment by FayCross** [comment]
Closing as text styles do seem to copy over with text
