### ISSUE TITLE
Panel width in dialog (for example)

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#528]
Is it possible to add the field where the developer can choose the widht of the panel in the wizard like on other pagetypes where you have a panel? Like in Quiz and Dictation for example?
Should this be possible in all pagetypes with a panel?
![2016-06-05_2138](https://cloud.githubusercontent.com/assets/5703781/15807745/ecaf65b2-2b65-11e6-86c1-ac4a877ff5e5.png)

**Comment by FayCross** [comment]
Done for all pages with a full height panel
