### ISSUE TITLE
Author Support notification

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#529]
Related to #514 

It might be useful to alert people to the fact that author support is turned on when they preview. I'm sure I've had someone ask me about the weird red text before as they had added author support not knowing what it did.

Maybe just a message at the top of relevant pages saying something along lines of 'You are seeing this red text because author support is turned on, to turn it off...'

Possibly only make author support visible in preview rather than play views too

**Comment by JohnSmith-LT** [comment]
Good idea, when I saw that in the forum I had no recollection of the Author Support although as soon as they said so I suddenly remembered seeing it before, but long ago...

I also like the preview/play difference as it means you don't have to keep switching it on and off before publishing...
