### ISSUE TITLE
Lines disappear in Drawing page after "Save" is pressed...

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#53]
Related to this forum post:

http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=332&Itemid=207&lang=en&limitstart=0

Julian is going to take a look at some point...

**Comment by torinfo** [comment]
I can still reproduce this, when using the Flash editor, but it doesn't occur in the HTML editor.

The actual flash swf files (the drawing editor themselves) are different, because the HTML5 wizard uses javascript to save the drawing.

**Comment by JohnSmith-LT** [comment]
Yeah I never got to the bottom of that one... very strange. Glad its gone though.
