### ISSUE TITLE
Add format painter button to WYSIWYG toolbar

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#530]
Requested in workshop at Apereo conference...
Add button to allow you to copy formatting from one chunk of text to another. Like format painter button in Word.

**Comment by JohnSmith-LT** [comment]
There was a ticket created 9 YEARS!! ago for this feature for ckeditor but looks like it's still not made it through... several requests in different places as well...

https://dev.ckeditor.com/ticket/1142

**Comment by FayCross** [comment]
Our oldest issue (3 years) doesn't seem too bad now

**Comment by JohnSmith-LT** [comment]
I was thinking that :-)

**Comment by FayCross** [comment]
Paste formatting button added with this commit: https://github.com/thexerteproject/xerteonlinetoolkits/commit/84b8da87ed07fac1aa7de924a45df2a1496c0ad0
