### ISSUE TITLE
Bootstrap page links - links to sections don't work

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#532]
When you add a page link to a Bootstrap project you get a choice in the drop down menu of all the pages and sections in the project. Only links to pages work.

Previously I think only the pages appeared in the page link menu - the sections appearing there too might have been caused by fix to #502

**Comment by JohnSmith-LT** [comment]
Yeah, sorry, I haven't even looked at Bootstrap yet although there was mention of deeplinking to sections in bootstrap too. I'll probably just make this available for 'xerte' projects just now.

**Comment by JohnSmith-LT** [comment]
Hi Fay, can you test if that fixes it for you just now? I'll change this to an enhancement request now.

**Comment by FayCross** [comment]
Yes that's fine now John - thanks
