### ISSUE TITLE
No Login Box and 500 error loading language files

### ISSUE THREAD

**Issue by patriclougheed** [thexerteproject/xerteonlinetoolkits#535]
I cannot get the login box to appear on my fresh install. The management page login works fine but I cannot manage language files from there as well. 

My log shows an error loading the language files:
PHP Fatal error:  Call to a member function xpath() on a non-object in /var/www/xerte/website_code/php/language_library.php on line 41

Which is `$xml_langs = $xml->xpath('/*/language');`

I am running NginX 1.11.1 with PHP 5.5. Not sure if it is an issue with my NginX config as I cannot find a working example for Xerte or if I am missing a PHP module. I have a dozen other sites like OwnCloud, GNUSocial running on same server without any issues.

What I miss?

**Comment by torinfo** [comment]
1. No login box. Which authentication method have selected in the magament page or during setup?

2. Langugae management: What OS? (I assume Linux, but which distribution)? Can you check whher simplexml is enabled i your php?

**Comment by patriclougheed** [comment]
1. LDAP then switched to DB, static and guest to test with no change.

2. Ubuntu 14.04 and SimpleXML is enabled.

**Comment by JohnSmith-LT** [comment]
What about the browser console? Do you see any javascript errors or 404 codes in the 'network' tab?

**Comment by torinfo** [comment]
And is 'dom' enabled?

**Comment by patriclougheed** [comment]
Console only reports a 500 error, no JS or 404. I upgraded to 5.6 with these modules:
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

Was able to see login box once, logged in with LDAP account no problem but no real UI after that. Management page reports the creation of the LDAP user but now the login box will not show again.

**Comment by torinfo** [comment]
What about the answer to John's question about the sitedetails site_url in the management page? Is the site_url the same as the url you use to access xerte?

**Comment by patriclougheed** [comment]
Only http no ssl yet.

**Comment by JohnSmith-LT** [comment]
Closing since this is now 6 months old.
