### ISSUE TITLE
Allow relative text sizes in wysiwyg editor

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#542]
Requested by UoN user

At the moment it you change the text size of some text in the wysiwyg editor it is fixed to that size even if the rest of the page's text is responsive or if the 'Default Text Size' is later changed. Could we have an option for text size changes to be relative to the size of the text on the rest of the page?

**Comment by ronm123** [comment]
Sorry I've added a similar issue to this as issue #582 probably worth discussing how best to do this and with future-proofing in mind during the developer days

**Comment by FayCross** [comment]
Closing as it's a duplicate of #582
