### ISSUE TITLE
Hotspot appearance change 

### ISSUE THREAD

**Issue by GraemeSamuels** [thexerteproject/xerteonlinetoolkits#546]
Hi I've just stumbled on this hub and not sure if it's the correct forum but.. 
Would it be possible to get a hotspot to change appearance after being clicked?

**Comment by FayCross** [comment]
Do you mean hotspots on the hotspot image page or one of the other pages? The hotspot image page will add a border around the hotspot when clicked but it's not possible to, for example, insert another image into the hotspot when clicked. You could see if the morph images page will do what you're after but it's only possible to have 1 hotspot on it.

The forums on the community site (http://xerte.org.uk/index.php?option=com_kunena&view=category&Itemid=760&lang=en&layout=list) or the xerte mailing list (http://lists.nottingham.ac.uk/mailman/listinfo/xerte) are probably the best places for questions like this. You might get some suggestions on how other people have achieved what you're after if you post there and describe the activity you're trying to create.

**Comment by GraemeSamuels** [comment]
Yes, on a hotspot image page. 
When you click on a hotspot you get a boarder or a visible boarder gets thicker. But there is no way to get the hotspot to be tagged to say it has been selected already. So if you have more than one  hotspot the learner doesn't not has a visual indicator that they have visited that hotspot. 
The function I'm describing is built into some of the menus that change colour after they have been clicked so with my very limited knowledge of programing, it would seem like something that can be achieved.

**Comment by GraemeSamuels** [comment]
Ps. I've not had any luck posting on the forum you mentioned.

**Comment by FayCross** [comment]
Ok, if you have a reasonably up to date version of Xerte then you can do this:

1. Add the optional property 'Script' to your hotspot page and paste this code into it:

`$("#hsHolder a.hotspot").click(function() {
  $(this).addClass("visited");
});`

2. Then add the 'Styles' optional property and paste this into it (adjusting colour etc. depending on exactly how you want a visited hotspot to look):

`#hsHolder a.hotspot.visited:not(.selected) {
  border: 1px solid black !important;
}`

This will show hotspots that have previously been clicked with a thin black border around them. You could also look at including background colour / opacity in the css to achieve a faded out look to the whole hotspot

I hope this helps. Unfortunately i don't have time to add a more user friendly way of doing this through editor options at the moment.

**Comment by GraemeSamuels** [comment]
That is fantastic. Thanks for your time 
Just one last question. 
I'm a user rather than owner of xerte so if I have an older version of the software is this going to be unachievable or would there be a work around?

**Comment by FayCross** [comment]
No problem. The styles & script optional properties are both reasonably new so won't be available to add on older versions. I'm not sure exactly when they were added though so aren't sure exactly how new your install will need to be. If they don't appear in the optional property list for the page then there is another way to get the code in. Let me know if you can't see the two options and we can try something else.

**Comment by GraemeSamuels** [comment]
Thanks. I've just had that conversation and we are on V. 3.0. So the additional properties are not available to me.

**Comment by nuuyoo** [comment]
_Photo SreenShort Samsung TabLet**ขอมีส่วนร่วมด้วยคน**_

**Comment by FayCross** [comment]
Ok, this isn't the most user friendly way of doing things but if you can't add the optional properties then try this:

In the 'Text' field on your hotspot image page, expand the editor's toolbar by clicking the small arrow in the top right of the text field.

Click the 'Source' button and paste this code at the very top of the text field (above any text you have entered for the page)

`<script>
$("#pageContents").on("click", $("#hsHolder a.hotspot"), function(e) {
  $(e.target).addClass("visited");
});
</script>
<style type="text/css">
#hsHolder a.hotspot.visited:not(.selected) {
  border: 1px solid black !important;
}
</style>`

Publish and preview your project

**Comment by GraemeSamuels** [comment]
Thanks again for your time. I will try this out later today. 
Would you have any objections to me copying the above over to the xerte forums as I have the same question posted there. It might help others

**Comment by FayCross** [comment]
No that's fine
