### ISSUE TITLE
Timeline in v3.3 breaks old LO's

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#548]
The new timeline model assumes that the drag label is valid html code

The single line editor is replaced by full textarea, to make it easier to use pictures as a draggable object. But this breaks old LO's.

Fix is straight forward, so implemented as a hotfix.

**Comment by ronm123** [comment]
@torinfo how doe the timeline fix resolve the issue with the matching texts?
I pulled down and tested with the latest develop yesterday and although I'm aware of the timeline fix that doesn't resolve this matching texts issue as far as I can tell?

**Comment by torinfo** [comment]
Sorry, than I was to quick, and will have a look. Apologies.

**Comment by torinfo** [comment]
I'll close this one, and re-open the matching text
