### ISSUE TITLE
Background Image 

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#554]
Could we have an options to make background images darker: you can control the opacity, but that only makes things lighter, I'd like to make some images darker to use white text over the top.

**Comment by JohnSmith-LT** [comment]
How would this work? We could easily overlay a black div with opacity set and that would darken the whole image, but including areas of white... you could then control the opacity of the div to control the darkening 0-100%... but not sure if that is what you want...

![image](https://cloud.githubusercontent.com/assets/3907362/22881916/93eae61c-f1e0-11e6-91c6-52b0abd1a03d.png)

vs

![image](https://cloud.githubusercontent.com/assets/3907362/22881864/536ea75e-f1e0-11e6-96b6-899353932a53.png)
