### ISSUE TITLE
Add theme options for Bootstrap and Decision templates

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#558]
Would be useful to add theme options like we have with the xot template for the Bootstrap and Decision project templates too.

**Comment by FayCross** [comment]
I've added the code for Bootstrap themes to work but don't have a proper example of an alternative theme yet. At the moment there's just a test theme in the site themes folder.

**Comment by ronm123** [comment]
Hi Fay thanks for this.
I've added a theme folder called blackgrey which works fine but a couple of questions:

1. did you remove your test.jpg because there isn't a view of the screenshots in the site template? Mind you there isn't in xot either.

2. At the moment the selected theme isn't included in export - what needs to be done to include the selected theme?

**Comment by ronm123** [comment]
Would be good to have a js file option in the themes too like in the Nottingham themes. I tried locally adding the following to application.js below the css inclusion but probably have the syntax wrong?

`$('head').append('<script src="'+ $(data).find('learningObject').attr('theme') + '/' + $(data).find('learningObject').attr('theme') + '.js' + '</script>');`

**Comment by FayCross** [comment]
Hi Ron, proper themes will need the jpeg I guess, although it would be better if we got these to actually show somewhere! I wondered about js file but didn't have time to add this afternoon. I think your code isn't working as I don't think the Bootstrap one uses jQuery so using $ selectors won't work (could be wrong about this)

Will try to look at export next week (not in until Thursday now). I always forget about export

**Comment by ronm123** [comment]
@FayCross my code didn't work because I stupidly not included the themePath and a syntax error too. :-(

So this is done now site themes included in export and themename.js file included in preview/play and export. Didn't think you'd mind me saving you have to do it  on Thursday! ;-)

**Comment by FayCross** [comment]
That's great Ron, thanks. I'll hopefully get a chance to add the same to the Decision Tree template soon too

**Comment by ronm123** [comment]
@FayCross That would be great. I have at least one test of styling the decision tree template that I could add as a theme. I've been exploring a new theme for the xot template too did you find that stylesheet you tested for changing the image icons?

**Comment by FayCross** [comment]
Just sent it to you @ronm123

**Comment by FayCross** [comment]
@ronm123 I've just added the same functionality for decision tree template (again with just a test example theme) so if you have a better one to commit please feel free to delete the themes/decision/test folder

**Comment by ronm123** [comment]
Great thanks @FayCross will have a look and add a theme once I'm happy with it.
Have a good w/e.

**Comment by ronm123** [comment]
Hi @FayCross I was just looking at adding a theme for the decision tree template but there seems to be a bug with the theme path values somewhere that I can't find.
My test theme plays fine via preview but not via play.
In decision.js if I debug themePath it shows as http://127.0.0.1/develop/themes//
and allParams.theme shows as undefined
but I might be looking in the wrong place especially as it works via preview but not play?

**Comment by FayCross** [comment]
This should be ok now Ron but let me know if not. Thanks

**Comment by ronm123** [comment]
@FayCross Yeah working now thanks. Will commit a theme in due course.
