### ISSUE TITLE
Add additional options to Xerte page links

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#561]
Would be good to add additional options to the Xerte Page link menus whether using the toolbar or right click method. e.g. as well as the specific page ID links that we have now which always work regardless of whether the destination page is moved would be good to also have static links like next page and previous page and possibly even first page and last page. The reason this would be useful is to have links within text/instructions that continue to the next page or go back to the previous page and continue to work when the page order is changed. I know we have next and previous links in the navigation bar but sometimes an instruction followed by a continue button is very effective.

This can be achieved now by adding code e.g.
`<p><a href="#" onclick="x_changePage(x_currentPage +1); return false;">Next page &gt;&gt;</a>
</p>
<p><a href="#" onclick="x_changePage(x_currentPage -1); return false;">&lt;&lt; Previous page</a>
</p>
`  
Not sure about historic back.
Would be good to make it easy for all users to do this.

**Comment by JohnSmith-LT** [comment]
This now added to Bootstrap also with commit https://github.com/thexerteproject/xerteonlinetoolkits/commit/3aaef2fb766686ee8f4ba82afee8c48e70ff68b0
