### ISSUE TITLE
pasting (or dragging) images into editor

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#567]
I'm sure we've all seen or been asked by end users about copying and pasting images into the editor rather than selecting to browse and upload and I've always been impressed with the likes of Trello and Google docs etc that facilitate this. I noticed there is a plugin available that allows this with CK editor e.g. http://ckeditor.com/addon/uploadimage although I think a later version than we currently use.

Just wondering if the license and integration required allows us to add this at some future point?

**Comment by JohnSmith-LT** [comment]
Yes, even here in Github (although other places do it a bit better by showing the images straight away). 

We need to upgrade at some point anyway so it's probably worthwhile - there is also a Format Painter type plugin for a later ckeditor version that is also down as an enhancement...

**Comment by torinfo** [comment]
- Updated CKEditor to version 4.6.2
     - Included the uploadimage plugin to be able to drag images into the
       editor. Paste should work as well, but I couldn't get it to work.
     - Also changed the image plugin to be able to hande percentages as sizes
       As soon as you drag the resizer, the size will be set in px again.

**Comment by ronm123** [comment]
@torinfo thanks for adding this.
The pasting of images works for me but there is a difference between how this currently works in the demo at http://sdk.ckeditor.com/samples/fileupload.html#uploading-dropped-and-pasted-images and how it currently works in Xerte. If I copy and past and image in Xerte it uploads and gets saved as image.png If I then paste another image either in the same editor window or another editor window it replaces the file named image.png in the media browser and therefore replaces the image even if that was added at an earlier time or on a different page etc. However in the online demo a second paste gets named image(1).png and image(2).png etc. Is that perhaps a configuration setting missing that controls naming and multiple pastes?

**Comment by torinfo** [comment]
This should be handled by the back-end handling function which I had to implement. As I didn't get it to work, I didn't know what I needed to do. 

Will implement this. Any preference for the name? pasted_image.png?

**Comment by ronm123** [comment]
@torinfo yes I guess it could be quite useful to distinguish between pasted images and others. I suspect over time people will get used to renaming in the media browser. Given that if they don't rename the images become part of browser cache etc for viewers I wonder if something a bit more subtle to distinguish between pasted images and others might be better e.g. pimage.png or p_image.png?

**Comment by ronm123** [comment]
@torinfo BTW I had to force refresh in the editor before it worked - could that be why you didn't get it to work? Is it working for you now?

**Comment by torinfo** [comment]
It's working in firefox now. And I fixed it. In the end, I left the name at image for now.

**Comment by ronm123** [comment]
works great! - have only tested in Chrome. For screenshots etc this is a great productivity enhancement!
