### ISSUE TITLE
Problem with RSS template

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#569]
While RSS now loads in the editor, when you create a new item there is no way to add the title, link, description or pubDate fields and when you duplicate one containing these fields then they are not copied over to the duplicate.

![image](https://cloud.githubusercontent.com/assets/3907362/22993414/d5485c58-f3ba-11e6-81c6-2d687c982e01.png)

**Comment by FayCross** [comment]
Closing as this template is now deprecated now flash isn't supported
