### ISSUE TITLE
add horizontal scrolling for when page or icon titles are longer than max width

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#572]
This has cropped up loads of times where authors have long titles in the tree which exceed the max width of the left hand pane in the editor and so push the little + for expanding icons to left and out of reach. I've tested this and an easy fix is to update the relevant css to set horizontal scrolling to auto e.g.
`.pane-west .content #treeview {
overflow-x: auto;
}`
I can make and commit that change but just wanted to check is /editor/css/complex.css our version or would that change get overwritten if we update the editor?

**Comment by ronm123** [comment]
BTW we could probably add a similar change to the right pane? e.g.
.optButtonContainer table {
    overflow-x: auto;
}

**Comment by torinfo** [comment]
complex.css is ours, so you can savely change that.

However, be carefull with the right panel, because of the way the widths of the buttons are set.  It was quite tricky to get them all the same length without using a fixed size.

**Comment by ronm123** [comment]
@torinfo thanks. Actually it looks like the right pane already has horizontal scrolling if needed so don't need to touch that and have comitted the left pane change.
