### ISSUE TITLE
hotspot editor could be larger

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#575]
not sure what determines/controls what size the hotspot editor displays but it seems like it could be larger and perhaps fill 90% of height or width?
As an example I was using the page type to show how a particular LO  was built and when adding hotspots to explain icons in the tree the hotspot editor displays in a very small window compared with the overall editor window and makes it difficult to position and resize the hotspots...

![image](https://cloud.githubusercontent.com/assets/5167146/23310741/71bfc444-faab-11e6-8d25-35cbcd5750df.png)

**Comment by torinfo** [comment]
This is controlled in /editor/css/complex.css (line 789)

`.hotspotLightboxImg {
    width:800px;
}`

**Comment by ronm123** [comment]
@torinfo thanks Tom. I've just tested setting that to first 90% and then in fact 100% which seems to work fine. There must be an outer wrapper so 100% is filling that but not the whole window but it's certainly bigger and more usable. However I'll test on a lower resolution monitor/computer before committing.

**Comment by ronm123** [comment]
Seems to work fine on lower res device so have committed the change.
