### ISSUE TITLE
help text in editor

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#576]
I like the potential of the help text when hovering over optional properties but wondering if we could/should make it more obvious wherever that exists similar to Moodle e.g. little help icons which show summary info on hover and more detail when clicked. Would also mean the tooltips only show when required rather than all the time when hovering over optional properties. 
Mock up as follows:
![image](https://cloud.githubusercontent.com/assets/5167146/23311654/bb90a1da-faae-11e6-9420-7b7a0df46ce5.png)

Also I'm not actually sure if the same tooltips are available for all properties rather than just optional properties or whether they are internationalised? Both would be desirable I think.

**Comment by FayCross** [comment]
No I don't think there is similar help for required properties but it would be very useful - I thought I had opened an issue about this a while ago but can't find it now.

**Comment by FayCross** [comment]
Related to #442
