### ISSUE TITLE
issue with resizing hotspot image connector pop up html window

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#577]
when a user resizes a hotspot image connector pop-up html window it snaps shut and then when the hotspot is clicked again opens with just the header showing and not the contents. If the user tries to resize again it just closes again. However it seems to vary a bit by what size and shape the pop-up is resized and sometimes when repeating the process the pop-up does reopen back to its default size.
Haven't tested in all browser but have tested in Chrome and Firefox.

**Comment by FayCross** [comment]
This should be fixed when we upgrade the version of jQuery we use: [https://bugs.jqueryui.com/ticket/7514](url)

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 

This appears to fix this long standing bug by using "auto" for the dialog box height. Can you please check that it doesn't break something else?

https://github.com/thexerteproject/xerteonlinetoolkits/commit/067f63ce7fa015e227bf2760e210eea930a2eac9

John

**Comment by JohnSmith-LT** [comment]
In fact that first commit, while apparently working, threw up lots of console errors where jQuery didn't appear to like "auto" dispite it being an option in the dialog plugin...

Since height was originally being set to undefined, simply removing it completely appears to fix things and retain the functionality that once a window is resized then it stays that size after closing and re-opening.

**Comment by ronm123** [comment]
@JohnSmith-LT for me when I resize the popup with Chrome it just closes and then reopens original size.

**Comment by JohnSmith-LT** [comment]
Yeah I think that's a bug with the jQuery UI library that may not be fixable at this version. What I was seeing before this commit was that occasionally when you went to resize it would close the window however when you reopened it it had collapsed to just a title bar and you couldn't get it back without reloading the LO. I can't make that happen anymore though - it always comes back at original size which should be the minimum to show all the content so perhaps the window would then never need resizing? Do you get any popups on any LOs/pages that still has a scrollbar and might need resizing?

**Comment by ronm123** [comment]
@JohnSmith-LT agree that at least having the popup open at original size and not just the title bar is better. Yes I think I have seen some examples where ideally the end user would resize either because there is a lot of content and therefore scrolling or just because they want to move and resize the window to be able to see the underlying content as well as the popup content. Will have a look later if I can find a suitable example but have to go offline now until later this afternoon.

**Comment by FayCross** [comment]
Closing as you can now open content in a lightbox rather than dialog & this is more suitable for cases where there's lots of text etc. to show.
