### ISSUE TITLE
lightbox functionality

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#580]
I'm adding this now because it cropped up in the discussion about additional plugins for the editor e.g. there is a lightbox plugin which uses lightbox2 http://lokeshdhakar.com/projects/lightbox2/ 

However although I think including that plugin would be useful and I think we might even have it or similar e.g. as part of the hotspot editor functionality I think it would also be good to replicate this functionality elsewhere e.g.
1. Allow an author to add text, icon or image links on a page which when clicked open up a lightbox and ideally not just an image and caption but if possible an html popup like we have in the hotspot image connector as an option.
2. In a tool like Articuate storyline it's possible to add a lightbox link to any slide/page which opens one of the other slides as a lightbox slide over the top of the existing slide. I'm not sure how easy this would be to achieve in Xerte but in the xot template we have a sequence of pages and it would be good to allow users to replicate this feature from Storyline in Xerte so that a single page with all its functionality could be opened over the top of any other page via a lightbox link. 
3. If we think 2 is possible then perhaps even making use of the hide page functionality so that as authors any page that we intend to use as a lightbox could be hidden from the normal linear navigation and list of pages but that when linked as a lightbox page still displays to the viewer. This can be useful for help screens, note taking screens etc or just more dynamic and less linear pulling of content by the learner.

Perhaps for further discussion during the developer days.

**Comment by FayCross** [comment]
Forgot to link to this issue from commit: https://github.com/thexerteproject/xerteonlinetoolkits/commit/0baba6887f76ef3072855a7b6d6abad1ebf1c527

**Comment by JohnSmith-LT** [comment]
Hmmm found this one too @ronm123. Now that the lightbox plugin is 99% complete (i hope) should we combine these perhaps into a new issue and see what is still outstanding and required and we can perhaps take a look at them with fresh eyes and having 3+ years of additional developments to bounce off?

**Comment by ronm123** [comment]
@JohnSmith-LT yes I think it probably is worth combining this and #758 into a new issue and then closing the old ones. As I originated both those issues leave it with me and I'll put on my to do list to close the old issues and create a new one in time for our next dev day if not sooner. Some of this overlaps with what we had on the meeting agenda and discussed during the last meeting and obviously directly with what you've enabled via the editor plugin too.

**Comment by FayCross** [comment]
Item no. 3 in Ron's list has just been committed - are the others done? Can we close this?

**Comment by FayCross** [comment]
Closing as most of the issues have been dealt with & those that haven't are in issue #758
