### ISSUE TITLE
Should we move the default theme(s) to the themes folder? Also change other defaults for new projects?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#583]
I often get asked can we change the defaults so that all new projects use a particular theme and possibly even some default properties and content. 

Default theme
For the theme I think the easiest option would be to have a management page option to set the default for the site which is then used to set the default theme for new LO's. Or perhaps even easier that if a default folder is found in the themes folder then that is used instead of the images and styles found in the parent_templates common_html5 folder.

Default properties for new projects
I wonder if we could/should change some of the defaults so that for instance:
Display mode is Fill Window
Theme is default if detected in themes folder or something else if set via management
Default text sizes and menu set to vmin sizes rather than fixed sizes to allow control over relative sizes throughout the LO

Control over default structure/content for new LO's
Perhaps via management the ability to import exported projects for each project template which then becomes the default for all new projects using that template or at least an option to do so.
I used to do this on one of the Jisc Techdis installation whereby I customised the data.xml in the templates folder and added media to the media folder which got used each time a new project was created. However it was a pain keeping that working after each upgrade and perhaps there is a need for more than one choice anyway.

**Comment by FayCross** [comment]
A lot of this has already been done either recently (default theme is now in theme folder) or in older releases (fill window is now default).

I've added request for default theme to be set in management to this issue: https://github.com/thexerteproject/xerteonlinetoolkits/issues/1139

@ronm123 I'll close this now but if you think anything else mentioned in this issue still needs to be done then it's probably best if it's moved to a new issue as I don't think they will be noticed in here with the other things that have been completed.
