### ISSUE TITLE
xerte favicon in exported files

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#585]
From a recent forum post asking about favicon in exported projects it seems that we have `<link rel="icon" href="favicon.ico" type="image/x-icon" />` in the index.htm file as part of an export but the .ico file isn't part of the export. Perhaps it should be?

**Comment by JohnSmith-LT** [comment]
Think this should fix this @ronm123

**Comment by ronm123** [comment]
@JohnSmith-LT Haven't tested every single export but yes favicon is there in xot and bootstrap exports now. Cheers
Ron
