### ISSUE TITLE
preventing the flash of blue header on the bootstrap template

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#586]
I think we've discussed this before but can't find an existing issue...
When the header colour is changed in a Bootstrap project there is still a flash of the default blue header when the page first loads. It shows up most when the header colour is set to white or even set to hidden as in this example http://xerteacademy.com/xt/play_9

I'm not sure how to prevent this and perhaps it will be helped if we have separate themes for the bootstrap project but would certainly be good if we could prevent this.

**Comment by ronm123** [comment]
Here's a simpler demo of the issue with the header colour set to white and the header text colour set to black there is an annoying 'blue flash' of the default header including default text when the page first loads http://training.mitchellmedia.co.uk/xot/play.php?template_id=278

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 can you check if that fixes this? I thought this was fixed a while back... I know you definitely mentioned it before though...

**Comment by ronm123** [comment]
Hi @JohnSmith-LT yes that definitely fixes it - thanks! Also sorry I just followed the links from github and realised that the first link I posted yesterday is part of a set embedded in my conference presentation last year so set to only display when viewed from that resource. However the second simpler link was fully public and I've updated both installations and both that don't show the flash of blue header.
Cheers
Ron

**Comment by FayCross** [comment]
Thanks John - I've been meaning to look into this for a while!

**Comment by ronm123** [comment]
Just added an additional change to this to also hide the top nav bar. Not sure if this quick animated gif will play here but shows that with some of my projects the black navbar was still flashing before this change.
Had to add an id so called it topnav hope that's ok.
![bootstrap_navbar_flash](https://cloud.githubusercontent.com/assets/5167146/23699605/ad4471be-03e7-11e7-975b-224cd1cf6a52.gif)
