### ISSUE TITLE
theme specific wizard options?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#588]
This is probably a topic for discussion during the developer days...
We currently have: 
LO Icon properties and optional properties
Common optional properties
Page type specific properties and optional properties
Particularly for the LO icon properties and optional properties we have a long list
This might tie in with the work Tom has started to do splitting the css from the model files but I started to wonder about Theme specific optional properties e.g. some optional properties that are only shown when a particular theme is selected e.g. in the XOT template it would be good to have header colour, footer colour, page colour controls that might work for all themes. However we might also have themes where button colours could be changed but this wouldn't work on all themes. It would be possible to build a theme that uses Font Awesome icons for the buttons so that icon, size and colours could all be changed by wizard options but having those options listed would be confusing where they are theme specific.

**Comment by FayCross** [comment]
I'd really like this. I think @JohnSmith-LT has mentioned a similar idea previously where you could group properties together, e.g. one background optional property through which you could control image used, opacity,  etc. without having to add everything separately.

**Comment by JohnSmith-LT** [comment]
Yeah I think I had the idea of being able to extend the input types (like the text, textarea, color, etc) that we have just now to create multiple ones. For simplicity we would still save the data in a single xml attribute but each item separated by a 'separator'.

So for example we create a new type called 'gradient' and we have a simple class that has three methods:

1) input - takes the raw xml attribute data and puts it in the required format
2) layout - defines how that data is 'used'. In the example above you could simply have ['colour', 'color'] which would mean you have 2 colour pickers side by side
3) output - converts the data from the two color pickers back to text for the xml attribute

Obviously the power would come from being able to have layouts like ['color', 'numeric', 'text'] but also ['color', 'xyz'] where xyz is defined in the module as a new type...

We could then also extract the datagrid etc out to their own separate modules to make it cleaner and easier to work on...

**Comment by FayCross** [comment]
Closing this as you can now do this with conditional xwd properties
