### ISSUE TITLE
Fullscreen background image option

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#590]
This has been raised on the forums but I couldn't find it listed here. Apologies if it is listed elsewhere and therefore this is duplication...
Enhancements to the LO background image and page specific background image options would be:
Options to set to percentage, cover, contain etc
Options to set to fill whole LO including header and footer e.g. make header and footer transparent and background image fills whole window 
Options to control repeating
Probably relevant to all templates but especially XOT

**Comment by ronm123** [comment]
Hi all
although this is an enhancement rather than a bug I was having a look whether we could quickly add at least some of this as part of the imminent release. e.g. even if we only add a simple option to prevent the background image on a title page and possible at LO level from stretching by including an option to make the image use cover instead. Possibly even making cover the default because people rarely like their background stretching and distorting. It's easy to achiever this with some css in the LO like `#x_background {
background:url(FileLocation + 'media/filename.jpg');
    background-repeat: no-repeat;
    background-size: cover;
}` so I was trying to get this to work via the code in xenith (before adding as an optional property) but clearly missing something because I couldn't get it to work. Anyone else had a look at this and got a solution that we could quickly add and include in 3.8?

**Comment by FayCross** [comment]
Your css won't work because the background images aren't actually added using css background but are actual images inside the x_background div. At the moment it looks like they are set to have height & width 100% which is making them stretch. You should be able to add some css to deal with this better but you can't use any of the css properties that affect background images (background-size/repeat etc).

It looks like you want to be targeting #x_background for background images added at project level & .pageBg for page level background

**Comment by ronm123** [comment]
@FayCross I knew it was something stupid I was doing wrong! :-(
I'll do some tests with object.fit instead and test what happens in IE if that is added.
I know we could also use something like https://github.com/constancecchen/object-fit-polyfill but probably a bit too tight to get that in and tested before the release.

**Comment by ronm123** [comment]
@FayCross I've tested this and can get it working by adding the following to the relevant bits of xenith if the optional property has been selected.
`$("#x_mainBg").css({
"object-fit"	:"cover"
});`
I guess I would need to do the same for .pageBg too.
However I can't decide how best to name and describe this. At the moment I've got the following:
`<backgroundFit optional="true" type="CheckBox" label="Image-fit" tooltip="Tick this option to have the background image fill the page but crop rather than stretch the image. Note: this will have no effect in Internet Explorer." defaultValue="false"/>`
and in the editor this shows as follows:
![image](https://user-images.githubusercontent.com/5167146/65597832-e662d700-df91-11e9-823a-7442c3d2db64.png)
So a few questions:
1. anyone got any comments re using backgroundFit as the node and Image-fit as the label or the tooltip as shown above?
2. I know there are other values that could be set e.g. contain, fill, scale-down, none so I could change to a dropdown list and make all those options available but I think a simple tick box and just cover as an option is all that is really required - does everyone agree?
3. A later improvement would be to add an option to give an option to fill the whole window and make the header and footer transparent but I think I'll leave that for a future release.

**Comment by FayCross** [comment]
Could it be a drop down with crop to fit vs. stretch to fit? Then we could add extra options at a later point if needed? The label next to the drop down could be simply 'Size'?

I think crop to fit should be the default option

**Comment by ronm123** [comment]
@FayCross Ok I'll change what I have for the moment to what you have suggested. I have this working for both LO background and page background but once I've committed it would be good if you or someone else could check and confirm that the condition for the page background is in the right place in xenith. There seems to be loads of places that reference pageBg and at the moment I have this check added just after $x_background.prepend($pageBg);

**Comment by ronm123** [comment]
@FayCross I have this working locally but am I missing something with default values?
If I have options="Crop to fit,Stretch to fit" data="cover,fill" defaultValue="cover" and create a new project with a background then all works fine however if I edit an existing project with a background already added then the new drop down list shows in the group and shows Crop to fit but doesn't actually work until I change the option to Stretch to fit and then back to Crop to fit. e.g. the default value isn't picked up in existing projects but is misleading because it shows that in the drop down. So I think it's better to have the default value as stretch to fit as it has always been unless I'm missing something? I know I could trigger the code if the value is undefined but that would change existing projects so I'm not sure that's the right thing to do?

**Comment by ronm123** [comment]
Have committed this so will close the issue. Can someone else test?

**Comment by ronm123** [comment]
Hi all
Could someone check the commits I've made here. It's mostly working but the page background option isn't changing when you navigate between pages so I'm guessing the condition I've added around line 2392 in xenith needs to be moved or also added somewhere for when the page is changed too?

**Comment by torinfo** [comment]
@ronm123 Regarding the optional property not working. You have to make sure in code that if the option is not set, it will behave as if the option was set to the default.

I'll have a look

**Comment by ronm123** [comment]
@torinfo I think I did that but it’s only changing on first load not when navigating back and forth.

**Comment by torinfo** [comment]
@ronm123 You almost nailed it. But you set the object-fit based on class, but all the page backgrounds have that class, so if one of the pages object-fit is different than the one before that, it suddenly resets the object-fit of that page too.

I just moved the setting of object-fit into the definition of $pageBg a few lines above your change. That seems to work fine.

**Comment by ronm123** [comment]
@torinfo great thanks seems to work fine now.
I've just committed a similar solution for the LO background option because to get it to work previously I'd added the same condition in two places. Now it's similar to your solution by setting a variable and then using that in the 2 places needed.
