### ISSUE TITLE
mark word page types - marking words breaks formating

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#592]
Not sure if this has been mentioned before but there was a question on the mailing list about the gap fill page and changing the font/style of the correct words. I thought why not just use the wysiwyg controls but upon testing it seems that any formatting applied stops at the first marked word e.g. the | character seems to stop the formatting even just making the paragraph a different colour.

I then tested the interactive text page and that seems to have a related but slightly different issue e.g. attempting to apply wysiwg changes like changing the text to green for the whole paragraph appears to work in the editor but when viewed results in some broken code at the beginning e.g. `2ecc71;">`

Not sure if there's an easy way to deal with all that e.g. the mix of html and different delimiters so should the wizard text boxes be non-wysiwyg for these page types? Or is there a way to enable both other than using css?

**Comment by JohnSmith-LT** [comment]
Has this been fixed Ron? I'm trying to reproduce and can't get it to mis-behave... Could it be fixed since Tom upgraded the editor?

**Comment by torinfo** [comment]
Ah yes! I tried to find this issue, so I could mark it fixed, but this is indeed fixed since I put in the new CKEditor. Also the similar function of making an internal link on an image (the image was thrown away previously)
