### ISSUE TITLE
Optional property delete icons disappearing

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#594]
The optional property delete icons for properties I've added to the page keep on disappearing. Once they go I have to refresh the page to make them appear again.

I've not noticed this happening before the new changes to the editor.

**Comment by torinfo** [comment]
I would be surprised if it has anything to do with the ckeditor replacement, But I'll have a look into that. I've noticed that the extra icons that indicate whther a page is (temporarilly) disabled disapear as well.

**Comment by ronm123** [comment]
@FayCross @torinfo I'm noticing this now too but does seem like a fairly new issue.

**Comment by JohnSmith-LT** [comment]
I did a bit of investigating into this last night and a way to reproduce is to:

Add a text page
Add the hidden page option and tick the box
The icon appears to show it is hidden.
Then click on the duplicate/copy button
The page will be copied but now neither (despite having the hidden option on the page) will have the hidden icon shown in the tree...

It seems that the code to insert the icon only runs on load and not when the tree is updated.

If you publish and then close the editor and reopen then the hidden flags are there and they do seem to survive a tree update...

**Comment by ronm123** [comment]
@JohnSmith-LT so does it only happen if a page is set to hidden and not if there aren't any hidden pages?
Or is it the copy/duplicate of a hidden page that is causing the problem?

**Comment by JohnSmith-LT** [comment]
I don't think it's the duplication code as the nodes seem to go into the tree ok - this shows if you save and reopen the editor and they are there...

It might just be as simple as the duplication code not calling a method that re-inserts the flags... Tom did most of that code and it's got quite intricate now so i'm not 100% clear yet of the flow but I'll have another look... 

I think the editor has got sufficiently large that it needs restructured - we made it in a modular way so we should be able to do quite readily to have modules that contain the code for only one function...

I'll speak to Tom about it next week...

**Comment by FayCross** [comment]
I should be able to fix the disappearing hidden icon problem as I did the original code for that bit.

The disappearing optional property delete icon is different though - it was the bin button disappearing from the wizard (not tree). I have to say I didn't really notice it yesterday when I did work on how we could have property groups - maybe I've inadvertently fixed it...

**Comment by FayCross** [comment]
Closing this as it was originally to do with the delete optional property buttons disappearing (which seems fine now)
I will open a new issue re. hidden icon issues
