### ISSUE TITLE
play v publish v cancel - perhaps need for extra button?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#595]
From a forum post this week re lost work after selecting cancel when prompted to publish.
I tested this and sure enough it's possible to type work in a page text box and if you don't play or publish and select cancel that change is lost. 
It seems that if you type in one box but then click in another text box e.g. title and then close, cancel without play/publish there must be some change of focus saving but perhaps not universal.
I'm not sure how often people need/use the possibility to make changes and only play rather than publish to save changes but not publish those changes to the public version so perhaps we should rename the publish button Save/Publish?
Or perhaps add automatic saving to preview even when cancel is selected?
Or even automatic 'interval' saving like Google docs etc

**Comment by torinfo** [comment]
The issue is not that the save doesn't work. Preview is saved (regardless of what button you press in the workspace)

However, the data from the textarea/wysiwig editor is not saved in the internal state that is sent to the server. We use the blur event to detect an out of focus event, and that works perfectly of you go to another element inside the editor. Regrettably, the event does NOT fire if you close the window, so the contents of the editor are not recorded correctly.

It seems that the current version of the editor supports the 'change' event better than before (there were lot's of issues with that, and that could be a solution. The drawback is that it fires on every keystroke. I've been playing with taht and so far I have not detected any issues with that. Shall I commit that?

**Comment by ronm123** [comment]
@torinfo I think the point was if they don't play or publish and then cancel the changes are lost.

If the new version saves on every keystroke is there a negative impact on undo? If not then yes sounds like that will minimise the chance of lost changes.

**Comment by torinfo** [comment]
Even if you don't play or publish, the preview is always saved (provided the state is correct)!

You can verify for yourself:
 1. Change an textarea item
 2. Go to a different field (internal state is updated now)
 3. Close editor and press cancel

It still should have the changes made in 1 if you re-enter the editor.

To lose data you have to:
 1. Change an textarea item
 2. Close editor and press cancel

If your findings are different, please let me know.

**Comment by ronm123** [comment]
Yes I can only assume it's the second process they were reporting. Or perhaps using an older version.
Regardless I'm not sure it would hurt to rename the publish button save/publish.

**Comment by torinfo** [comment]
If we do that, I would propose to introduce a new 'Save' button to save the preview. 'Publish' will continue to only save data.xml.

Otherwise, you can wonder what the purpose is of have a difference between data.xml and preview.xml.

**Comment by ronm123** [comment]
I sort of agree but I guess we need to consider if having 3 buttons introduces even further confusion? I wonder what percentage of users even appreciate or make use of the difference between play and publish? In my experience more people want a save button to be confident that their changes are saved than want a button that doesn't save the changes to the published version. They click publish to save and to avoid having to click play and wait for the window to open all the time. They click publish regularly to save because most of the time they develop the lo privately before making it available. We also didn't have the hide page option previously which now provides an additional way of making changes or additions that aren't visible to end users. I think if the change event works now to automatically save to preview without any adverse impact on undo then that's probably the better option rather than introduce and extra button. I think it's more important to minimise loss of changes than to maintain a difference between preview and play that most people don't care about anyway.

**Comment by torinfo** [comment]
Please test

**Comment by ronm123** [comment]
@torinfo seems to work great! Can't spot any adverse effects.
