### ISSUE TITLE
(Deep) linking to decision tree is strange

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#599]
See https://xot.12change.eu/play.php?template_id=988

The Xerte page link menu suggests that you can deeplink into the subpages of the decision tree. The pages are listed separately (with separate link ids)

 - When you choose Facebook, and then press the image, you will land on the page after the decision tree
 - If you press the 'back button' you go back (in this case) to the page with the image (so not the first subpage of the decision tree)
 - If you go to the last page, there is a link to the twitter sub page, but it arrives (again) on the facebook sub page.

It seems that if you arrive back in the decision tree (either by using the back button, or by using the xerte page link to the (a sub) page of the decision tree it will show the last page visited in the decision tree.

**Comment by FayCross** [comment]
I've just looked into this and it seems to be a general page link problem not specific to decision tree page, Any page with nested content has it's children appear on the Xerte page link menu. This makes sense for pages like the navigators but it even happens for pages like morph images where the child is definitely not something you can link to.

Would it be possible to turn on/off page links for a page's children?

**Comment by torinfo** [comment]
I'll look into that. Probably not that simple. We probably need some information from the subpage to determine whther you can link to it.

Different question then: Would it be possible to enable (internal) linking to a sub-page of the decision tree?

**Comment by JohnSmith-LT** [comment]
Sorry, this was probably me... I did some stuff to get first, last, next, previous links in for Ron and to enable deeplinking in Bootstrap and probably removed the check for XOT only instead of making it XOT and Bootstrap only...

I never noticed the issue with deeplinking to subpages that aren't really subpages but as Tom says we'll probably need a flag of some sorts...

Deeplinking to Decision shouldn't be an issue if it supports it...

**Comment by ingedonke** [comment]
Is there any news about this issue?

**Comment by FayCross** [comment]
Deep links to decision tree steps now work. Linking to the page directly will show the page as last viewed but direct links to a step will reset any answers that have previously been selected and start a new decision from that step.

I'll open a new issue for the problem with links being available to children where they should be
