### ISSUE TITLE
add glossary option to bootstrap template?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#600]
Was asked about this during a training session and I wonder if we could re-use the relevant code from the XOT template to enable glossary functionality in site projects?

**Comment by FayCross** [comment]
I'd really like to do something like #462 where you can create glossary outside of individual projects and link to them

**Comment by ronm123** [comment]
@FayCross think there's probably room for both options e.g. internal glossary and external glossary.

**Comment by FayCross** [comment]
@JohnSmith-LT you added the glossary option to xwd back in March but I don't think you added anything to get it working in the projects. Shall I remove it for now until it's working?

**Comment by JohnSmith-LT** [comment]
Hi Fay, Yes please, I made a start on this but struggled to get any time to complete it.

**Comment by FayCross** [comment]
This is partially done. The words become highlighted in the text & bring up a definition when hovered over. But at the moment there's no button to click to see all the words like there is in the XOT template. Not sure where to put a button like this in the interface as there's not a toolbar as such like in the XOT template.

I was wondering about adding several options for how the whole glossary could be viewed e.g. button in toolbar or the glossary on it's own page (like an example you've shown me before @ronm123 where a glossary is on its own page in alphabetical order)

**Comment by ronm123** [comment]
Looks good @FayCross 
Yes I think giving authors options might work well. Thinking out loud options might include:
Show glossary button y/n
Show glossary definitions on hover y/n
Position of glossary button navbar L/R, Footer L/R
Glossary display separate page or pop-up where clicking the term or button links to that page or pop-up

What this the example you meant? [https://xerte.cardiff.ac.uk/play_4069]
