### ISSUE TITLE
Make the panels sized by percentage

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#610]

**Comment by FayCross** [comment]
How would this work for existing projects where the panel width is already set as small, medium, large or full? We could end up with two properties for controlling panel width in the editor which would be confusing.

**Comment by ronm123** [comment]
Can't those existing sizes map to percentage e.g.
Small = 20%
Medium = 50%
Large = 75%
Full = 100%

**Comment by torinfo** [comment]
And then deprecate the current panelsize and add a new mandatory property containing percentages.

It will require some code in each model to figure it out, but yes, it would be very good.

**Comment by FayCross** [comment]
It was how it would look in editor that worried me - I get how it would work in page models.

The deprecated properties will still show up in editor in existing projects & then by adding a mandatory property you'd end up with this on lots of pages in existing projects

![capture](https://cloud.githubusercontent.com/assets/8926470/24961526/f4b0925c-1f90-11e7-9cea-ffd98301cf6c.JPG)

I know we have deprecated things before but this seems a bit clunky considering how many pages & projects this will appear in

**Comment by JohnSmith-LT** [comment]
Hi all,

This was raised at the Edinburgh event and from memory I think it was more to do with how the panels react when responsive is on...

So rather than having a 60% option @FayCross I took from it that it was how small, medium, etc are interpreted to make sure that small for example stays at 25% of the total width as you expand the LO...

**Comment by torinfo** [comment]
Yes, I agree, but it is definitely an improvement. 

We can also follow John's proposal, and reading back, I think that's what Ron is suggesting as well.

**Comment by FayCross** [comment]
Oh ok, all the panels where you select whether it's small, medium or large are all responsive already (40%, 60%, 80%). But there are other kinds of pages where panels are used where I think there's a max size set (e.g. morph images?) These do need looking at. I misunderstood and thought it was about sizing the pages with full height panels (like navigators)

**Comment by JohnSmith-LT** [comment]
Are you happy @FayCross that this one is fixed?
