### ISSUE TITLE
problem with latest develop/unstable branch and results page code

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#612]
Hi all
I just created a new install to test the latest develop and after creating a simple LO (XOT template) and clicking play I get an  empty window. Upon further investigation and turning debugging on the error was:

Parse error: syntax error, unexpected '[' in .../website_code/php/xmlInspector.php on line 180

If I comment out line 180 and line 181 as follows then the project plays fine:
`//$this->resultpageEnabled = (string)($this->xml->xpath('/*')[0]->attributes()->resultpage);
        //$this->hasResultPage = ($this->xml->xpath('/*')[0]->children());`

I tried leaving the code uncommented and adding the results page option but still the same problem. I suspect this is more than just a syntax error but could be wrong.  In fact I'm not getting the same error via xampp so could this be another one of those PHP version specific issues? On this particular server its 5.3.8 so perhaps the code involved requires a later version?

**Comment by torinfo** [comment]
I'll fix it. It has to do with the [0]. In earlier versions you cannot do that on a result of a function directly, but requires storing the result in a temporary variable, and than using [0] on the variable.

**Comment by torinfo** [comment]
@ronm123, is it working now?

**Comment by ronm123** [comment]
@torinfo yes it's working now in as far as LO's play ok now but am I right in thinking with current develop the results page doesn't show? e.g. added the optional property > results page but don't get a results page at the end of the LO. Not a problem I know that's still being developed anyway but the optional property is there so might confuse people at the moment.

**Comment by torinfo** [comment]
@ronm123. That is correct, because they are working on a fork, so everything you saw last week is on the fork. It's not merged into the main repository yet. The goal is to be able to do that by the end of the month at the latest.

**Comment by ronm123** [comment]
@torinfo assumed that's the case thanks.
