### ISSUE TITLE
IE issue - next button skips a page when @import used in css file

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#614]
If you use import in a stylesheet (e.g. @ import url('http://fonts.googleapis.com/css?family=Open+Sans');) and upload it to your project via an optional property it causes unexpected behaviour in IE where button clicks are fired twice so next/prev buttons skip 2 pages rather than 1.

**Comment by torinfo** [comment]
Which version of IE? This is really weird. Does using the sketch them expose the same issue (Sketch uses @import to load a font as well.)

**Comment by ronm123** [comment]
I've used the sketch theme extensively (and obviously developed it) and have never noticed this. IE version might be a factor/difference or is it a difference between @import in the theme it'self compared with adding as an optional property?

**Comment by FayCross** [comment]
I have found a fix but didn't have time to commit before I left for a
meeting. Will do it this afternoon

**Comment by FayCross** [comment]
Hmm, I'm not going to commit fix.

It was an issue on UoN install that's not entirely up to date. IE10 & 11 with stylesheets uploaded to optional property. It seemed to be because the css onload event was being fired twice with the import line included and that meant some other interface setup code was being called twice... therefore button clicks were firing twice too.

I can't recreate issue on up to date xampp install though (although could before I updated it with changes from last week). Perhaps Tom's recent css changes have fixed it? I'll close this for now but will also test properly next week to make sure it's def not a problem any more

**Comment by FayCross** [comment]
I've just looked into this some more & found that with up to date code, the onload events for css files containing import (including sketch theme) are called twice in IE. Even though this isn't causing any issues at the moment I've stopped this happening as it's not ideal that so many functions are being called multiple times.
