### ISSUE TITLE
TOC tickboxes now showing all pages visited continuously

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#616]
Hi all
has anyone committed a change to develop likely to have stopped the TOC tick boxes from working correctly? I just noticed this on the install I've been using so tested locally via develop too and it seems the tick boxes are showing continuously regardless of having visited pages or not. My sense is this must be a recent change because I'm sure it was working in the last week or so.
Shutting down now but will see if I can spot the cause tomorrow.
Ron

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 

I think what i'm seeing happening here is that @torinfo Tom's code to use the separate css files is not loading in the menu.css file...

Also the css to initially hide the ticks

#menuItems .menuItem .notvisited {
		display: none;
	}

seems to have dropped off when the merge happened...

**Comment by torinfo** [comment]
Yes, menu.css is not loaded because it's handled completely different then other pages. Will have a look.

Are there other similar issues?

**Comment by torinfo** [comment]
Yup: coulorChanger, language and glossary.

**Comment by ronm123** [comment]
@torinfo likewise have updated xampp and online install and this is working again now after a force refresh.
