### ISSUE TITLE
Make display mode be 'fill window' by default

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#619]
Make display mode be 'fill window' by default (requested by user at UoN)

I've wondered about this before, particularly now we have responsive text on by default which doesn't actually do anything until display mode is changed to fill window.

Are there any potential problems with doing this?

**Comment by FayCross** [comment]
Maybe we could do this after we are happy that all pages are nicely responsive (media etc.).

Is there anything we can do to get around the problem that when you add a new page and preview (without changing the text) the default text is often not responsive. I think this is because it's not in p tags which are added by ck editor when you edit text. Could we force the default text to be in tags or does this have knock on effects?

**Comment by torinfo** [comment]
If we're happy with responsive, I think we should make fill window the default.

Also, I think it would be a good idea to put the default text between <p> taqgs.
