### ISSUE TITLE
issue with bootstrap export?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#622]
Hi all
have just been testing a potential issue with Bootstrap export but because of an external problem with my broadband at the moment not able to test efficiently. However as far as I can see exporting a Bootstrap project and then uploading to a vle or webserver isn't displaying the LO contents and I could be wrong but due to an error in application.js e.g.
Uncaught TypeError: Cannot read property 'getAttribute' of undefined line 356
var msg = languageData.find("hiddenPage")[0].getAttribute('label') != null ? languageData.find("hiddenPage")[0].getAttribute('label') : "This page will be hidden in live projects";

Bootstrap LO's exported with older Xerte versions seem to be fine so this appears to be a recent problem. Anyone else able to replicate this?
Cheers
Ron

**Comment by ronm123** [comment]
Hi all
after some further testing just to add it's definitely line 356 that is causing the problem here. Even when viewing offline via Firefox the exported Bootstrap project doesn't display but if I comment out line 356 it plays fine. e.g.
`//var msg = languageData.find("hiddenPage")[0].getAttribute('label') != null ? languageData.find("hiddenPage")[0].getAttribute('label') : "This page will be hidden in live projects";`

I'm not sure what's wrong with that line or any additional code involved but it does seem to be what's causing the problem. The similar line around 386 re section header doesn't seem to be causing the same problem.

**Comment by ronm123** [comment]
actually I tell a lie - upon further testing both line 356 and line 386 have to be commented out for the LO to play correctly. This is not an issue when playing from Xerte but is when playing/viewing an exported Bootstrap project.

**Comment by FayCross** [comment]
The hide page stuff I added a while ago used some strings from the language file & this doesn't seem to be exported. I'm not sure how to get it included in the export so I've just fixed it so it doesn't break if the language file doesn't load. It's not a problem at the moment as the string was only used in preview (so would never be needed in exported project anyway) but if we ever use other things from the language file then it would be worth getting the language file to be part of the export too.

**Comment by torinfo** [comment]
I'll have a look at that, so I'll re-open this issue for exporting the language file.

**Comment by ronm123** [comment]
Thanks both. I wondered whether that was the issue but as far as I can tell the language folder has never been part of bootstrap project export so I thought it must be something else.

**Comment by jorgeccmm** [comment]
Please guys I have tried to export a bootstrap object as second option (not scorm) and it is not responsive at all. Please how to export in a pack that contains HTML5 file to upload it into my hosting server. I have tried linking to localhost and it does not work neither. Is it this tool really responsive?
