### ISSUE TITLE
enabling resuming showing twice

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#626]
Hi all
I just noticed that with the latest develop the enable resuming option is showing twice. I can see why because looking at data.xwd it's there at line 29 and then again at line 37. Obviously that's being built from the src basic.xwd which has the 1st instance on line 28 and the second on line 36.

I could easily fix and commit that probably by removing line 36 but wondering if anyone recognises this e.g. perhaps @FayCross was it part of your re-organisation of optional properties and should it be line 28 rather than 36 is deleted?

Ron

**Comment by FayCross** [comment]
It looks like it ended up being duplicated when all the new functionality was merged last week. It's fine to delete one of the lines in basic.xwd

**Comment by ronm123** [comment]
Thanks Fay this is done now.

**Comment by torinfo** [comment]
Apologies. I did see that, and I thought I had fixed that. Apparently not.
