### ISSUE TITLE
documentation page New Media issue on export

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#628]
Hi all
adding this as an issue here following a post on the community site forums
http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1312&Itemid=759&lang=en 

It seems there's a bug in the code when exporting a project containing a documentation page that has images add via the New Media option. The image doesn't show when viewing the export and shows an error that "No media selected" instead.

Looking at the exported documentation.html model it has a case statement looking for a url substr containing USER-FILES in the xml which is obviously incorrect on export and I guess why the image shows when viewing via Xerte but not when exported. 

If I change the case statement e.g. change:
`case 'media':
if (xml.getAttribute('url').substr(0,10) == "USER-FILES") {
to
if (xml.getAttribute('url') != undefined) {
`
then all seems fine.
Is that the correct solution or does it need to do more checking that that?

**Comment by torinfo** [comment]
I am ok with your change. 

Just a remark:
In other places in the code where we check for media, we check for the substring media (as this is valid in the exported packages as well). Perhaps that would be a better check. @JohnSmith-LT ? Any preferences?

**Comment by ronm123** [comment]
@torinfo @JohnSmith-LT just wondering about this and what if the image is added with a full url rather than uploaded to the project? Wouldn't that mean that checking for substring USER-FILES or media would also result in the image not showing? e.g. If I put a full url in the image field of a graphic and sound page the image shows fine when viewing the page but if I do the same in the new media field of the documentation page then even when viewing via Xerte it shows as No media selected. The same would happen whether the substring check is USER-FILES or media and although I appreciate that in most cases authors will be using uploading media, given that we have the facility to use full url's to external images (e.g. re-using common media) the substring check for  either value obviously doesn't accommodate that.  The check in the graphics and sound page uses x_evalURL via xenith.js so perhaps that's what needed in the documentation page too?
Ron

**Comment by JohnSmith-LT** [comment]
Hi, Yeah i'm ok with that change too except we might also want to check for "" too, so something like

if (xml.getAttribute('url') != undefined && xml.getAttribute('url') != '') {

and potentially we also need a check to cater for the 'default text' such as "Select image..." or whatever it is when it is in default state...

if (xml.getAttribute('url') != undefined && xml.getAttribute('url') != '' && xml.getAttribute('url') != 'Select image...') {

Ideally we'd probably want a common function check that anything added was a valid URL though and move that function into xenith...

John

**Comment by JohnSmith-LT** [comment]
We have this function too 

x_checkMediaExists(...    ...)

which performs a request to see whether anything valid is returned... so we could do something like

`					case 'media':
					  x_checkMediaExists(x_evalURL(xml.getAttribute('url')), function(mediaExists) {
					    if (mediaExists) {
					      $element = $('<img class="itemImg">')
					        .attr('src', xml.getAttribute('url'));
					    }
					    else {
					      $element = $('<div>')
					        .html("<p class='alert'>" + (x_currentPageXML.getAttribute('mediaError') != undefined ? x_currentPageXML.getAttribute('mediaError') : "No media selected") + "</p>");
					    }
					  });
						break;
`

**Comment by JohnSmith-LT** [comment]
@ronm123 I think when I quickly cobbled that documentation page together then it would have been me who used that      ...substr(0,10) == "USER-FILES"   as a crude way to detect the existence of media and it's just never been updated...

lets wait for @FayCross to reply but I think if we have the ability to check for the actual existence of media then it's worthwhile doing since a valid URL doesn't mean that it's not been typed incorrectly.

John

**Comment by FayCross** [comment]
I added the x_checkMediaExists function when I added the optional property groups as it became more likely that media properties would be added but with no media uploaded & I didn't want pages to break. I haven't had time to roll it out across all media on all pages though so it's just on pages affected by opt property groups & maybe some other pages I've worked on since. We definitely need to do checks like this in more places as I think there are probably a few other pages where if you haven't uploaded media it just stops.

**Comment by FayCross** [comment]
I'm not really familiar with the export side of things though

**Comment by JohnSmith-LT** [comment]
Yes, the export side of things is always a concern... i'm not sure whether that call would fail in a offline export due to browser restrictions...

**Comment by JohnSmith-LT** [comment]
The change you initially mention though @ronm123 should fix this issue so lets go with that just now and we can look into the rest for the next release...

**Comment by ronm123** [comment]
Have changed it to the basic check for not undefined and no empty for now. e.g. used:
`if (xml.getAttribute('url') != undefined && xml.getAttribute('url') != '') {`

Obviously that isn't checking for the default string but I wan't sure how that worked with different languages so left that out for now.

**Comment by JohnSmith-LT** [comment]
Are we happy @ronm123 that this is fixed and no further problems are obvious? Will we close?

**Comment by ronm123** [comment]
@JohnSmith-LT yes I think this media issue is fixed but we do need to sort the issue that when projects are exported and viewed outside of the Xerte install via a VLE or locally the download button predictably doesn't work. I can't remember if I listed that as a separate issue on github. I think I did and what I've done for one organisation is hardcode the full url to their download.php in the model file and in then works from Blackboard even when exported. I've wondered if we could do that automatically on export somehow e.g. dynamically pick up the url of the installation and insert into the model file or pull that value from the xml and use that instead?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123,

Just letting you know that i've made some changes to insert a download path into engine for all export options except for Archive and xAPI...

Can you test (no hurry) with the Scorm packages etc that you were using in Blackboard?

**Comment by ronm123** [comment]
Hi @JohnSmith-LT sorry I'm being thick - how does it work?
Does the author add the url to their installation or is it added automatically?

I'm not seeing an option in the editor and I can see a change in the exported model file but that shows x_downloadURL 

Cheers
Ron

**Comment by ronm123** [comment]
Hi John
ok sorry scrub that I can see it's part of the exported index file and seems to work fine!
I'm only testing via my local develop at the moment so the url works but obviously wouldn't when uploaded online. I know there are users out there that don't have an online installation and so use a xampp copy and then export and upload but I suppose the only way around that would be to have a fall back link to a download.php on the community site or something like that? But this is a big step forward so at least it will work for anyone with an online installation.
Cheers
Ron

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 
Yes that is how it works just now but if you think there should also be an option in the editor then that would work also. There could simply be an order of preference:

1) Any url entered into the editor
2) The installation url (relevant only if exported)
3) The default url - /download.php

Would that work? Alternatively at a later date there could be an entry into the management page to manage it there for an install - so that an institution could point the download link at a different location but it could start getting messy...

**Comment by ronm123** [comment]
Hi @JohnSmith-LT thinking about this a bit I think what you've already added is great and I'm not sure there's much value in having an option for a authors or admin to set the download URL - to easy to get that wrong!

The only thing might be worth adding is to either flag up when the detected site URL is localhost or to use a URL to one of our download pages instead eg The community site installation?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123, sorry i've read that second bit a few times and I don't really get what you mean by 

> flag up when the detected site URL is localhost or to use a URL to one of our download pages instead

Do you mean something like an indicator image with some alt text? Or some text actually displayed? Or ... ?

**Comment by ronm123** [comment]
Hi @JohnSmith-LT I think on export one of the following:

1. If localhost or 120.0.0.1 is detected as part of the site URL use the download link to xot.xerte.org.uk if @torinfo thinks that would be ok.
Or
2. Display a js alert; Please note the download option in your documentation page(s) will not work when exported from a localhost installation. You need to export from an online installation instead.

**Comment by JohnSmith-LT** [comment]
Ok. Both are easy enough to do so I'll hold off to see if @torinfo is happy with number 1 and also any other 'localhost' type URLs that you can think of? For example on Mac I always setup with a .local URL (http://xot.local/) which is an industry standard. Is that used on Linux/ windows or are there any others to detect?



Sent from my Samsung Galaxy S6 Edge - powered by Three


-------- Original message --------
