### ISSUE TITLE
logo divs included by default in site template

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#63]
In the bootstrap play and preview files in current 2.1 and current develop we have code to load a logo but no logo in the location it looks so shows a broken image holder and arguably wasted vertical space. This applies to existing LO's as well as new LO's.

Ideally this ought to be an optional property together with options for logo upload and placement. Until we have time to add that should we remove these divs from \modules\site\play.php and \modules\site\preview.php?

**Comment by ronm123** [comment]
Seems like the simplest for this would be to make the page title field a textArea rather than textInput and allow logo images or other images to be added and controlled via the wysiwyg editor?
Not sure whether there would be an impact on existing project that way or what else would be required for that to work?

**Comment by JohnSmith-LT** [comment]
Do we even need the logo code there? Your suggestion seems fine with me but like you I'm not sure how it will impact existing projects...

**Comment by ronm123** [comment]
I don't think it's causing any problems since your previous fix and is in use in some places I think. I know Notts use it but via a customised site index page I think. People do often ask about adding a logo and controlling where it appears so it's definitely still a desirable enhancement but arguably not urgent.

**Comment by JohnSmith-LT** [comment]
Would probably be safer and relatively easy to just make it visible and add it to the xwd as a property. I suppose then any LO already using it through an embedded hack would still work as intended?
