### ISSUE TITLE
Import pages & glossary bugs

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#632]
When I try to import a glossary from another project it doesn't work. It hangs and then the editor freezes.

**Comment by FayCross** [comment]
Also, import page only seems to work about half the time too. It hangs for a while and then page goes blank as it's gone to http://localhost/xertetoolkits/merge.php?source_project=1&target_project=2&target_page_position=10&source_pages=0&merge_glossary=false

**Comment by JohnSmith-LT** [comment]
Do you get any errors in the console? I've just tried to reproduce and they all imported fine, multiple times but they weren't that big and didn't have any special characters etc...

**Comment by FayCross** [comment]
No errors. It was a clean install so I've made no changes it anything

**Comment by FayCross** [comment]
I've tested this some more and have found why it was freezing & a few other bugs. I'll update the title of this issue as they are bugs with importing both glossary & pages...

1. If your glossary has images in it the merge won't work. It freezes as described above.
2. If you import a page from a project with a glossary it will always import the glossary too (whether this is selected or not)
3. This means that if you individually import several pages from another project with a glossary you end up with its glossary too & with the items duplicated numerous times
4. This also means that if the glossary has an image in it (see bug 1 above) then it freezes on trying to import a page from the project
5. If you import a page from a project without a glossary it will add the glossary optional property to the project anyway (with no content in it)

**Comment by FayCross** [comment]
Thanks for fixing this @torinfo It all seems to work fine now... it's a great feature!
