### ISSUE TITLE
New problem with IE11 and latest develop

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#635]
Hi all
I had someone report to me today that when they try to edit a project they get the buffering animation and can't edit. I said I couldn't replicate that but then found out they were using IE 11 and so tested with that and sure enough even via a local xampp install I get the same problem. I can't replicate it in Chrome or FF or even Edge but I can replicate it consistently in IE 11.

I'll paste a screenshot below but questions are:

1. Can you replicate this in IE 11?
2. Any ideas re cause/solution - I suspect another doctype issue or something?

![image](https://user-images.githubusercontent.com/5167146/27193672-ad66e5ce-51f7-11e7-8bae-18f453021c24.png)

**Comment by ronm123** [comment]
BTW the console isn't showing any errors.

**Comment by FayCross** [comment]
I get the same problem but do get an error (line 135 of toolbox.js). It works if I comment out the line. I think it's something @torinfo added reasonably recently to do with import so probably best if you could have a look Tom please? Thanks

**Comment by torinfo** [comment]
Does it work now?

**Comment by ronm123** [comment]
@torinfo yes that seems to have fixed it. Why only an issue with IE 11?

**Comment by torinfo** [comment]
Probably a small difference in how DOM works in IE11

**Comment by ronm123** [comment]
If only they all worked the same! ;-)
