### ISSUE TITLE
Printing from decision tree project template

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#637]
Hi all (particularly @FayCross)
I was helping someone troubleshoot printing from her decision tree project which by default only prints one page even though there should be many in this particular project.

I can see that \modules\decision\parent_templates\decision\common\css\styles.css has the following:
`html, body {
	height:		100%;
	overflow-x:	hidden;
}`
and that hidden value seems to be what is restricting the printing to a single page.
If I add an optional styles property to the LO and then add the following print css:
`@media print {
      html, body {
    height: 100%;
    overflow-x: visible;
}
}`
Then when printing the multiple pages are printed.
So ok to add this to styles.css or is there another solution or any reason not to add this?
Cheers
Ron

**Comment by FayCross** [comment]
It's so long ago that I've looked at this template that I really can't remember why the overflow-x was needed there. I'll change it so that when you click print it temporarily removes that bit of css and then adds it again when after printing

**Comment by ronm123** [comment]
Great thanks @FayCross
