### ISSUE TITLE
Bootstrap - 'New embedded XOT LO' option

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#643]
I seem to be showing people how to embed a single XOT activity in to Bootstrap projects quite often at the moment. It would be good if we could have an option in the 'New...' list that allowed you to add one without having to paste in the iframe.

With options such as:

- URL

- Page Number

- Hide header/footer

**Comment by ronm123** [comment]
@FayCross That sounds like a good plan! But also either make the default width of the iFrame 100% or have options for width and height.
