### ISSUE TITLE
Strange insert menu appearance in Chrome

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#645]
Today on both Nottingham's install & my xampp install the insert menu in Chrome looks like this...

![menu](https://user-images.githubusercontent.com/8926470/27857947-595a83ae-616b-11e7-9da1-311ceb098e52.JPG)

Where have all the big gaps come from?! Everything looks as expected in Firefox etc. & it's just Chrome that's changed (it was fine on Friday). Has this happened to anyone else? Maybe to do with a Chrome update?

**Comment by torinfo** [comment]
Inge saw it during a demo on Monday as well.

**Comment by FayCross** [comment]
Fixed 895dff3e6a916b96656607cfe2b2a7381a737e74
