### ISSUE TITLE
Import page not working

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#646]
Import page no longer works for me with most recent code.

If I click the import button I get this error & don't get to the bit where I can choose projects / pages:
Uncaught SyntaxError: Unexpected token in JSON at position 9637

**Comment by FayCross** [comment]
Sorry i hadn't noticed Ron having the same error.

I think it may be caused by a project where some of the page titles have line breaks in them. I'll send you the json

**Comment by torinfo** [comment]
Possible fix commited.
