### ISSUE TITLE
Import pages via insert menu

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#647]
Should we remove the option to import pages via the insert menu & just leave the button next to duplicate?

At the moment if you do it via the insert menu it gives you these options:

![bug2](https://user-images.githubusercontent.com/8926470/27869519-1c8348bc-6198-11e7-8c23-cba71b5d792c.png)

... but if you select before, after or at end it will try to insert a page type called 'Import Pages':

![bug1](https://user-images.githubusercontent.com/8926470/27869557-340a9fe4-6198-11e7-975f-0351f3b9c37b.JPG)

**Comment by torinfo** [comment]
Obviously it should work, but I think it's clearer to just have one option.

If others think both ways are usefull, I'll try to fix this one.
