### ISSUE TITLE
New Import Page Bug - Page Titles

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#649]
@torinfo I am now getting odd page titles appearing when I try to import pages. The project titles are coming in ok and the pages do import fine now but the titles aren't right:

![capture](https://user-images.githubusercontent.com/8926470/28167363-5002c06e-67d3-11e7-84d0-23d98cde4d74.JPG)

I don't get any errors

**Comment by torinfo** [comment]
This is bacause of caching, or because of partial implementation....

The titles are base64 encoded, and need to be decoded in choose-import.js

**Comment by FayCross** [comment]
Ah, sorry, I had missed updating one of the files - it's working ok now
Thanks
