### ISSUE TITLE
Tree scroll bars issue after page import

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#650]
Extra & unnecessary scroll bars appear on the tree section after importing pages (or glossary):

![capture](https://user-images.githubusercontent.com/8926470/28215094-b2f9d12c-68a4-11e7-97c0-c2386a4a9227.JPG)

**Comment by JohnSmith-LT** [comment]
Looks like extra <div class=treeview></div> are added by the system

![image](https://user-images.githubusercontent.com/3907362/28617464-51046902-71f8-11e7-8a07-ddc014229451.png)

**Comment by JohnSmith-LT** [comment]
Does #d2c4ed34fe6c93d06ec976f9b2f5c3aef48f9dd8 fix it for you @FayCross ?

**Comment by FayCross** [comment]
Yes, thanks @JohnSmith-LT
