### ISSUE TITLE
Clarification re management and configdetails

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#652]
Hi all
this is not really a bug or issue just a couple of points to note and perhaps worth clarifying re upgrade to 3.5 and also re moving/changing an installation.

1. I've now upgraded a few installations to 3.5 and most of these were already 3.3 or 3.4 etc or rather a recent revision of develop so I didn't run upgrade.php. However I noticed an issue when trying to make a change via the first section of management.php that it would result in "Site changes failed" whereas later sections of management e.g. template descriptions would work fine. It turns out running upgrade.php resolved this and the results of upgrade.php referenced: "Creating LRS Endpoint settings fields - ok ? true". However there seems to be some variation in database version reported e.g. 9 or 10. So as I say not really a bug but if you upgrade an install probably worth running upgrade.php anyway and then testing a simple change via managment e.g. I've added v3.5x to the copyright text as a visual reference that the site has been upgraded.

2. Over the years I've moved a few installs either from one server to another or to different locations on a server. Generally I've only needed to change the relevant values in sitedetails to get this working either via management or direct in the database. However a lot of the values in sitedetails are also replicated in configdetails and I'm unsure whether both need to be updated when moving/changing an install especially as I've had a moved install working fine but with some incorrect values in configdetails. So questions are: 
a) what's the relationship between sitedetails and configdetails and when/where is configdetails used?
b) do both tables neede to be updated when moving/changing an installation?

**Comment by torinfo** [comment]
@ronm123 

I can answer the configdetails part.

Configdetails was an attempt to simplify and update the sitedetails table.  The intention was to buidd as a dictionary, and to be able to leave things like site_url out of it (and then it would just use the URL passed by the browser).

At the moment configdetails is not used anywhere.

Regards,

Tom

**Comment by ronm123** [comment]
@torinfo ok cheers Tom. Useful to know that configdetails isn't used anywhere yet. 

The other item re management changes was really just for everyone's reference more than anything else so I'll close this but can obviously be found when searching closed issues.
