### ISSUE TITLE
Issues with Misc page types - Delicious and RSS Feed

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#654]
Hi all
now that we've released v3.5 I've been checking the various page types and noticed a couple of issues with these page types in the Misc category:

1. The external del.ic.ous site now seems to have gone forever so we should probably remove this page type as it won't even work for older/existing projects now.

2. The Google API that I think we currently use in the RSS Feed page has now been shut down. Not sure if we can use a different API or perhaps even change this to use local code?

**Comment by JohnSmith-LT** [comment]
We happy that this is resolved @ronm123 ?

**Comment by ronm123** [comment]
Hi @JohnSmith-LT yes both resolved:

1. delicious deprecated and showing a message about that rather than just the previous error
2. RSS feeds now working again

Re the RSS solution as you know I removed the double quotes but also today I changed the http link to rss2json.com to https instead - hope that's ok.

But also in testing I noticed a small issue with that service that got me wondering about future reliability. e.g. I added a few projects from a xerte installation to that site's RSS feed and then put that feed link in an RSS Feed page and it showed as feed not available but was showing the feed results via the browser. So I then tested that feed direct in rss2json.com and it displayed a message that the feed was too new so to try again later or to add an api key. So I wonder if down the line the site is going to require registration and setting up of api keys and therefore whether at some point we should look at a solution that is directly part of the Xerte install e.g. would this from W3schools work with a bit of tweaking?
https://www.w3schools.com/php/php_ajax_rss_reader.asp

**Comment by ronm123** [comment]
BTW a little later that feed I added was showing in the feed page so I guess that issue might not happen in normal use but still if there is a solution to not rely on an external service that would obviously be better.

Indeed if we had a solution as part of the install instead of an external service I wondered about the option like in Moodle to add a number of source feeds and have the results merged into the same page.
