### ISSUE TITLE
Tsugi code in develop branch incomplete

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#655]
Hi @jorisburgers / @torinfo 

Some Tsugi code has made it into develop (that is stopping export working for Nottingham projects) because there are includes that aren't found. Have these libraries been omitted accidentally or have the includes in /modules/xerte/export.php made it in there accidentally and can I revert that file back to a working version?

John

**Comment by torinfo** [comment]
Hi, yes, apologies for that. We forgot to commit the tsugi folder.

However, the tsugi code shold not have ended up in Export. It was an quick experiment that should have been removed. I'll clean it up after my vacation.

**Comment by JohnSmith-LT** [comment]
No worries, enjoy your holiday!
