### ISSUE TITLE
default debug.log location?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#657]
Not specifically an issue but adding this now while It's cropped up again...
Is there any reason why the default debug file location is /tmp/debug.log and not the error_logs folder inside the XOT install directory? e.g. error_logs/debug.log
Or should I say is there any reason why it shouldn't be the latter by default?

I know debugging isn't turned on by default but when it is turned on by someone trying to troubleshoot an issue, in at least some case like shared hosting, or restricted access, they won't have access to the /tmp folder but are more likely to have access to the error_logs folder.

Also as far as I can see storing debug.log in the error_logs folder provides access to view the errors and also delete the debug.log via management whereas it doesn't seem to show when set to the default location - at least not according to my xampp test.

Might help to change this and make it part of 3.5 to help troubleshooting when people upgrade?

**Comment by JohnSmith-LT** [comment]
Sounds like a good idea to me...

**Comment by ronm123** [comment]
Thanks @JohnSmith-LT I've committed this simple change. @torinfo if there's a reason not to change this please just revert back.

**Comment by torinfo** [comment]
No. That's fine.
