### ISSUE TITLE
New options for groupset of properties in the editor

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#659]
Working on the option to disable social buttons in Bootstrap and it struck me that as a groupset of properties gets more complex it might be nice to have some instructions appear within the box also... Something like this:

![image](https://user-images.githubusercontent.com/3907362/28676605-f9ede2ce-72e2-11e7-9dff-f18f40cf4005.png)

Also, what about a columns option for the groupset so that they don't need to be one after the other (which could get lengthy). So as above you would have:

![image](https://user-images.githubusercontent.com/3907362/28677228-c4ac96a8-72e4-11e7-8318-195e49414061.png)

**Comment by FayCross** [comment]
That would be great!

**Comment by ronm123** [comment]
+1 :-)

**Comment by JohnSmith-LT** [comment]
Hi @ronm123, I have added instructions box and columns (you can have up to 3). When cols= option not added to xwd then you just get a normal box but with columns it could be difficult to tell which option the checkbox is for so do you like this:

![image](https://user-images.githubusercontent.com/3907362/28744063-507044a6-7451-11e7-8abd-cd6bdf880e24.png)

better than this:

![image](https://user-images.githubusercontent.com/3907362/28744076-90818352-7451-11e7-9be9-c2f1072b824d.png)

Or any other suggestions before I commit?

**Comment by ronm123** [comment]
Sorry @JohnSmith-LT missed your question here but looks great!

**Comment by JohnSmith-LT** [comment]
Cheers @ronm123. I figured that there was no point holding off once I was done... Really pleased with how it came out myself...
