### ISSUE TITLE
Issue with grouped properties and colour pickers when only some changes required

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#661]
Hi @JohnSmith-LT @FayCross I'm adding this as a separate issue but it's only something I've noticed and realised is an issue since exploring the new theme functionality with bootstrap but this issue applies regardless of theme selected.

The issue is that with the header properties grouped and added you can't for instance add logos without also setting header and font colour because the colour pickers can't be empty. Unless I'm missing a trick with that? Likewise you can't just change the header font colour without also setting the background colour for the same reason.

I noticed this when testing the blackgrey theme that I've added and so with the header group added it instantly changes the header background colour. But in fact even with the default Bootstrap theme adding the header group instantly changed the default graduated header background colour to a flat blue colour and you can't add a logo left or right without forcing those colour changes too.

I guess the simplest option would be to remove the Background colour and Text colour options from the Header group and just leave theme as separate optional properties like we probably had previously before the group functionality.  Or perhaps there's a better way? Is there a way to get the colour picker to allow an empty value? Or perhaps a tick box alongside each colour picker to ignore or apply when ticked?

There's a similar issue but  perhaps less of a problem with the Media group of properties in the xot template e.g. you can't add that group without it adding Caption Colour and Caption Highlight Colour values.

**Comment by JohnSmith-LT** [comment]
Do we just need some way of turning them off within the group? Like this:

![image](https://user-images.githubusercontent.com/3907362/28772933-8e7e164e-75df-11e7-962e-285f35a46caf.png)

**Comment by ronm123** [comment]
@JohnSmith-LT yeah that looks like it would work!

**Comment by ronm123** [comment]
@JohnSmith-LT I've added a navbar group to the bootstrap options to control position of navbar and option to hide it too which all seems to work ok. While I was at it I added options to control the background colour of the navbar and ideally text colour and text hover colour too. The background colour works fine but with the text colour and text hover colour options included it stops the hover colour from working and I'm not sure why. Not sure if !important is used somewhere because I know I can get it working via styles but I've also read that it's not so straightforward to add !important via jquery so haven't managed to get the hover change to work yet. Any suggestions?

**Comment by ronm123** [comment]
Just adding here a reference to #596 because I've added a simple solution for now and described that in the discussion for that issue.

**Comment by FayCross** [comment]
I'll fix this - I hadn't thought of this issue when I made the groups. Most of the time (without themes anyway) it works ok as it just uses the default value but in this example it's swapping from 2 colours in a gradient to 1 so is more obvious.

I'll commit the code tomorrow

**Comment by ronm123** [comment]
@FayCross It shouldn't be replacing the gradient for any new LO's or if you remove and then re-add the group? 

I made the default values the same 0xEEEEEE and set that value to be ignored. But if there's a better way to deal with that great!

**Comment by FayCross** [comment]
Sorry, I meant in general the way it worked before not that there was a problem with your fix. I've got it working so it just starts blank instead of with EEEEEE as it seems neater that way (& we're bound to have someone say that they need it to be #EEEEEE!). Just need to test properly before committing.

**Comment by FayCross** [comment]
@ronm123 could you try my last commit out please & see if it works ok for you. The header & footer colours should now show as blank when 1st added. Thanks
