### ISSUE TITLE
Broken link to zip of stable release 

### ISSUE THREAD

**Issue by lucytallents** [thexerteproject/xerteonlinetoolkits#663]
The link given in the installation instructions for downloading the stable release (http://www.nottingham.ac.uk/xerte/downloads/xertetoolkits.zip) gives a 404 error.

**Comment by ronm123** [comment]
Hi
it took a while to identify where you was seeing that link but I have corrected that now. Most of the guidance for installing and upgrading is within the documentation folder in the download and for those downloading a zip rather than using Github should download from http://xerte.org.uk
HTH
Ron

**Comment by lucytallents** [comment]
Thanks for responding, and letting me know that I wasn't precise enough about where the problem was.
