### ISSUE TITLE
Bootstrap TOC highlighting not working correctly in Firefox & IE

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#664]
In Bootstrap projects with several pages & several sections within each page the highlighting of the current section in the TOC menu doesn't always work correctly. It seems to work on the first page but then after moving to another page the highlighting sometimes stops working all together (so no section is highlighted on TOC) or the highlighting gets stuck on the top section even though you've selected or scrolled down to a later section. This doesn't always happen immediately on changing page but after a few page and section changes (clicking & scrolling) it often goes wrong.

I can't work out what's causing this & whether it's something in our code or the Bootstrap js stuff. Any ideas anyone?

This bug doesn't seem to happen in Chrome

**Comment by ronm123** [comment]
Hi @FayCross this was mentioned by Neil Pollock from Cardiff previously too http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1313&Itemid=759&lang=en#4519 but looks like none of us responded. I've noticed this and can replicate it too but like you not sure re the cause/solution or indeed whether it's always been the case.

**Comment by FayCross** [comment]
Thanks Ron, I hadn't remembered seeing that bug from Neil. I've tried troubleshooting it but can't find anything in our code that seems to cause it (links are triggering correctly and the 'active' class doesn't seem to be removed by us anywhere). At some point I guess we'll have to update the version of Bootstrap we use as it's pretty out of date now...

**Comment by FayCross** [comment]
Duplicate of #1026 which has been fixed
