### ISSUE TITLE
Properties panel - LTI2/Tsugi tab errors

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#665]
There's a new tab in the project properties panel called 'LTI2/Tsugi' but when I click on it I get these errors showing in window:

Warning: require_once(../../../tsugi/config.php): failed to open stream: No such file or directory in C:\xampp\htdocs\xertetoolkits\website_code\php\properties\tsugi_template.php on line 2

Fatal error: require_once(): Failed opening required '../../../tsugi/config.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\xertetoolkits\website_code\php\properties\tsugi_template.php on line 2

**Comment by torinfo** [comment]
I'll fix it when I am back next week.
