### ISSUE TITLE
Decision tree do not show images and i frames

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#667]
Hi,

After the update it is not possible anymore to see images or videos (using iFrame) on the second (and following) pages of the decision tree. Did something change here?

In the edit mode I see the image and video but in the show mode I don't see them. (see print screens)

Bye,
![edit__mode](https://user-images.githubusercontent.com/5703781/29611320-6731da3c-87fd-11e7-997a-397af10c9ac2.png)
![show_mode](https://user-images.githubusercontent.com/5703781/29611319-672a5122-87fd-11e7-9c5e-f2def44bda77.png)
Inge

**Comment by torinfo** [comment]
No errors whatsoever in console or php error logs.

 - It works fine on the first page, but not on other pages
 - It works in 3.4

I've got no idea what's going on. Any hints?

**Comment by FayCross** [comment]
Are you running most up to date code? I think I fixed this on 9th August https://github.com/thexerteproject/xerteonlinetoolkits/commit/6d45064803d326b8aa6fdeee9698f2d264a62432

**Comment by torinfo** [comment]
Ah, brilliant!

No, we're running release. We'll check and confirm the fix. @FayCross I suppose this should be escalated into master. Agree?

**Comment by FayCross** [comment]
Yes, sorry, I should have done that

**Comment by torinfo** [comment]
Cherry-picked 6d45064803d326b8aa6fdeee9698f2d264a62432 into master
