### ISSUE TITLE
Readme file wrong version in package

### ISSUE THREAD

**Issue by jayaich** [thexerteproject/xerteonlinetoolkits#668]
Hi,

Just downloaded the Xerte 3.5 and 3.5 updates zip files, and noticed that the 'readme.md' file starts with:

``Latest release : v3.2 (released on April 11, 2016)``

I can see that commit 9a463e5bec24639d87ac54dc5fb4a0599973dd3a corrects this, but perhaps the new readme.md file should go into the updates zip file? It could avoid some confusion.

**Comment by torinfo** [comment]
Thank you!

Done
