### ISSUE TITLE
File checks - cannot easily be enabled

### ISSUE THREAD

**Issue by jayaich** [thexerteproject/xerteonlinetoolkits#688]
Xerte has code to perform various checks on files which are uploaded, and when saved by the editor. The checks are (1) anti-virus check; (2); file extension check; (3) mime type check; (4) XML validity check.

However, most of these checks are not enabled - in fact, as far as I can tell, only the XML check is enabled and that only for files saved by the editor.

Ideally all the checks would be enabled by default in both circumstances (uploads and saving). Suddenly activating these checks may well cause users problems though! It would be nice to be able to enable/disable each check from within the admin user UI, as well as set various options (e.g. the path to the antivirus program; options used by that program, mime types that are allowed, file extensions to be disallowed, etc, etc). To do this probably involves adding entries to the backend database (probably a new table rather than adding to the 'sitedetails'?).

Locally we have been running all 4 checks for over a year with no problems. These have been 'enabled' in the code though, not through the admin UI or the database. I'll see if I can put together a pull request which allows the checks to be enabled/disabled and makes use of the UI and database.

**Comment by torinfo** [comment]
That sounds very good!

I would prefer you to add  the fields to sitedetails for now. And also, please update.php if you can.

One of the things I want to do is to refactor siredetails into a key, value table (see the configdetails table for a start)

**Comment by jayaich** [comment]
Okay, that's all noted. Looking at upgrade.php though there are a couple of things I noted:
1) it seems that the table 'configdetails' is only created during an 'upgrade' not a new installation.
2) The table is created as upgrade 5, so anything that modifies 'sitedetails' after that will not be reflected in the configdetails table. (That is, shouldn't upgrade 5 (in effect)  be run last?)

**Comment by torinfo** [comment]
No. Correct. configdetails is unfinished business and needs to be finalized. I was just pointing it out to you because that's what we want to use in the future, but even though it is created, it's not in use yet.

So for now, please use sitedetails, and update sitedetails in upgrade.php

**Comment by jayaich** [comment]
I'm going to close this issue as the latest develop branch code now has options in the management interface for these checks (except for the XML check).
