### ISSUE TITLE
Issues with management functionality

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#689]
Hi all
This is something I've been meaning to test further for a while and prompted by all the work John Horne has been doing on the Management side I've finally tested in a way that I can replicate on numerous installations...

1. There seems to be an issue when trying to edit a users project(s) via management that you have to be logged into the same installation as a user via the same browser you are logged in via management to be able to publish the changes made. Otherwise a pop-up is displayed simply saying error.
Can you replicate this? e.g. login to an installation management page in a browser where you haven't logged into the installation in any other way and try editing a users project. If you get an error on publish then login via that same browser to the normal workspace and then in the previous tab try the same edit via management again.

2. Regardless whether logged in via both normal workspace and management or just management I can't get any of the export formats to work. Console shows a 500 (Internal Server Error)
Are you able to export projects via management?

**Comment by jayaich** [comment]
In response:

1) Yes - confirmed. All I get is a popup with 'error' in it. 
2) Yes - confirmed. Using management nothing happens when I click any of the export types. Logging in as the user, all the export types work fine.

My heads spinning at bit with the file uploads stuff, so I' may well take a look at (1) this afternoon if you like. (It's not on my work list, but what the heck :-))

**Comment by ronm123** [comment]
@jayaich sure great if you can look at 1. if/when you have time. I suspect that might be session related or something like that. Doesn't seem to matter which account is logged into the normal workspace once that is the case then editing works via management regardless of user project.

**Comment by jayaich** [comment]
Just added a pull request that should sort out both problems.

**Comment by ronm123** [comment]
@jayaich that's great thanks. 
@torinfo will you merge the pull request?

**Comment by torinfo** [comment]
merged
