### ISSUE TITLE
Add page linking to children/specific Navigator panes and/or top of page in Bootstrap template

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#690]
Hi all
I think @FayCross previously extended the ability to use Xerte Page links to link to specific navigator panes in the XOT template e.g. where the names of Navigator panes show in the page links list as preceded by hyphens and then when arriving at the relevant pane the specific pane is opened.

I was asked if this is also possible in Bootstrap projects and it doesn't appear to be. So two questions:

1. Anyone got a workaround to achieve this in Bootstrap projects? e.g. Link on page 1 to page 2 to pane 2 etc.

2. Could we add similar child linking functionality to the Bootstrap project.

**Comment by ronm123** [comment]
In response to the post on the community site by Neil Pollock http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1373&Itemid=759&lang=en#4678 
There's another issue:
3. By default page links to another page need to go to the top of the page rather than remain at the scroll depth of the originating page/section link.

Does anyone have a script workaround for that to use before any changes are implemented?

**Comment by ronm123** [comment]
Hi all
I've had it reported that when visiting a Bootstrap project it automatically scrolls to below the header rather than the very top of the page. Sure enough if you visit our bootstrap demonstrator via https://xot.xerte.org.uk/play.php?template_id=137 you land down the page and the header isn't shown until you scroll back up. After some testing it seems this happens if the navbar is set to below rather than above the header. However I'm not sure if that's always been the case or if its something that has crept in as a result of the additional page linking functionality that Fay added in https://github.com/thexerteproject/xerteonlinetoolkits/commit/9b4bfda1ac230273e42acf04674e9e86c1dea961 

I think those additions are great and really useful to be able to add page IDs that relate to the topic of the page e.g. https://xot.futureteacher.eu/play.php?template_id=4#flipped but again if you visit that link it lands on that page but without the header showing until you scroll back up. I'm not 100% sure at this point whether this has always been the case when the navbar is below the header but I don't think it is. @FayCross @torinfo @JohnSmith-LT any idea when this changed?

I think by default a link to a page should open at the very top showing the banner and regardless of whether the navbar is above or below the header, unless a section link has been used. However I also wonder if we need to (and if we can) add an optional property which controls this (either at LO level or page level) so that the author can decide whether the links should open as they do now e.g. scrolled down the page if the navbar is below the header.

I'm adding this update before checking the code but it seems to me this is quite an urgent issue really because I think we would all expect bootstrap links to open with the banner showing and I can't remember that not being the case previously?

**Comment by ronm123** [comment]
@FayCross @torinfo @JohnSmith-LT unless I'm missing something it never ceases to amaze me how we all miss the impact of very simple changes :-( But perhaps I am missing something here and that this changed recently rather than ages ago so correct me if I'm wrong...

Ages ago we added an optional property so that the navbar in the bootstrap project could be below the header instead of above the header. I think I may have even added that or at least contributed to it being added because in the early days I became aware that end users weren't even noticing those page links when above the header.

I'm not sure at what point goToSection('topnav'); was added but whenever that was it seems links to specific pages will have been loading with the header not showing if the navbar was set to below the header.

I've committed a change https://github.com/thexerteproject/xerteonlinetoolkits/commit/a718c0db69b344c50f4346111d8f8ea27d1d2d83 so that goToSection('topnav'); is now goToSection('overview'); so that the header displays even when the navbar is below the header and I can't find a scenario where this breaks anything. e.g. if the link loading a page contains a section too that still works.

Can you test and verify this is ok please? 

@torinfo if it is ok can you update the xot.xerte and xot.futureteacher installs with this change and at some point pull this and the other recent commits across to the downloads too? It seems to me there are a few recent commits that need to be in an updated download?

**Comment by FayCross** [comment]
@ronm123 This fix has the opposite problem - if you have the page links above the header it now scrolls to the top of the header so the links are hidden. I'll look into & fix

**Comment by FayCross** [comment]
I've added a div with id 'alwaysTop' that's used to scroll to top of page on page loads. This is always above header block & page links so that it doesn't matter if the header or page links bar is top or is either are hidden - the top of the page will always be shown initially. The only exception to when pages are loaded at top of page is when it's a link to a specific section - then the pages will be automatically scrolled down to that section.
