### ISSUE TITLE
Gap Fill Issues

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#691]
We have a UoN user who has used the gap fill page a lot in the past but isn't happy with the way it now works. I think it's partly because of the way the page has been changed to allow for tracking. I've been testing it and there are quite a few small bugs I've found too. Here's a list of the things that need doing:

**Drag & drop interactivity type:**

- [x] When mark at end is off the feedback doesn't show when all labels are placed.

- [x] When mark at end is off and you complete activity, change page & then go back it says all your answers are wrong even though they're not.

- [x] After checking your answers you can't try again with the labels that were wrong. This means there's no way of knowing what the correct answer should have been as there's also no 'show correct answers' button.

**Fill in blank interactivity type:**

- [x] Hint no longer seems to work

- [x] There's no way of seeing correct answers if you keep on getting the answers wrong. 

- [x] It is always 'mark at end' now. He would like the option to not have a check button but have the answers turn green immediately when you type in the correct answer (as it used to be). I think the hint isn't working because this option is no longer here.

**Drop down menu interactivity type:**

- [ ] Remove drop down menu styling when answer is marked as correct

& finally for all the interactivity types:

- [x] When there's a check button it only lets you check the answers when the whole activity is complete. For long activities it would be useful if you could use this button to check your progress when you hadn't completed everything.

I'll start working through these but want to check that making these changes won't mess up the tracking marks.  So, if i change it so that you can retry incorrect drag & drop labels is that ok? & what about being able to check answers halfway through? Does it just take the mark from when you 1st submit or will it update ok in these circumstances?

**Comment by FayCross** [comment]
I realised my questions at the end probably aren't clear (I guess it won't mess up the tracking if I make the changes right!) I was wondering really about whether allowing people to change their answers or check answers halfway through when tracking is on is ok (do we allow this on other page types?)

**Comment by torinfo** [comment]
Please note that the University of Utrecht complained about some of the same issues, and most of those have been fixed (some days ago).

**Comment by FayCross** [comment]
Oh ok, when do you think they'll be committed to develop? Thanks

**Comment by torinfo** [comment]
I'll try to do that tomorrow or Friday.

**Comment by FayCross** [comment]
@torinfo I fixed several of these issues on our install as I needed to fix them for some live projects. Is it going to mess up the changes you have ready if I commit these now? Elly on the forum has also reported issues with this page so we could do with fixes being available as soon as possible

**Comment by torinfo** [comment]
@FayCross One of the students fixed this some time ago, nad that patch is in use by Utrecht now.

It is however in the fork that the students are working on, and it's not that easy to create a pull request for that work.

So, perhaps the best way forward is for you to commit the changes, and subsequently I will merge in the fixes of the studenst, hopefully resulting in a all the problems being fixed.

After that we should consider if we want to merge this is on master. (I think we do).

**Comment by torinfo** [comment]
@FayCross Just saw the new remarks of Elly, so, yes, please commit you r fixes. I'll retest and check the fixes done by the students. I will then cherry-pick into master and install for Elly.

**Comment by FayCross** [comment]
Ok, I'll do that later today

**Comment by torinfo** [comment]
@FayCross Hi Fay, as far as I can tell, this you have not comitted yet. Is that correct?

**Comment by FayCross** [comment]
@torinfo - I've just committed the changes. I tried to be careful with all the tracking code in there so hopefully that will all still work ok
