### ISSUE TITLE
NEW FEATURE REQUEST - A PAGE ALLOWING TO EMBED HTML 

### ISSUE THREAD

**Issue by danieledivito** [thexerteproject/xerteonlinetoolkits#716]
There are a lot of new tools for creating HTML5 simulation or contents that can be embedded by only using a single HTML file.  for example https://phet.colorado.edu 
It would be nice to have the possibility to upload the html file and to use it.
I know that Media Lesson allow to embed an html file but you need to use a video for synchronization and it's not so easy to embed an html file, cause it ask for an url not for a file from the media library.

**Comment by FayCross** [comment]
Hi, you can already upload html files and embed them in your project:

1. Select your project in the workspace & click the project properties button

1. Select the Media & Quota tab, choose the html file you want to upload & click Import

1. After it has uploaded, select the file from the list and copy the link you are given to it

1. Now open your project in the editor and insert an Embed Content page (in the navigators menu)

1. Paste the link to your HTML file into the 'Embed Code or URL' box.

Hope this helps
