### ISSUE TITLE
Double click to open editor bug

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#717]
You can normally double click a project in the workspace to open it in the editor. This doesn't work when the project is in a folder.

**Comment by JohnSmith-LT** [comment]
Double clicking on a folder or a file inside a folder doesn't fire the dbclick handler at https://github.com/thexerteproject/xerteonlinetoolkits/blob/4bd58830343157ea8030f7d984ed43dadf47bdd4/website_code/scripts/screen_display.js#L796 whereas all the rest do. The handler is called for double clicks on workspace and recycle bin and handles them correctly...

![screen shot 2017-11-17 at 12 39 41](https://user-images.githubusercontent.com/3907362/32947850-ebc37000-cb94-11e7-9e12-d99bd305dada.jpg)

Not sure if the "double click to open folder" functionality of the jstree is somehow overriding and interfering with our double click action...

**Comment by JohnSmith-LT** [comment]
Gets a bit weirder - the folder does fire the event if it's empty, just not when there is something in it...

**Comment by FayCross** [comment]
I'm going to close this as double clicking on projects that aren't in folders no longer works now too... at least it's now consistent! I think it's unlikely this was widely used anyway.
