### ISSUE TITLE
MCQ feedback issue

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#718]
When MCQ page is set to single answer but there are several options that could be correct, the feedback will always show as incorrect even if the answer selected is correct.

**Comment by JohnSmith-LT** [comment]
Hi @FayCross , can you test that this fixes your issue? It seems the logic for both cases is quite different so i've separated them out to simplify them.

**Comment by FayCross** [comment]
Yes that's great, Thanks @JohnSmith-LT
