### ISSUE TITLE
problem with install script?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#719]
Hi all
for various reasons I just tested setup after pulling down a new copy of develop and I get an error:

![image](https://user-images.githubusercontent.com/5167146/33069586-ebad5a8e-ceac-11e7-804a-f6fef8deb015.png)

I can't see any console errors and I tried setting debug to true but I don't think it's getting as far as that.
Can anyone else replicate this?

**Comment by jayaich** [comment]
Just tried this with the latest develop, and got no problems.
Basic.sql does not have a blank line at the end. But if I add a blank line, then yes it throws the error you see.

**Comment by ronm123** [comment]
@jayaich Hi John what dev environment/tools do you use?
To test again I did the following:
Create a new folder in htdocs named develop_nov17 in my Windows 10 xampp installation
Pulled down a copy of develop (I use TortoiseGit)
Run through setup naming the database develop_nov17
Setup fails with the failed to execute error
Check and remove the empty line from the end of \develop_nov17\setup\basic.sql
Repeat setup and the installation completes without error

As you say I don't see an empty line via https://github.com/thexerteproject/xerteonlinetoolkits/blob/develop/setup/basic.sql but it's somehow being added when I pull it down and visit that file locally. This was a new empty folder so it's not that the file with empty line already exists in the local folder. If nobody else is getting this problem then it's not a big issue but I think @FayCross and @thexerteproject use TortoiseGit and Windows so I'd be curious if they can replicate?

TBH I'm also seeing much more worrying issues with importing media and exported projects and I'm about to detail that as a separate issue.
Cheers
Ron

**Comment by jayaich** [comment]
This was tested on a RedHat 7 Linux server.
Could you try changing line 93 of 'setup/xampp.php' from:
`if($query!=""){`
to
`if(strlen($query) > 1){`

**Comment by torinfo** [comment]
Changed line 84 of page2.php to 

`if ( strlen($query) > 2 )`

Because EOL is 2 characters on Windows

**Comment by ronm123** [comment]
@torinfo @jayaich 
I can confirm that has fixed the setup issue when using Windows/XAMPP.

I repeated the process with a new clean install and all worked fine. But I am still getting the import issues  detailed in #720 and will add an update to that shortly.
