### ISSUE TITLE
latest develop won't import media

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#720]
Hi all
I've been investigating an issue with narration on different pages that an end user reported with their copy of 3.5x and I'll add that separately but in testing this I'm hitting issues with my long term copy of develop and a new clean install of develop where I can't import any media via the editor or media and quota and I can't import previously exported projects either. e.g. if I create a new xot based project, add a title page, add optional narration, browser to add an mp3 file I get the following error:
![image](https://user-images.githubusercontent.com/5167146/33274300-90cdf36e-d387-11e7-820e-0d2c0f92521f.png)
However if I try adding an image or other formats I get the same error and I get this on both my existing copy of develop and a new clean copy of develop. Both of these are updated to the latest revision. I also ran upgrade.php on both just in case that was part of the problem/solution.

Can anyone else replicate this?

**Comment by jayaich** [comment]
Sorry, but I can't reproduce the problem. Using the same new develop version from this morning (on RHEL7 Linux server), I imported a project successfully. I then imported some png/jpg files via quota/media - again no problems.

**Comment by ronm123** [comment]
@jayaich I've tested this now on both xampp and on a centos server and a clean install of the develop code on both.

If I try to upload a jpg via media and quota on both installations I just get an Importing spinner but the upload doesn't complete
![image](https://user-images.githubusercontent.com/5167146/33321901-383f6652-d43f-11e7-8d42-4142cf16530a.png)

On the xampp install if I add a graphics and sound page then browse to upload an image I get: 
![image](https://user-images.githubusercontent.com/5167146/33321943-6201dfb0-d43f-11e7-8537-075a1b3350b0.png)

On the centos install doing the same I get
![image](https://user-images.githubusercontent.com/5167146/33321965-70b0f726-d43f-11e7-8a10-779e4a100a80.png)

I'm not seeing any errors in the browser console when testing this.

However on both installs I can copy and paste an image into the editor and that uploads without a problem.

**Comment by torinfo** [comment]
I have the same error on XAMPP (didn't try Linux yet), and the problem is with lines 933-937 in editor/elfinder/php/elFinder.class.php.

The function apply_filters is not found. If I uncomment that block, everything works. @jayaich: Any idea where that function is supposed to be defined?

**Comment by jayaich** [comment]
The function comes from the wordpress plugins (website_code/php/wp_plugins.php line 137).
I have created a pull request ( #722 ) which should sort it out.
I am a bit confused though. I checked the test server and it doesn't have the fix in it. So I checked our live server, and it does have it in it. So I'm not sure why things seemed to work on the test server, unless I was doing something wrong.

**Comment by ronm123** [comment]
@jayaich @torinfo 
just pulled down the changes in develop and tested via xampp and that seems to have resolved the adding of media via the editor but not via media and quota. Via the latter I still get a spinner and no upload completion.

**Comment by ronm123** [comment]
Just to add I tested via my Centos test install and the same applies there e.g editor import seems to be working but not via properties > media and quota
I just get never ending spinner on both installs.

**Comment by jayaich** [comment]
Can I just ask about the 'editor import' again - for my own understanding, what is the sequence you perform?
For me I take this to mean the following:
1) Access Xerte (on test server it is using guest login). It shows the 'Workspace' tree with 2 imported projects under it.
2) Click on project 1 and then the 'Edit' icon (to the left). This opens a separate window with a tree structure of the project pages on the left.
3) Click on the 'Insert' (plus sign) icon. From the dropdown list select Media->Graphics and Sound->After. This creates a default page showing 'Enter Page Title' etc.
4) In the middle pane, to the bottom right, click on the 'Import Media' icon. This shows a new window with the files in the media directory (in my case 'USER-FILES/2-guest2-Nottingham/media').
5) Highlight an image file, and then click on the 'Select files' button (looks like an arrow pointing up and left).
6) For the new page the 'Image' location is now set to the file selected (in my case it shows "FileLocation + 'media/atom.jpg'".

That's it.

**Comment by ronm123** [comment]
@jayaich yes sort of John. But the bit that was failing was the step where you then click the upload files option to upload and select a new file rather than an existing file. However that was fixed by the changes you and @torinfo committed.

The bit that still isn't working is as follows:
1. Select a project in the workspace
2. Select properties
3. Select Media and Quota
4. Browse for an image
5. Select Import
That just displays the spinner without completing the upload

**Comment by jayaich** [comment]
Okay, I'm not seeing any 'upload files' option anywhere.
Importing via media/quota is still working for me. I'm asking about the editor import in case I am not seeing something that you are, and likewise missing something in the media/quota problem.

**Comment by ronm123** [comment]
Not sure what you mean - how did you get the images into your test project?

As I said this bit is working now but to be clear with the media browser open either 1. click the upload files icon/button or 2. right click and select Upload files where you can then 3. drag and drop onto the window.
![image](https://user-images.githubusercontent.com/5167146/33385677-1bfb76d8-d521-11e7-957f-ac1c5f87dc6e.png)

There's something wrong with whatever upload process happens via project properties media and quota and workspace properties import because both just show the spinner and do not complete. Screenshots below:
![image](https://user-images.githubusercontent.com/5167146/33385962-d482ea56-d521-11e7-928a-fb947d542a78.png)
![image](https://user-images.githubusercontent.com/5167146/33385971-db3f4e02-d521-11e7-84c5-56d85ddd2e16.png)

**Comment by jayaich** [comment]
Okay, in your first image where you have the red '1' for the 'Upload files' button I have instead the text 'No files selected.'. The button/icon image is the same, just the text is different when holding the mouse over it. I didn't use that button during testing. Have to admit I didn't think of right-clicking.
That was using the Firefox (version 57) browser. If I use google Chrome then I get the 'Upload files' text. A bit worrying, and something to be aware of.

**Comment by jayaich** [comment]
Okay. The problem is - again - a browser issue. I'm using Firefox, and the media/quota problem works fine (i.e it's not a problem). Trying it with google Chrome, and the spinner just spins as you say.

**Comment by jayaich** [comment]
Just submitted pull request 724 to remove the spinner for these 2 situations. Now that I can reproduce the problem, I can take a better look to see what is (or is not) going on.

**Comment by jayaich** [comment]
PR #726 just created. It should sort out the spinner problem.

**Comment by ronm123** [comment]
@jayaich thanks. Once @torinfo merges in the pull request I'll test and report back.

**Comment by ronm123** [comment]
@jayaich @torinfo Hi both
just reviewing this and I can see that in latest develop the various ways to import/upload are currently working but I'm not seeing the spinner anywhere. Reading through the thread it seems the temporary fix here was to remove the spinner but I think in #726 they were restored but perhaps that hasn't yet been merged?

**Comment by torinfo** [comment]
@ronm123 
I just merged #726 in.

**Comment by ronm123** [comment]
@jayaich @torinfo as far as my testing goes this seems to be working fine now so will close this and #726
