### ISSUE TITLE
issue with exported projects containing narration

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#721]
Hi all
I'm not sure if this is a new issue or has been the case with previous versions too but someone asked me why the audio in their exported projects was working fine when the project was uploaded online but not when viewed offline. They had tried both deployment and offline export and were confused because the audio was working on some pages but not all. Upon further investigation myself I've found the following:

the project exported and uploaded online works fine (regardless of the export option chosen) and both sound and narration plays wherever it has been added.

The deployment export extracted and opened locally in Firefox plays fine except that only audio added as 'sound' shows and plays but audio added as narration doesn't even show on the page.

You might say that's predictable and only offline export will play reliably offline but exactly the same is true of the offline export whether viewed in Firefox or Chrome.

I created a simple test file containing a graphic and sound page with a sound option added and a title page with a narration option added and exported as offline export.
When I extract and view that project the graphics and sound page is fine but the title page doesn't even show the narration/player bar. 
If I check the Chrome console and view the title page I get a cross origin error e.g. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https. but the graphic and sound page is fine with no such error.
The same project uploaded and viewed online or via localhost plays fine with both audio types showing.

The same is true of an exported copy of the project the user sent me.  That had narration on most pages including title, orientation, documentation, dialogue and hyperlinks and had sound added to the transcript reader page. When the offline export is viewed offline only the audio on the transcript reader page works and all the other 'narration' audio on the other page types doesn't even show. The same project uploaded and viewed online works as expected.

Not sure if this is a new issue and due to recent code changes or has been there for sometime and just not picked up?

**Comment by FayCross** [comment]
There are some checks in xenith to see whether media exists before it's loaded into the interface (e.g narration audio & background image). For some reason this function (x_checkMediaExists) is always returning false if the project's being run locally.

**Comment by ronm123** [comment]
@FayCross testing that with one of the exported projects that I was using for testing and putting alerts in the copy of xenith in that export I can see that the line: x_checkMediaExists(x_evalURL(x_currentPageXML.getAttribute("narration")) is finding the correct value/path of the audio file but then the following if(mediaExists) isn't triggering as true.
If I change that just for testing to if(mediaExists==false) then the audio loads.

**Comment by FayCross** [comment]
Not sure this is fixed in the best way but it will now force the checkMediaExists function to return true if a project's viewed locally
