### ISSUE TITLE
Known/current issues with new XOT template themes

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#728]
Hi @FayCross @torinfo I'm adding a few notes here regarding the new xot template themes I've added and some outstanding issues I'm aware of...

1. Interactive Diagram
There's the issue we've discussed re the interactive diagram page when set to 'Labels' mode and when the theme is one of the percentage width themes e.g.  Modern: Urban Blue.

2. Flash Cards
On changing from front to back text from the first side remains on screen while the card is turning. I'm wondering if this is a consequence of the change of loading order or perhaps I just haven't noticed before and also I only see this on mobile devices (ipad and iPhone*) not on my laptop. 

3. Dialogue
Again I haven't noticed this before and it's only on iPad/iPhone* not desktop but the button alignment isn't staying bottom right of the text boxes e.g. the button is moving position and to left of text boxes as you progress through the button clicks.

4. Media Lesson
I know we're aware of some issues with this on smaller screens but with the various new themes I'm seeing problems with a simple two panel layout displaying the second panel below the first especially on iPad* but also on desktop/laptop too it seems unpredictable. In some cases I've noticed that if you navigate past the page and then back again the alignment is corrected but not always. I'm guessing it's to do with how the panel widths are being set/updated?

There might be other issues that I haven't yet noticed but these are the ones I can replicate fairly reliably.

*Also where I've referenced iPhone/iPad I don't think there's a way to force refresh just for a particular page/site/resource and I've learnt from previous experience that clearing cache can lose saved stuff that I wouldn't want to lose. So I'd be interested to know if you can replicate all of these issues regardless of any caching?

Ron

**Comment by FayCross** [comment]
I've narrowed down the problem with the flash cards page. For some reason iOS doesn't like the combination of the flip plugin with overflow set to auto on the cards. If I remove the overflow css then side 1 content disappears correctly when flipped but it means that if the content on the cards is too big for the cards then it overhangs the edges which obviously looks awful. I don't know if there will be an easy way around this without more fundamentally changing the way the page is set up. This won't be done in time for this release

**Comment by ronm123** [comment]
@FayCross do we know if this happens on other tablets/phones too not just iOS? From what you say this must have always existed? I guess if the problem has always existed and isn't a consequence of recent changes then I'm not aware of it being raised as an issue by many others. Obviously it's an 'unpleasant' effect but doesn't break the learning. So perhaps just an issue to keep on the list to fix for a future release.

**Comment by FayCross** [comment]
@ronm123 I will check on an android phone at home later. I don't think it has always been this way as I should have checked it on my iPad when I first made the page model.

**Comment by FayCross** [comment]
Interactive Diagram issue fixed (#666). I'll try to look at media lesson issues (& Tom's new stuff in it) tomorrow

**Comment by FayCross** [comment]
Closing this as most issues have been fixed. I've opened https://github.com/thexerteproject/xerteonlinetoolkits/issues/1150 with the outstanding issue relating to Flash Cards page on iPhones so it's more likely to be picked up
