### ISSUE TITLE
XAMPP - issue loading xml files

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#735]
I think this was working until I upgraded my xampp install with the commits done by Tom last week.

I used to be able to test changes on my xampp install on my iPad & phone by visiting myPCsIPaddress/xertetoolkits rather than localhost/xertetookits. This no longer works. I can login & open editor but if I try to preview/play projects the project data doesn't load.

It's failing because it's looking for localhost/xertetoolkits/USER-FILES/48-guest2-Nottingham/preview.xml when I it needs to use myPCsIPaddress/xertetoolkits/USER-FILES/48-guest2-Nottingham/preview.xml. The editor still uses the correct path & loads the xml fine.

Would you be able to look to see if the way the path to the xml is made has changed @torinfo please? I wanted to do some testing on the media lesson page on my phone for @ingedonke but I can't at the moment

**Comment by torinfo** [comment]
@FayCross Yes, I will have a look a.s.a.p.

**Comment by FayCross** [comment]
Thanks @torinfo
