### ISSUE TITLE
mediaLesson video display on mobile devices

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#736]
The mediaLesson doesn't show (or only shows) a very tiny part of the video on mobile devices

This is caused by the fact that mobileTheme.css is used, and when usin that the way pageHolder is set up gives it a completely different height then when not on a mobile device.

The solution I've take for now, is to do the height calculations in mediaLesson based on mainHolder in stead of pageHolder

@FayCross Do you agree with this?

**Comment by torinfo** [comment]
I'll commit this later today. @FayCross, we can rework it if needed.

**Comment by FayCross** [comment]
I'm going to have a look at all the changes you've made this afternoon Tom - but yes, mainHolder is probably the best one to use
