### ISSUE TITLE
Email messages being sent without domain name

### ISSUE THREAD

**Issue by jayaich** [thexerteproject/xerteonlinetoolkits#742]
I'm not entirely sure of the circumstances of how these are being sent, but we have occasionally received error email messages back from our Xerte server complaining that an email address is missing the domain.
For example:

+++++++++
A message that you sent contained one or more recipient addresses that were
incorrectly constructed:

  auser@: domain missing or malformed

This address has been ignored. There were no other addresses in your
message, and so no attempt at delivery was possible.

------ This is a copy of your message, including all the headers. ------

To: auser@
Subject: File available - "NEW Key Software for Employees"
X-PHP-Originating-Script: 0:template_close.php
From: xerte-user@plymouth.ac.uk
Content-Type: text/html; charset="UTF-8"
Message-Id: <E1eyHzm-0001TT-Tk@xerte-server.plymouth.ac.uk>
Sender: Apache <apache@xerte-server.plymouth.ac.uk>
Date: Tue, 20 Mar 2018 14:12:10 +0000
+++++++++

As can be seen the To: header is just 'auser@' - the email address domain is missing.
Fortunately the headers are telling us that the file producing the message is 'template_close.php'.

I can fix the problem in this instance (pull request will be sent later on).
However, it seems that there is another place emails can be sent (properties_library.php), and in both of these it is possible for an email address to end up with '@' but without a domain. The solution would be to only add the domain if it has been configured (in the site configurations under the 'Email' section, labelled 'The site email to add to username is'). This way a domain is used if it is configured, but if not configured then only the username is used (implying a local user).
Again, I can send a pull request for this later on.

**Comment by jayaich** [comment]
Pull request #743 created.

**Comment by JohnSmith-LT** [comment]
Thanks for that John.
