### ISSUE TITLE
Button display top of management area

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#754]
Hi all
I've just noticed a bit of an issue after running upgrade with the display of the button at the top of the management area. e.g. because we now have the Groupings button too there isn't room for all the buttons and there's some odd wrapping going on. I've tested with Chrome, Firefox, Edge and IE11 and all are the same as it stands e.g.
![image](https://user-images.githubusercontent.com/5167146/38562409-672bd490-3cd2-11e8-9c63-39cf1993a973.png)
That is with .xerte_button set to display:inline-block;
As a quick fix I tested the following display:inline-flex;:
![image](https://user-images.githubusercontent.com/5167146/38562499-a2d307c0-3cd2-11e8-9c29-08c0e1f2e4db.png)
and display:inline-grid;:
![image](https://user-images.githubusercontent.com/5167146/38562524-b13b57c2-3cd2-11e8-80d3-d3bb93a18e6d.png)
There's probably a better way to do this but I think display:inline-grid; looks/works ok except doesn't seem to have any effect in IE11.
Thoughts/suggestions?

**Comment by ronm123** [comment]
Ok scrub that quick fix - just noticed that .xerte_button is used in other places too e.g. the buttons in the editor! Need a different fix or perhaps a class/ID unique to that area?

**Comment by torinfo** [comment]
It always looked skewed in Dutch (beacuse Dutch even takes more space).

I like the 3rd option (even if it doesn't work in IE11)

**Comment by torinfo** [comment]
So, do that fix, with different class (I can add the different class if you want me to)

**Comment by torinfo** [comment]
You can use a different selector:

.admin_mgt_area_middle_button_left .xerte_button {
    display: inline-grid;
}
.admin_mgt_area_middle_button_right .xerte_button {
    display: inline-grid;
}

**Comment by ronm123** [comment]
Ok cheers Tom I'll test that and commit if ok and report back if not.
