### ISSUE TITLE
Workspace inaccessible in ipads and androids

### ISSUE THREAD

**Issue by obgeneralao** [thexerteproject/xerteonlinetoolkits#757]
Hi,

I can access my workspace from my computer as shown below,

![image](https://user-images.githubusercontent.com/13013814/39755479-938e9180-52f8-11e8-969a-635d810ac79c.png)

But in my ipad and even android device (using different browsers like safari, firefox, chrome, opera), Workspace is missing 

![image](https://user-images.githubusercontent.com/13013814/39755872-03a6defe-52fa-11e8-82b3-32cf29b0e423.png)

Thanks in advance for your help.

**Comment by torinfo** [comment]
On the desktop you use the http version of your installation, on the screenshot of the iPad, you use https

You cannot mix the two. You HAVE to use the url that is configured in the site->url (management.php)

**Comment by obgeneralao** [comment]
Thank you very much, I got it working. 👍
