### ISSUE TITLE
Whole lo stops playing if title page background property empty

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#76]
As reported on the community site a user had been working on an LO which then wouldn't play or preview and it seems having an empty background property on the title page e.g. no path to an image stops the whole lo playing. I think there are other occurrences of this when image fields are empty but thought they just stopped that particular page from playing. Maybe that's the case here too but as it's the first page stopped any of the lo playing.
I guess we need to go though and prevent this somehow as part of the general tity up at some point.

**Comment by JohnSmith-LT** [comment]
I'm going to close this and open a more generic one for code cleanup.
