### ISSUE TITLE
medialesson - More than one medialessons in one learningobject causes race conditions

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#772]
@FayCross 

Hi Fay. 

We have an LO with 6(!) medialessons after each other (It's a webinar with a total length of 3.5 hours, split up in 6 parts). All the medialessons have a panel with quick access buttons (using mcq). Now, when you quickly scroll through the medialessons, until for example the 4th, the buttons of the 1st, 2nd and 3rd end up in the panel as well. This is just because the mcq plugin just sends the buttons to panel #panel2 too late.

Now, I've tackled this by changing the id of the panels and include the pagenumber. So the ids changed from #panel0, #panel1 and #panel2 to #panel_4_0, #panel_4_1 and #panel_4_2 for page 4. So when page 6 is active, and the mcq plugin tries to place the buttons for page 4, it tries to place them in #panel_4_2, which doesn't exist any more at that point in time.

This seems to work fine. Do you agree with this approach, and can you think of some circumstance (with one of the other many options of the medialesson) where this might break things?

**Comment by FayCross** [comment]
I think you're solution should be fine. I'll have a play with it this afternoon (have you committed your code?) and see if I can break it! Thanks
