### ISSUE TITLE
Glossary hover position issue with some new themes

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#774]
The new XOT themes that are centred in the screen (Modern themes) show the glossary word hover bubbles a long way from where the mouse is.

**Comment by ronm123** [comment]
@FayCross well spotted! ;-) Just tested and it's even worse when the full screen button is switched back to default. To my knowledge there's nothing in those themes directly controlling the glossary so I'm guessing its something to do with how the position of the tooltip is calculated? Or a style I've overlooked?

**Comment by FayCross** [comment]
I'll look into it. I'm pretty sure the xenith code for the tooltips just looks at the position of the mouse & offsets it slightly so it's an odd one.
