### ISSUE TITLE
Bug with one of the page types when in an iFrame on Firefox

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#78]
Reported by @pgogy 

![image](https://cloud.githubusercontent.com/assets/3907362/3536925/0ebcff98-0818-11e4-9672-638ef8fcfa13.png)

Possible Fix:

<style>
#pageContents{
position:relative;
top:60px;
}
</style>

**Comment by FayCross** [comment]
Closing as I can't recreate this now
