### ISSUE TITLE
menu connector incorrectly showing nested pages and therefore those links don't work

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#782]
Hi all
I thought I'd already added this as an issue but can't find it so adding again here.
I noticed in a page types project that if I use a menu connector showing all pages then some of the buttons show nested pages e.g. Media - Multiple Perspectives | Video Two shows multiple times. Upon further investigation it's showing the second video regardless of name so if I move video 3 to position 2 then the menu shows Media - Multiple Perspectives | Video Three multiple times.
This may be a consequence/error from when I added the completion ticks to the menu connector but I can't spot where/why.

But also with that tick code there was a problem anyway if only a subset of pages are shown because the tracking of pages viewed is then out of sync.

**Comment by ronm123** [comment]
@FayCross no I didn't fix it and it's still an issue but maybe only for older/existing projects...

Try adding a menu connector at the beginning of an existing page types project do you see the issue then? I do. e.g. I see multiple Audio Slideshow buttons.

However I just quickly created a new projected added a title page a couple of audio slideshow pages and a summary page and then added the menu connector at the beginning and didn't see the issue.

I then duplicated my existing page types project and deleted the audio slideshow page. I then see multiple multiple perspectives buttons. Delete that page type and I see multiple synced video buttons. Delete the synced video page and I see multiple transcript reader buttons. Delete the Transcript reader page and I see multiple accordion navigator buttons. At that point I've stopped deleting pages because the pattern seems clear. I then added a new audio slideshow page and it doesn't show multiple audio slideshow buttons again but still shows multiple accordion navigator buttons. I then moved the existing button navigator up the tree to below the new audio slideshow and it now shows multiple button navigator buttons instead of multiple accordion navigator buttons. So it's creating multiple buttons for the first page type with nested pages that it finds but only existing page types not newly added page types. 

Are you able to reproduce? Does this point to the cause? 

Obviously if it's only an issue for existing projects with pages with children and the menu connector in use then it's less likely to surface for everyone but ideally it should be possible to add menu connectors to existing/older projects without getting this issue.

**Comment by FayCross** [comment]
Yes I can see it in a really old project now, I'll look into it now
