### ISSUE TITLE
Issue with password protected projects that contain links to other password protected projects

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#784]
When password protected projects contain links to other password protected projects you have to login every time you follow a link even though you have already entered your login details.

@torinfo I've commited a fix for this (https://github.com/thexerteproject/xerteonlinetoolkits/commit/400953d39077d1080170e402d9de26fce2d620a8) but as aren't sure if it's a terrible way of doing things. Could you have a look when you get the chance please and see if there's a better way. Thanks

**Comment by torinfo** [comment]
@FayCross Did it a bit different. Just to use the same session variables as we use for normal login processing. Also allows to go into xerte without logging in again, and than allows to logout.

**Comment by FayCross** [comment]
Thanks Tom
