### ISSUE TITLE
use of pageID or linkID in url especially for site/bootstrap projects

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#787]
Hi all
I noticed an issue on the community site download page where we have previously had links to system requirements that pointed to template_id=81#page9 of our release notes resource. However as we have added pages the system requirements are now on page 11 rather than page 9 so those links are now pointing to the wrong page. However just correcting the links to point to page 11 instead is likely to break again in future as we add more pages to the resource. This is obviously a problem that could arise with any other project too. So I thought I should generate a more permanent link to the system requirements page and thought the way to do this would be to add an internal xerte page link, grap the ID from that and then use that as either #pageID=PG1521123214340 or #linkID=PG1521123214340. However neither of those formats seem to work with the site/bootstrap template? I couldn't remember whether I had tested or used the same format with the xot template so tested that and with that #linkID=xyz does work but #pageID=xyz doesn't. So a few questions:

1. Should either #pageID=PG1521123214340 or #linkID=PG1521123214340 work with site/Bootstrap projects in the URL or is there a different format to use so that the link works even if the page is moved?

2. At least with a quick test project #linkID=xyz seems to work with xot projects in that it jumps to the page with that ID but the parameter disappears from the URL should and/or could it remain as part of the URL?

3. Should #pageID=xyz work in the same way? I have old notes that suggest it should/did but that might have been referring to internal page links rather than parameters in the url.

**Comment by FayCross** [comment]
1. Ideally it should work in Bootstrap projects too but I've had a quick look at the code & there doesn't seem to be a way of doing it at the moment (without just using page numbers)

3. I've never known why we have linkID & pageID. What was the original reasoning behind that?

**Comment by FayCross** [comment]
Ha, it's renumbered my comment - no. 2 is an answer to no. 3 (it changes back whenever I edit it!)

**Comment by torinfo** [comment]
The LinkID is automatiaclly generated (and prior to the current editor you had to remember it and type it in to use it) Hence the intruduction of PageID, which you could set with an optional property (and thus, in theory remember easier).

**Comment by JohnSmith-LT** [comment]
Hi. We used to have an optional property to add a custom pageID in XOT but that seems to have been taken out in favour of the linkID which is automatically generated in the editor. Shouldn't we add it back in? (for instances where you wish to for example call page 2 [section1] and page 8 [section2] so that you can link to these externally with #pageID=section2

I seem to remember there being a discussion about this but don't remember the justification for removing these. Plus there is no easy way to see what linkID has been generated by the editor for a particular page other than link to it from another page and then look in the source code. Or hold down shift when you press the Play button (which isn't that intuitive).

**Comment by FayCross** [comment]
@JohnSmith-LT I'd be fine with it being added back in. It may have been me who removed it (if it was I don't remember why).

**Comment by ronm123** [comment]
Just reminded myself of this issue and whether we changed anything following a post on the forums https://www.xerte.org.uk/index.php/nl/forum/general-chat/1743-external-link-to-a-specific-page-in-bootstrap#5837

It would definitely be good to add linkID functionality to (or back to) Bootstrap projects.
