### ISSUE TITLE
Video issue on Safari and Firefox

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#79]
Issue where pressing Esc on fullscreen at end of video doesn't return correct state

Safari - colapse panel
![screen shot 2014-07-09 at 15 31 07](https://cloud.githubusercontent.com/assets/3907362/3537989/b707a684-0828-11e4-8764-3976c2106c4f.png)

Firefox - wrongly scaled video
![screen shot 2014-07-09 at 10 59 53](https://cloud.githubusercontent.com/assets/3907362/3538009/0b4bab28-0829-11e4-96f0-0be49a64e967.png)

**Comment by torinfo** [comment]
Seems to work fine on Firefox on Windows.and Safari on my Mac, so I am closing this one.
