### ISSUE TITLE
Table page csv option - allow semi colon separators

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#791]
Allow csv files used in table pages to accept semi colons as the separators. As requested on the forum
[https://www.xerte.org.uk/index.php?option=com_kunena&view=topic&layout=reply&catid=3&id=1544&mesid=5328&Itemid=759&lang=en](url)

**Comment by JohnSmith-LT** [comment]
@FayCross can you take a look and see if this is enough to solve this and close if you are happy?

I tried to figure out a way to auto-detect by counting but when you take european decimals and quotes into consideration then it becomes far too difficult...

**Comment by FayCross** [comment]
Thanks John - I’ll get back to you about this (& the rest of the issues you’ve asked about!) tomorrow as I’m out of the office at the moment with no access to stuff. Thanks

**Comment by JohnSmith-LT** [comment]
No hurry @FayCross i'm just getting back into it so asking some questions about the other stuff but might not get around to doing anything until Christmas break anyway...

**Comment by FayCross** [comment]
@JohnSmith-LT this works well - thanks. I've grouped the two csv properties together
