### ISSUE TITLE
Inventory language options not correct

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#793]
Hi,

In the inventory page you have in the language options the possibility to edit the submit butoon. But in the inventory page itself this is not used. Shouldn't the submit language option not be depricated?
![2018-09-16_1408](https://user-images.githubusercontent.com/5703781/45596287-3e97ee00-b9ba-11e8-933f-0dd01cc61727.png)

Bye,
Inge

**Comment by FayCross** [comment]
This submit button is used but only if when 'Display Feedback' on a question is on
