### ISSUE TITLE
quiz question text not wrapping in edge browser

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#796]
Issue raised in forum and solution suggested by Neil Pollock

There appears to be an issue in Microsoft Edge with quiz question text not wrapping (so it just appears as a single line which expands the width of the page).

I've found a fix, which is adding "width: 100%" to the legend element. However, I was wondering whether this could be fixed for future releases?

**Comment by JdenHartog** [comment]
Some more details on the quick-fix/workaround ronm123 suggest:

One can add the *Optional Property* **Styles** to the *Learning Object* and paste te follwing code into it:
```javascript
#qTxt {
	width: 100%;
}
```
Hopefully this doesn't mess up the layout of other Xerte pages having a `qTxt` id. I don't know if there are any other then the *Quiz* page.

**Comment by JohnSmith-LT** [comment]
This id field is also used in opinion, inventory and hotspots page.

**Comment by torinfo** [comment]
Yes, but we can add it to the quiz.css Than it will only be used for quiz.
