### ISSUE TITLE
Getting Error in xerte X (git X-v3.7.4-2-g3c75844)

### ISSUE THREAD

**Issue by GaneshKandu** [thexerteproject/xerteonlinetoolkits#798]
Hi

Getting Error in xerte X (git X-v3.7.4-2-g3c75844)

 ``Site Administration``  > ``LTI/Moodle settings. (Not Tsugi/LTI)`` > ``LTI Keys``

```
Error No: 1146 - 0MySQL error Table 'xerte_db.lti_keys' doesn't exist
Query:

#0 {{PATH}}/website_code/php/management/site.php(325): UoN_LTI->get_lti_keys()
#1 {main}
```

**Comment by ronm123** [comment]
Hi
was this an upgrade? If so you need to run upgrade.php.
But also tsugi isn't installed with Xerte you have to add and configure that manually.

**Comment by torinfo** [comment]
This table is the 'old'lti keys configuration in management.php, not Tsugi.

And indeed, if this is an upgrade, please run http(s)://<xerte url>/upgrade.php

**Comment by GaneshKandu** [comment]
its latest install not old
its not upgrade

**Comment by GaneshKandu** [comment]
Its Normal install of latest not upgarde

**Comment by torinfo** [comment]
I just did a fresh install. The error suggests that the table lti_keys does not exist, but as far as I can tell it is created correctly, if I do a clean install. Could you please check your database and database credentials? (the credentials that are used, can be found in database.php.)

**Comment by torinfo** [comment]
Ah.. I'll fix it. Thank you for helping us solving this.

**Comment by GaneshKandu** [comment]
@torinfo  @ronm123
look at https://github.com/thexerteproject/xerteonlinetoolkits/pull/803

**Comment by GaneshKandu** [comment]
i am still getting same issue in xerte online toolkits 3.7.11

**Comment by JohnSmith-LT** [comment]
Hi @GaneshKandu 

I'm just going through some Xerte issues that remain open and wondering if you can confirm the status of this one? I've looked at the code and it was seemingly patched in October 2018 but you replied that it still existed afterwards? Is this still the case?

https://github.com/thexerteproject/xerteonlinetoolkits/blob/1af4da3059fca472a8eede95ea853a3263abc4e2/website_code/php/management/site.php#L322-L325

Please let me know your thoughts and i'll look into it or will close in 10 days.

John

**Comment by GaneshKandu** [comment]
@JohnSmith-LT its working now
