### ISSUE TITLE
Admin panel is not loaded properly in xerte version 3.7.7

### ISSUE THREAD

**Issue by GaneshKandu** [thexerteproject/xerteonlinetoolkits#804]
Hi,

### 1
 i tried manual installation of xerte version 3.7.7 on  PHP 5.3 (with authentication mode db). 
 
 However i am facing an issue while doing so. After installation is complete and when i log inside the admin panel .the admin panel is not loaded properly . This is how it's loaded
 
 ![img_20181029](https://user-images.githubusercontent.com/12833130/47642229-1fca7100-db8e-11e8-8ea4-e6200595b6bd.png)
 
 What could be causing the issue?. Could you replicate this at your side?

### 2

https://github.com/thexerteproject/xerteonlinetoolkits/issues/798 is still in xerte version 3.7.7

**Comment by torinfo** [comment]
@GaneshKandu Regarding Issue 1. No I don't have that issue. Do you have a 'normal' user with the same loginname as the admin user?

@2 yes, we do not patch ALL errors to the relase. So #798 will end up in the next release (thank you for your pull-request).

**Comment by GaneshKandu** [comment]
Hi

i followed this step mentioned on [readme.md](https://github.com/thexerteproject/xerteonlinetoolkits/blob/develop/readme.md#installation-instructions-stable-release-zip)
Installation Instructions (Stable release, .zip)

------------------------------------------------

Here's a quick guide to installing toolkits on your local computer:

 1. Download and install XAMPP from http://www.apachefriends.org/download.php?xampp-win32-1.7.0-installer.exe accepting the default settings;
 2. Download Xerte Online Toolkits from http://xerte.org.uk
 3. Unzip the folder 'xertetoolkits' to c:\xampp\htdocs\, giving you c:\xampp\htdocs\xertetoolkits
 4. Start Apache and MySQL in XAMPP control panel
 5. Visit http://localhost/xertetoolkits/setup
 6. Click the XAMPP button.

Server administrators should choose the 'full install' option and step through the wizard. When copying the files to a server, you can use the setup utility at http://yourserver.com/yourtololkitsfolder/setup

**Comment by obgeneralao** [comment]
@GaneshKandu , I also had the same issue so I had to revert to previous versions of XOT

**Comment by ronm123** [comment]
Hi
I just replicated this and can confirm that it's a bug that has crept into both the Xerte X code and our latest develop code. So we'll look into it further and fix it asap.

However just to clarify - using Xerte with XAMPP is only meant for local development/testing and not for production use. 

HTH
Ron

**Comment by ronm123** [comment]
Hi again
as a temporary fix for this with the latest 3.7.7 and develop code there is a file named auth_confirg.php.dist rename that to auth_config.php e.g. remove the .dist and all should be well?

This was an attempt to prevent an upgrade replacing an already configured auth_config.php but means that a new install doesn't have that file until it is renamed. This is standard practice in many other applications but hasn't been needed in Xerte before now. We'll see if there is another solution but for now renaming the file should fix your issue - please confirm?

**Comment by GaneshKandu** [comment]
@ronm123 Hi renaming ``auth_config.php`` is working
