### ISSUE TITLE
Gap Fill with 2 Fill in Blanks, hangs when going over pages using next/back buttons

### ISSUE THREAD

**Issue by JdenHartog** [thexerteproject/xerteonlinetoolkits#807]
Using XOT 3.7.4 one can reproduce this by:

- creating a new project
- inserting a *Gap Fill*
- duplicate that 2 times
- select the one in the middle
- set Interactivity to *Fill in Blank*
- mark 2 words in Gap Fill Text `Enter interactive |text| |here|.`
- click *Play*
- click *Next* button 2 times
- click *Back* button 2 times
- crash  :collision:

**Comment by JohnSmith-LT** [comment]
@torinfo Can you please check that this doesn't interfere with or somehow change the logic of the tracking code? Error was:

![image](https://user-images.githubusercontent.com/3907362/64920885-629c3400-d7b4-11e9-8476-6090e37c9b79.png)

**Comment by torinfo** [comment]
@JohnSmith-LT That looks perfectly fine. Thanks!
