### ISSUE TITLE
Colour Changer doesn't work when exporting Offline Zip.

### ISSUE THREAD

**Issue by JdenHartog** [thexerteproject/xerteonlinetoolkits#808]
The *Colour Changer* for choosing *Black on Yellow* for example, doesn't work when one exports the project as an *Offline Zip.*
When clicking *Preview* in XOT 3.7.4 the *Colour Changer* works perfectly, but after exporting the project via *Properties* > *Export* > *Get Offline Zip.* checkboxes *Black on Yellow* and *Invert* do nothing. This did work in XOT 3.6.x

**Comment by torinfo** [comment]
This is probably caused by the fact that in 3.7 the coulour changer uses (special) themes to handle the change and these themse are not being exported (I think). I'll have a look.

**Comment by JdenHartog** [comment]
After unsuccessfully searching for those (special) themes in an old XOT 3.6.x *Offline Zip*, I managed to temporarily solve this problem by replacing the file `\offline\offline_colourChanger.js` in the XOT 3.7.4 *Offline Zip* by one from an old XOT 3.6.x *Offline Zip.*

**Comment by JohnSmith-LT** [comment]
I can't reproduce this in the latest develop branch. Has this been fixed? Both development and offline exports work:

![image](https://user-images.githubusercontent.com/3907362/49334324-fb1d4b00-f5ca-11e8-9c1e-f24295a1b1e7.png)

![image](https://user-images.githubusercontent.com/3907362/49334334-1ab47380-f5cb-11e8-97a3-2559df5bcfff.png)

**Comment by torinfo** [comment]
Yes this is fixed (in 974f4f5523bf8ec19f94ab1d3d82829974b1b526)
