### ISSUE TITLE
Gap Fill answer incorrectly becomes red when going over pages using next/back buttons

### ISSUE THREAD

**Issue by JdenHartog** [thexerteproject/xerteonlinetoolkits#810]
Using XOT 3.7.4 one can reproduce this by:
- creating a new project
- inserting a *Gap Fill*
- set Interactivity to *Fill in Blank*
- add Optional Property *Mark at End*
- duplicate *Gap Fill* ones
- select the first and mark the word `|text|`
- select the second and mark the word `|here|`
- click *Play*
- enter "text"
- click *Check* button (text correctly becomes green)
- click *Next* button
- click *Back* button
- click *Next* button
- click *Back* button
- "text" incorrectly becomes red

I think the cause is the same as for issue #807

**Comment by JohnSmith-LT** [comment]
I can no longer reproduce this. Can anyone else reproduce: @fay @ronm123

**Comment by FayCross** [comment]
Yes - I can recreate. You have to go to next page & back twice as described above - the first time you go back to page 1 the text is still green but the second time you go back the text is red.
