### ISSUE TITLE
gapfill feedback and possibly other page types too..

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#814]
Hi all
I had a report that the feedback on gapfill when it is set to drop down doesn't work on Safari or Chrome on MacOS. Specifically the feedback says: "Your correct answers are shown in green. Try again with those you have got wrong." but on MacOS the text in the drop down doesn't turn green so the feedback doesn't make sense. I have just committed a fix for this: https://github.com/thexerteproject/xerteonlinetoolkits/commit/04f2faf6e7ef5bf23d342c2d4af1e440e2ed8551 but in terms of accessibility it's not a good idea to rely on colour alone to provide feedback etc. I guess we could change the default feedback to something like: "Your correct answers are shown in green and/or locked/disabled. Try again with those you have got wrong. E.g. The options that aren’t locked/disabled." But two questions:

1. Is there a better solution to avoid relying on just green colour to show correct answers and better default feedback.
2. Are there other page types or optional modes in page types where we only use a change of colour to indicate feedback rather than ticks and crosses etc?

Thoughts?

**Comment by ronm123** [comment]
Hi all
I was reminded about this today and given the current focus on all things accessibility what do you think about this as a solution for now https://xot.xerte.org.uk/play.php?template_id=116#resume=53 e.g display a dotted box around the correct answers and in the default feedback to make that clearer for anyone who can't see the green clearly? The only problem is the feedback isn't currently separate so I had to add a pan with a relevant class name in the feedback box. Any better way to do this or other comments?

For consistency I added a dotted boredr on the text entry version too https://xot.xerte.org.uk/play.php?template_id=116#resume=54

Shall I add and commit these changes at some point or is there a better way?

**Comment by torinfo** [comment]
@ronm123 As far as I am concerned, this looks good. Only alternative would be to place checkmarks and/or crosses next to the words.  I do not have a preference.

**Comment by FayCross** [comment]
Looks fine to me Ron

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 did this every get committed? I'm not seeing it working for me.

**Comment by ronm123** [comment]
@JohnSmith-LT I don't think I ever committed that. From memory I think I thought if there was a way to add ticks and crosses that looked ok with list menus like @torinfo commented then that would be more consistent with what we do with other interactions.
