### ISSUE TITLE
Urgent - problem with existing multiple choice pages and Xerte X

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#817]
Hi all
I mentioned this to @torinfo by email recently but now it has become clear that it's a difinite issue and potentially affecting lots of existing LO's.

I've had reports from two different organisations about LO's with MC pages. e.g. "sometimes don’t have the Check box, if we do and click check, it doesn’t give us feedback and when you click the forward arrow, it doesn’t go forward - the slide goes blank".

When I look at the console I see an Uncaught Error: Syntax error, unrecognized expression: …

I think I’ve found where the problem lies or at least roughly where it lies.
This was a long existing LO rather than a new LO. I created a new MCQ page in the same LO and populated that with the same text and settings etc and that question worked fine. When I compare the xml of the working mcq page and the faulty mcq page the latter is missing multiWong multiRight singleWrong and singleRight

I’m guessing they were later additions and causing an error with existing pages built with previous versions?

**Comment by FayCross** [comment]
Those bits of info being missing from the xml shouldn't cause a problem as the code checks to see if they are undefined before continuing (see lines 182-185).

Doesn't the error in the console say which line the error is on?

**Comment by ronm123** [comment]
@FayCross just sent you a direct email with a link to a page types example on one of my installations where this is happening too. Here's a link to a quick demo with just the mc page and a plain text page after it. The page in this case was imported from an existing LO rather than created new because if created new all is fine. https://training.mitchellmedia.co.uk/xot/play.php?template_id=347

**Comment by FayCross** [comment]
Could you test this possible fix please @ronm123 ? Thanks

**Comment by ronm123** [comment]
Thanks @FayCross. @torinfo can you pull this into the release asap?

Should we notify users somehow? Potentially there are lots of LO's with faulty MC pages until this fix is applied?

**Comment by ronm123** [comment]
Do we know at what version this would have become an issue?

**Comment by torinfo** [comment]
@ronm123 Done

**Comment by FayCross** [comment]
From 7th September - not sure what version that would be

**Comment by torinfo** [comment]
@ronm123, @FayCross That would be X-v3.7.1.

@ronm123 Yes we apparently did. This is mentioned at the top of the registration form:

> Use this form to register your organisation and installation as part of the official Xerte community.
When you register your site: You are added to a low-volume mailing list for important notifications such as security alerts and new releases of Xerte. Basic info like Organisation name and Country will be added to our publicised list of users worldwide.

**Comment by ronm123** [comment]
@torinfo so how do we post to that list? :-)

and should we post details of bugs like this that we have fixed or wait until people discover them?
