### ISSUE TITLE
language string problem with xerte x code PROJECT_INFO_ACCESS_SET_AS

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#819]
I’ve just done a clean install of Xerte X 3.7.12 and in testing noticed a language string problem where for instance the project I created in the workspace shows as: Access: PROJECT_INFO_ACCESS_SET_AS Private rather than Access: This project is currently set as Private. I checked an earlier Xerte X revision and that has the same problem.

It seems like this is because the line define ("PROJECT_INFO_ACCESS_SET_AS", "is currently set as"); has been removed from /languages/en-GB/website_code/php/properties_library.inc  I checked on gihub and that line is in the develop file but not in the master file.

@torinfo 
How has that happened?
What’s the best way to fix it? I’ve manually added that line back in to the install I’ve just created but I’m assuming it’s all populated via xertetrans but if so then I don't know why master is different to develop?

**Comment by ronm123** [comment]
Quick update - I mentioned checking an earlier Xerte x revision but actually that was also 3.7.12 whereas a 3.7.9 install doesn't have the same problem. So I guess that string got removed between more recent commits.

**Comment by JohnSmith-LT** [comment]
This appears to be fixed.
