### ISSUE TITLE
Admin panel is not loaded properly in xerte version 3.7.13

### ISSUE THREAD

**Issue by GaneshKandu** [thexerteproject/xerteonlinetoolkits#820]
i tried manual installation of xerte version 3.7.13 on  PHP 5.3 (with authentication mode db). 
 
 However i am facing an issue while doing so. After installation is complete and when i log inside the admin panel .the admin panel is not loaded properly . This is how it's loaded
 
 ![img_20181029](https://user-images.githubusercontent.com/12833130/47642229-1fca7100-db8e-11e8-8ea4-e6200595b6bd.png)
 
Renaming ```auth_config.php.dist``` file doesn't working

**Comment by GaneshKandu** [comment]
### Step to reproduce

- install xerte 3.7.13 ( with Authentication method:db )
- after successful install first login will work
- logout and login

second login will give you blank content

**Comment by GaneshKandu** [comment]
Thanks ! seems resolved in new version 3.7.14

**Comment by torinfo** [comment]
Thank you for confirming.
