### ISSUE TITLE
LO not accessible even when access is set to public (develop branch) when Moodle authentication is also used

### ISSUE THREAD

**Issue by obgeneralao** [thexerteproject/xerteonlinetoolkits#822]
Hi,

The current develop branch makes LO inaccessible even when set to public.

**Comment by ronm123** [comment]
You'll have to provide more detail here I can't reproduce this. e.g. I can make LO's public with develop and all works fine.

**Comment by obgeneralao** [comment]
Hi Ron,
I have XOT installed  inside moodle. Accessing the LO would just show a white blank page. So, for now I am stucked on master branch which enables my LO to be accessible to anyone when set as public.

**Comment by ronm123** [comment]
Ok so yes I can replicate this now. To be clear your original issue just referred to "develop branch makes LO inaccessible even when set to public" with no mention of using Moodle for authentication. Public LOs work fine from develop when using guest or db authentication but at the moment there does seem to be a bug when current develop is used together with Moodle for authentication. We'll update this issue once resolved and were already aware of an issue with the LTI integration when Moodle is used for authentication too which @torinfo is looking at. I suspect the two issues may be related.

**Comment by obgeneralao** [comment]
Hi,

Is this issue solved with [2d1f1f8](https://github.com/thexerteproject/xerteonlinetoolkits/commit/2d1f1f851a71e5904f5d53ea4df4ca8251fe0fec)?

**Comment by torinfo** [comment]
No regrettably not, but I will look into this.
