### ISSUE TITLE
Hotspot Image page issues with latest develop code

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#823]
As far as my testing goes it seems the hotspot image page is now broken for existing projects as well as not working fully in new projects. Here's some quick notes from my tests:

highlight hotpots doesn't show hotspots like it did previously
click explore only allows selection of first hotspot not any and all hotspots like it did previously
show me doesn't work as it did - now shows each question in turn but then waits for user interaction to click next and then click hotspot and doesn't allow re-selection of previous hotspots
now seems to be based on a question per hotspot without an option to just use original behaviour
question and feedback is shown above and below the image and the feedback is not shown in left panel as it was before
it seems we now can't drag to move hotspots when editing/adding them
users can no longer tab to hotspots using the keyboard this seems to have broken the accessibility

Not a bug but authors ideally need an option to set image size if only small, medium, large, full etc

**Comment by torinfo** [comment]
I addressed these concerns, and also the concerns mentioned in #824 

- I created a new hotspot editor 
- hotspot connector and hotspot image support flexible hotspots and rotated rectangles
- annotated diagram and drag drop hotspots are limited to rectangles

When you edit existing hotspots in hotspot image, these are restricted to ractangles. Creaet a new hotspot to create a flexible hotspot

Questions:
 - There is some help text below the image. Are these adequate? Sensible and correct English?
 - I introduced a 'Reset' icon, to restart drawing a polygon (or rectangle). Is the icon crear enough, and is the term 'Reset'clear enough.
