### ISSUE TITLE
Multiple perspectives and video pages not playing YouTube clips in Firefox and IE

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#829]
Hi all
I'm not sure if this is a new issue or just not noticed or reported but it was reported on the forums that the multiple perspectives page doesn't work in Firefox or IE but works ok in Chrome and Edge. I investigated and it seems Firefox is giving an error of: Specified "type" attribute of "video/youtube" is not supported.

Searching for that error reveals some old stuff about media elements and mime types etc but I'm wondering if recent browser changes or Flash changes or YouTube changes have now meant this is broken. Obviously embed code from YouTube works in any of our pages but it seems the page types where we have an upload link and our own player window is now broken in Firefox and IE at least when YouTube links are used. A vimeo link in the multiple perspectives and video page still seems to work fine so perhaps the problem is a change at the YouTube end?

**Comment by FayCross** [comment]
I've just tried the newest version of the mediaelement.js and this fixes this issue. I'll check it doesn't break anything else & update if it all seems ok
