### ISSUE TITLE
Strange issue with Bootstrap project template when using Edge browser

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#836]
Hi all
I was delivering some training yesterday and a strange issue came to light (Bootstrap and Edge) that I wasn't aware of and haven't noticed before but can replicate consistently across different laptops etc.

When creating a Bootstrap project using Edge browser it seems some features work but others don't. e.g. using edge add a section and new text element to a Bootstrap project and try changing the title text of the section and text element including play/publish to see those changes. It seems changes like that don't currently work in Edge? I can successfully add text to the Text box but not to the Title field. I can add an image or navigator but not change the title field in either.

![image](https://user-images.githubusercontent.com/5167146/57769176-2d4be080-7705-11e9-9936-d22fb97e24a8.png)

This is using the current download so v3.7.14 but at this point I'm not sure if this has been an issue in previous versions too.

BTW I can't see any similar issues with the XOT template so this seems to be some kind of issue with Edge and the Bootstrap template.

@FayCross @juliantenney @JohnSmith-LT @torinfo can you replicate this?

It looks like this may be the relevant error:
![image](https://user-images.githubusercontent.com/5167146/57769209-3dfc5680-7705-11e9-90e9-b97a48e18979.png)

**Comment by juliantenney** [comment]
I'm in a different office at the moment and don't have a machine with Edge, but will test when I get to one that does,


Julian


________________________________

**Comment by FayCross** [comment]
I can recreate if I am using current develop code but it works ok on Uon install (3.7). The error above doesn't appear when on our install so that seems to be the problem

**Comment by FayCross** [comment]
Sorry - UoN install where it works is 3.6 not 3.7

**Comment by FayCross** [comment]
@ronm123 possible fix - try removing '1' from the beginning of modules/site/edithtml.php file
That fixes it for me but I don't know why that's there to begin with

**Comment by ronm123** [comment]
@FayCross well spotted! ;-) Yes removing that fixes it for me too. That 1 has to be an error inadvertently left over from someone editing that file. Seems bizarre that it was only affecting Edge and only title fields too.

**Comment by ronm123** [comment]
Removed the 1 and committed the change to develop so closing the issue. Thanks @FayCross
