### ISSUE TITLE
Gap fill drop down menu - option to choose sorting method

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#837]
Request from [forum](https://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=18&id=1699&Itemid=759&lang=en#5721)

Instead of always just sorting drop down items alphabetically have the option to randomly sort them too

**Comment by JohnSmith-LT** [comment]
Hi @FayCross 

Can you check this meets the need and close?

**Comment by FayCross** [comment]
Thanks @JohnSmith-LT
