### ISSUE TITLE
mediaelements playbar issues Bootstrap template

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#841]
Hi all
I'm adding this here but I'm sure it has cropped up before. At the moment in Bootstrap projects where audio or video has been added directly it uses the mediaelements library and as far as my testing indicates there is a problem with the playbar in Chrome and Opera but seems fine in Firefox, Edge and even IE. Two problems as far as my testing goes:
1. The volume control sometimes wraps to below the player (see screenshot)
2. A similar issue with the video player that the fullscreen button doesn't show in Chrome and Opera (see screenshot)
I've tested this with a new version of mediaelements (4.2.10.3) and the issue seems to be resolved. However I think @torinfo is keen to switch to using Popcorn instead of mediaelements so I'm not sure if we should update media elements in the meantime or look at switching instead? I'm also not sure how mediaelements is used in different places and whether there might be an issue upgrading it. @FayCross any thoughts on that? As far as my testing goes I can't see any issues with an updated version for the bootstrap template which is where this issue occurs. Not sure about the other templates?

Here's the screenshot:
![image](https://user-images.githubusercontent.com/5167146/59848672-a3271580-935d-11e9-8500-68270d3e1cb0.png)

and you should be able to see this in Chrome and Opera via https://xot.xerte.org.uk/play.php?template_id=137#page2section3

**Comment by FayCross** [comment]
Argh, I didn't know anyone wanted to move to use popcorn instead of mediaelement - I've nearly finished a big bit of work updating mediaelement on all the templates & improving the way media generally shows (making sure it's properly responsive on all pages which it wasn't always). It's taken a while as I've tried to also fix lots of minor bugs or odd things in the media pages as I've gone along but it's nearly ready to commit now. Can you leave updating mediaelement.js in bootstrap template for now Ron as it'll be done when I commit my stuff soon. Thanks

**Comment by ronm123** [comment]
@FayCross sorry I might be wrong about what @torinfo was thinking anyway and possibly we need to be more specific about which templates or even page types too. I was just testing how the bug with the rail/volume/full screen video button could be fixed and it is with a newer version of mediaelement. Has your work been with the newer version anyway Fay?

I know @torinfo is planning to send out a doodle or just a Google doc or something to assess availability for an online dev meeting and so hopefully we can find common availability to discuss things like this and a schedule for the next release.

**Comment by FayCross** [comment]
Yes I'm using new version of mediaelement

**Comment by torinfo** [comment]
@FayCross, @ronm123 I was certainly not planning to change over for this releas. The main reason for the change would be:
 - Consitency and one player to keep working with all the kinds of media
 - Tracking only needs to be implemented in one of the players and is already implemented in popcorn.

But like I said, not before this release.
