### ISSUE TITLE
Issues with emails sent when shared projects become available for editing

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#842]
Earlier I tried to edit a project that was already being edited by a colleague. Later I received an email containing this text:

'You've requested to be informed when the file "Statistics 2019" becomes available for editing. The file was made available at 03:35 pm on Wednesday, 3rd July'...

I didn't request to be informed of this though. In fact there doesn't seem to be an option to request an email - the only thing that you are asked when you view a project that's locked is whether you want to delete the lock file.

I also think (from quick look at code) that if you've tried to edit locked project more than once then you'll receive multiple emails when it becomes unlocked.

**Comment by torinfo** [comment]
@FayCross Yes, and this functionality has not changed for the last 10 years or so.
I don't even know if you can disable the notifications, but if the e-mail domain is entered in the management page, and your e-mail happens to be username@domain, than you will receive these notifications.
