### ISSUE TITLE
File path issue for swf files added via wysiwyg toolbar

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#844]
If you add a swf file to a project using the Flash button on the toolbar the file path is in this format in source view: "https://www.nottingham.ac.uk/toolkits/USER-FILES/11111-aaaa-site/media/flash.swf"

When previewed the swf doesn't show as the file path changes to: "FileLocation + 'media/flash.swf'"

You can get around this by manually adjusting path in source view to be in this format: "USER-FILES/11111-aaaa-site/media/flash.swf"

I know that we shouldn't be using swf but there are still some animations being used here that haven't been converted to another format!

**Comment by JohnSmith-LT** [comment]
Hi Fay,

Is this fixed from the editor update? I can't reproduce... I uploaded a sample swf file from online, using the flash button on the ckeditor and in editor mode I see this:

![image](https://user-images.githubusercontent.com/3907362/64918472-7b95ec80-d796-11e9-9654-c7d0b4bf3382.png)


but in preview mode I see this:

![image](https://user-images.githubusercontent.com/3907362/64918459-60c37800-d796-11e9-917b-fa14e4e6cc4a.png)

**Comment by FayCross** [comment]
I can't recreate now either
