### ISSUE TITLE
Firefox - changing page when swapping to fill screen

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#846]
To recreate:
- Create a project with 2 pages & set display mode to fixed size
- Preview & click forwards to 2nd page
- Click button to make it fill screen... the project will also automatically go back to page 1

It only seems to be happening in Firefox & seems to be related to enabling repsonsive.css

The x_continueSetUp1 function should only be called when css loads on first viewing the project but in FF it's being called when the css is enabled too (it's initially loaded & then disabled until you click button to make full screen) I have no idea why & haven't managed to fix it. Calling this function again causes a knock on effect of lots of other things happening including moving back 1 page.

Anyone got any ideas?

**Comment by JohnSmith-LT** [comment]
Hi @FayCross 

This is a very weird one indeed. I narrowed it down to these line. If you set the following breakpoints in xenith.js

![image](https://user-images.githubusercontent.com/3907362/65394049-9eb93100-dd80-11e9-8b26-d7c97b4b0d79.png)

and then follow your instructions to recreate then when you click the maximise button you land at 3205. then if you step through each of the breakpoints then when you leave the line:

`$(x_responsive[i]).prop("disabled", false);`

In Chrome you see the font change in the page title but it stays with the title for the second page. In Firefox however the font changes but the text also changes to the text from Page 1 and the page indicator changes to 1/2...

I can only assume that some event is firing but not sure where or why it is only doing so in Firefox...

**Comment by FayCross** [comment]
@JohnSmith-LT yes it's to do with the disabled attribute being removed from the responsive css style tag. The x_continueSetUp1 function is called when the responsive css file has finished loading (when project 1st viewed). The problem is that this css file is enabled/disabled when swapping between full screen/fixed size & FF seems to also trigger the event that says the css file has loaded when it swaps from disabled to enabled (so when fill screen button clicked). This doesn't happen in other browsers. I've tried just ensuring that everything in x_continueSetUp1 will only run once & this stops it changing page but the layout of the page then goes wrong:

![firefox](https://user-images.githubusercontent.com/8926470/65590331-831d7880-df82-11e9-8a6b-24aedaf3a150.PNG)

**Comment by JohnSmith-LT** [comment]
I'm assuming that you tested it on Windows too but it does the same on a Mac in Firefox. It's a strange one to trace...

Maybe when the button is clicked we set a flag and test the flag setting in x_continueSetUp1 or in the  css.onload event. Or if the event should only fire once then we remove the event at the end of the event code so that it isn't called again...

I'm sure there must be a better way to do all this as that whole load procedure has gotten a bit fragmented - do we need to do the relevant sizing after each css file loads or could we just load them all and then move on once they are all loaded?

**Comment by FayCross** [comment]
Yeah I think you're right that it needs looking at generally as it's a bit messy at the moment. I tried adding the flag to x_continueSetUp1 & that fixed this issue but caused it to look like the screenshot above.
