### ISSUE TITLE
Xerte SCORM Package in Moodle not resuming

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#847]
Ron emailed as a reaction to a forumpost:

Did you see the post on the forums about Xerte SCORM objects not resuming in Moodle and my response? Before I responded to say resuming does work I quickly reminded myself by checking some previous tests and sure enough they resume to the page I last viewed if not completed. However I did some further testing this morning and it seems something with that functionality has become broken. I’m not sure what version/revision whatever the bug is has crept in but here’s a summary of what I have found so far:
   

1.     I had a test file in Moodle that does resume but I don’t know what Xerte version I exported that from.
2.     Newer test files exported from develop and imported into Moodle don’t resume.
3.     I imported the older LO that did resume back into develop and re-exported that and then imported into Moodle and it then didn’t resume.
4.     I replaced xttracking_scorm1.2.js in that new export that didn’t work with the xttracking_scorm1.2.js from the older copy and then imported into Moodle and that does then resume.

**Comment by torinfo** [comment]
It's more complicated than that....

The problem is taht the (new) state has contains more data, and now is too long for SCORM 1.2. SCORM 1.2 only supports strings of max length 4k. So ... back to the drawing board.

SCORM 2004 should work because the limit there is 64k.

I am looking into
 - compression
 - Not storing the whole state

**Comment by torinfo** [comment]
I minimized the data stored for 1.2 and that seems to work. 

Although now the suspend data is stored, it was missing the currentpageid.
Also SCORM 2004 3rd Ed was missing the currentpageid. Fixed that as well.

**Comment by ronm123** [comment]
@torinfo my test projects re-exported as 1.2 and 2004 now work with these changes. Do we know what Xerte version/revision this previously stopped working?
