### ISSUE TITLE
Misc menu doesn't show page types at top of the list

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#85]
Have tested this with two different installations and using 2 different browsers.

Selecting any of the insert menus seem to work fine apart from the Misc menu. If I select the Misc menu the top 3 items are not showing and will not scroll up using the mouse scroll wheel. I can use the keyboard up arrow to select the page types at the top of the list but this is guesswork because you can't see what is selected. It looks like it's Flickr, Delicious and QR Code which don't show - see screenshot below:

![misc_menu_issue](https://cloud.githubusercontent.com/assets/5167146/4701021/004fe4a2-5854-11e4-9237-e71ce2b38c85.png)

**Comment by FayCross** [comment]
Fixed with new insert page menu
