### ISSUE TITLE
Import Decision Tree templates bug

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#854]
When importing a decision tree template project it is changed it into a xot template project so won't load editor or play

**Comment by torinfo** [comment]
I've seen this happening with old decision tree projects. Not with newly created ones.

It does NOT matter that the install is recent, it only matters when the LO was created. The learningObject node of template.xml in the zip file misses the targetFolder="decision" attribute.

**Comment by FayCross** [comment]
Ok, that makes sense - it was the very first decision tree project made that I was trying to do this with. Would it be possible to add the targetFolder attribute to the xml when exported if it's not there? I realise there are probably very few projects this would affect though

**Comment by JohnSmith-LT** [comment]
Hi @FayCross & @torinfo & @ronm123 

I've made an attempt to recognise imports of old projects created before the targetFolder attribute is present, by looking at the attributes present on the learningObject tag and calculating a probability. This was an export of a Decision tree LO where I exported it, took out the targetFolder attribute and re-imported and it went back in as a Decision tree. Scores were as follows (highest wins):

![image](https://user-images.githubusercontent.com/3907362/69388637-7fc41600-0cc1-11ea-9d74-8f5814ecf1f1.png)

I know it's not going to be perfect and i'm not even sure I have the correct attributes to match older projects yet but what do you think? Useful?

I think the next step would be to make sure if that attribute is missing from an LO that we insert it before saving again.

**Comment by JohnSmith-LT** [comment]
To do: 

- Identify the correct/best set of attributes that were present before targetFolder was introduced
- Perhaps reduce the score based on attributes that are present that are never present in other models
- Look at processing child tags and attributes and performing same correct/wrong processing above
- Pull attributes from xwd files although these will have evolved since targetFolder was introduced so this may not be feasible.
- Perhaps make the weighting non-linear since decision has many attributes but default bootstrap only has 3

**Comment by FayCross** [comment]
This looks good John. I thought it would be easier to add the attribute on export but if this is way works then that's good too. I don't suppose there are lots of people out there who have lots of old exported projects that they are likely to import to be honest - I don't think anyone outside us few have ever reported this issue anyway!

**Comment by JohnSmith-LT** [comment]
Cool. I've left notes about possible improvements to the detection but might not put a lot of effort into implementing them - what I did was easy to do so i'll probably just close this after @torinfo has a chance to comment in case i'm doing something seriously wrong.

**Comment by torinfo** [comment]
@JohnSmith-LT No comment, I am happy to go with it as is :-)
