### ISSUE TITLE
links added to text area content on the hyperlinks page do not display

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#859]
Hi all
I was looking at an issue reported to me directly and that was noticed on the Future Teacher project  that hyperlinks added via the URL option in the wizard on this page can end up displaying over the top of textarea content see an example here https://learningapps.co.uk/futureteacher/play_112#resume=20 

I think someone must have worked on that because in my latest develop that same page displays the link at the bottom of the text area content so that's good. However I know this page only existed originally because of the limitations of the Flash Player at the time not being able to tab to hyperlinks within the text content so this page was added to make a page of hyperlinks accessible. However looking at this now I was going to suggest to the person who reported the issue to leave the URL box empty and add hyperlinks to the text area itself which then means you have control over where the link(s) show and the length of the text vs the length of the actual url. 

So what's the issue? Well maybe I have forgotten about the reason for this, or possibly never tried it, but it seems any hyperlinks added to the text area content are not actually displayed. They don't appear to be stripped out but they simply don't display. Perhaps again that dates back to the Flash Player days or maintaining backwards compatibility but if that is the case we should change the text area to a text only box without the editor toolbar or somehow enable any links added that way to show without breaking any existing projects etc?

**Comment by FayCross** [comment]
I've partially fixed this so that the links in text aren't removed.

Current develop still has the issue with the images overlapping the borders & link though. For me the first time I view the page it overlaps but then if I refresh it's fine. It's because the height of each link block is set to match the tallest in the row & this is calculated as soon as the page loads (before the images have loaded properly). So when I view again & images are in cache it's loading them quicker & their height is taken into account.

**Comment by FayCross** [comment]
There's probably a better way of doing this layout now anyway without having to fix the height of the blocks - I'll look into it

**Comment by ronm123** [comment]
Thanks @FayCross I can see that links in the text are showing now. 
I've just added a tooltip attached to the URL field to say that this can be left blank and links added to the text area instead. 

BTW I was going to explain that the exception would be if your project is still using the old Flash engine but after viewing my test page with &engine-flash its seems the display of the page is all messed up anyway so not much point in adding that caveat. Given that browsers like Chrome are going to be dropping Flash compatibility altogether I guess it's not something we should worry about. In fact viewing a page types demo with &engine=flash we obviously have a lot of pages that no longer work via the Flash engine.
