### ISSUE TITLE
Scrollbar missing in Safari on ipad

### ISSUE THREAD

**Issue by obgeneralao** [thexerteproject/xerteonlinetoolkits#865]
Hi,

When I play the XOT in Google Chrome in a windows laptop, I can see the scrollbar.

![Scrollbar](https://user-images.githubusercontent.com/13013814/67958500-3a687780-fc32-11e9-9a4c-5b0bd22cf187.png)

But when I played it in Safari on my ipad, the scrollbar is missing.

![Scrollbar_2](https://user-images.githubusercontent.com/13013814/67958557-54a25580-fc32-11e9-8ef6-83fb2c01331e.png)

**Comment by ronm123** [comment]
Hi
This is just the way iOS hides scrollbars by default as part of its UX design. If you use your finger to scroll the page the page and/or the tabbed content panel should still scroll if scrolling is needed e.g. if the content exceeds the height of the page or panel. If you view a scrolling webpage you'll see the same unless that webpage has css to change the default behaviour.

If you really want to force scrollbars to show you could add an optional styles property and then something like the following:
`::-webkit-scrollbar {
    -webkit-appearance: none;
    width: 10px;
    height: 10px;
}
::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background-color: rgba(0,0,0,.5);
    -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
}`
If you search around you'll find similar variants of this of if you know css you can change it however you want.
I'm going to close the issue but you can reopen it again if you think this doesn't answer your question.
