### ISSUE TITLE
Export time-out issue

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#872]
I've noticed some projects where there are multiple unnecessary folders / files that are created in the user-files folder. I think this happens when the export of the project fails (e.g. times out because of the size of the media folder).

Is there a way to avoid this happening?

![export_fail](https://user-images.githubusercontent.com/8926470/71988929-a7971b00-3228-11ea-826c-6791f00104ac.PNG)

Also, it would be useful to have a message appear to user when export fails as it's not obvious what's happened otherwise - particularly because export often takes a while anyway

**Comment by torinfo** [comment]
It is caused by the fact that the export routine builds the whole structure of the zip file in the USER-FILES folder.

After a successfull export all those files are cleared again, but when something goes wrong, than the cleanup does not take place.

I'll have a look
