### ISSUE TITLE
upgrade font awesome across all project templates?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#877]
Adding this as a point of discussion for the next developer day.
I received a question about the Font Awesome version available in Xerte and effectively a wish for 5.x. I can see that we have a 5.x folder in the XOT project template files but not Bootstrap or Decision and I think it's still 4.3 in the editor.

**Comment by FayCross** [comment]
We seem to have a lot of different versions of font awesome in different places. Regardless of whether we update I think they need to be tidied up

**Comment by JohnSmith-LT** [comment]
Often wondered whether we should have a root/libraries folder and put single versions of all these things in there: jquery, bootstrap, fa, etc and then we update them in one place. We may share things between the engines in some cases but we at the very least have different versions between the editor and engines...

**Comment by FayCross** [comment]
@torinfo can this be closed now you've included FA 6 in 3.13?

**Comment by torinfo** [comment]
@FayCross yes it can.
