### ISSUE TITLE
Bootstrap upgrade

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#878]
We've discussed this before but as I've been asked about this again worth discussing on the developer day.
Can/Should we upgrade the bootstrap version in the bootstrap template and/or add a new upgraded Bootstrap template?

**Comment by FayCross** [comment]
Yes we should - but it's very time consuming to do. I started looking at it on last developer day but didn't get very far

**Comment by FayCross** [comment]
Close as duplicate of #469
