### ISSUE TITLE
"Insert Page" dialog is badly sized

### ISSUE THREAD

**Issue by usernamenumber** [thexerteproject/xerteonlinetoolkits#88]
The default size of the Insert Page dialog doesn't fit many of the menus, despite taking up much less vertical space than it could. The attached screenshot represents what I see in Chrome, Firefox, and Safari (OSX 10.9.5).

Setting the height of this div to, say, 70% instead of auto would give it enough room to fit all of its submenus without overlapping the bottom of the editing interface.

![screen shot 2014-11-03 at 11 51 53 am](https://cloud.githubusercontent.com/assets/188349/4886295/23dadb16-637b-11e4-93e9-7a42d7e11d8d.png)

**Comment by FayCross** [comment]
Fixed with new insert page menu
