### ISSUE TITLE
Issue with Xerte RSS feeds and the Xerte RSS Feed page type

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#880]
Hi all
I've been alerted to an issue with the Xerte RSS Feed page type when used with Xerte feeds and I suspect this happened when we added the RSS Xerte Download Feed page and related functionality but somehow we missed it.
Currently the Misc > RSS Feed page displays normal feeds like BBC news e.g. http://feeds.bbci.co.uk/news/world/rss.xml but not feeds from a Xerte install e.g. https://xot.xerte.org.uk/rss.php 
The Misc > RSS Xerte Download Feed page does display the Xerte feed and if you view a Xerte feed like https://xot.xerte.org.uk/rss.php  via your browser or another feed reader that works too.
Here's a demo of this to which you all have access https://xot.xerte.org.uk/play.php?template_id=194

I'm guessing the issue lies with either the RSS Feed page model or else the proxy code and I'm guessing it's the latter. @torinfo I know you added the new proxy code so any ideas re cause/solution?

**Comment by torinfo** [comment]
@ronm123 It's caused by the page model. This page model uses a intermediate service to get the rss feed data into a json file, and that service doesn't support the extra items we included in the Xerte feeds, i.e. the service is not standards complient.

We should deprecate the original rss in my opinion.

**Comment by ronm123** [comment]
@torinfo I thought the extra items were added in a way so as not to impact other things. I can't remember what version/revision we added this but if it was the initial 3.8 then any installs using that currently have broken rss pages if they have Xerte feeds added to them. I know that's a few if's but there's obviously a big difference between deprecating for future proofing and deprecating because it's currently broken. Is there a way we can get both working in the short term?

**Comment by torinfo** [comment]
@ronm123 Yes we should be able to fix it by just using the rss download version.

I'll have a look.

**Comment by torinfo** [comment]
@ronm123 I thought we tried to avoid using the extra items (which are standards compliant) when we detect that rss.php is used. Apparently we do not properly detect when rss.php ise being used.

**Comment by ronm123** [comment]
@torinfo sometimes things seem stupid with the benefit of hindsight e.g. I'm sure we checked everything was ok with the new page type but clearly we didn't check properly with the standard rss feed page :-(

**Comment by ronm123** [comment]
@torinfo I think this is fixed now so I'll close the issue.
I removed all the optional properties but left a few bits in that are usually empty and so not used but thought we might want to add to the Xerte rss in future. Anyway at some point please check in case there are any issues but seems to work fine.
