### ISSUE TITLE
Files missing from SCORM media folder - space vs. underscore issue?

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#891]
I've come across a project where the SCORM export is missing some of the media files that are used in it. The images show correctly in the editor & preview but when you view the project properties the images say not used against them (which I assume is why they aren't included in the export)

I have worked out that it's likely that the original image files that were uploaded to the project contained spaces in their names. The elFinder media browser we use converts any spaces in file names to underscores & this has indeed happened in this case (see screen shots below). The problem is that the file path it has added in the URL field still the original file path so uses the HTML space code %20 instead of underscores. The browser seems to cope with this in preview (even though the image tag's src uses %20 & the actual file now contains _) and shows the image ok.

I can't work out how this has happened - if I try uploading files containing spaces then they are converted to _ in URL field too. Has anyone come across this before?

![file_issues](https://user-images.githubusercontent.com/8926470/75553356-27bf4d00-5a30-11ea-9c34-5853bffca97d.png)

**Comment by ronm123** [comment]
@FayCross is it possible that the files were uploaded via media and quota rather than the elFinder? If you upload files that way the spaces aren't replaced. Or is the project quite old and the files were uploaded via an older version of elFinder? I'm not sure it always automatically replaced spaces. I just did some quick tests with develop and on export even files that are reported as unused and have spaces in file names are still part of the export. That said I'm testing via xampp on windows so I guess in could be different via linux.

**Comment by ronm123** [comment]
@FayCross tested again via linux and a 3.8.4 install and same results e.g. uploaded media via media and quota with spaces in file name, used one of those in a graphics and sound page, two others unused but are still part of the export.

**Comment by FayCross** [comment]
Hmm, you're right. I've just tested with a copy of the project & it's fine. To be honest I noticed the 'not used' thing in the media list and the space/underscore difference and assumed that was why it didn't work for them. Is there any other reason why files might be missed out of an export? I've had occasions where exports fail because it times out with large media files but then it fails to download anything rather than creating an incomplete zip. Odd

Re. uploading via the media browser (even if it's unrelated to the zip problem) should we force files uploaded via media browser to convert spaces to underscore too? I've just played around & you can end up with some odd situations. e.g. 

1. upload image via media browser (space remains in name)
2. add to page via elFinder (file path comes back including %20)
3. open elFinder again & re-upload the file (original version is overridden but then it renames it to include underscores). Unless you double click the file in elFinder after upload the path in the wizard keeps the %20.
4. upload the image again via media browser and it won't override the version you uploaded via elFinder so you end up with two versions of what's essentially the same file (e.g. 'my photo.jpg' & my_photo.jpg)
