### ISSUE TITLE
Refactor Xenith engine code

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#898]
Xenith engine has got rather huge and spaghetti like and it's really hard for me to follow (having not been around the code for a while) so it must be impossible for anyone new coming in and it's only going to get more difficult for us to support unless we try and modernise it, group related code and refactor. It is getting on 8 years old now!

Anyway, i've run this past @FayCross a while ago but didn't have the time to implement any of it but with this self-isolation  thing i've got all the time in the world!!

To start i'm going to refactor:

- Variables code (that's a good 600 lines alone)
- Glossary
- Menu 
- Dialog

I'll leave them in xenith.js for now (xenith will get bigger just now but will eventually have the code blocks separated out to separate files) but I also have a loader which can load on the fly each of the blocks, when needed, but need to work on that to make sure it works offline and in scorm. 

I know there are probably other bugs and developments that need done but i'm hope this refactor will reduce the complication of tracing and fixing those issues. 

I've done VARIABLES and it's working fine as far as I can see. So i'll start committing them as separate commits and tag this issue so we can keep track of them.

Hope you guys are all safe!

**Comment by FayCross** [comment]
@JohnSmith-LT If you go back to a page you've previously viewed you now get some console errors that I think are caused by these commits. xenith.js line 3770: list is not defined

**Comment by JohnSmith-LT** [comment]
Thanks @FayCross , does that fix it for you?

**Comment by FayCross** [comment]
Yes - thanks

**Comment by FayCross** [comment]
I've just committed a change to Bootstrap template that allows variables to be used in that template. I've just copied the code from the xenith & tweaked a few things so it's also using your refactored version of doing this @JohnSmith-LT

**Comment by JohnSmith-LT** [comment]
I'm going to close this because refactoring of any more of xenith is going to be scapped I think. I think if this is going to go ahead then it probably needs to come from the ground up and be OO right from the start and i'm not 100% sure now that this is the correct mudule pattern to use  - perhaps using classes and compiling back to ES5...
