### ISSUE TITLE
Problem with Database Passwords during Setup

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#900]
Hi @torinfo , @ronm123 

Wonder if you've come across this issue before. I was in the process of setting up Xerte on a subdomain of a new site i'm creating and everything was going smoothly until I got to Page 4. I had already setup a MySQL database and had used LastPass to generate a 30 character password, as I normally do, with all characters turned on a-zA-Z0-9$_ etc

When I got to Page 4, only the Xerte header loaded and nothing else and the subdomain URL kept redirecting back to /setup since it wasn't finishing.

Eventually I traced that page4.php was giving a 500 server error so I got error logging turned on and found the error log file and saw this (i've changed or redacted some of the personal data):

`[17-Apr-2020 19:33:39 UTC] PHP Notice:  Undefined variable: d8cBRF in /home/xxxxxxxxxx/domains/mydomain.com/public_html/xot/database.php on line 29
[17-Apr-2020 19:33:39 UTC] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on boolean in /home/xxxxxxxxxx/domains/mydomain.com/public_html/xot/website_code/php/database_library.php:126
Stack trace:
#0 /home/xxxxxxxxxx/domains/mydomain.com/public_html/xot/setup/page4.php(41): db_query('SELECT * FROM s...')
#1 {main}
  thrown in /home/xxxxxxxxxx/domains/mydomain.com/public_html/xot/website_code/php/database_library.php on line 126`

Initially I went on github and search for variable d8cBRF and couldn't find it. Then I downloaded database.php and looked at it. It turns out that LastPass had generated me a password like  `xxxxxxxxxxxxxxxxxx$d8cBRF`

The line:

`$xerte_toolkits_site->database_password ="xxxxxxxxxxxxxxxxxx$d8cBRF"`

was then trying to substitute the value of a variable called `$d8cBRF` into the string and not finding it so throwing an error...

Obviously i've changed the password now and it all works but my question is, should we patch this to allow $ (which is a valid password character) or should we add a message to say what characters are allowed and a check to prevent $ being entered in the database password field?

John

**Comment by torinfo** [comment]
@JohnSmith-LT I am surprised we did not run into this before!

Should be as simple as to replace the " (double quote) by a ' (single quote).

**Comment by JohnSmith-LT** [comment]
Yes @torinfo i'm very surprised it's never happened before...

It's an easy fix as you say but I just wonder if allowing it here could cause other problems down the line. I'm going to be setting up another subdomain for testing anyway so i'll make some changes to single quotes before I set it up and see what happens.

**Comment by torinfo** [comment]
@JohnSmith-LT It should not :-)

But better safe than sorry. The only place where the password should be used is in /website_code/php/database_library.php in db_connect. database.php itself is included in config.php.
