### ISSUE TITLE
Bootstrap image path issues & 404 errors

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#906]
When you add an image to a Bootstrap project via the WYSIWYG toolbar the images display correctly but you also get a 404 error in the console for each image. The path in the console suggests that initially the image attempts to load when including 'FileLocation + fileName.jpg' rather than after the correct URL has been evaluated. Try this project in Chrome & you'll see the error in console: [https://xot.xerte.org.uk/play.php?template_id=207](https://xot.xerte.org.uk/play.php?template_id=207)

In projects where you have a lot of images added in this way you get loads of 404 errors! Has it always been this way? I find it hard to believe I haven't noticed before

**Comment by FayCross** [comment]
Actually if you follow that link it doesn't seem to show the 404s when you first view - you may have to refresh before you see them

**Comment by ronm123** [comment]
@FayCross well spotted! I'm just about to join a meeting so can't test further at the moment but I checked a few versions/revisions and at least with a quick glance it looks like it's a recent issue e.g.

the example with the issue that you linked to on xot.xerte is 3.8.5-13
the same issue exists in develop and also 3.8.5-23
However I tested on a 3.8.5 install and the issue doesn't seem to exist on that version.
So it looks like it's an issue that got added after the original 3.8.5 release and is part of the later updates.

@torinfo @JohnSmith-LT any ideas?

**Comment by FayCross** [comment]
We're on 3.7 here & have 404s appearing in console. It's odd though - I have some older projects with images added via the wysiwyg toolbar where you don't get the 404s, even though looking at the underlying xml I can't see anything obviously different between them.
