### ISSUE TITLE
Flashcard flip button not working on MacOS Safari

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#910]
I received a report that the flash card page doesn't work on Safari on MacOS and specifically the flip button doesn't trigger flipping the cards. I tested this and can replicate the issue but I can't spot why it's an issue. @FayCross does this ring any bells with you?...

As far as my testing goes this works on Safari on iOS but not on Safari on MacOS. It works fine on Chrome and Firefox on MacOS so it appears to be a Safari specific issue on MacOS. I'm not sure if the MacOS version or Safari version makes a difference but I'm aware that this doesn't work on at least two different combinations.

If I inspect the flipBtn I see a couple of different styles which if either is disabled enables the button to work:
-webkit-backface-visibility:hidden disable this and the button works again
or
.emptyDiv{height:4em;} change this to 4px or disable it and the button works again.
Likewise putting that style in the LO as 4px rather than 4em and it works.

However I'm not sure what the emptyDiv is doing and I do notice that flipping the cards does show the contents of both sides as it flips on Safari on both MacOS and iOS.

**Comment by FayCross** [comment]
Hi Ron, I don't have a way of testing Safari on MacOS. Off the top of my head the backface-visibility style was there to force the button on the back of the card to be hidden (I think some browsers showed the button in an odd way without this). I can't remember what the purpose of the emptyDiv was. I'm guessing it was some kind of spacer to make sure the content above never overlapped the buttons but I can't be sure. Feel free to remove this if you it fixes the safari issue & it doesn't introduce another problem in any other browser with any of the card layouts.

I did know about the card content on both sides showing on Safari - I think this was an issue with the js library used for the flip & not something we can easily fix ourselves. It might be worth seeing if there's a better way of dealing with this now.

**Comment by ronm123** [comment]
@FayCross ok thanks. If the emptyDiv is just a spacer, (and it looked like that when I made it red to check) then changing the 4em to 4px seems to fix the issue with Safari on MacOS. I'll test wether it should be a higher px value before I commit that change.

**Comment by ronm123** [comment]
@FayCross I tested this further and couldn't see a problem as a result of changing the height of the empty div from 4em to 4px so I committed that change. However that didn't really seem right so I tested further and with the empty div assigned a background colour and restored to 4em I could see that on Safari on Mac for some reason the flip button was behind the empty div and with the div at 4em it covered the whole button and so the button wasn't clickable. Setting the div to 4px meant it wasn't covering the button because it was just a thin line above it. On Windows and other browsers on MacOS the div set to 4em covers the same area but below the flip button so the button still worked. So I've changed the commit and restored the empty div height to 4em but set the z-index of the flipBtn to 1 which on MacOS seems to fix the issue. At some point please check what the original intention of the empty div was/is and whether this change is likely to impact that?
In the meantime I'll close the issue.
