### ISSUE TITLE
XOT Drag Drop strange behaviour

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#915]
Hi all,

@torinfo made an update to the DragDrop page in May but this seems to have introduced a couple of strange behaviours:

- [ ] Drop target drawn really wide of the image
- [ ] Drop targets all bunched into top left corner
- [x] Labels float off targets after resize
- [ ] Labels not reset after they return to label holder
- [x] Drop targets screwed up if you zoom in far enough and out again to 100%

I've recorded some gifs of each of them happening but it is easy to reproduce:

**Drop target drawn really wide of the image**
If you enter the page and don't attempt anything and then navigate away and return to the page then the drop targets have all shifted position and some have been drawn really for right and really far down thus creating scrollbars in the LO that shouldn't be there...

![DragDropNoAttemptChangePage](https://user-images.githubusercontent.com/3907362/88567241-215ced80-d02f-11ea-8766-35f2e5a1413a.gif)

**Drop targets all bunched into top left corner**
If you then refresh the LO again and complete the task and click Submit (and get them all correct) then leave the page and return, the drop targets this time are all drawn in the top left, really thinly.

![DragDropAllCorrectChangePage](https://user-images.githubusercontent.com/3907362/88567409-59fcc700-d02f-11ea-82ed-67f5fc2dec93.gif)

**Labels float off targets after resize**
If you drop a label (or a few) and then resize the LO then the labels float off the targets 

![DragDropLabelFloatOnResize](https://user-images.githubusercontent.com/3907362/88568778-62ee9800-d031-11ea-9208-4b3d2ebd350f.gif)

**Labels not reset after they return to label holder**
If you click check before all labels are dropped then the correct ones get a tick but you can still drag them to other targets. If you drag them to a wrong target and click check again then the wrong label is returned to the label holder but the correct tick is not removed

![DragDropLabelTickNotCleared](https://user-images.githubusercontent.com/3907362/88569324-31c29780-d032-11ea-99e5-293c5f2aa299.gif)

**Drop targets screwed up if you zoom in far enough and out again to 100%**
If you zoom in (ctrl +) until the picture disappears and then zoom out (ctrl - or ctrl 0) to 100% again then the targets are all drawn as a tiny point in the top left

![DragDropZoomInZoomOut](https://user-images.githubusercontent.com/3907362/88591878-fab1ad80-d054-11ea-96d4-de29afd2d4ad.gif)

I've seen a few other things but struggling to remember the exact steps to reproduce however I will add them here when I manage. I'm surprised these haven't come up before though so has @torinfo 's changes really introduced all of these or did most/all of them exist before?!? If you have access to an older install @ronm123 / @FayCross can either of you reproduce these prior to the May patch?

I'm going to work on fixing these I think for or on 30th July.

Regards,

John

**Comment by torinfo** [comment]
@JohnSmith-LT Thank you for this. I'll have a look. The reason for the patch is that if you did not answer anything, navigated to the next page, and than navigated back again, nothing worked. You could drop 1 label, but the others would not work. I'll try to find the original complaint.

**Comment by JohnSmith-LT** [comment]
Hi @torinfo , I did some further investigation last night and the majority of these issues are NOT to do with what you changed, perhaps you just made them a bit easier to see...

Perhaps this is new or perhaps it's been a fatal flaw in the way we've done pages since the beginning of Xenith code but this page doesn't seem to maintain state at all between page changes despite being wrapped within a new Function closure... This could be one of the main reason that as pages get more complex, multiple pages of the same type seem to interact and screw up the previous page.

For example, I created a two page LO with 2x DragDrop pages. When you go to Page 1, tooltips gets initialised to [] and then populated (in this case to [null, null, null, null].
Then we move on to Page 2. Because it has new been opened before, the function runs again and tooltips is set to [] and then populated to the 4x tooltip texts. This SHOULD be fine because it is a new Function, however this is not the case.

When you return to Page 1 again, this time the page comes from built[] so in theory tooltips should be [null, null, null, null] again but it is not, it is populated with the tooltips from Page 2 because they were the ones last set...

Then to make things worse, on each re-entry of the page, the tooltips are re-processed so the tooltips array just keeps getting bigger and bigger each time you go back and forward between pages. I captured this in a gif:

![DragDropTooltipsIncreasingIssue](https://user-images.githubusercontent.com/3907362/88637925-b0f7b000-d0b2-11ea-8e1a-240f36532741.gif)

But it's not even just that variable. If you log out 'interactivity' in the pageChanged() event handler then (if page 1 is a Match type page and Page 2 is a Describe type page), then after you go to Page 1, Page 2 and back to Page 1 again (that's the first time pageChanged() fires) then 'interactivity' shows Describe and then it gets updated again on Page 1 to Match and then if you go back to Page 2 it shows Match and NOT Describe... 

What this means is that for each of these complex pages that we are assuming maintains state (but are not) we need to repopulate all the variables each time we re-enter the page but worst of all we will have stored HTML from any previous interaction so we need to re-process that to infer the current state of iny previous interactions...

I know all of that is quite confusing but it does demonstrate why perhaps this page and the Gap Fill have had many re-curring and unexplained issues going way back to 2018...

**Comment by ronm123** [comment]
@JohnSmith-LT @torinfo @FayCross I was going to add a new issue with the drag and drop labelling page but it seems appropriate to add it here...
I was asked to look at an example containing two drag and drop labelling pages mixed in with other pages and where both drag and drop labelling pages were set to match mode. These work fine when first visiting the page but when you then move away and return they no longer work and probably because something is then wrong with the hotspots. The same interactions set to describe mode work fine even when returning to the pages.
I've created a demo on xot.xerte named drag and drop labelling issue ID 233 and you each have co-author access. The first page contains an example of the interaction from the real project and page 2 and 3 contain simple examples one in match mode and the other in describe mode. You'll see that when you return to each page the describe example still works but the two match mode examples do not.
