### ISSUE TITLE
Change lang="en"dynamically according to language option in LO?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#918]
@torinfo during accessibility testing with Alistair the need for correct lang="xx" value came up as being important. There's an example of why it is important here: https://webaim.org/techniques/screenreader/#language

I had a look at the player files and it seems we have lang="en" in the xot player and nothing in the bootstrap and decision players. So a few questions:

1. Should we be adding lang="en" to the html tag of the bootstrap and decision players?
2. Is there a way and should we be changing that lang value dynamically based on the language setting of each LO?

Or are we dealing with this somehow already?

**Comment by torinfo** [comment]
Committed as 77a8249d8cfaef8fa2a5c402f4dacc996cc0ca8e
