### ISSUE TITLE
transcript options for wherever narration, sound and/or audio is added?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#919]
Adding this here for discussion during the next developer day...
The question of how to enable a transcript option wherever authors can add narration, sound and/or audio via the wysiwyg toolbar came up during accessibility testing. We know it's possible to add a link in any text area to an uploaded transcript for that media but the question is can we do more than this e.g.
1. Include an optional property with the narration and sound optional properties to type or paste a static transcript?
2. Extend that option and allow adding of a timed transcript and display that somehow in sync with the audio. Not sure if we're using this anywhere? https://gist.github.com/nfreear/905453fb86124bcd3f38 or https://github.com/mediaelement/mediaelement-plugins/blob/master/docs/a11y.md
3. Provide similar options when the wysiwyg is used to add audio.

We discussed the narration option and that when added that sits flush to the footer so is there for instance scope to add an additional button to the player which when clicked opens the transcript in a lightbox?

For discussion during the next developer day unless anyone has ideas in the meantime.

**Comment by FayCross** [comment]
I've just had this question asked by a colleague who wanted to add transcripts to the narration bar. I've shared some code and css with him that he's adding to the project that will add an extra button to the end of the narration bar. The button then opens a transcript in a light box:

![transcript](https://user-images.githubusercontent.com/8926470/192771044-3f245bb1-bf91-4e81-854b-423e5fd9e880.PNG)

This would be pretty easy to add as an option to editor. Does anyone have an idea of a better way of doing this? Is the icon in screenshot above ok or any better suggestions of a FA icon to represent a transcript. I also wasn't sure if a lightbox was the best place for the transcript to open (but couldn't think of an alternative)

**Comment by FayCross** [comment]
Also, should this be added as an option to all places where an audio player can be added to a page or is the way that the transcript works on pages like graphics & sound better (where there's a big button below that reveals the transcript when clicked - not in lightbox)?

**Comment by FayCross** [comment]
Closing as all places where audio is added a property to page now have option of adding an associated transcript. Transcript for audio added via wysiwyg is covered in this issue: https://github.com/thexerteproject/xerteonlinetoolkits/issues/545
