### ISSUE TITLE
review wherever images can be added and add a caption optional property too

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#920]
When adding images via the wysiwyg editor there is both an alt text option and a separate caption option. However we have various pages where images are added via optional properties and these only provide an alt text option without a separate caption option. The question is should we and can we add a caption option to those current optional image properties?

For discussion during next dev day.

**Comment by FayCross** [comment]
Where captions are possible they should use format:
`<figure><img...><figcaption>Caption here</figcaption></figure>`

This is done already by images added via wysiwyg but not in other places (graphics & sound page / lightboxes)
