### ISSUE TITLE
Decision Tree 'Go to page' optional property issue

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#928]
On a decision tree result step there is an optional property 'go to page ID'. This is currently a text field rather than the drop down menu populated with page names. Needs to be changed to something similar to those used on connector pages

**Comment by JohnSmith-LT** [comment]
Did this before receiving your last message so will commit and you can just test later...

**Comment by FayCross** [comment]
@JohnSmith-LT thanks - just tested & works well. Will also continue to work if anyone did manually enter a pageID into text field
