### ISSUE TITLE
Xerte page links bug when changing 'Page ID'

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#932]
When you create a Xerte page link to a page with the optional property 'Page ID', the link is populated with this id rather than the unique identifier from XML. This causes the links to break if the page id is later changed. It would be best if they both used the PG1234 way of linking as this shouldn't change

`<a href="#" onclick="x_navigateToPage(false,{type:'linkID',ID:'intro'}); return false;">Page with ID</a>`

`<a href="#" onclick="x_navigateToPage(false,{type:'linkID',ID:'PG1596120241424'}); return false;">Page with no ID</a>`

**Comment by JohnSmith-LT** [comment]
Hi @FayCross can you check that this fixes your issue and doesn't break anything else you are doing? I'm not sure why we favoured pageID in this situation but given that it required extra code and bigger if condition it must've been for a reason...

**Comment by FayCross** [comment]
Thanks John - I’ll check next week as don’t have access to computer at moment. No need to look at the other issues I logged - they were mostly to remind me of things to look at next week.

**Comment by FayCross** [comment]
Just tested & now works. Like @JohnSmith-LT said I don't know why we were looking at pageID before for links so please reopen issue if anyone knows why it wouldn't be ok to take this out
