### ISSUE TITLE
Hotspot image and Hotpsot image connector

### ISSUE THREAD

**Issue by obgeneralao** [thexerteproject/xerteonlinetoolkits#939]
Hi,
When I edit the image, the window opens where you can edit the hotspot, but the buttons would not work at all. I am using Chrome and I tried it with Firefox as well, I got the same issue.

Thanks for looking into this.

**Comment by FayCross** [comment]
Hi, this has now been fixed https://github.com/thexerteproject/xerteonlinetoolkits/commit/25d9a087b0ec902d25f31e707c6e37ac8291d4c3
