### ISSUE TITLE
Bootstrap carousel 'dots' issue

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#943]
The dots in the corner of the carousel that normally are highlighted as each slide shows & can be clicked to jump to another slide do not work when the carousel is set to auto-play

**Comment by JohnSmith-LT** [comment]
Hi @FayCross I created a quick mockup and cannot reproduce this, i.e. they work fine for me? Is it some specific example that you are using and/or do you have a link to a non-working example?

![CraigDavidCarousel](https://user-images.githubusercontent.com/3907362/92577094-31006080-f282-11ea-8d3f-47065a76bfe8.gif)

@JohnSmith-LT

**Comment by ronm123** [comment]
@FayCross @JohnSmith-LT just tested in my local develop works for me to with or without autoplay enabled.

**Comment by JohnSmith-LT** [comment]
Probably should say that I only tested in Chrome on Windows 10 so it could be browser bug...

**Comment by ronm123** [comment]
Good point @JohnSmith-LT but I just tested with Chrome, FF and Edge and all worked fine. But this is with develop so @FayCross was your issue with develop or your older live version? ;-)
BTW I's be inclined to make the dots a bit bigger e.g.
`.carousel-indicators li {
    width: 1.0em;
    height: 1.0em;
}`

**Comment by FayCross** [comment]
Hmm, it was reported to me on our main install but I did check on develop too before posting this. I'm wondering if I hadn't quite brought my xampp up to date though before I did that (wouldn't have been too out of date with develop but perhaps wasn't quite). I'll check & see if I can still recreate. Thanks for testing it

**Comment by JohnSmith-LT** [comment]
Hmmm, is this what you meant @FayCross ?

![CarouselIndicatorsNotWorking](https://user-images.githubusercontent.com/3907362/92787188-ca259900-f3a0-11ea-9350-0153fb94366a.gif)

I didn't change anything and now they work if you click them but the indicators don't work...

**Comment by FayCross** [comment]
Yes, that's it @JohnSmith-LT I thought they didn't work when you click them but I've just tried again and they do. It's just without the highlight of the dots changing you easily lose track of which slide you're on so if you try to click the current dot it doesn't seem like it's working.

**Comment by JohnSmith-LT** [comment]
It's very strange because it was obviously working when I recorded the first gif... I didn't change anything and there are no errors from today's commits or anything so not sure why it would change for me also?!?
