### ISSUE TITLE
Project properties - Give Project - co-creator bug

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#945]
When you are the project creator you can't use the 'give project' function in the project properties window to give a copy of the project to yourself (your name won't appear in the list). This makes sense as you should probably just duplicate the project instead. However, if you are a co-creator on a project you can find your name on the 'give project' panel & attempt to use this to give yourself a copy. This doesn't work properly & the new copy is empty.

**Comment by FayCross** [comment]
Has this functionality broken for everyone (not just when you're trying to give copy to yourself) in 3.12? Just tested giving a copy of a project to myself and got error message in console (& no copy created in workspace). Then tested trying to give Ron the same project and get same error in console. @ronm123 @torinfo could you see if you have access to a new project called 'XOT Pagina typen' on xot.xerte.org. It was a project created by Inge that I am co-author on and I have tried to give you both a copy of it via project properties. If you don't have a copy then looks like this has broken

**Comment by ronm123** [comment]
@FayCross what's the ID of that project? Also you definitely mean on the xot.xerte.org.uk install? I can't spot a project named 'XOT Pagina typen' in my workspace. I had a quick trawl through to see if I'm co-author rather than creator on any projects to try giving to you Fay but I'd be nervous about doing that on any important projects so do you want to create a test project, make me co-author and I'll try giving to you and @torinfo

**Comment by FayCross** [comment]
@ronm123 I don't know what the id will be as I was trying to give you a copy of a project and not just add you to a project that I already have.

I've just created a project called 'Test sharing FC' and attempted to give you a copy. I get console error so I assume it hasn't worked. My project id is 474 so yours should have been 475 (I have created another new project and that's 475 so duplicate owned by you seems to have failed to be created).

I have also added you as co-author to the 474 project so you can see if you can give copy of project to Tom but it looks like it's a bug regardless of whether you are a co-author or creator.

@torinfo - to skip to the important part of this **it looks like 'give this project' in project properties panel no longer works regardless of your role**

**Comment by FayCross** [comment]
@ronm123 no, I can't see that project

**Comment by torinfo** [comment]
@ronm123 @FayCross I don't see the Project that Fay shered with me either. I'll have a look at this later tonight.

**Comment by torinfo** [comment]
@ronm123 @FayCross I fixed this in develop, and cherry-picked it in master (1fe964690262a828da2991d6f7f317c7eaf550d2)

Also deployed on xot.xerte.org.uk

**Comment by FayCross** [comment]
@torinfo has some stuff been accidentally included that shouldn't be? Just noticed on xot.xerte.org.uk there are now two pages that I don't recognise - choose image and summaHotspot

**Comment by torinfo** [comment]
@FayCross  Oops. I'll check a.s.a.p.
