### ISSUE TITLE
Interactive Diagram - diagram editor

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#946]
Is the only way to edit Interactive Diagram pages still via the Flash editor that opens in a new window? Does this still work for anyone? I get 'This text is replaced by the Flash movie.' when I try to edit this page on https://xot.xerte.org.uk/

If this is the only way to create one of these pages then do we need to deprecate it (or come up with a new way of doing this before the end of the year - Flash end of life)?

**Comment by JohnSmith-LT** [comment]
I know you closed this @FayCross but I fixed it anyway (well in Chrome at least) so that older projects can still use it up to December 2020, if required...
