### ISSUE TITLE
Hotspot editor not working in develop

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#947]
When I create a new hotspot I can't save the changes I make to its size & position or change to the polygon hotspot tool. It opens the editor, allows me to resize etc. but neither the tick or cross buttons do anything. No errors in console. I have to refresh the page to get out of the hotspot editor & then of course the changes aren't saved. Works fine in 3.8 but not in current develop.

**Comment by JohnSmith-LT** [comment]
Hi @fay, think this is fixed now. Can you check?

**Comment by FayCross** [comment]
Thanks - looks fine now
