### ISSUE TITLE
properties_library - invalid susbstr call

### ISSUE THREAD

**Issue by jayaich** [thexerteproject/xerteonlinetoolkits#948]
In the middle of trying to sort out a problem and I noticed a PHP warning about an invalid call. The relevant line is in the file website_code/php/properties/properties_library.php   line 846 (looking at the github version). The code around this line shows:

         default:
            if (substr($accessStr,0,5) == "Other")
            {
                $accessStr = "Other";
                $accessTranslation = PROJECT_INFO_OTHER . " ('" . substr(5) . "')";
                $nrViews = $row_access["number_of_uses"];

'substr(5)' is invalid, and I suppose should be 'substr($accessStr,5)'.

**Comment by jayaich** [comment]
Actually you will need to swap around a couple of lines because otherwise you'll be taking a substr of the string 'Other'.
So swap around the lines:

            $accessStr = "Other";
            $accessTranslation = PROJECT_INFO_OTHER . " ('" . substr(5) . "')";
to:

            $accessTranslation = PROJECT_INFO_OTHER . " ('" . substr($accessStr,5) . "')";
            $accessStr = "Other";

**Comment by JohnSmith-LT** [comment]
Thanks John, i'll merge that into our next release which is imminent...
