### ISSUE TITLE
dynamically change html title in bootstrap and xot projects as each page changes

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#949]
Another suggestion from the testing with James is that we should change the html title for each page in the xot project but also I guess in the bootstrap project. So I was just testing this in Bootstrap and around line 1433 in application.js we have the following:
`$('#pageTitle').html(page.attr('name'));`
So I added the following below that:
`$(document).prop('title', page.attr('name')  +' - ' + $(data).find('learningObject').attr('name'));`
But if there is html like FA icons or styling that becomes part of it. Do we already have a function to strip that out or how do we do that?
I haven't committed the above and it's only a single line so happy for anyone else to add this and also similar in xot.

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 don't think so in bootstrap. We just added this in xenith

https://github.com/thexerteproject/xerteonlinetoolkits/blob/38bbf1b71d2b5809ed128a5167b36f453c50fb8f/modules/xerte/parent_templates/Nottingham/common_html5/js/xenith.js#L3264

so something along lines of

`$(document).prop('title', $('<p>' + page.attr('name') +' - ' + $(data).find('learningObject').attr('name') + '</p>').text());`

should do it...

**Comment by ronm123** [comment]
Thanks @JohnSmith-LT that works and have committed this for both Bootstrap and XOT so will close the issue. 
BTW didn't bother calling the existing function in Xenith as it's only one line.
