### ISSUE TITLE
File upload spinner not working correctly (fixed in PR)

### ISSUE THREAD

**Issue by jayaich** [thexerteproject/xerteonlinetoolkits#952]
Whilst investigating a large file (300MB+) upload failure, it was noticed that the spinner started and then stopped a second or two later. The file upload carried on it seems in the background. No popup window appeared saying the upload had occurred, so the user was left confused as to what had actually gone on.
File uploads can occur via 2 mechanisms (that I am aware of):

1) By editing a project page and selecting to include an image/video/etc and then selecting to upload it (or use drag and drop).
This method works fine; a (different) spinner appears and remains present while the file uploads. Upon completion the user sees a popup window.
2) Highlight a project from the workspace, and then select the 'i' icon above to get the project properties. Select the 'Media and quota' tab; select a file for uploading, and then click on the 'Import' button. The button icon changes to 'Importing...' but very soon changes back to 'Import'. No popup window appears.

Using the browser console I could see that what is being returned to the javascript is actually HTML code from the fileupload.php file. What should be returned is something like '**** File successfully uploaded'. I found a similar issue from 2013 (!). To correct it the 'src="#"' attribute has to be changed to 'src=""'. When I did this, the file upload worked correctly - the spinner stayed spinning, and a popup window appeared after the file upload.
Tested with a small file (<1MB), and other files of various sizes - 40MB, 110MB, 190MB and 340MB. The largest file took around 6 minutes to upload, but the spinner worked correctly spinning away during that time, and then the popup window appeared when the upload completed.

The fix for the spinner problem is in pull request #951.

**Comment by jayaich** [comment]
The PR also includes a commit for when an oversize file is uploaded. currently the error defaults to being an 'invalid file type' error. This commit checks the file size against the PHP max upload size, and states that the file is too big if it is over that limit.

**Comment by JohnSmith-LT** [comment]
Have merged. Thanks @jayaich
