### ISSUE TITLE
Glossary terms don't show in the Glossary Dialog for Modern: Urban Blue theme

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#954]
From here:

https://www.xerte.org.uk/index.php/en/forum/bugs-and-issues/2210-glossary-background-colour-different-from-hover-over#6873

**Comment by ronm123** [comment]
@JohnSmith-LT leave this one with me. In return I'll add an an issue I discovered while updating the release notes which may me an issue with the link/lightbox plugin but hopefully an easy fix :-(

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 it seems that this is an issue in another theme (Modern Sleek Grey) also so perhaps these all need looked at:

https://www.xerte.org.uk/index.php/en/forum/bugs-and-issues/2214-text-with-glossary-text-term-not-displaying-when-using-theme-modern-sleek-grey#6885

**Comment by ronm123** [comment]
@JohnSmith-LT slightly different issue to the OP but yes I've just committed a fix for the sleek grey theme and will check the others too.
