### ISSUE TITLE
Problem with Import code or am I missing something?

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#957]
@torinfo when I use the Import button, some projects show up as having no pages to import...

![image](https://user-images.githubusercontent.com/3907362/94084112-a6307180-fdfc-11ea-80d6-1f7e30751c42.png)

Despite them obviously containing pages...

![image](https://user-images.githubusercontent.com/3907362/94084180-ceb86b80-fdfc-11ea-8bbb-cc190d2ae22e.png)

Is there some condition or subset of pages that can be imported or is this a bug? Both are XOT templates...

**Comment by torinfo** [comment]
@JohnSmith-LT Don't know by heart. There is no condition as far as I know. Could it be difference between preview.xml and data.xml?

**Comment by ronm123** [comment]
@JohnSmith-LT I just tested that theory from @torinfo and that seems to be the answer! e.g. 
1. created a new project (import test) and imported some pages from another project then previewed but didn't publish and also cancelled when prompted to publish when closing the editor.
2. Opened another project and tried importing pages from import test and it showed no pages in this project.
3. Published import test and repeated step 2 and pages were now showing and could be imported.

**Comment by JohnSmith-LT** [comment]
@torinfo Yes you are 100% spot on... in my mind I would have though you might want to copy pages that you are still editing but don't want to publish yet, for example, you create a template and you need to copy that into several other LOs so that you can insert specific info only... In that case we'd probably need some way to switch between the preview and published xml...

Perhaps we just need some sort of help icon though on that page to tell end users that they can only copy from the published LO...

PS. just saw your comment @ronm123 pop up as I was typing... thanks for confirming also... do you think this is this a non-issue?

**Comment by ronm123** [comment]
@JohnSmith-LT I think the days of needing a difference between preview and publish to avoid end users seeing changes that we don't yet want them to see are long gone since we've had the ability to hide pages. I always advise people to publish as a matter of habit during editing and hide any pages they don't want to show in the published version. So yes perhaps just a tooltip or even addition to the 'No pages in this project' message to make it clear that only published pages will show.

**Comment by JohnSmith-LT** [comment]
Yeah ok, that makes perfect sense... thanks @ronm123
