### ISSUE TITLE
Import Bootstrap pages

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#964]
Would be useful to allow import of pages from other projects in Bootstrap in same way as you can in XOT projects

**Comment by torinfo** [comment]
Yes. I agree!

**Comment by ronm123** [comment]
+1
Perhaps pages and/or specific sections.

**Comment by FayCross** [comment]
I'll leave this open as I've only got it working for whole pages (not individual sections)

**Comment by ronm123** [comment]
@FayCross pages better than nothing! ;-)
