### ISSUE TITLE
Flash after 2020 

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#969]
Changes that need to be made in preparation for Flash end of life:

- [x] Project properties > project tab: remove check boxes to change between Flash / HTML5

- [x] Project properties > export tab: remove check boxes to export as Flash / HTML5

- [x] Should any projects that are still set to use Flash be forced to use HTML? Or can we flag them to users in workspace in some way so they know which ones they should look at?

- [x] Disable RSS feed template so it doesn't appear in template list for creating new projects (as no HTML version of template)

**Comment by FayCross** [comment]
I've just added an extra point above about the RSS template that's no longer useful. We could do with talking about all of this at next dev day.

**Comment by FayCross** [comment]
@torinfo Can the RSS feed template be made inactive as part of v3.10 upgrade? I guess there would have to be something in upgrade.php that makes this change directly in the database (if active anyway - at UoN I've already disabled it manually)

**Comment by torinfo** [comment]
@FayCross Will do (in upgrade.php)

**Comment by JohnSmith-LT** [comment]
Hi @torinfo just identifying some issues to work on and came across this...

How easy is it to disable this in the Workspace so that no more can be created, since it's flash only now? Seems this is the only remaining part of this issue so it can be removed.

**Comment by FayCross** [comment]
It's just a field in the database that needs changing (originaltemplatesdetails > active) so just through upgrade.php I think. I turned it off at UoN by manually changing that field

**Comment by JohnSmith-LT** [comment]
Ok, thanks @FayCross, there's at least 1x other open issue linked to this so I think we should just go for it since it hasn't worked properly for a while anyway and now doesn't do anything because of Flash - will hold off to see if @torinfo agrees

**Comment by torinfo** [comment]
@JohnSmith-LT @torinfo Is hould have done this prior to releaseing 3.10. 

This is indeed making the template inactive in upgrade.php. I would do that in the function _do_cleanup. This woiuld be the rist db change in that function. I can do that if you want. @JohnSmith-LT What is the related issue?

**Comment by JohnSmith-LT** [comment]
@torinfo if it's easier for you to do it then yes, please do - I'll probably mess it up!

The other issue was this https://github.com/thexerteproject/xerteonlinetoolkits/issues/296 but I've closed it now.

**Comment by JohnSmith-LT** [comment]
@torinfo I've implemented this now, as you said, in _do_cleanup rather than as a database upgrade.

Have tested several times and all seems to work for me but please cast an eye over when you get a spare moment to make sure that I haven't messed up somewhere and close if you are happy :-)

**Comment by FayCross** [comment]
I've just upgraded my xampp and it's removed the option of creating new RSS projects. I haven't tried a brand new install though - I guess it's also turned off by default in those?

**Comment by JohnSmith-LT** [comment]
Hmm, I'm not sure @FayCross, @torinfo is a change to upgrade.php enough for new installs also  - i.e is upgrade.php run after new install or is there somewhere else that would need changed in order to fix this in a new install?

**Comment by ronm123** [comment]
@FayCross @JohnSmith-LT @torinfo wasn't this discussed previously and because that template required flash it was disabled/hidden?

**Comment by torinfo** [comment]
@JohnSmith-LT @FayCross No, only upgrade.php is not good enough. There is a setup/basic.sql that inserts a few templates in the database, and that needs changing as well.

I can do that for you if you want.

**Comment by JohnSmith-LT** [comment]
Thanks @torinfo. I've changed the entry in line 90 of setup/basic.sql to:

(8,'xerte','Rss','Rss','Easily create and maintain an RSS Feed.','2008-04-02','RSS Feed',0,'*',0)

The 0 on the very end seems to be the 'active' flag.

I've committed the change so if you just confirm that I've not messed up ;-) then we should be good to close this one!
