### ISSUE TITLE
Page links broken in Bootstrap from 3.9 onwards

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#972]
I think this is related to changes @FayCross made in september to fix links. I'm about to commit a change that 'i think' fixes it but since @ronm123 is away it will probably need @FayCross  and/or @torinfo  to double check before being pushed as a fix  since i'm not sure if it would break something else...

**Comment by JohnSmith-LT** [comment]
Not sure what happened with whitespace on that commit sinc eI never chose to commit those changes?!? but anyway the important changes are at lines 1311 -14

**Comment by FayCross** [comment]
I’ll try this in a bit. I‘m not sure I can recreate the problem though - I tried yesterday (develop not 3.9) & links worked fine without Page ID set.

**Comment by JohnSmith-LT** [comment]
Hi @FayCross it was the manual links that you insert in the text that I found to be the problem, the page menu links work fine

**Comment by FayCross** [comment]
Ah, I realised it was those links but the links I tested with were pointing to 1st page & going to 1st page was what happened when link failed (so it wasn't apparent to me that it wasn't working). Could you test this is still ok for you @JohnSmith-LT please? This should allow links with & without custom IDs to work, as well as sub-section links & links to stand alone pages (no matter where they are in project). Thanks

**Comment by JohnSmith-LT** [comment]
Hi @FayCross this all looks good to me now...

**Comment by torinfo** [comment]
@JohnSmith-LT @FayCross Should I cherry-pick both those commits to 3.9?

**Comment by JohnSmith-LT** [comment]
Yeah I think @FayCross reversed mine anyway but I tested all above and they worked for me...

**Comment by FayCross** [comment]
Yes please @torinfo 
@JohnSmith-LT your fix worked but caused a problem if there was a stand-alone page before the page being linked to (wouldn’t be apparent in vast majority of projects!) I tested pretty extensively last night & think this is ok now. Thanks
