### ISSUE TITLE
dragDropLabel - hotspots are completely off when returning to the page

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#980]
In the dragDropLabel using the 'match' exercise, the hotspots are placed completely in the wrong position when returning to the page.

So the first time, everything looks ok and works fine. However, when navigating to a different page and returning, the hotspots are in a different position. I thought I already fixed that some time ago. I also see that @JohnSmith-LT changed some code on July, but I can't figure out why that should not work. As I understand the code now, everything is rebuilt, so why does it not work?

The scaling is off. You can see that clearly if you use an image that is too large. When returning to the page, all of a sudden extra scroll bars are added (depending on the exact postions of the hotspots, but as a test put 1 in the lower left corner, and another in the upper right. It looks like the hotspots are draw as if the image is not scaled at all.

**Comment by ronm123** [comment]
@torinfo I added this to a previous issue and commented end of Sept https://github.com/thexerteproject/xerteonlinetoolkits/issues/915 including creating an example that we all have access to in order to test and replicate.

**Comment by JohnSmith-LT** [comment]
Hi @torinfo & @ronm123 does this fix sort it for you? Xenith resize code has been storing origSize in data() during the image resize code but it seems that this now wasn't persisting when you change page and return...

Since we are only supporting IE9+ I have used $image.prop("naturalWidth") and $image.prop("naturalHeight") to calculate the scaling and this seems to work on this page in my basic testing but I suspect that that means that other pages (that resize the image dynamically and use the original size for some calculation) may also be broken... :-(

Does this quick fix work for you, at least with this problem?

**Comment by ronm123** [comment]
@JohnSmith-LT I'll try to test before we start the dev meeting tomorrow.

**Comment by torinfo** [comment]
@JohnSmith-LT Regrettably it does not seem to fix it for me. It's better, and sometimes it's ok, but not all the time.

**Comment by JohnSmith-LT** [comment]
Thanks @torinfo I used one of the naturalHeight commands incorrectly but upon fixing it I was getting some strange errors where the droptargets had a left,top of 0,0 in certain situations (like returning to a drag drop page after resizing on a different page)

It seems that position().top() and position().left() have a few issues occasionally... have now changed to .css('left') and 'top' and I can't make it break now...if you can then can you list the steps to reproduce?

**Comment by ronm123** [comment]
@JohnSmith-LT @torinfo not sure if your testing matches mine but I did some testing locally and then added the updated model file to one of the installations where this had been reported previously and after a clearing of offline files the two examples they had on that installation seem work be working fine now even when in match mode. As I described at the end of https://github.com/thexerteproject/xerteonlinetoolkits/issues/915 the issue reported seem to apply when returning to a page in match mode whereas describe mode worked fine. But now match mode seems to work fine too so if you can't find any further issues on consequences of the changes then I think both 980 and 915 can be closed?

**Comment by torinfo** [comment]
@ronm123 @JohnSmith-LT My testing so far also is successful :-) 
So I agree that these issues can be closed.
