### ISSUE TITLE
Strange bug, LO defaults to yellow if google font doesn't load...

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#982]
@torinfo / @ronm123 

Can either of you reproduce this bug? Was working on some stuff tonight and put the laptop into airplane mode as the kids were having skype music lessons. Anyway, I refreshed the LO i was working on and it loaded yellow:

![image](https://user-images.githubusercontent.com/3907362/100275156-6d755b80-2f57-11eb-8e82-c8142e1acd0c.png)

I though I must have enabled Black on Yellow or changed theme or something but checked and they were all fine. Eventually I noticed that although I was working from localhost, this Google request was blocking (due to no internet connection) https://fonts.googleapis.com/css?family=Roboto 

Anyway, I came off airplane mode, refreshed and it went back to default black and white XOT template. So to reproduce, open an LO and open console and go to Network tab. Refresh and find https://fonts.googleapis.com/css?family=Roboto and right click and block it. Then refresh. Does it load with a yellow background?

Not sure if thisis an issue that we need to fix but if Google move or delete that URI then I think all LOs out there could then just default to yellow...

**Comment by ronm123** [comment]
@JohnSmith-LT @torinfo just had a look at this and it seems the attempt to load the Roboto font was coming from the Black on Yellow theme and isn't even used in that theme so I've removed it. Probably my fault that it was in there from when I added SCSS to that theme. Not quite sure why the Black On Yellow theme is being automatically loaded by xenith when an LO is set to another theme like the default theme but I guess that's just part of the theme switching functionality. 

I guess the same issue could happen with themes that do use the Roboto font like RGBO but I tested with an LO set to RGBO after removing it from Black on Yellow and now can't replicate the issue. If you can't either after pulling down my change then I think the issue can be closed.

**Comment by JohnSmith-LT** [comment]
Thanks @ronm123 I cannot reproduce it now so i'll close this.
