### ISSUE TITLE
Duplicating a Quiz Question results in undefined in the tee navigation

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#987]
![XerteQuizQuestionUndefined](https://user-images.githubusercontent.com/3907362/102016818-cff19880-3d5a-11eb-9132-55f9d72f1846.gif)

**Comment by JohnSmith-LT** [comment]
Related to https://github.com/thexerteproject/xerteonlinetoolkits/issues/713

**Comment by torinfo** [comment]
@JohnSmith-LT I cannot reproduce that.
![copy_sub_node](https://user-images.githubusercontent.com/5166596/102058684-21983280-3df0-11eb-8191-97fb44ade4c1.gif)

**Comment by torinfo** [comment]
@JohnSmith-LT Is this 3.9 or develop? I tested in develop.

**Comment by JohnSmith-LT** [comment]
Up to date develop... XAMPP though if you think that may alter things...

**Comment by JohnSmith-LT** [comment]
Hmmm I can't reproduce it now @torinfo... but i've definitely seen it before (#713)... seems to be sporadic. Will close this now and keep an eye on it

**Comment by torinfo** [comment]
@JohnSmith-LT Does it happen if the session is expired?

**Comment by JohnSmith-LT** [comment]
I don't think that was it because I just opened it last night to do a quick quiz page to get a few screenshots... As soon as you referesh it updates or as soon as you edit the field then it updates...

**Comment by FayCross** [comment]
I can reproduce this - it only happens if you have renamed the label that shows in the tree during the same session. I won't reopen this though because of the existing issue https://github.com/thexerteproject/xerteonlinetoolkits/issues/713
