### ISSUE TITLE
not compatible with php 8.0 

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#989]
The latest xampp uses php 8.0 

Xerte does not work with php 8.0 yet.

**Comment by ronm123** [comment]
@torinfo I was curious about this so tested a new install with the latest xampp and PHP 8. I haven't tested extensively but in terms of the install routine I first got the following error:
Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in page4.php:28 Stack trace: #0 {main} thrown in page4.php on line 28.
If I comment that out there are 3 more errors re $magic_quotes but the install completes.
Warning: Undefined variable $magic_quotes in I:\xampp\htdocs\xerte39\setup\page4.php on line 106
Warning: Undefined variable $magic_quotes in I:\xampp\htdocs\xerte39\setup\page4.php on line 122
Warning: Undefined variable $magic_quotes in I:\xampp\htdocs\xerte39\setup\page4.php on line 139

I'm able to create end edit Bootstrap and Decision Tree projects but when I create an XOT project the editor window just displays a spinner and doesn't load.

I turned on Xerte debugging but nothing particular useful in the debug.log but I can see errors in the Apache log. So a few questions:

Is PHP 7.4 ok with the latest Xerte code? I've got installs using 7.3 but haven't tried 7.4 yet.
What are the issues with PHP 8? 
Are you working through those and do you need any help?
No need to reply we can discuss during the next dev day but as I've just tested thought I would add this here now.

**Comment by torinfo** [comment]
@ronm123 Yes 7.4 seems to work fine

And yes you have the same observations as I have. The setup is easy to fix. Have not looked at all yet to the launching of the XOT project editor, but it is probably also easy to fix. I have not looked yet.

**Comment by ronm123** [comment]
@torinfo you may have noticed that after testing this and seeing a clean install again I updated page3.php in setup to change the default pod info for pod 1 and news/other resources pod. Well I tested that with a new install with PHP 8 and noticed that although the workspace showed what I wanted when viewing via management I was getting an error. So I thought perhaps I'd made a syntax error in page3.php. However I tested a clean install using an earlier PHP version and that works fine for both workspace and management. So I checked again with the page3.php that is part of current 3.9 and with PHP 8 I was getting the same error in management:
Fatal error: Uncaught Error: Undefined constant "MANAGEMENT_TUTORIAL_TEXT" in \website_code\php\management\site.php:70 Stack trace: #0 {main} thrown in \website_code\php\management\site.php on line 70 
So I'm concluding that the changes I have made and committed are fine and this is just another PHP 8 incompatibility. Again no need to reply just adding details after committing the changes and testing.

**Comment by torinfo** [comment]
This has been fixed (see 5788a93bbe699a8518c278c324bf7bba9c0bc807, 315a74b230dc1c711b8a8a3e90043e30d08c1557 and 07b2830b8149a9e362fc9216856f50f9f6463467)
