### ISSUE TITLE
Warning message when deleting projects that aren't private

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#996]
It would be good to have an extra warning when attempting to delete a project where the access is something other than private. Currently you just get the 'are you sure you want to delete message' but this could have extra info in it when the project's public.

**Comment by FayCross** [comment]
It would be great if you could take a look @torinfo - Thanks

**Comment by torinfo** [comment]
I added functionality to warn about published projects (including enabling LTI) and also (separately) about shared projects. 
Message is different for multi select and for single select.
@FayCross @ronm123 Could you please verify and change the messages is needed?
