### ISSUE TITLE
Deleted projects only appear in recycle bin for user that deleted them

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#999]
If I add a co-author to a project and then delete it, I can see it in the recycle bin and can no longer edit it. The co-author can still see it in their workspace and can still edit it. Ideally it should also be moved to the recycle bin of everyone it's shared with too (or perhaps just be hidden from their workspace completely)

**Comment by torinfo** [comment]
@FayCross Interesting. I'll have a look.

**Comment by torinfo** [comment]
@FayCross There is a check that filters out LO's that are in the recyclebin. For whatever reason this did intentionally NOT happen for co-authors. So co-authors could still see the LO. 

I fixed that.
